### ISSUE TITLE
Restarting VM fails during docker setup

### ISSUE THREAD

**Issue by dcherman** [abiosoft/colima#1]
Hi,

First, want to say this is an absolutely awesome project!  I ran into this while looking for alternatives to Docker Desktop (like many others) and this has been very seamless to use after tweaking some of the mount options for the generated vm.

During the docker setup part of the `start` command, it looks like the VM is restarted after docker is installed, however at least on my setup, it looks like the VM is not actually stopped after the `stop` command returns, meaning the subsequent `start` command fails.  That leaves the install in a weird state since the launch config/docker socket is not setup.

To fix this, I introduced the following bit of code.  Happy to make a PR if you feel this would be useful.

```bash
	log waiting for VM to stop

	while [[ "$(limactl ls | tail -n +2 | grep "^$NAME " | awk '{print $2}')" != "Stopped" ]]; do
          sleep 1s
	done;

	log vm has stopped, restarting
```

That ensures that the VM has stopped prior to calling `start`.  Everything worked great after I modified that.

**Comment by abiosoft** [comment]
Happy to hear that you found it useful. 
Your snippet works (as a stopgap) but should not be required. I will try to reproduce it on my end.

Thanks.
