### ISSUE TITLE
Colima wont start with M1 MacBook 

### ISSUE THREAD

**Issue by cblicous** [abiosoft/colima#100]
Did install colima  on M1 MacBook Pro with 
` brew install --head colima`

crashes with the following output: 

`INFO[0000] starting colima                              
INFO[0000] starting ...                                  context=vm
> msg="Using the existing instance \"colima\""
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/user/.lima/colima/serial.log\")"
> msg="SSH Local Port: 62432"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] QEMU has exited"
> msg="exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see \"/Users/user/.lima/colima/ha.stderr.log\")"
FATA[0000] error starting vm: error at 'starting': exit status 1 `

file "serial.log" is empty 

ha.stderr.log says 
`{"level":"debug","msg":"firmware candidates = [/usr/local/share/qemu/edk2-x86_64-code.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/qemu/ovmf-x86_64-code.bin]","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"OpenSSH version 8.6.1 detected","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2022-01-06T16:32:57+01:00"}
{"level":"info","msg":"Starting QEMU (hint: to watch the boot progress, see \"/Users/user/.lima/colima/serial.log\")","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"qCmd.Args: [/usr/local/bin/qemu-system-x86_64 -cpu host -machine q35,accel=hvf -smp 2,sockets=1,cores=2,threads=1 -m 2048 -drive if=pflash,format=raw,readonly=on,file=/usr/local/share/qemu/edk2-x86_64-code.fd -boot order=c,splash-time=0,menu=on -drive file=/Users/user/.lima/colima/diffdisk,if=virtio -cdrom /Users/user/.lima/colima/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:62432-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:1c:29:05 -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/Users/user/.lima/colima/serial.sock,server=on,wait=off,logfile=/Users/user/.lima/colima/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/user/.lima/colima/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-colima -pidfile /Users/user/.lima/colima/qemu.pid]","time":"2022-01-06T16:32:57+01:00"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/user/.lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=user -o ControlMaster=auto -o ControlPath=\"/Users/user/.lima/colima/ssh.sock\" -o ControlPersist=5m -p 62432 127.0.0.1 -- /bin/bash]","time":"2022-01-06T16:32:57+01:00"}
{"error":"signal: abort trap","level":"info","msg":"QEMU has exited","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: Unknown Error","time":"2022-01-06T16:32:57+01:00"}
{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 62432: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 62432: Connection refused\\r\\n\": exit status 255","time":"2022-01-06T16:32:57+01:00"}`

**Comment by almike** [comment]
worked for me on m1, I didn't try with ` --head` though
do you have ssh enabled on your mac? `ssh localhost` works ?

**Comment by cblicous** [comment]
Same results without head , version 0.2.2 has the same problem 

ssh works generally yes  

it seems to be an issue with the qemu system somehow ...

**Comment by cblicous** [comment]
found similar issues here : https://github.com/lima-vm/lima/issues/42 in the comments but dont know how to solve

**Comment by cblicous** [comment]
I think the important part here is "{"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: Unknown Error","

**Comment by abiosoft** [comment]
How did you install Qemu? It seems you're trying to use the x86 version on an m1 device.

**Comment by cblicous** [comment]
i just installed colima with brew ... 

now I tried this version "simnalamburt/x/qemu-hvf" of qemu , but this did not seem to help either ...

**Comment by cblicous** [comment]
@abiosoft Thanks for the hint, after removing all qemu versions from brew and then reinstalling colima, the error disappared. I assume that there was a old x86 qemu version somehow on my mac
