### ISSUE TITLE
Colima not starting after upgrading to MacOS 14.5

### ISSUE THREAD

**Issue by rachellawson** [abiosoft/colima#1029]
### Description

I’m seeing a failure to Start Colima after upgrading my MacBook Pro M3 to Mac OS 14.5

Startup log appears to be:

`{"level":"debug","msg":"Creating iso file /Users/rlawson/.colima/_lima/colima/cidata.iso","time":"2024-05-14T09:53:04+01:00"}
{"level":"debug","msg":"Using /var/folders/kt/_k_x72x90370249hvcjh29lhb9_9bm/T/diskfs_iso1647795550 as workspace","time":"2024-05-14T09:53:04+01:00"}
{"level":"debug","msg":"Failed to detect CPU features. Assuming that AES acceleration is available on this Apple silicon.","time":"2024-05-14T09:53:04+01:00"}
{"level":"debug","msg":"OpenSSH version 9.6.1 detected","time":"2024-05-14T09:53:04+01:00"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2024-05-14T09:53:04+01:00"}
{"level":"info","msg":"hostagent socket created at /Users/rlawson/.colima/_lima/colima/ha.sock","time":"2024-05-14T09:53:04+01:00"}
{"level":"info","msg":"Starting VZ (hint: to watch the boot progress, see \"/Users/rlawson/.colima/_lima/colima/serial*.log\")","time":"2024-05-14T09:53:04+01:00"}
{"level":"fatal","msg":"dial unix /Users/rlawson/.colima/_lima/_networks/user-v2/user-v2_fd.sock: connect: connection refused","time":"2024-05-14T09:53:04+01:00"}
`

### Version

colima version 0.6.8
git commit: 9b0809d0ed9ad3ff1e57c405f27324e6298ca04f
limactl version 0.22.0
qemu-img version 9.0.0
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

installed via brew

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] colima is not running 

### Reproduction Steps

1. Upgrade to Mac OS 14.5
2. Run colima
3.

### Expected behaviour

Colima starts

### Additional context

I tried totally removing colima and reinstalling. No difference.

**Comment by mscrivo** [comment]
Same here

**Comment by Physium** [comment]
> actually, I got it working by running:
> 
> ```
> rm -rf ~/.colima/_lima/_networks/user-v2
> colima restart
> ```

not sure what this does but this works! thanks!

**Comment by diei** [comment]
My colleague had the same problem. The following steps helped:
```
# Install all colima updates
brew upgrade

# Cleanup whole colima (images, volumes etc. are deleted)
colima delete

colima start
```

**Comment by snapcarebriggs** [comment]
Just adding that deleting the `~/.colima/_lima/networks` solved the issue for me. I knew this update might be a problem, as I saw it here last week. I updated macOS anyway. Rebooted. Noticed it Colima wasn't running. I tried to execute it. Saw the `FATA[0002] error starting vm: error at 'starting': exit status 1` error. Deleted the aforementioned directory. Ran `colima start` and it's fine now.

**Comment by steinmb** [comment]
Non of the "soft" fixes did it for me. Only the fix above worked for me https://github.com/abiosoft/colima/issues/1029#issuecomment-2112429291

**Comment by writerofcode1** [comment]
I was fine on Sonoma 14.5 but it broke after upgrading to Sonoma 14.6.1.

However, https://github.com/abiosoft/colima/issues/1029#issuecomment-2112146400 fixed it for me.

**Comment by vishal06jain** [comment]
> My colleague had the same problem and deleting `~/.colima/_lima/_networks/user-v2` did not help.
> 
> The following steps helped:
> 
> ```
> # Install all colima updates
> brew upgrade
> 
> # Cleanup whole colima (images, volumes etc. are deleted)
> colima delete
> 
> colima start
> ```
Worked

**Comment by cozma** [comment]
> actually, I got it working by running:
> 
> ```
> rm -rf ~/.colima/_lima/_networks/user-v2
> colima restart
> ```

This worked! I also had to exit my docker instance.

**Comment by andrw** [comment]
+1 to `rm -rf ~/.colima/_lima/_networks/user-v2` fixing it for me, happened after upgrade to 15.1.1

**Comment by abiosoft** [comment]
This should be resolved now with the new release https://github.com/abiosoft/colima/releases/tag/v0.8.1.
