### ISSUE TITLE
`colima start` appears to overwrite `lima.yaml` with defaults at each launch

### ISSUE THREAD

**Issue by spkane** [abiosoft/colima#106]
I am trying to get shared networking setup (https://github.com/lima-vm/lima/blob/master/docs/network.md#managed-vmnet-networks-via-vde_vmnet), but each time I add a few lines to `~/.lima/colima/lima.yaml` and then run `colima start --cpu 8 --memory 8 --disk 100 --runtime containerd --with-kubernetes` those lines vanish and the files looks exactly like it did before my edits.

Am I doing something wrong? Or is `colima` clobbering this?

**Comment by jandubois** [comment]
> Or is `colima` clobbering this?

It probably is. Put your settings into an `override.yaml` file as I explained in https://github.com/abiosoft/colima/issues/105#issuecomment-1010291320.

These settings will be merged with the `lima.yaml` content when the VM is started.

The merged state is not visible to `limactl ls`, even though they were applied; I've created https://github.com/lima-vm/lima/issues/510 to (eventually) deal with this.

**Comment by spkane** [comment]
Great. Thank you. I will give that a try.

**Comment by spkane** [comment]
That appears to have worked. Thanks!

**Comment by abiosoft** [comment]
@spkane that is the recommended way as colima dynamically generates the lima config on each start.

Thanks again @jandubois.
