### ISSUE TITLE
Run mount in Dockerfile doesn't work as expected

### ISSUE THREAD

**Issue by risentveber** [abiosoft/colima#1076]
### Description

Mounted via `RUN --mount=type=bind` folders don't persist any changes during and after docker build. Expected behaviour is described into https://docs.docker.com/build/guide/mounts/.

### Version

colima version 0.6.10
git commit: 12c0c834633986e1c05ec2bd2d53c6cb06c89aef
limactl version 0.22.0
qemu-img version 9.0.2
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [X] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima [profile=docker] is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0001] address: 192.168.106.3
INFO[0001] socket: unix:///Users/b.s.strelnikov/.colima/docker/docker.sock

### Reproduction Steps

1. `mkdir mod`
2. `docker build . --progress=plain` with following Dockerfile:

```
FROM alpine

RUN --mount=type=bind,source=./mod,target=/mod,rw \
    touch /mod/touch.txt && ls -la /mod
RUN --mount=type=bind,source=./mod,target=/mod,rw \
    ls -la /mod
```
Result
```
#6 [stage-0 2/3] RUN --mount=type=bind,source=./mod,target=/mod,rw     touch /mod/touch.txt && ls -la /mod
#6 0.809 total 8
#6 0.809 drwxr-xr-x    1 root     root          4096 Jul 25 15:29 .
#6 0.809 drwxr-xr-x    1 root     root          4096 Jul 25 15:29 ..
#6 0.809 -rw-r--r--    1 root     root             0 Jul 25 15:29 touch.txt
#6 DONE 1.0s

#7 [stage-0 3/3] RUN --mount=type=bind,source=./mod,target=/mod,rw     ls -la /mod
#7 0.851 total 8
#7 0.851 drwxr-xr-x    2 root     root          4096 Jul 25 15:28 .
#7 0.851 drwxr-xr-x    1 root     root          4096 Jul 25 15:29 ..
#7 DONE 1.0s
```

### Expected behaviour

Changes in mounted directory are persisted between dockerfile steps and visible on a host machine.

### Additional context

If one tries to remove `rw` modifier there is an error related to modification of read-only filesystem.
```
RUN --mount=type=bind,source=./mod,target=/mod\
    touch /mod/touch.txt && ls -la /mod
```
so looks the directory is properly mounted.

**Comment by risentveber** [comment]
@abiosoft any ideas?

**Comment by abiosoft** [comment]
I am not fully sure what the expected behaviour is as I got same experience on another environment.
I would need to dig into this a bit more.

Can you give an example of where you've got the desired behaviour?

Thanks.

**Comment by risentveber** [comment]
I just tried to speed up local Docker image build process in the way described in https://docs.docker.com/build/guide/mounts/ and it doesn't give any performance gain due to inability to really write and read data between builds.

**Comment by milas** [comment]
FWIW This is actually expected behavior from Docker (not a Colima issue) that's poorly documented.

See https://docs.docker.com/reference/dockerfile/#run---mounttypebind

Specifically, for the `rw` argument:
> Written data will be discarded.

In practice, _build_ bind mounts are one-way (host->build).

[I filed a docs issue upstream @ https://github.com/docker/docs/issues/20549.]

**Comment by risentveber** [comment]
@milas my bad, thanks!
