### ISSUE TITLE
Incorrect detection of overlapping mounts when 1 name is a substring

### ISSUE THREAD

**Issue by neil-greenwood** [abiosoft/colima#108]
colima version 0.2.2
git commit: b2c7697bee2d73e995f156fe8e9870eb246c07e6

```
$ colima start --mount $HOME/.aws/,$HOME/.aws_legacy/,$HOME/.ssh/,$HOME/git:w
INFO[0000] using docker runtime
INFO[0000] starting colima
FATA[0000] error starting vm: overlapping mounts not supported: '/Users/neil/.aws' overlaps '/Users/neil/.aws_legacy'
```

I would expect this to work, instead of the error message that is displayed.
I guess it might be a problem with lima, not colima itself.

**Comment by neil-greenwood** [comment]
I tried the .aws_legacy directory with the name .aws-legacy first, and renamed it in case it was a word-separator issue. It still doesn't work when the directory is called .awslegacy.

**Comment by jandubois** [comment]
See https://github.com/lima-vm/lima/issues/302

**Comment by neil-greenwood** [comment]
But these don't overlap!

**Comment by neil-greenwood** [comment]
This was my attempt to workaround lima-vm/lima#302

**Comment by jandubois** [comment]
Oops, sorry, looks like the check for overlapping mounts is in colima, and is just doing substring matches. So you should try renaming `.aws_legacy` to `.legacy_aws` and see if that works.

**Comment by neil-greenwood** [comment]
That works. So it is the check that is at fault.

**Comment by jandubois** [comment]
Yes, it is a simple `HasPrefix` match: https://github.com/abiosoft/colima/blob/d99e306af18b4459ea1562434899756b234816d6/environment/vm/lima/yaml.go#L200

@abiosoft I would "normalize" the names before comparison by making sure each mount ends with a `/`.
