### ISSUE TITLE
Cannot access pod logs or port foward anything in kubernetes deploy.

### ISSUE THREAD

**Issue by drew-viles** [abiosoft/colima#1081]
### Description

I've run colima as follows:

`colima start --cpu 4 --memory 8 --network-address --kubernetes`

However When I'm trying to port-forward anything or access logs, I'm getting the following error:
```
error: error upgrading connection: error dialing backend: proxy error from 192.168.106.2:6443 while dialing 192.168.106.2:10250, code 502: 502 Bad Gateway
```

When I remove the `--network-address` flag, it works as expected.

The problem is as I'm using this for Kubernetes, I've been replying on that flag to allow me access to services, such as nginx ingress, in the cluster when testing things.

Is this a bug, a known feature as part of the `--network-driver` flag removal or something that has been accidentally introduced (regression - was working in a previous version)?

### Version

```
brew info colima
==> colima: stable 0.6.10 (bottled), HEAD
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [x] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
colima status
INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] address: 192.168.106.2                       
INFO[0000] socket: unix:///Users/drew/.colima/default/docker.sock 
INFO[0000] kubernetes: enabled
```

### Reproduction Steps

1. `colima start --cpu 4 --memory 8 --network-address --kubernetes`
2. `kubectl logs -f -n kube-system deploy/coredns`

### Expected behaviour

I should be able to port-forward and fetch logs (it may well affect other functions too)

**Comment by abiosoft** [comment]
Wow, thanks for reporting. It is definitely a bug.

I have reproduced it successfully and would work on a fix.

**Comment by drew-viles** [comment]
Wow thanks for the RAPID response on this!

**Comment by abiosoft** [comment]
@drew-viles can you try with the development version and see if this is fixed?

```sh
# install development version
brew install --head colima

# reset current instance
colima delete

# start a new instance with network address enabled
colima start --kubernetes --network-address
```

**Comment by drew-viles** [comment]
That works perfect. Thanks very much for fixing this so qucikly!

**Comment by abiosoft** [comment]
Thanks for confirming, a new release is imminent.
