### ISSUE TITLE
TLS Cert Signing Error with Second Cluster

### ISSUE THREAD

**Issue by richard-autry** [abiosoft/colima#1087]
### Description

Starting the first cluster works as expected, however I am now receiving a TLS error getting pods for a second started cluster.

### Version

```
colima version 0.7.0
git commit: 4b14e8a9993b17d2e6f5071fd9059513111cd365
limactl version 0.22.0
qemu-img version 9.0.2
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima [profile=mirror0] is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] address: 192.168.106.2
INFO[0000] socket: unix:///Users/richardautry/.colima/mirror0/docker.sock
INFO[0000] kubernetes: enabled
```

### Reproduction Steps

1. `colima start mirror0 -k --kubernetes-disable=traefik -c 4 -m 8 --network-address`
2. `kubectl get pods` result as expected
3. `colima start mirror1 -k --kubernetes-disable=traefik -c 4 -m 8 --network-address`
4. `kubectl config use-context mirror1`
5. `kubectl get pods` results in

```
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### Expected behaviour

You should be able to get pods status, logs, etc using `kubectl` on the second cluster.

### Additional context

Recently upgraded to `colima` 0.7.0, but this multi-cluster test was working previously.

**Comment by abiosoft** [comment]
Thanks for reporting. I have identified the problem.

**Comment by abiosoft** [comment]
This should be fixed now. 

Can you kindly confirm by installing the development version with `brew install --head colima`?

**Comment by richard-autry** [comment]
> Can you kindly confirm by installing the development version with `brew install --head colima`?

@abiosoft 
`brew` is not showing another version to be installed beyond `0.7.0`.  Am I missing a step to use latest here?

```
brew install --head colima
Warning: colima HEAD-4b14e8a is already installed.
The currently linked version is: 0.7.0
```

**Comment by richard-autry** [comment]
Awesome. LGTM! Thanks for replying/fixing so quickly. You rock 🚀
