### ISSUE TITLE
> instance "colima" already exists ("/Users/abc123/.colima/_lima/colima") FATA[0000] error starting vm: error at 'creating and starting': exit status 1 

### ISSUE THREAD

**Issue by dparm** [abiosoft/colima#1096]
### Description

FATA[0000] error stopping vm: error at 'stopping': exit status 1 
➜  ~ git:(master) ✗ colima stop
INFO[0000] stopping colima                              
INFO[0000] not running                                   context=vm
INFO[0000] done                                         
➜  ~ git:(master) ✗ colima start --verbose
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] creating and starting ...                     context=vm
> Terminal is not available, proceeding without opening an editor
> instance "colima" already exists ("/Users/abc123/.colima/_lima/colima")
FATA[0000] error starting vm: error at 'creating and starting': exit status 1 
INFO[0001] deleting colima                              
> Ignoring non-existent instance "colima"
> open /Users/abc123/.colima/_lima/colima/lima.yaml: no such file or directory
FATA[0002] error during teardown of vm: exit status 1   
➜  ~ git:(master) ✗ 

### Version

colima version 0.7.0
git commit: 4b14e8a9993b17d2e6f5071fd9059513111cd365
limactl version 0.22.0
qemu-img version 9.0.2
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] colima is not running       (colima start not working)

### Reproduction Steps

colima start

**Comment by abiosoft** [comment]
```sh
# remove all colima files
rm -rf ~/.colima

# try again
colima start
```

**Comment by dparm** [comment]
It worked, thank you!
