### ISSUE TITLE
downloads are performed twice

### ISSUE THREAD

**Issue by jconley** [abiosoft/colima#1098]
### Description

`downloadFile` runs `curl -Ls -o /dev/null -w %{url_effective} url` to get any redirected url.
this downloads the entire file to /dev/null (when fetching an image, can be ~400MB)
on a slow connection, it can time out; thus subverting the next call to curl with the ability to continue a (slow/failed) download

curl version: 8.7.1 (also tested 8.9.1)

a bit of searching+testing suggests to add `-I` to only download the headers:
`curl -s -L -I -o /dev/null -w '%{url_effective}' url`

### Version

colima version 0.7.0
git commit: 4b14e8a9993b17d2e6f5071fd9059513111cd365

runtime: docker
arch: aarch64
client: v27.1.1
server: v27.1.1
limactl version 0.22.0
qemu-img version 9.0.2

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Reproduction Steps

1.
2.
3.

**Comment by abiosoft** [comment]
Thanks for spotting this, I would verify and update accordingly (if that is the case).

**Comment by abiosoft** [comment]
This has been fixed. You can verify by installing the development version.

```sh
# remove stable version
brew uninstall colima

# install development version
brew install --head colima
```
