### ISSUE TITLE
`colima start` fails during provisioning docker with lima v0.6.4 and some host username

### ISSUE THREAD

**Issue by irisTa56** [abiosoft/colima#11]
- My environment:
    - colima: v0.1.9
    - lima: v0.6.4
    - Host OS: macOS Big Sur Version 11.4
- My host username (`Takayuki.Kobayashi`) is `firstname.lastname` form.
    - I found that, from lima v0.6.4, some problematic usernames fallback to `lima`.
        - Related to https://github.com/lima-vm/lima/pull/214, https://github.com/lima-vm/lima/pull/243
- Terminal output:
  ```
  $ colima start
  [colima] 09:42:29 creating and starting VM ...
  [colima] 09:43:24 provisioning VM ...
  [colima] 09:43:24 provisioning docker ...
  [colima] 09:43:24 provisioning docker in VM ...
  $ echo $?
  6
  $ colima status # errors related k8s is ok because I don't use it
  docker is installed VM?
  success

  docker is running in VM?
  success

  docker is installed on Host?
  success

  docker client on host can access the VM server?
  error

  kubernetes is installed in VM?
  error

  kubernetes is running in VM?
  error

  kubernetes client on host can access the VM?
  error

  some checks failed :(
  ```
- Extract from `~/.colima/out.log`:
  ```
  [...]
  time="2021-09-19T09:42:29+09:00" level=warning msg="local user \"Takayuki.Kobayashi\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
  [...]
  usermod: user 'Takayuki.Kobayashi' does not exist
  exit status 6
  ```

[When adding lima user to `docker` group](https://github.com/abiosoft/colima/blob/63222f415a5f71ee5451650cca04c796bcc80643/colima#L280-L281), it assumes that username on lima is the same with the host username.
But, for some problematic usernames, it doesn't exist on lima.

Currently my workaround is to specify username in [`socket.sh`](https://github.com/abiosoft/colima/blob/63222f415a5f71ee5451650cca04c796bcc80643/colima#L180) (by replacing `127.0.0.1` with `${USER}@127.0.0.1`) and start with overwritten `USER` (by `USER=lima colima start`), but there should be a better way...

**Comment by abiosoft** [comment]
Thanks for your detailed response and workaround.

I have actually considered this before but I thought it will be a rare case. I should work on a fix soon.

**Comment by abiosoft** [comment]
@irisTa56 can you try this version?https://raw.githubusercontent.com/abiosoft/colima/7e2bca1d8e4c7b0d598bcdf340f07f97c56ab83e/colima

I am pretty sure it is fixed now. But want to confirm from your end before making a new release.

Thanks.

**Comment by irisTa56** [comment]
@abiosoft 
Thank you very much for such a quick update!!

I confirmed the followings:

```
$ curl -LO https://raw.githubusercontent.com/abiosoft/colima/master/colima && sudo install colima /usr/local/bin/colima
[...]
$ colima delete
Are you sure you want to delete the VM and all settings? [y/N] y
[colima] 16:37:11 deleting docker and kubernetes configs ...
$ rm -rf ~/.colima # to remove my workaround script
$ colima start
[colima] 16:44:04 starting VM ...
[colima] 16:44:34 provisioning VM ...
[colima] 16:44:34 provisioning docker ...
[colima] 16:44:34 starting docker ...
[colima] 16:44:35 docker startup successful
[colima] 16:44:35 done
(base)   [21-09-19T16:44:35 Takayuki.Kobayashi@Y55-66738:~/_github/Raise_Server]
$ colima status
docker is installed VM?
success

docker is running in VM?
success

docker is installed on Host?
success

docker client on host can access the VM server?
success

kubernetes is installed in VM?
error

kubernetes is running in VM?
error

kubernetes client on host can access the VM?
error

some checks failed :(

// and docker commands works fine!
```

**Comment by irisTa56** [comment]
P.S.

I noticed that I didn't run `colima delete` successfully because of `kubectl: command not found`.
So I commented out [this line](https://github.com/abiosoft/colima/blob/7e2bca1d8e4c7b0d598bcdf340f07f97c56ab83e/colima#L440), and then confirm again:

```
$ colima delete
Are you sure you want to delete the VM and all settings? [y/N] y
[colima] 17:04:20 deleting docker and kubernetes configs ...
[colima] 17:04:20 deleting colima VM ...
[colima] 17:04:20 stopping docker ...
[colima] 17:04:21 stopping VM ...
[colima] 17:04:22 done
[colima] 17:04:24 deleting other configs ...
[colima] 17:04:24 done
$ colima start
[colima] 17:04:32 creating and starting VM ...
[colima] 17:05:28 provisioning VM ...
[colima] 17:05:28 provisioning docker ...
[colima] 17:05:28 provisioning docker in VM ...
[colima] 17:05:56 restarting VM to complete docker setup ...
[colima] 17:06:30 VM restarted
[colima] 17:06:31 starting docker ...
[colima] 17:06:31 docker startup successful
[colima] 17:06:31 done
$ colima status
docker is installed VM?
success

docker is running in VM?
success

docker is installed on Host?
success

docker client on host can access the VM server?
success

kubernetes is installed in VM?
error

kubernetes is running in VM?
error

kubernetes client on host can access the VM?
error

some checks failed :(
```

**Comment by abiosoft** [comment]
> P.S.
> 
> I noticed that I didn't run `colima delete` successfully because of `kubectl: command not found`.
> So I commented out [this line](https://github.com/abiosoft/colima/blob/7e2bca1d8e4c7b0d598bcdf340f07f97c56ab83e/colima#L440), and then confirm again:
> 

thanks for catching that
