### ISSUE TITLE
homebrew bump for v0.3.0

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#110]
I imaging you're already working on this, and apologize, but I don't see a PR in the homebrew queue for v0.3.0.

I was just going to bump the version requirement and run [ddev](https://github.com/drud/ddev) tests on colima 0.3.0 and found it wasn't there yet.

**Comment by abiosoft** [comment]
@rfay it was a community effort (see https://github.com/abiosoft/colima/issues/16), I'm not skilled with brew.

I am hereby mentioning the maintainer so he gets the notification @vladimir-kotikov. 
Anyone else is also free to do this.

Thanks.

**Comment by rfay** [comment]
OK, should be an easy followup. I always do a tap homebrew setup, which doesn't require any approval by the homebrew team or anything. We'll eventually probably want to figure out how to get this into the release process or automation for colima. 

And I forgot to say... CONGRATULATIONS ON v.0.3.0! It's working great.

**Comment by abiosoft** [comment]
> OK, should be an easy followup. I always do a tap homebrew setup, which doesn't require any approval by the homebrew team or anything. We'll eventually probably want to figure out how to get this into the release process or automation for colima.

And I just made another release :| Help wanted for this.

**Comment by abiosoft** [comment]
@rfay v0.3.0 is on brew already.

And FYI for the whomever is handling the next brew update, colima is no longer limited to macOS and works on both Linux and macOS.

**Comment by rfay** [comment]
@ChrisLane did it, https://github.com/Homebrew/homebrew-core/pull/93065 - Thanks @ChrisLane

Also thanks for updating 3.0.1 and adding linux! :)

**Comment by rfay** [comment]
@chenrui333 did the 3.0.1 bump, https://github.com/Homebrew/homebrew-core/pull/93077

I'll open a new issue for linux support.

**Comment by rfay** [comment]
* https://github.com/abiosoft/colima/issues/116
