### ISSUE TITLE
Provide an option to make out of range CPUs requests result in a warning rather than an error.

### ISSUE THREAD

**Issue by sflanker** [abiosoft/colima#1101]
### Description

I'm working with a docker compose file wherein the `cpus` setting for one of the services is higher than what I've configured for Colima. However in reality this container would run fine with fewer CPUs. It would be nice if I could configure Colima to only report a warning instead of an error when this happens.

**Comment by abiosoft** [comment]
Kindly follow the issue template next time.

Can you share the steps to reproduce and the error message you got?

**Comment by sflanker** [comment]
When you create a new GitHub issue and select "Feature Request" there is no template. It's just a description text box. FYI.

## Repro steps:

Install and start Colima with the default configuration.

On MacOS:

```
brew install colima
brew services start colima
```

 Create a docker-compose.yml that specifies more than the default available CPUs (2 on my system):

```yaml
services:
  busybee:
    image: busybox
    cpus: 4
    command: 'tail -f /dev/null'
```

Attempt to start this

```
docker compose up -d
```

Observed behavior:

```
Error response from daemon: Range of CPUs is from 0.01 to 2.00, as there are only 2 CPUs available
```

I think the default behavior is correct, however what I'm looking for is a configuration option to turn this message into a warning and just start the container with 2 (or whatever the max is) CPUs.

However, now that I've done a little more digging into how Colima works I think this would be the purview of the actual container runtime I am using, in this case Docker. So unless you have a different suggestion I think I can take my request there. Sorry for the confusion

**Comment by sflanker** [comment]
And I know I could change the colima config to change the CPU count, but I'm trying to avoid that, because the docker compose file I'm working with is just over provisioned.

**Comment by abiosoft** [comment]
I don't think there's much Colima can do in this regards. 
It's an error from Docker and I think the issue should be reported to Docker instead, like you suggested.
