### ISSUE TITLE
Mention steps needed to update to `0.3.0`

### ISSUE THREAD

**Issue by voxpelli** [abiosoft/colima#111]
Maybe its painless to update to `0.3.0`, but seeing eg. mentions of moving from Ubuntu to Alpine and such, that makes me think that it may be a bit more disruptive.

Could you document the steps needed to update, the consequences of those steps and, if relevant, the different levels of updating one can do (if one already have a Ubuntu VM, then maybe one won't get the Alpine one with `0.3.0`? And if so: How do one perform an upgrade where one do get the Alpine one?)

Since I installed colima using Homebrew I'll wait for #110 anyhow, but depending on the possibly destructive nature of an upgrade I will then consider whether I should `brew pin colima` in a similar fashion as I have with eg. `brew pin postgres` (as I like for my database to not be updated as part of a generic `brew upgrade`)

**Comment by abiosoft** [comment]
@voxpelli thanks for that. I would update the README and the release note accordingly.

The main requirement is that v0.3.0 requires a fresh start. i.e. `colima delete` existing instances.

**Comment by abiosoft** [comment]
Readme and release note has been updated.
