### ISSUE TITLE
Unable to start colima after upgrade to 0.7.3

### ISSUE THREAD

**Issue by joggeli34** [abiosoft/colima#1116]
### Description

After the upgrade, the colima service is not able to start anymore and failes with a "connection refused"
```
{"level":"debug","msg":"Creating iso file /Users/joggeli34/.colima/_lima/colima/cidata.iso","time":"2024-08-20T17:18:12+02:00"}
{"level":"debug","msg":"Using /var/folders/yd/fq77396j36q832zq7k7ygd8r0000gn/T/diskfs_iso2456784916 as workspace","time":"2024-08-20T17:18:12+02:00"}
{"level":"debug","msg":"Failed to detect CPU features. Assuming that AES acceleration is available on this Apple silicon.","time":"2024-08-20T17:18:12+02:00"}
{"level":"debug","msg":"OpenSSH version 9.7.1 detected","time":"2024-08-20T17:18:12+02:00"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2024-08-20T17:18:12+02:00"}
{"level":"info","msg":"hostagent socket created at /Users/joggeli34/.colima/_lima/colima/ha.sock","time":"2024-08-20T17:18:12+02:00"}
{"level":"info","msg":"Starting VZ (hint: to watch the boot progress, see \"/Users/joggeli34/.colima/_lima/colima/serial*.log\")","time":"2024-08-20T17:18:12+02:00"}
{"level":"fatal","msg":"dial unix /Users/joggeli34/.colima/_lima/_networks/user-v2/user-v2_fd.sock: connect: connection refused","time":"2024-08-20T17:18:12+02:00"}
```

brew services list shows follwoing:
```
brew services list  
Name    Status     User        File
colima  error  256 joggeli34 ~/Library/LaunchAgents/homebrew.mxcl.colima.plist
```

I'm using vz and have a apple m3 Pro

### Version

colima version 0.7.3
git commit: a66b375e8df84ff2860797efc683e66632bcbce3
limactl version 0.23.1
qemu-img version 9.0.2
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers
Docker version 27.1.2, build d01f264bcc

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] colima is not running

### Reproduction Steps

Just trying to start with `brew services restart colima`

**Comment by joggeli34** [comment]
Yes that did the job. 
Thanks for the help

**Comment by abiosoft** [comment]
This should be resolved now with the new release https://github.com/abiosoft/colima/releases/tag/v0.8.1.
