### ISSUE TITLE
Multiple environment/runtime/instance support

### ISSUE THREAD

**Issue by lunalucadou** [abiosoft/colima#1127]
### Description

I use Colima to run x86 Oracle DB containers for application testing in an x86_64 runtime on my ARM Mac. It works great, except now I also need to run Elasticsearch, which dies during startup with either a NullPointerException or the JRE encountering a fatal error.

Elasticsearch runs fine in the default ARM runtime (which makes sense, given that it has a native ARM build), but the Oracle container dies during startup because Rosetta2 is an imperfect translator (and unfortunately, this is Express Edition, which has no ARM builds).

So I have to juggle between the two, which would be fine if Colima could do multiple environments/instances. I don't care about running them concurrently, I just don't want to have to start fresh every time I switch from working on the part of the application that requires Oracle to the one that requires Elasticsearch and back, because re-downloading these containers is a lengthy process.

Looking at the documentation, there appears to be no way to juggle environments/instances, so I will have to manually make do messing around with symlinking `~/.colima`. I would like to request a more official way of doing this, whether that be through some separate Colima manager application or available as a parameter which I can specify with `colima start`.

**Comment by abiosoft** [comment]
You can run as many instances as you want concurrently. 
Passing an extra argument after the `start` command creates a new instance with the argument as the instance name.

```sh
# start the default one for arm containers e.g. elasticsearch
colima start 

# start another one for oracle db
colima start oracle --arch x86_64
```

They would both run fine. The only issue would be with switching docker contexts for the docker command.

You can either use `docker context use` or set the `DOCKER_HOST` environment variable.

* to point to the default context
    ```
    docker context use colima
    ```
* to point to the oracle context
    ```
    docker context use colima-oracle
    ```
* to check the current context
    ```
    docker context show
    ```

**Comment by codeape2** [comment]
Thanks! The answer is referenced here https://stackoverflow.com/questions/78614378/using-colima-how-can-i-run-aarch64-and-x86-64-docker-images-at-the-same-time

**Comment by lunalucadou** [comment]
I completely missed the `[profile]` argument, thanks!
