### ISSUE TITLE
homebrew formula for colima should support amd64 linux as well

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#116]
Currently the homebrew formula for colima only supports macOS, but it should support linux as well, see https://github.com/abiosoft/colima/issues/110#issuecomment-1012165342

The homebrew formula is at https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/colima.rb

Anybody should be able to do the required fixup.

**Comment by abiosoft** [comment]
Colima actually supports both amd64 and aarch64 linux.

**Comment by rfay** [comment]
Right, but homebrew does not support arm64.

**Comment by abiosoft** [comment]
Fixed https://github.com/Homebrew/homebrew-core/pull/102040

**Comment by rfay** [comment]
Thanks!
