### ISSUE TITLE
`colima nerdctl run -it -v /Users/er:/build avivace/iosevka-build` fails on Nix

### ISSUE THREAD

**Issue by erwagasore** [abiosoft/colima#117]
- Installed `colima` using `nix-env -iA colima` and it was successful.
- Started colima for containerd `colima start --runtime containerd` successfully.
- Installed nerdctl aliases on host using `colima nerdctl install -f` and worked.
- tried to run `colima nerdctl run -it -v /Users/er:/build avivace/iosevka-build` and any other run commands and fails with `FATA[0000] unknown shorthand flag: 'i' in -it

I am using `MacbookPro M1` and I am using `nix`, `home-manager` instead of `brew`.

**Comment by aaschmid** [comment]
@erwagasore @abiosoft -> https://github.com/NixOS/nixpkgs/pull/154815

**Comment by abiosoft** [comment]
I believe that this is fixed
