### ISSUE TITLE
Issue with port forwarding and latest lima 1.0

### ISSUE THREAD

**Issue by matejsp** [abiosoft/colima#1181]
### Description

When starting docker port forwarding does not work. I can run docker commands and start containers, however port forwarding is not working anymore.

### Version

colima version && limactl --version && qemu-img --version 
colima version 0.7.6
git commit: 3ab92f54210503770223a8c9bb61662725e23004

runtime: docker
arch: aarch64
client: v27.3.1
server: v27.3.1
limactl version 1.0.0
qemu-img version 9.1.1
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/matej.spiller-muys/.colima/default/docker.sock 

### Reproduction Steps

1. upgrade lima
2. colima stop
3. colima start
4. port forwarding is not working (not TCP not UDP)

### Expected behaviour

I was actually looking forward to UDP socket with docker.

### Additional context

Workaround is to run as:
LIMA_SSH_PORT_FORWARDER=true colima start

**Comment by abiosoft** [comment]
Thanks for reporting this.

**Comment by abiosoft** [comment]
This has been created as a workaround https://github.com/abiosoft/colima/pull/1182.

**Comment by abiosoft** [comment]
@matejsp can you confirm if the workaround fixes it?

```
brew install --head colima
```

**Comment by k0d3r1s** [comment]
@abiosoft it fixes it :) came here to report same issue but it is now working correctly

**Comment by matejsp** [comment]
Nice. The workaround works. But it is still workaround. 
Looking forward to proper solution so we can get UDP port forwarding working. 

Should we open another task for enabling new port forwarding? 
Why is it not working with new better and faster way?
Can you perhaps point me to what would need to be changed to achieve this?

**Comment by abiosoft** [comment]
I am not yet sure and I would need to do more testing to verify the root cause.

> Should we open another task for enabling new port forwarding?

@matejsp maybe we can utilise this issue for that https://github.com/abiosoft/colima/issues/708.

**Comment by matejsp** [comment]
Perfect!

**Comment by abiosoft** [comment]
A new release has been published.

**Comment by matejsp** [comment]
Hey based on the workaround made with 1.0.0 it is now impossible to test with LIMA_SSH_PORT_FORWARDER set to false:
https://github.com/abiosoft/colima/pull/1182/files

Would it be possible to change to true value only if not passed from outside.

**Comment by abiosoft** [comment]
> Would it be possible to change to true value only if not passed from outside.

Yeah, that can be done.

**Comment by abiosoft** [comment]
PR created https://github.com/abiosoft/colima/pull/1263

**Comment by matejsp** [comment]
Perfect! thank you. will test with latest lima changes if it works better
