### ISSUE TITLE
Colima and containers becoming unaccesible after lima 1.0.0 update

### ISSUE THREAD

**Issue by tonilampela** [abiosoft/colima#1185]
### Description

I think this issue is related to yesterday’s lima 1.0.0 update. Since I installed I’ve started to see all my containers becoming inaccessible after a random period of running. I use docker-compose and even docker-compose restart for a project just hangs.

There is a [new issue](https://github.com/lima-vm/lima/issues/2859) in lima github that might be related to that, but I don’t have technical knowledge to know for sure.

### Version

colima version 0.7.6
git commit: 3ab92f54210503770223a8c9bb61662725e23004
limactl version 1.0.0
qemu-img version 9.1.1

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/toni/.colima/default/docker.sock 

### Reproduction Steps

1. Start colima
2. Start some docker containers
3. Wait x minutes
4. Containers become unreachable

**Comment by msogrin** [comment]
I had a similar problem, but with VZ.
Containers became unresponsive.  After a few more minutes, Colima was reporting "Stopped" status for the profile without me stopping it.

**Comment by msogrin** [comment]
Recreating Colima profile from scratch results in the same behaviour.
Errors in ha.stderr.log, repeated many times
```
{"level":"debug","msg":"error in tcp tunnel for id: tcp-127.0.0.1:5432-127.0.0.1:64847 error:readfrom tcp 127.0.0.1:5432-\u003e127.0.0.1:64847: rpc error: code = Unavailable desc = error reading from server: EOF","time":"2024-11-07T09:44:33Z"}
{"error":"rpc error: code = Unavailable desc = error reading from server: EOF","level":"warning","msg":"guest agent events closed unexpectedly","time":"2024-11-07T09:44:33Z"}
```
Container itself (Postgres, in this case) seems to be working (printing new log messages), but inaccessible from network.

**Comment by msogrin** [comment]
Workaround from https://github.com/abiosoft/colima/issues/1181#issuecomment-2458980581 seems to work.

**Comment by abiosoft** [comment]
A release is imminent.

**Comment by abiosoft** [comment]
A new release has been published https://github.com/abiosoft/colima/releases/tag/v0.8.0.
