### ISSUE TITLE
Unable to start Colima using VZ on a brand new Mac

### ISSUE THREAD

**Issue by dcitterio** [abiosoft/colima#1188]
### Description

It is not possible to run Colima in a new Mac after Lima 1.0.0 was released.

Colima requires `qemu-img` to convert the downloaded image from qcow to raw, but the utils is not shipped with `colima` formula.
It is shipped with `qemu` that was previously a dependency from `lima` itself.

Now Lima has no longer this dependency

### Version

colima version 0.7.6
git commit: 3ab92f54210503770223a8c9bb61662725e23004
limactl version 1.0.0
zsh: command not found: qemu-img

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima start`

INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] creating and starting ...                     context=vm
INFO[0000] downloading disk image ...                    context=vm
FATA[0071] error starting vm: error at 'creating and starting': error getting qcow image: exec: "qemu-img": executable file not found in $PATH 

### Reproduction Steps

1. Remove `colima` and `lima` using brew
2. Clean up `colima` and `lima` caches
3. Install colima again using `brew install colima`
4. Run `colima start --network-address -t vz -c 3 -m 8 --vz-rosetta --verbose -f`

### Expected behaviour

Colima VM start with the expected configuration

**Comment by abiosoft** [comment]
This is being fixed https://github.com/abiosoft/colima/pull/1187.
A new release would follow suit.

**Comment by abiosoft** [comment]
This has been addressed in the latest release https://github.com/abiosoft/colima/releases/tag/v0.8.0.
