### ISSUE TITLE
Cannot reach applications on localhost

### ISSUE THREAD

**Issue by erzz** [abiosoft/colima#119]
From the beginning:

```bash
brew install colima
brew install docker
brew link docker

colima start

docker build -t test:latest .
docker run -p 8080:8080 test:latest

docker ps

CONTAINER ID   IMAGE         COMMAND                  CREATED              STATUS                        PORTS                                         NAMES
654fec3a53f2   test:latest   "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:49153->8080/tcp, :::49153->8080/tcp   angry_mirzakhani

```

Trying an request to http://localhost:8080 will just hang in the browser

Tried another known working container and same result

```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED         STATUS         PORTS                                       NAMES
476f0458b408   ghcr.io/xalvarez/github-team-dashboard:4.2.1   "java -jar /home/app…"   5 seconds ago   Up 3 seconds   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   friendly_ganguly
```

As a clue - I was trying out Rancher Desktop and also other lima based solutions.  But I cleared out those including the ~/.lima ~/.docker and anything else that looked related before starting with colime

**Comment by abiosoft** [comment]
@erzz are you sure it's nothing to do with your docker image, have your tried other containers like caddy or nginx?

```
docker run --rm -it -p 8080:80 caddy
```

**Comment by erzz** [comment]
Yes, as I said above I used a good known image too (github-team-dashboard)

But - I deleted a few more suspicious looking files and ran a couple of app deletion programs for anything related to Docker / lima / rancher and then rebooted. Now its working 🤞🏻  

Will post back after a few days use to report on any further issues or close

**Comment by abiosoft** [comment]
Something else is probably using the port already.

I do not believe this is an issue and will be closing this. Feel free to re-open if you experience otherwise.
