### ISSUE TITLE
x509 cert issues on docker pull

### ISSUE THREAD

**Issue by colton-freeman** [abiosoft/colima#1195]
### Description

I am having issues getting a docker pull to work with Colima. I have been trying to figure this out for hours now and have tried multiple different approaches to get this cert trusted but no dice.

This is the error
`Error response from daemon: Get "https://<registry>/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority`

If anyone has any advice please let me know. Also if you need more info please let me know.

### Version

colima version HEAD-38c20fc
git commit: 38c20fc1ee04d6202375fa66cb3c3e46571c413a

runtime: docker
arch: aarch64
client: v27.3.1
server: v27.3.1
limactl version 1.0.1

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/colton/.colima/default/docker.sock 

### Reproduction Steps

1. brew install --head colima
2. colima start
3. docker login (this succeeds)
4. docker pull <image>

### Expected behaviour

Docker pull works without any cert issues.

### Additional context

I have added the certs and trusted them to my systems keychain. I have also tried to add this to multiple locations within my system and have restarted Colima as well but no luck. I have also tried uninstalling and reinstalling Colima.

**Comment by colton-freeman** [comment]
`openssl s_client -connect gitlab.devops.nswccd.navy.mil:443 -CAfile ~/ca.crt` succeeds so the cert is fine. I do have Jamf installed on my machine so that could be playing a part in this but was curious if anyone has any suggestions.

**Comment by abiosoft** [comment]
Have you tried this https://docs.docker.com/desktop/troubleshoot-and-support/faqs/macfaqs/#add-client-certificates ?

**Comment by colton-freeman** [comment]
I have and unfortunately no luck. If that should solve this problem it is possible that there is a STIG on my machine from Jamf. I will look into that but any suggestions would be appreciated.

**Comment by zisuu** [comment]
Hi, I can use our internal docker registry by adding our company internal ca certs to `~/.docker/certs.d/`, as suggested by @abiosoft in the comment above. Colima imported these with the initial creation of the Colima VM. But you have to ensure that each `.crt` file only contains one cert, otherwise the update-ca-certificates import will ignore the file with something like this: `rehash: warning: skipping Intermediate contain exactly one certificate or CRL rehash: warning: skipping RootCA.pem,it does not contain exactly one certificate`

**Comment by colton-freeman** [comment]
i will look into that, thank you. for the time being i have just switched over to Rancher and everything is working fine. I prefer Colima so ill keep at this.

**Comment by colton-freeman** [comment]
for those struggling with this still, the fix for me was this
```
- brew install colima
- mkdir -p ~/.colima/default/certs/
- openssl s_client -showcerts -connect <registry>:443 </dev/null 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/.colima/default/certs/<name>.crt
- colima start --kubernetes --mount ~/.colima/default/certs:/etc/ssl/certs:rw
- docker login <registry>
```
pulling now works just fine.
