### ISSUE TITLE
VZ with Rosetta not working on MacOS 15.1.1 Sequoia

### ISSUE THREAD

**Issue by bobobobo** [abiosoft/colima#1204]
### Description

Unable to start Colima with rosetta support on MacOS 15.1.1. 

### Version

colima version HEAD-ad5102e
git commit: ad5102e433be710867578726d867d39cf1208d85

runtime: docker
arch: aarch64
client: v27.3.1
server: v27.3.1
limactl version 1.0.1
qemu-img version 9.1.0
Copyright (c) 2003-2024 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/bobo/.colima/default/docker.sock 

### Reproduction Steps

1. Start Colima with rosetta: colima start --vm-type=vz --vz-rosetta --arch aarch64 --very-verbose

This gives the following error:
Errors:
> [hostagent] Setting up Rosetta share
> [hostagent] Unable to configure Rosetta: failed to create a new rosetta directory share caching option: unsupported build target macOS version for 14.0 (the binary was built with __MAC_OS_X_VERSION_MAX_ALLOWED=130300; needs recompilation)

TRAC[0075] cmd ["lima" "sudo" "sh" "-c" "stat /proc/sys/fs/binfmt_misc/rosetta || echo ':rosetta:M::\\x7fELF\\x02\\x01\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x02\\x00\\x3e\\x00:\\xff\\xff\\xff\\xff\\xff\\xfe\\xfe\\x00\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xff\\xfe\\xff\\xff\\xff:/mnt/lima-rosetta/rosetta:OCF' > /proc/sys/fs/binfmt_misc/register"] 
> stat: cannot statx '/proc/sys/fs/binfmt_misc/rosetta': No such file or directory
> sh: 1: echo: echo: I/O error
WARN[0075] unable to enable rosetta: exit status 1 

### Expected behaviour

Colima started with rosetta support

**Comment by nonononoka** [comment]
Hi, I was facing same error, and it was fixed by `brew unlink lima` and `brew install --head lima`.
I'm curious why it was fixed by installing head. I was looking into the difference between head and release version, but I could not find the difference related to the rosetta.

@bobobobo

**Comment by bobobobo** [comment]
> Hi, I was facing the same error, and it was fixed by `brew unlink lima` and `brew install --head lima`. I'm curious why it was fixed by installing head. I was looking into [the difference between head and release version](https://github.com/lima-vm/lima/compare/v1.0.3...master?diff=split&w=), but I could not find the difference related to the rosetta.
> 
> [@bobobobo](https://github.com/bobobobo)

I think the fix was released earlier than lima 1.0.3, but colima had a dependency to an older version. So you probably did not need HEAD, I think 1.0.3 would have worked just as good.

**Comment by nonononoka** [comment]
@bobobobo 
Thank you for your quick reply!
How was this problem fixed? Could you specify the related commit to solve this problem?
I saw https://github.com/lima-vm/lima/issues/2767 , but I didn't figure out how it was fixed.

**Comment by bobobobo** [comment]
@nonononoka 
I think this is the PR that fixes the problem: https://github.com/lima-vm/lima/pull/2773
