### ISSUE TITLE
Lingering `.colima/_lima/_networks` files prevent start

### ISSUE THREAD

**Issue by lloeki** [abiosoft/colima#1212]
### Description

Colima sometimes fails to start due to lingering files. This is Apple VZ, not QEMU.

Attempted to clean up with `colima stop -f`, but still seeing this:

```
failed to stop usernet "user-v2": Get "http://lima/services/dhcp/leases": dial unix /Users/<USER>/.colima/_lima/_networks/user-v2/user-v2_ep.sock: connect: connection refused
```

After making sure no `lima` or `colima` process remained up (manually killing them if need be), this makes it work:

```
rm -rf /Users/$USER/.colima/_lima/_networks
colima start # this time it's OK
```

### Version

```
$ colima --version
colima version 0.7.6
$ limactl --version
limactl version 0.22.0
```

Using `vz`, not `qemu`, so:

```
$ sw_vers 
ProductName:		macOS
ProductVersion:		15.2
BuildVersion:		24C101
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/loic.nageleisen/.colima/default/docker.sock 
```

### Reproduction Steps

1. unknown, happens kind of randomly
2. maybe an unclean/partial stop on, say, reboot? or some race condition on restarting?

### Expected behaviour

- at a minimum: `colima stop -f` cleaning it all up
- better: ensure colima stops cleanly

**Comment by abiosoft** [comment]
This should be resolved now.
