### ISSUE TITLE
Docker registry mirror does not work

### ISSUE THREAD

**Issue by zisuu** [abiosoft/colima#1224]
### Description

According to #225 and https://docs.docker.com/docker-hub/image-library/mirror/, it should be possible to set a custom docker registry mirror in the docker config.json file:
```json
  "registry-mirrors": [
    "https://docker.tools.mycompany.zz"
  ]
```
This registry has a valid TLS certificate for which the CA cert chain has already been added to Colima. So there is no need to have it as [insecure registry](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#how-to-customize-docker-config-eg-add-insecure-registries).

We have already used this configuration for the Docker Desktop. We are used to the behaviour that if you pull an image without defining the registry, it uses the custom mirror first. But with Colima, this does not work.

If I do a `docker pull busybox:latest` it uses docker.io instead of the prefix from our registry mirror:

```bash
latest: Pulling from library/busybox
9c0abc9c5bd3: Pull complete
Digest: sha256:2919d0172f7524b2d8df9e50066a682669e6d170ac0f6a49676d54358fe970b5
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
```

It is possible to pull via our registry with Colima manually:
```bash
docker pull docker.tools.mycompany.zz/library/busybox:latest
latest: Pulling from library/busybox
9c0abc9c5bd3: Pull complete
Digest: sha256:2919d0172f7524b2d8df9e50066a682669e6d170ac0f6a49676d54358fe970b5
Status: Downloaded newer image for docker.tools.mycompany.zz/library/busybox:latest
docker.tools.mycompany.zz/library/busybox:latest
```

I've set the `registry-mirrors` configuration in the following places:
```bash
> myuser@colima:/Users/myuser$ cat .docker/daemon.json | grep mirror -C 1
  },
  "registry-mirrors": [
    "https://docker.tools.mycompany.zz"
> myuser@colima:/Users/myuser$ cat .colima/default/colima.yaml | grep mirror -C 1
docker:
  registry-mirrors:
    - https://docker.tools.mycompany.zz
> myuser@colima:/Users/myuser$ cat /etc/docker/daemon.json | grep mirror -C 1
  },
  "registry-mirrors": [
    "https://docker.tools.mycompany.zz"
```

Am I missing something, or is this also not working for others, e.g. a bug?

### Version

```bash
> colima version && limactl --version && qemu-img --version
colima version 0.8.1
git commit: 96598cc5b64e5e9e1e64891642b91edc8ac49d16

runtime: docker
arch: aarch64
client: v27.4.0
server: v27.4.0
limactl version 1.0.2
zsh: command not found: qemu-img
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```bash
> colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/myuser/.colima/default/docker.sock
```

### Reproduction Steps

1. Set custom docker registry mirror as explained in the description and restart colima
2. `docker pull busybox:latest`
3. check in the output if the mirror has been used or not

### Expected behaviour

The busybox should be pulled directly from the custom docker mirror, not docker.io.

Expected:
```bash
docker pull busybox:latest
latest: Pulling from library/busybox
9c0abc9c5bd3: Pull complete
Digest: sha256:2919d0172f7524b2d8df9e50066a682669e6d170ac0f6a49676d54358fe970b5
Status: Downloaded newer image for docker.tools.mycompany.zz/library/busybox:latest
docker.tools.mycompany.zz/library/busybox:latest
```
Actual:
```bash
docker pull busybox:latest
latest: Pulling from library/busybox
9c0abc9c5bd3: Pull complete
Digest: sha256:2919d0172f7524b2d8df9e50066a682669e6d170ac0f6a49676d54358fe970b5
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
```

### Additional context

I am using the Ubuntu Colima image, not the Alpine.

**Comment by abiosoft** [comment]
Can you share the output of the following command.

```
colima ssh -- cat /etc/docker/daemon.json
```

**Comment by zisuu** [comment]
sure:
```bash
> colima ssh -- cat /etc/docker/daemon.json
{
  "exec-opts": [
    "native.cgroupdriver=cgroupfs"
  ],
  "features": {
    "buildkit": true
  },
  "proxies": {
    "http-proxy": "http://host.docker.internal:3128",
    "https-proxy": "http://host.docker.internal:3128",
    "no-proxy": "local,localhost,10.0.0.0/8,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.168.0.0/16"
  },
  "registry-mirrors": [
    "https://docker.tools.mycompany.zz"
  ]
}
```

**Comment by zisuu** [comment]
@abiosoft you could try with
```json
{
  "registry-mirrors": ["https://mirror.gcr.io"]
}
```
that is googles public mirror, the coverage of all public Dockerhub images is not guaranteed, but the busybox seems to be there:
```bash
docker pull mirror.gcr.io/busybox:latest
latest: Pulling from busybox
9c0abc9c5bd3: Pull complete
Digest: sha256:2919d0172f7524b2d8df9e50066a682669e6d170ac0f6a49676d54358fe970b5
Status: Downloaded newer image for mirror.gcr.io/busybox:latest
mirror.gcr.io/busybox:latest
```

**Comment by zisuu** [comment]
Sorry, I think I am wrong. I reproduced the same steps with the same configuration as Docker Desktop on a Windows 11 machine, and it behaved the same way. I was misunderstanding the docker configuration and behaviour. It seems like Docker never appends the custom registry mirror with this configuration. :-(

**Comment by carljmosca** [comment]
Apologies for commenting on a closed issue; I noticed a few others with this same issue.  I made some updates to the FAQ in a fork [here](https://github.com/carljmosca/colima/blob/main/docs/FAQ.md#how-to-customize-docker-config-eg-adding-insecure-registries-or-registry-mirrors) (starting with the Note:) which may be relevant.
