### ISSUE TITLE
Failed to start Colima because of username is invalid

### ISSUE THREAD

**Issue by Danny521** [abiosoft/colima#125]
When I start Colima, I got this error. Is there any solution to solve this except change account name?
```
INFO[0000] starting ...                                  context=vm
> msg="Using the existing instance \"colima\""
> msg="[hostagent] local user \"tao.zhang1\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] json: cannot unmarshal string into Go struct field Proxies.SPNetworkDataType.Proxies.HTTPPort of type int" fields.level=fatal
> msg="host agent process has exited: exit status 1"
```

**Comment by abiosoft** [comment]
@Danny521 looks like this upstream issue https://github.com/lima-vm/lima/issues/407.

To get more details, can you kindly do the following.

* start colima with verbose enabled i.e. `colima start --verbose` and share the output.
* try using lima directly `limactl start` and see if you see same error.

**Comment by jandubois** [comment]
The message about your user name is just informational; it just informs you that your user name inside the VM is `lima`.

The problem you are running into is https://github.com/lima-vm/lima/issues/403. It has been fixed in lima 0.8.0, so please update.

**Comment by abiosoft** [comment]
@Danny521 you can do that via brew `brew upgrade colima lima`.

Actually, the latest version of colima requires lima 0.8.1 on brew, so you're likely running an older version of colima as well.

**Comment by Danny521** [comment]
@jandubois @abiosoft Thanks. It is worked after upgrade lima to the latest version.
