### ISSUE TITLE
docker commands fail with `error during connect ...`

### ISSUE THREAD

**Issue by lflorent** [abiosoft/colima#126]
Hi,

I trying colima for the first time and have some difficulties.

### My local env on MBP M1 Pro

```bash
% sw_vers
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

```bash
% colima version
colima version 0.3.2
git commit: 272db4732b90390232ed9bdba955877f46a50552

runtime: docker
arch: x86_64
```

```
% lima --version
limactl version 0.8.1
```

```
% docker --version
Docker version 20.10.11, build dea9396
```

```
% docker context ls
NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT                                      KUBERNETES ENDPOINT   ORCHESTRATOR
colima *            moby                colima                                    unix:///Users/lohenflorent/.colima/docker.sock                             
default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                                swarm
desktop-linux       moby            
```

```
% colima status
INFO[0000] colima is running                            
INFO[0000] runtime: docker                              
INFO[0000] arch: x86_64
```

### My Goal

 Try to run some linux/amd64 containers on my arm64 MBP M1 Pro.

### My Issue

After have run with success

`% colima start --arch x86_64 --cpu 2 --memory 8 `

I have errors when try some docker commands : 

```
% docker ps
error during connect: Get "http://%2FUsers%2Flohenflorent%2F.colima%2Fdocker.sock/v1.24/containers/json": EOF
```

```
% docker images
error during connect: Get "http://%2FUsers%2Flohenflorent%2F.colima%2Fdocker.sock/v1.24/images/json": EOF
```
Maybe i missed something... 

Thanks for your help.

**Comment by abiosoft** [comment]
This is very strange, it seems the docker client is treating the unix socket as an http endpoint.

If you have homebrew installed, can you install docker client from there? Trying to be sure if it's not something specific to the docker client in Docker for Mac.

```
brew install docker
brew link docker
```
Then try again and see if it's same error.

You can always revert the homebrew's version with

```sh
brew unlink docker # temporary
brew uninstall docker # permanent
```

**Comment by lflorent** [comment]
@abiosoft 

First, thanks for your prompt help. I really appreciate.

Yes it's very strange ... finally after reboot my machine the error has disappeared by magic ! 

I had forgotten to specify when I opened this issue that with the default docker context (the Docker for Mac one) the docker commands didn't throw error. 

I really don't know why with the new installed colima context he treated the unix socket as an http endpoint.

Maybe if I had time later in the week I'll try to fully reinstall colima (with brew) to maybe get the error again ...

**Comment by kukat** [comment]
had the same issue, `colima stop && colima start` fixed it
