### ISSUE TITLE
`colima ssh` returns an error `ash: cd: line 1: can't cd to XXX` before the command

### ISSUE THREAD

**Issue by georgettica** [abiosoft/colima#128]
# Issue
the command fails but returns the necessary output after

# Expected 
that the error won't happen (that the code won't try and `cd` into the hosts folder)

# Repro steps:
```shell
$ mkdir -p /var/folders/53/xjgvxj6d39d3wsspv7prff640000gn/T/tmp.acQGOCzw0M
$ cd  /var/folders/53/xjgvxj6d39d3wsspv7prff640000gn/T/tmp.acQGOCzw0M
$ colima ssh -- echo hi
ash: cd: line 1: can't cd to /var/folders/53/xjgvxj6d39d3wsspv7prff640000gn/T/tmp.acQGOCzw0M: No such file or directory
hi
$ cd ${HOME}
$ colima ssh -- echo hi # no error happens here
hi
```

# related
#127 
I found this by trying the command in a different folder

**Comment by abiosoft** [comment]
This is expected as colima does not have access to files and folders outside of $HOME directory.
I will be closing this as this is not an issue.

The error message may be better but that is not priority at the moment.

**Comment by georgettica** [comment]
but why is colima try and access these files?
I just want to `echo hi` (as an example)

**Comment by abiosoft** [comment]
> but why is colima try and access these files? I just want to `echo hi` (as an example)

It is not accessing the files. For convenience, Lima `cd` into your working directory.
e.g. if you're in `$HOME/projects`, `colima ssh` will drop you into `$HOME/projects` in the VM.
