### ISSUE TITLE
PHP code has problem reading files from host-mounted volume

### ISSUE THREAD

**Issue by kumikumi** [abiosoft/colima#129]
PHP code running inside a container in some cases fails to access files from outside the container.

This is a local development setup with a volume mounted to the php container from outside (ie. it is shared between the container and host).

### Steps to reproduce

Save the following as `test.php`: 

```php
<?php
$dir = new RecursiveDirectoryIterator(__DIR__);
$iterator = new RecursiveIteratorIterator($dir);
$iterator->setMaxDepth(0);
$files = iterator_to_array($iterator);
echo "Number of files: ".count($files).PHP_EOL;
```

Running `php test.php` outside Docker correctly prints out the number of files in the directory: e.g. `Number of files: 12`
Running it inside a container (ie. with docker exec) prints out `Number of files: 0`

Here is a one-liner to test it with (after creating test.php)
```
docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:7.4-cli php test.php
```

(Should never print Number of files: 0 because the directory contains at least the test.php file itself)

**Comment by abiosoft** [comment]
@kumikumi what version of Colima are you using?

**Comment by abiosoft** [comment]
I would advise upgrading both lima and colima `brew upgrade colima lima` and ensure lima version `>=0.8.1`, there is a filesystem cache fix in the latest release.

**Comment by kumikumi** [comment]
`lima --version` prints out `limactl version 0.8.1`

**Comment by kumikumi** [comment]
@abiosoft Are you able to reproduce this issue? Is there anything I can do to help?

**Comment by abiosoft** [comment]
I believe it is related to https://github.com/lima-vm/lima/pull/556. It is merged but would not be available until the next Lima release.

Can you build lima from source and see if it fixes it?

**Comment by kumikumi** [comment]
I haven't built it from source before, but I can give it a try later today, thanks.

**Comment by abiosoft** [comment]
I will try to reproduce it as well as see.

**Comment by jandubois** [comment]
> I believe it is related to https://github.com/lima-vm/lima/pull/556. It is merged but would not be available until the next Lima release.

It is not merged, it has been replaced by https://github.com/lima-vm/lima/pull/564, which makes the `cache` option configurable via `lima.yaml`, but the default remains `false`. You have to explicitly enable caching again to revert the previous change.

**Comment by LionsAd** [comment]
I strongly suggest to give `mutagen` a try for PHP projects. (We use it with ddev, which recently added `colima` support in dev version. Thanks for this project!)

**Comment by kumikumi** [comment]
@abiosoft I have found out that this issue is a possible regression. Related to #136 ? My coworker could not reproduce this issue prior to upgrading to the current version, but now it reproduces for him (at HEAD-784cec0).

The "good" version was:

colima version HEAD-5090a0a
git commit: 5090a0aee5e6da0fa7adf23d577cc9edcda5630a

**Comment by glook** [comment]
I have the same issue with running phpUnit tests it uses same iteration classes

```php
$iterator->append(
                    new Iterator(
                        $path,
                        new \RecursiveIteratorIterator(
                            new \RecursiveDirectoryIterator($path, \RecursiveDirectoryIterator::FOLLOW_SYMLINKS | \RecursiveDirectoryIterator::SKIP_DOTS)
                        ),
                        $suffixes,
                        $prefixes,
                        $exclude
                    )
                );
```

**Comment by luisdavim** [comment]
> I strongly suggest to give `mutagen` a try for PHP projects. (We use it with ddev, which recently added `colima` support in dev version. Thanks for this project!)

Is there any place I can find some documentation on how to setup mutagen with colima?

Would it make sense for colima to officially support mutagen and make is easy to setup?

**Comment by jandubois** [comment]
> I have found out that this issue is a possible regression. Related to #136 ?

#136 looks different, as it doesn't seem to mount host files at all.

> My coworker could not reproduce this issue prior to upgrading to the current version, but now it reproduces for him (at HEAD-784cec0).

I'm very much interested if this is a regression in lima or in colima. The sshfs caching options for host file access have changed in lima 0.8.1, and are breaking composer when used with the host file system.

If possible, could you try testing your setup with both lima 0.8.0 or earlier, and 0.8.1, and report if this makes a difference?

**Comment by jandubois** [comment]
Alternatively, could you provide enough instructions for somebody not familiar with PHP to reproduce the error, so I could try it myself with different lima configurations?

For example https://github.com/dschaaff/rancher-desktop-issue-1349 is a user-provided repo to showcase the composer problem, that made it easy to investigate for me (and to confirm that the changing default for `sshfs.cache` was indeed the root cause).

**Comment by kumikumi** [comment]
@jandubois Thank you for your interest in solving this. To reproduce, please follow the instructions in the original post.

Just to recap, while Colima/Docker is running: 

1. Save the provided code snippet as `test.php`
2. Navigate to same directory as where you saved test.php in your terminal
3. Copy-paste the attached oneliner to your terminal and press enter
4. If it prints `Number of files: 0`, then you are affected by the issue.

**Comment by gms8994** [comment]
Can confirm this happens for me as well since switching from Docker Desktop. Installed lima 0.8.0

```
brew tap-new $USER/local-lima
brew extract --version=0.8.0 lima $USER/local-lima
brew install lima@0.8.0 
brew link --overwrite lima@0.8.0
lima --version
> limactl version 0.8.0
colima delete
colima start
# rebuild images, restart via docker-compose
```

And it works correctly.

**Comment by glook** [comment]
In lima 0.8.2 everything works fine  🎉

<img width="352" alt="CleanShot 2022-02-01 at 10 24 37@2x" src="https://user-images.githubusercontent.com/545998/151928194-1928e9e2-a2cb-4c96-bb10-929ba8e2ba18.png">

**Comment by kumikumi** [comment]
I can confirm this to be resolved with lima 0.8.2. Thanks everyone!

**Comment by enavarrocu** [comment]
> > I strongly suggest to give `mutagen` a try for PHP projects. (We use it with ddev, which recently added `colima` support in dev version. Thanks for this project!)
> 
> Is there any place I can find some documentation on how to setup mutagen with colima?
> 
> Would it make sense for colima to officially support mutagen and make is easy to setup?

Did you found anything?

**Comment by rfay** [comment]
@enavarrocu  DDEV fully packages mutagen and works perfectly with colima+mutagen, in fact that's the recommended environment. DDEV is a full local dev environment for PHP (and other) websites. It's free and open-source. It's easy to try, and you'll like it.  You'll be up and going in a few minutes. https://ddev.readthedocs.io/en/latest/

**Comment by enavarrocu** [comment]
@rfay Thanks for your reply. Unfortunately, I use a completely different stack that is not related to PHP.
