### ISSUE TITLE
Possible to add support for `host.docker.internal`?

### ISSUE THREAD

**Issue by billyvg** [abiosoft/colima#13]
[Docker Desktop provides this](https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds) to allow containers to connect to a service on the host.

[lima provides `host.lima.internal`](https://github.com/lima-vm/lima/blob/master/docs/network.md#host-ip-19216852). It would be great to have colima maintain this compatibility.

**Comment by abiosoft** [comment]
The host is accessible from the container at the fixed address `192.168.5.2`, you can use the ip directly.

We may look at adding something similar for convenience but it would not be hardcoded to `host.docker.internal`, rather something more generic as Colima will not limited to docker containers anymore from v0.2.0.

**Comment by billyvg** [comment]
Thanks, it'd be nice to have an entry for `host.docker.internal` for migration purposes, but makes sense to not have it long-term.
