### ISSUE TITLE
How to switch back to Docker Desktop?

### ISSUE THREAD

**Issue by jgosmann** [abiosoft/colima#134]
I am having some issues with Colima that I do not have time to investigate right now. Instead I wanted to switch back to Docker Desktop temporarily. However, my Docker command line still looks for the wrong socket:
```
$ docker ps
Cannot connect to the Docker daemon at unix:///Users/gosmannj/.colima/docker.sock. Is the docker daemon running
```
How do I fix this? Would it be possible to document how to properly uninstall Colima or switch back and forth with Docker Desktop?

**Comment by jgosmann** [comment]
To answer my own question:
Set `currentContext` to `"desktop-linux"` in `~/.docker/config.json`.

**Comment by abiosoft** [comment]
By simply switching to the default docker context.

```
docker context use default
```

**Comment by kamilmodest** [comment]
Also, don't forget to remove (or comment) these rows from your `.zshrc` or `.bshrc` file:

```shell
export DOCKER_HOST="unix://${HOME}/.colima/docker.sock"
export TESTCONTAINERS_HOST_OVERRIDE="$(colima ls -j | jq -r '.address')"
```

and `unset` these variables if they're already set.

**Comment by CloudzSander** [comment]
> Also, don't forget to remove (or comment) these rows from your `.zshrc` or `.bshrc` file:
> 
> ```shell
> export DOCKER_HOST="unix://${HOME}/.colima/docker.sock"
> export TESTCONTAINERS_HOST_OVERRIDE="$(colima ls -j | jq -r '.address')"
> ```
> 
> and `unset` these variables if they're already set.

This fixed it for me, thanks! 😄
