### ISSUE TITLE
ctop compatibility on M1 pro

### ISSUE THREAD

**Issue by nadworny** [abiosoft/colima#142]
I'm using [ctop](https://github.com/bcicen/ctop) as an easy way to debug the containers. Unfortunately, after start the ctop tool, it can't connect to the runtime with the following error:
`[11:15:50 CET] Get "http://unix.sock/info": dial unix /var/run/docker.sock: connect: no such file or directory  `

I've tried setting the `DOCKER_HOST` to something that I found in https://github.com/abiosoft/colima/issues/141 but I'm still getting the following error: `[11:14:35 CET] Get "http://unix.sock/info": dial unix /Users/lima/.colima/docker.sock: connect: no such file or directory  `

Any idea what am I missing or maybe it's a problem of ctop itself? Thanks

# Environment
macos 12.1
MacBook Pro (14-inch, 2021)
colima version 0.3.2
git commit: 272db4732b90390232ed9bdba955877f46a50552
runtime: docker
arch: aarch64

**Comment by abiosoft** [comment]
Ensure you use the same value you see in `docker context ls` including the triple slash e.g.

```
export DOCKER_HOST=unix:///Users/lima/.colima-docker/docker.sock
```

**Comment by regulskimichal** [comment]
Wasn't colima creating a symlink before in /var/run? Many of my colleagues in my company report similar issue but in IntelliJ. Something has changed and suddenly many people experience this problem.

**Comment by nadworny** [comment]
setting docker_host worked 👍

**Comment by abiosoft** [comment]
> Wasn't colima creating a symlink before in /var/run? Many of my colleagues in my company report similar issue but in IntelliJ. Something has changed and suddenly many people experience this problem.

@regulskimichal Colima switched from overriding the default docker socket by using docker contexts instead, which is a cleaner solution as it no longer clashes with other docker servers (e.g. Docker for Mac) and supports creating multiple instances with `--profile` flag.

With JetBrains IDEs, simply specify the docker socket path, retrievable via `docker context ls` in the docker configuration.

<img width="359" alt="Screenshot 2022-01-26 at 4 33 42 PM" src="https://user-images.githubusercontent.com/240448/151194679-a4c7769d-336b-4819-9a0b-ff5cc8f3b6d2.png">

<img width="681" alt="Screenshot 2022-01-26 at 4 34 51 PM" src="https://user-images.githubusercontent.com/240448/151194713-4db08e63-326a-483b-8eb9-05ce3a0b34c4.png">

**Comment by abiosoft** [comment]
I may introduce an option of overriding the default docker context in future releases. 

If you prefer the previous experience, you can do that by manual symlink.

```
sudo rm -rf /var/run/docker.sock
sudo ln -s "$HOME/.colima/docker.sock" /var/run/docker.sock
```

**Comment by mrmachine** [comment]
An option to override the default docker context would be great for users who are not running Docker Desktop side by side or are otherwise only using colima and therefore have no need for switching contexts.
