### ISSUE TITLE
Docker daemon support

### ISSUE THREAD

**Issue by TheFriendlyCoder** [abiosoft/colima#144]
I just discovered your project and was testing it out for some of the projects I work on which use the Docker REST APIs to interact with the Docker daemon to orchestrate container operations. Unfortunately I'm getting errors in my projects because I am unable to connect to the same API endpoints as those exposed by Docker. Do you support container orchestration via REST APIs or expose an API that is compatible with the Docker daemon? If so, how do I go about setting up my environment to work with it?

**Comment by TheFriendlyCoder** [comment]
For context, if you run any of the examples provided in the [Docker SDK docs](https://docs.docker.com/engine/api/sdk/examples/) showing how to do basic interactions with Docker using the API, none of them work. For example:

`curl --unix-socket /var/run/docker.sock http://localhost/v1.41/containers/json`

just returns:

`curl: (7) Couldn't connect to server`

Similar problems happen when using the [dockerpy](https://docker-py.readthedocs.io/en/stable/) library for Python as well.

**Comment by TheFriendlyCoder** [comment]
I just figured out the cause of my problem. For others benefit, it looks like the default unix socket used by the Docker daemon is located under /var/run/docker.sock. However, colima puts this socket in the current users' home folder under ~/.colima/docker.sock. Updating your connection parameters to compensate should fix the problem, as in:

`curl --unix-socket /Users/kevinp/.colima/docker.sock http://localhost/v1.41/containers/json`

**Comment by sdemura** [comment]
I was able to `ln -sf ~/.colima/docker.sock /var/run/docker.sock` worked for me.

**Comment by riccardoNovaglia** [comment]
It works for me too! Thanks!

**Comment by gregorybosch** [comment]
Working well for me thus far.  I had forgotten to remap a couple of volumes on colima startup.  Thanks for the fix.
