### ISSUE TITLE
fail to "download and install" ,doing "colima start --with-kubernetes"

### ISSUE THREAD

**Issue by ronnin** [abiosoft/colima#149]
`$ colima start --runtime containerd --cpu 4 --memory 8 --disk 100 --with-kubernetes
INFO[0000] starting colima
INFO[0000] already running                               context=vm
INFO[0000] starting ...                                  context=containerd
INFO[0000] downloading and installing ...                context=kubernetes
> ash: cd: line 1: can't cd to /opt/homebrew/etc/privoxy: No such file or directory
> gzip: invalid magic
FATA[0000] error provisioning kubernetes: error at 'downloading and installing': exit status 1`

Q:
1.  why `cd to /opt/homebrew/etc/privoxy`?  
A local proxy with http_proxy and https_proxy to http://127.0.0.1:9889 is set in host Mac OS, which is powered by privoxy, whose configuration is located in  /opt/homebrew/etc/privoxy. but why colima  'cd to it' ?
2.  It seems a broken file was downloaded. How can I clean it up?

Thanks for your hardwork.

My Env:
OS:  macOS 12.1
CPU: M1 Max
colima:  0.3.2
runime: containerd

**Comment by davidwincent** [comment]
I have the same problem on M1 Pro.

Have tried the following,

1. kubernetes reset
```bash
colima kubernetes reset
INFO[0000] deleting ...                                  context=kubernetes
INFO[0000] reverting config ...                          context=kubernetes
INFO[0000] downloading and installing ...                context=kubernetes
> gzip: invalid magic
```

2. delete and reinstall
```bash
colima delete
rm -r ~/Library/Caches/lima
rm -r ~/Library/Caches/colima
colima start -a aarch64 -c 8 -d 100 -m 16 -r containerd -k
INFO[0000] starting colima
INFO[0000] creating and starting ...                     context=vm
INFO[0512] starting ...                                  context=containerd
INFO[0517] waiting for startup to complete ...           context=containerd
INFO[0517] downloading and installing ...                context=kubernetes
> gzip: invalid magic
FATA[1162] error provisioning kubernetes: error at 'downloading and installing': exit status 1
```

3. docker runtime
```bash
brew install docker
colima --verbose start -a aarch64 -c 8 -d 100 -m 16 -r docker -k
INFO[0000] starting colima
INFO[0000] already running                               context=vm
INFO[0000] provisioning ...                              context=docker
> colima
> Current context is now "colima"
INFO[0001] starting ...                                  context=docker
>  * Starting Docker Daemon ... [ ok ]
INFO[0006] waiting for startup to complete ...           context=docker
INFO[0006] downloading and installing ...                context=kubernetes
> gzip: invalid magic
FATA[0006] error provisioning kubernetes: error at 'downloading and installing': exit status 1
```

```
colima version
colima version HEAD-6f7f8a9
git commit: 6f7f8a9662984b23a110473095929f1ef3a671d8

runtime: docker
arch: aarch64
client: v20.10.12
server: v20.10.11
```

**Comment by anuragagarwal561994** [comment]
Duplicate: https://github.com/abiosoft/colima/issues/176

Found the issue after several hit and trials.

These are the steps for installing kubernetes:

https://github.com/abiosoft/colima/blob/57469b9e8c02404498e134f1afb0f824424fa768/environment/container/kubernetes/k3s.go#L17

3 files are downloaded using https://github.com/abiosoft/colima/blob/main/util/downloader/download.go

If you read the description above, the files are cached on your host system and are made available to your colima vms.

Cache Directory from https://github.com/abiosoft/colima/blob/v0.3.3/config/config.go is `os.UserCacheDir`

And from https://pkg.go.dev/os#UserCacheDir it is stated where are the cache directories located for different OS.

For Mac it is at $HOME/Library/Caches/colima/cache.

So the whole picture here is that colima while installing kubernetes downloads and caches 3 files on your host and makes it available to your guest vm. It stores these files as `sha256sum` of the url from where the files are downloaded.

Now if there occurs an error while downloading the files or there occurred network issue or you cancelled the installing in mid way, it may happen that your caches are not consistent and are left in either .downloading state or the file size is 0.

In those cases, either the colima setup would get stuck or will copy the empty files as gz to the guest vm where when it will do gzip -f -d <empty file> it will throw `invalid magic`. If there is a .downloading file, it might get stuck forever.

@abiosoft I guess few corner cases are unhandled here. At least user should be given an option to may be evict this cache till the time these cases are handled. What do you think?

**Comment by abiosoft** [comment]
> Solution for now is to delete these caches manually if you found something like 0 bytes file or .downloading type of files in your caches. Meanwhile @abiosoft I guess there should be a more robust solution for the same as it is common to get network errors while downloading 200-400 MB of data.

@anuragagarwal561994  The download actually does resume if terminated. Though nothing fancy is done, it simply relies on curl's resume ability which works fine in my tests. 

Nonetheless, I do agree that assumptions should be minimal and a better download verification should be done. I will also consider providing a way to purge the cache.

Thanks for your observation

**Comment by ronnin** [comment]
Thank you all.

**Comment by cheburakshu** [comment]
Worked for me when I deleted the configs under `~/.colima`

**Comment by Xianyu026** [comment]
### 

> **__**
