### ISSUE TITLE
How to use custom kubernetes version with Colima

### ISSUE THREAD

**Issue by iamkryptonite** [abiosoft/colima#152]
Currently Colima is running K8s server version `v1.22.4+k3s1`. But I want `v1.19.16+k3s1` because in the latest version, certain apis have been deprecated. Is there a way to do that? Basically when I run `colima start -k` it should run `v1.19.16+k3s1` version.

```
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4+k3s1", GitCommit:"bec170bc813e342cdba9710a1a71f8644c948770", GitTreeState:"clean", BuildDate:"2021-11-29T16:49:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by zhengyongtao** [comment]
I also think this feature is very important.

**Comment by zhengyongtao** [comment]
I agree with you.

**Comment by zhengyongtao** [comment]
Yes, this is important.
