### ISSUE TITLE
Support for multiple runtimes at the same time for testing

### ISSUE THREAD

**Issue by matejsp** [abiosoft/colima#154]
I would like to have all 3 runtimes available at the same time.
For now it is not possible it seems.

- docker
- cointanerd
- kubernetes

**Comment by abiosoft** [comment]
This is not currently supported based on the current implementation. Kubernetes needs one of [docker, containerd] but not both.

Why not use `--profile` or `-p` flag to create multiple instances?

```sh
colima start # default docker
colima start -p test --runtime containerd # additional instance for containerd

# to interact with other profiles, specify the profile flag
colima -p test nerdctl ps

# the specified profile is preserved in the nerdctl alias script
colima -p test nerdctl install
nerdctl ps
```

**Comment by matejsp** [comment]
I completely missed this. Can this example be added to readme.md of this git repo? It is super useful.

**Comment by abiosoft** [comment]
> I completely missed that. Can this example be added to readme.md of this git repo? It is super useful.

I guess it is safe to assume no-one ever checks `colima start --help` 😄

**Comment by rafaribe** [comment]
> > I completely missed that. Can this example be added to readme.md of this git repo? It is super useful.
> 
> I guess it is safe to assume no-one ever checks `colima start --help` 😄

After reading this I checked the help and it is indeed there. Thanks for the detailed explanation. This is super useful!
But is there a way to use my local nerdctl instead of relying on `colima nerdctl commands` ?

**Comment by abiosoft** [comment]
> But is there a way to use my local nerdctl instead of relying on colima nerdctl commands ?

No, if you're referring to a local client similar to docker. nerdctl is not yet supported outside of Linux.
But for convenience `colima nerdctl install` will put a `nerdctl` script in $PATH.

**Comment by jandubois** [comment]
> No, if you're referring to a local client similar to docker. nerdctl is not yet supported outside of Linux.

The issue really is that `nerdctl` needs access not just to the containerd socket, but also to the filesystem used to store the images.

**Comment by rafaribe** [comment]
> > No, if you're referring to a local client similar to docker. nerdctl is not yet supported outside of Linux.
> 
> The issue really is that `nerdctl` needs access not just to the containerd socket, but also to the filesystem used to store the images.

Ah that makes sense. That's probably why I had some issues with using nerdctl with volumes in Rancher Desktop

I also found out that we can try both of them out without much effort by having `containerd` as the default profile and creating a separate profile for `docker` .

If I do it the other way around, It becomes weird to specify the -p flag using `nerdctl` because this is also a flag for `ports`, while using docker with a profile is fine because it only relies on the local docker socket which `colima` takes care of mounting.

**Comment by abiosoft** [comment]
@matejsp I think it's fine to close this issue.
