### ISSUE TITLE
screen flashing asking to start a service

### ISSUE THREAD

**Issue by gedw99** [abiosoft/colima#156]
I don't know why but a recent a brew upgrade messed things up.

every 1 minute i get a OS dialogue flashing up and disappearing after half a second.
I cant read it of course, but its the standard dialogue you see for giving permission for a port to open or a service to start

**Comment by NickHackman** [comment]
My apologies here, attempted to setup a Homebrew service, but it causes Colima to boot loop.

Resolves this issue: https://github.com/Homebrew/homebrew-core/pull/94264

Going to look more into it later to see if this can be resolved and also how to not enable the service by default in brew. 

Temporary workaround:

```shell
brew services stop colima
colima start
```

**Comment by NickHackman** [comment]
@abiosoft should be good to close this issue now since the homebrew PR has been reverted.

**Comment by gedw99** [comment]
Thanks @NickHackman for such a quick response .

yes I did a “brew services start colina”, so looks like that is it
