### ISSUE TITLE
Using kind with colima? 

### ISSUE THREAD

**Issue by exdx** [abiosoft/colima#159]
Running colima 0.3.2 and kind v0.11.1 together on intel macOS generates a kubelet related error when running `kind create cluster`:

```
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
```
I'm wondering if others are able to successfully run kind on their colima VM? Is the colima kubernetes feature the preferred way to use kube via colima, and kind not supported? kind does work on the docker desktop vm however.

**Comment by exdx** [comment]
Running `colima start --cpu 2 --memory 4` allocates enough resources for kind to start but resulted in the same error.

**Comment by AkihiroSuda** [comment]
Seems a duplicate of https://github.com/abiosoft/colima/issues/153 .

`brew install --HEAD kind` seems to work.

**Comment by exdx** [comment]
Thank you, I can install HEAD then. Closing as duplicate.
