### ISSUE TITLE
What does colima ssh do ?

### ISSUE THREAD

**Issue by heSKa** [abiosoft/colima#160]
When I do Colima ssh it seems like I am still in my current working directory with colima prompt, I thought I should be inside the VM.

**Comment by spkane** [comment]
You are inside the VM, with your current working directory mounted into the VM for your development convenience.

If you type  `ls ~`, `ls /`, or even `cat /etc/os-release` this should become clear.

**Comment by abiosoft** [comment]
> When I do Colima ssh it seems like I am still in my current working directory with colima prompt, I thought I should be inside the VM.

Yeah, you are inside the VM. Easy verifiable with `uname -a`.
