### ISSUE TITLE
Colima should offer the option to use a different Linux OS other than Alpine

### ISSUE THREAD

**Issue by uliromahn** [abiosoft/colima#163]
While Alpine might be more lightweight, there are quite a few applications that won't work on Alpine because those Linux apps depend on glibc which is not available on Alpine.
I really would like to have the ability to configure the OS to be used for the lima VM.

**Comment by jandubois** [comment]
> there are quite a few applications that won't work on Alpine because those Linux apps depend on glibc which is not available on Alpine.

Can you provide an example of this?

I understand that the applications couldn't run directly on Alpine, and that you couldn't use an Alpine base image when running it inside a container. But I don't understand why you can't run an application using glibc inside a container on top of an Alpine host.

**Comment by uliromahn** [comment]
@jandubois the best example is that I am unable to run kind inside the Alpine VM but I can successfully start it inside a lima vm after I installed docker-ce there manually.
Also, it is very restrictive to "force" people to a single Linux OS, especially to one that is less "standard".
I personally have nothing against Alpine since it is great for docker container. But it is less than optimal as a general purpose Linux.
I looked into the code and found it strange that the lima config is being statically constructed in a go file. I am happy to take a look at this and make it more configurable and create a PR for that.

**Comment by jandubois** [comment]
> Also, it is very restrictive to "force" people to a single Linux OS, especially to one that is less "standard".

In my understanding, `colima` is a specialized tool to provide you containers on macOS and Linux, not a general Linux VM. In this view, the choice of Linux distro is just an implementation detail, that you shouldn't care about.

If you want a "general purpose Linux" VM, why do you run `colima` and not `lima`, which gives you a lot more flexibility?

Anyways, I work only on lima, not on colima, and was just wondering how the lack of glibc does affect which kind of applications you can run inside containers, and I guess we agree that it doesn't affect containers at all.

**Comment by uliromahn** [comment]
> and I guess we agree that it doesn't affect containers at all.

I am not sure I actually agree with that.

I already provided you with one example where the kind base container won't work properly in the colima VM. I am sure I can find other examples.

I understand the desire to have a very small base image but not at the cost of constantly worrying whether my containerized app will actually work or not. In this case, I'd rather have a larger base image and the certainty that 99% of my containers will run.

Also, as already mentioned above, I consider the hard-coding of the lima config via a go file bad practice. Such things should be externally configurable as it is done in lima. Why change that and not re-use what has been implemented there?

**Comment by jandubois** [comment]
> I already provided you with one example where the kind base container won't work properly in the colima VM.

Both #153 and #159 show that `kind` (latest `HEAD` version) works with `colima`, so not sure what you mean.

**Comment by uliromahn** [comment]
Hmm, looks like a kind issue. I don't want to and can't run kind HEAD, so I probably have to wait until kind 0.11.x has been released before I can use it with colima.

Nevertheless, my last comment/opinion stands with regards to the "hard-coded" lima config. :)

I'll close that ticket then since it doesn't seem to be a colima issue.

**Comment by abiosoft** [comment]
> In my understanding, `colima` is a specialized tool to provide you containers on macOS and Linux, not a general Linux VM. In this view, the choice of Linux distro is just an implementation detail, that you shouldn't care about.
> 
> If you want a "general purpose Linux" VM, why do you run `colima` and not `lima`, which gives you a lot more flexibility?

This is pretty much the summary of the choice of Alpine. 

The Alpine used is a custom built distro image for running containers. It is (a fork of ) the same image used by Rancher Desktop.

For context, before v0.3.0 colima was using Ubuntu as the underlying distro. The download size of the iso is `~560MB` and a further download of `~125MB` of packages  is required to install docker on first run.
Compare that with Alpine that only needs to download `~150MB` of iso and nothing more.

**Comment by BenTheElder** [comment]
It's possible to run a debian-ish distro with smaller images (see e.g. debian-slim image), debian/ubuntu isn't inherently large and there are many available sub variants with less pre-installed contents.

FWIW I don't consider alpine a good base environment for containers, the somewhat naive UDP only DNS resolver affects the container runtimes and the choice of openRC is unusual and poorly supported / not tested in the ecosystem, I don't think any of (runc, crun, containerd, podman, docker, ...) is running CI on non-systemd environment so it's always subject to problems like currently discovering that cgroupns=private containers cannot run on colima (https://github.com/kubernetes-sigs/kind/issues/3277).

**Comment by pierre-vigier** [comment]
After stumbling on some issue as well with kind, and looking at running non alpine image on colima, here is a solution to make it work, colima is based on lima, and when starting your colima instance, it's possible to edit the configuration.
if you start colima with

```
colima start -e
```

It's possible to edit the configuration of the VM before it is created, and one can then use Lima option in the file to specify images to use, following for instance templates form lima directly: https://lima-vm.io/docs/templates/
By specifying a different images, the created vm will use that vm.

**Comment by abiosoft** [comment]
@pierre-vigier that is not supported. Colima makes assumptions based on the image i.e. dependencies, provision scripts and distro specific commands.

From v0.6.0, Colima now uses Ubuntu as the distro, which resolves the compatibility with Kind.

**Comment by pierre-vigier** [comment]
oh, i guess, i just happened to upgrade colima at the same time then

**Comment by jms1voalte** [comment]
So there *is* no way to make `colima` NOT use ubuntu on the Linux VM?

Is there at least a way to make it NOT start all the unnecessary "snap" crap? I don't like the idea of an operating system "phoning home" like that for no reason.

**Comment by abiosoft** [comment]
> Is there at least a way to make it NOT start all the unnecessary "snap" crap? I don't like the idea of an operating system "phoning home" like that for no reason.

There is no snap included, many packages were removed including snap. 
You can inspect it here https://github.com/abiosoft/colima-core/blob/12bb3117f2d0192dcbb221a0edf8f1cb535a551d/scripts/qcow.sh#L65-L66.

**Comment by jms1voalte** [comment]
[Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) showed the VM trying to connect to `api.snapcraft.io` when it starts up. That's what led me to *find* this issue in the first place.

However, after deleting and re-crating the VM, it looks like the *current* VM image doesn't do this anymore.

I'm guessing whoever maintains the image, removed the snap stuff from it. Any idea what version or date this happened? Is there a CHANGELOG file for the VM image somewhere?
