### ISSUE TITLE
`docker login` fails with connection refused to backend.sock

### ISSUE THREAD

**Issue by bhavanki** [abiosoft/colima#167]
I recently set up colima via Homebrew on my Big Sur laptop. I still have Docker for Mac installed, but it is not running. I'm attempting to run `docker login` to authenticate to an AWS ECR repository. (In the command below I've replaced the AWS account ID and my local username.)

```
$ aws ecr get-login-password | docker login --username AWS --password-stdin 111222333444.dkr.ecr.us-west-2.amazonaws.com
Error saving credentials: error storing credentials - err: exit status 1, out: `Post "http://ipc/registry/credstore-updated": dial unix /Users/username/Library/Containers/com.docker.docker/Data/backend.sock: connect: connection refused`
```

* `docker context inspect` reports that the "colima" context is active and has the correct socket listed there: `unix:///Users/username/.colima/docker.sock` (with the correct username).
* My `docker` CLI was the one that shipped with Docker for Mac, so I installed the ordinary CLI via Homebrew (20.10.12) and linked it to /usr/local, to avoid any odd defaulting behavior the former one might have. No difference.

**Comment by bhavanki** [comment]
Thank you, that was indeed the problem! I'm now using:

```
	"credsStore": "osxkeychain",
```

I gather that the desktop helper goes through / requires Docker Desktop / for Mac? Are there any downsides to using "osxkeychain" even for Docker for Mac?

Thanks again!

**Comment by jandubois** [comment]
I don't know; `desktop` seems to be just a wrapper for the native mechanism; you can retrieve credentials stored by `desktop` with `osxkeychain` and vice versa. `desktop` is not open source, so we don't know what else it does; it probably hooks into Docker's extended services. But if you are not using Docker Desktop, then you obviously don't need those...

**Comment by jandubois** [comment]
Just for sake of completeness: `osxkeychain` still requires that `docker-credential-osxkeychain` is installed. But that is open source and can be installed with e.g. `brew install docker-credential-helper`. You may have had it installed because you already had Docker Desktop.
