### ISSUE TITLE
kubectl port-forward fails

### ISSUE THREAD

**Issue by ventsislav-georgiev** [abiosoft/colima#170]
It seems this issue is back: https://github.com/abiosoft/colima/issues/5
```
unable to do port forwarding: socat not found
```

manual fix was:
```
colima ssh
sudo apk update
sudo apk add socat
```

**Comment by abiosoft** [comment]
Hi, thanks for reporting this.

This is actually a known issue and will be fixed soonest. It was an oversight.

For now, the workaround suffices.

**Comment by abiosoft** [comment]
This has been fixed already https://github.com/abiosoft/colima/releases/tag/v0.3.3-pre-02 and v0.3.3 will soon be released.
