### ISSUE TITLE
Unable to login on AWS registry when using `containerd`

### ISSUE THREAD

**Issue by ViBiOh** [abiosoft/colima#171]
First of all, thank you for bringing alternative to Docker Desktop 😌 It works like a charm =)

But, I have a problem :p 

When using colima with `containerd` runtime, I cannot login to the AWS registry using the `nerdctl login` (that I have aliased to `docker` command). Regular login to the "Official" Docker registry works fine.

The issue seems discuss and resolved on [nerdctl](https://github.com/containerd/nerdctl/issues/429). So is it about a dependencies update or I miss something?

I've tried running `lima` directly with nerdctl and it works (I guess the ubuntu image for containerd is more stuffed than the alpine used by colima).

```
> colima start --runtime=containerd
> colima nerdctl install --path "${HOME}/opt/bin/docker"
> aws --profile "shared-services-aws" ecr get-login-password --region "${AWS_REGION}" | docker login --username "AWS" --password-stdin "${AWS_SHARED_SERVICES_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

time="2022-02-09T08:30:34Z" level=error msg="failed to call tryLoginWithRegHost" error="unexpected status code 404" i=0
time="2022-02-09T08:30:34Z" level=fatal msg="unexpected status code 404"
```

**Comment by jandubois** [comment]
You probably need to update `nerdctl` to 0.16.1. Even though lima 0.8.2 uses this version, it will not update an existing VM (nerdctl runs inside the VM and not on the host). So you will need to destroy and recreate your VM to get the update.

**Comment by ViBiOh** [comment]
> > You probably need to update `nerdctl` to 0.16.1. Even though lima 0.8.2 uses this version, it will not update an existing VM (nerdctl runs inside the VM and not on the host). So you will need to destroy and recreate your VM to get the update.
> 
> @ViBiOh you can override the inbuilt nerdctl by following this [#105 (comment)](https://github.com/abiosoft/colima/issues/105#issuecomment-1010291320).
> 
> If that does fixes it, I would make a version bump for the nerdctl 0.16.1.

That's what I was looking for, testing with an up-to-date `nerdctl` and it works when in the last version =)

So if you have time for bumping to the 0.16.1, it will be great =)

**Comment by jandubois** [comment]
Ah yes, my bad, I forgot for a moment that in the Alpine image `nerdctl` is part of the ISO and not installed by Lima. Sorry about that!

**Comment by abiosoft** [comment]
@ViBiOh can you give this a try and see if it's fixed?

https://github.com/abiosoft/colima/releases/tag/v0.3.3-pre-01

**Comment by kigawas** [comment]
Perhaps there is also a similar problem #164, preventing building from public ECR.

**Comment by ViBiOh** [comment]
> @ViBiOh can you give this a try and see if it's fixed?
> 
> https://github.com/abiosoft/colima/releases/tag/v0.3.3-pre-02

It works out of the box 👍
