### ISSUE TITLE
colima start takes a long time 

### ISSUE THREAD

**Issue by shahasim** [abiosoft/colima#175]
Hi,

I need some help please, when I start Colima it takes ages at the essential requirement step 1.

`colima start --arch aarch64`

`msg="[hostagent] Waiting for the essential requirement 1 of 5:`

<img width="566" alt="Screenshot 2022-02-10 at 11 38 57" src="https://user-images.githubusercontent.com/26812995/153401600-dab40f14-1c87-44eb-8a3c-6fdb4239b271.png">

eventually when it starts the volume mount process is very slow and the commands I try against the container timeout 

**Setup**
`lima version 0.8.2`
`colima version 0.3.2`
`QEMU emulator version 6.2.0`
`Mac M1 Pro`

**Comment by abiosoft** [comment]
This looks like qemu is emulating. Did you install qemu separately?

Also, you should not need to specify `--arch` as it defaults to your CPU type.

**Comment by shahasim** [comment]
if I don't pass the arch parameter I get this 

<img width="1076" alt="Screenshot 2022-02-10 at 12 34 59" src="https://user-images.githubusercontent.com/26812995/153409632-0d220961-74c7-49a3-8fdb-d95d5b593c10.png">

**Comment by shahasim** [comment]
`cat $HOME/.lima/colima/serial.log` is empty, i have pasted the out from `cat /Users/Syed/.lima/colima/ha.stderr.log` below

`
{"level":"warning","msg":"local user \"Syed\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"firmware candidates = [/usr/local/share/qemu/edk2-x86_64-code.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/qemu/ovmf-x86_64-code.bin]","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"OpenSSH version 8.6.1 detected","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"AES accelerator seems available, prioritizing aes128-gcm@openssh.com and aes256-gcm@openssh.com","time":"2022-02-10T12:36:06Z"}
{"level":"info","msg":"Starting QEMU (hint: to watch the boot progress, see \"/Users/Syed/.lima/colima/serial.log\")","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"qCmd.Args: [/usr/local/bin/qemu-system-x86_64 -cpu host -machine q35,accel=hvf -smp 2,sockets=1,cores=2,threads=1 -m 2048 -drive if=pflash,format=raw,readonly=on,file=/usr/local/share/qemu/edk2-x86_64-code.fd -boot order=d,splash-time=0,menu=on -drive file=/Users/Syed/.lima/colima/basedisk,media=cdrom,readonly=on -drive file=/Users/Syed/.lima/colima/diffdisk,if=virtio -cdrom /Users/Syed/.lima/colima/cidata.iso -netdev user,id=net0,net=192.168.5.0/24,dhcpstart=192.168.5.15,hostfwd=tcp:127.0.0.1:51538-:22 -device virtio-net-pci,netdev=net0,mac=52:55:55:b8:36:9f -device virtio-rng-pci -display none -device virtio-vga -device virtio-keyboard-pci -device virtio-mouse-pci -parallel none -chardev socket,id=char-serial,path=/Users/Syed/.lima/colima/serial.sock,server=on,wait=off,logfile=/Users/Syed/.lima/colima/serial.log -serial chardev:char-serial -chardev socket,id=char-qmp,path=/Users/Syed/.lima/colima/qmp.sock,server=on,wait=off -qmp chardev:char-qmp -name lima-colima -pidfile /Users/Syed/.lima/colima/qemu.pid]","time":"2022-02-10T12:36:06Z"}
{"level":"info","msg":"Waiting for the essential requirement 1 of 5: \"ssh\"","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"executing script \"ssh\"","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"executing ssh for script \"ssh\": /usr/bin/ssh [ssh -F /dev/null -o IdentityFile=\"/Users/Syed/.lima/_config/user\" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o NoHostAuthenticationForLocalhost=yes -o GSSAPIAuthentication=no -o PreferredAuthentications=publickey -o Compression=no -o BatchMode=yes -o IdentitiesOnly=yes -o Ciphers=\"^aes128-gcm@openssh.com,aes256-gcm@openssh.com\" -o User=lima -o ControlMaster=auto -o ControlPath=\"/Users/Syed/.lima/colima/ssh.sock\" -o ControlPersist=5m -p 51538 127.0.0.1 -- /bin/bash]","time":"2022-02-10T12:36:06Z"}
{"error":"signal: abort trap","level":"info","msg":"QEMU has exited","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 51538: Connection refused\\r\\n\", err=failed to execute script \"ssh\": stdout=\"\", stderr=\"ssh: connect to host 127.0.0.1 port 51538: Connection refused\\r\\n\": exit status 255","time":"2022-02-10T12:36:06Z"}
{"level":"debug","msg":"qemu[stderr]: qemu-system-x86_64: Unknown Error","time":"2022-02-10T12:36:06Z"}
`

**Comment by abiosoft** [comment]
@shahasim how did you install qemu?

**Comment by shahasim** [comment]
I did not install it separtaly, it must've been with Colima... but I've been struggling with this since yesterday and have tried quite a few `brew uninstalls` and `brew reinstalls`

Do you want me to uninstall qemu?

**Comment by abiosoft** [comment]
This looks similar to https://github.com/abiosoft/colima/issues/172.

Unfortunately, I do not have an M1 device to verify this. There is a thread of M1 users https://github.com/abiosoft/colima/issues/75 but it seems to work fine for everyone else.

Are you able to use lima directly? Try `lima start` and see if it is successful.

**Comment by shahasim** [comment]
Thanks, I'll look at the thread, `lima start` didn't work

<img width="715" alt="Screenshot 2022-02-10 at 12 47 28" src="https://user-images.githubusercontent.com/26812995/153411534-b65922ac-70e0-4358-88fd-219ed4728a27.png">

**Comment by shahasim** [comment]
No luck, I'm afraid :(

<img width="1781" alt="Screenshot 2022-02-10 at 12 48 58" src="https://user-images.githubusercontent.com/26812995/153411788-86b3529b-5310-4619-8c01-af2d71b152f6.png">

**Comment by shahasim** [comment]
you reckon, I sound install from this branch `git checkout fix-m1-containerd-k3s` ?

**Comment by abiosoft** [comment]
> you reckon I sshould install from this branch `git checkout fix-m1-containerd-k3s` ?

That is not related. This looks something specific to Lima and we may need to create an issue upstream instead.

**Comment by abiosoft** [comment]
@shahasim this is probably your situation as well https://github.com/abiosoft/colima/issues/204#issuecomment-1083349682

**Comment by shahasim** [comment]
@abiosoft I think you are right. I believe this is probably because I used the migration assistant on my old (intel) MacBook Pro to move stuff over to my M1 MacBook Pro

**Comment by abiosoft** [comment]
Feel free to re-open if this https://github.com/abiosoft/colima/issues/175#issuecomment-1086334877 is not indeed the case.
