### ISSUE TITLE
how to add the config message into the /etc/docker/daemon.json

### ISSUE THREAD

**Issue by Lionelpang** [abiosoft/colima#185]
when i want to add some cus config in to /etc/docker/daemon.json, but the config reset when colima restart.

**Comment by abiosoft** [comment]
https://github.com/abiosoft/colima#faq

> On first startup, Colima generates Docker daemon.json file at `$HOME/.colima/docker/daemon.json`.
>
> Simply modify the daemon.json file accordingly and restart Colima.
