### ISSUE TITLE
3-part port binding for `docker run` or docker-compose is not respected, so services can be exposed on network

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#186]
### Description

(bouncd back from https://github.com/lima-vm/lima/issues/655) 

macOS 12.2 arm64, colima 0.3.2, limactl version 0.8.2, docker back-end

docker/docker-compose support a 3-part port-binding technique where the interface to bind to can be chosen explicitly. For example:

`docker run -p 127.0.0.1:8080:80  --name nginx -d nginx`

Given that example, you should be able to `curl localhost:8080` on the system where you ran it, but you should not be able to connect from another interface. For example, if `10.211.55.2` is another interface, `curl 10.211.55.2:8080` should fail.

This has very serious security implications for applications that are not supposed to bind to all interfaces, see

* https://github.com/drud/ddev/issues/3560

When you bind to all interfaces (the default, 0.0.0.0) it typically means that any user on the local network can access any service running under lima. 

To demonstrate this, 
1. run the example nginx container: `docker run -p 127.0.0.1:8080:80  --name nginx -d nginx`
2. Connect from localhost, `curl localhost:8080` - you'll see the default nginx output
3. Connect to another interface on your machine, `curl 10.211.55.2:8080` for example, and it will also show the default nginx output. It should not.

You can repeat the same with any version of docker and you won't see this exposed behavior.

**Comment by rfay** [comment]
Explanation there by @AkihiroSuda

> Lima does not listen on 0.0.0.0 by default, but Colima does: https://github.com/abiosoft/colima/blob/ac876a5d9e4eda7d1d015896ebfbe1dd16b8c203/environment/vm/lima/yaml.go#L54-L63

**Comment by abiosoft** [comment]
Colima used to bind to `127.0.0.1` by default but was changed to `0.0.0.0` due to a user request and there were no objections at the time. I reluctantly decided to go with that after noticing the default behaviour for Docker Desktop was to bind to `0.0.0.0`.

You can still workaround that by using the `--port-interface` flag. 
```
colima start --port-interface 127.0.0.1
```

As at now, there is no way to distinguish a port forward of 127.0.0.1 or 0.0.0.0 from Lima VM to the host.

**Comment by abiosoft** [comment]
I would do some more investigations to see how this can be properly supported.

**Comment by rfay** [comment]
Thanks, yes, the current default is pretty problematic, major security issues. For example, on ddev it would mean that anybody on the local network could access and alter the database of a project. It also is overriding the explicit configuration given to the container.

**Comment by abiosoft** [comment]
This has been fixed upstream in Lima and tested successfully. 
It will be part of the next release.

**Comment by rfay** [comment]
Thanks so much. It wasn't my understanding that https://github.com/lima-vm/lima/pull/660 was actually fixing this problem...

**Comment by abiosoft** [comment]
@rfay can you kindly try with the latest development version and see if this is fixed? `brew install --head colima`.

**Comment by rfay** [comment]
I confirm that with HEAD colima both issues are solved, thanks so much!

* Bound ports with 3-part binding and using localhost are no longer accessible on other interfaces.(here and https://github.com/lima-vm/lima/issues/655). 
* Both host.docker.internal and host.lima.internal are defined and usable inside a plain-vanilla debian container, (https://github.com/lima-vm/lima/issues/491 and various other issues.

**Comment by abiosoft** [comment]
Thanks for confirming, will create a release soon.
