### ISSUE TITLE
Trying to Restart an Application on File Change

### ISSUE THREAD

**Issue by HertelDavid** [abiosoft/colima#187]
### Environment

macOS Monterey 12.0.1

```
colima version

colima version 0.3.3
git commit: ac876a5d9e4eda7d1d015896ebfbe1dd16b8c203

runtime: docker
arch: x86_64
client: v20.10.12
server: v20.10.11
```

### Issue

I'm attempting to volume mount the source code of a typescript application so that I can change the code locally and have it show up within the running container. I'm also using a file watcher to restart the application when file changes do happen using `ts-node-dev` but I'm not sure if the file changes are being picked up within the container.

When I open a terminal into the container I can see the file has changed but the application hasn't restarted. I also ran an experiment where I installed chokidar and ran a script to see file changes within the container but that wasn't picking up changes either.

I'm wondering if anyone else has been able to get file change events working for them in containers running in colima?

**Comment by ggoodman** [comment]
I've just run into this issue as well. I wonder if it has something to do with how fs events are triggered (or more importantly, are _not_ triggered) on the `sshfs` mount from the host.

**Comment by abiosoft** [comment]
This is a limitation of sshfs and currently being tracked upstream in Lima https://github.com/lima-vm/lima/issues/615.

**Comment by abiosoft** [comment]
You can try out the development version `brew install --HEAD colima` and try the experimental `--mount-inotify` flag?

```
colima start --mount-inotify
```
