### ISSUE TITLE
Support native volume mount on Mac with 9pfs

### ISSUE THREAD

**Issue by srdcarrion** [abiosoft/colima#192]
Just wondering if anyone has looked into supporting 9pfs per:

https://github.com/containers/podman/issues/8016#issuecomment-1034091359 

Really like Colima and have been working around the issues sshfs presents.

**Comment by kingbuzzman** [comment]
Holly crap! Thats A LOT faster, no comparison!

**Comment by abiosoft** [comment]
There has been progress on this upstream on Lima and qemu, should make it into colima soon.
