### ISSUE TITLE
Delete a vm with colima delete

### ISSUE THREAD

**Issue by gayanhewa** [abiosoft/colima#193]
👋🏼  I've tried to use colima delete to remove vm. And even ever a complete reinstall I still have the old VM's available under colima list

![Screen Shot 2022-02-21 at 12 28 22 pm](https://user-images.githubusercontent.com/1681406/154874640-1ead19b9-a873-4f92-914b-85563d4650ad.png)

What am I missing here 🤔 

I ran into a few issues with my end and wanted to do a complete reset.

**Comment by abiosoft** [comment]
What errors are you getting? You simply need to reply `y` to the prompt message or `colima delete -f` if you would rather not deal with the prompt.

Feel free to re-open if there is indeed an issue.

**Comment by gayanhewa** [comment]
There aren't really any errors showing 🤔 

![Screen Shot 2022-02-21 at 7 43 35 pm](https://user-images.githubusercontent.com/1681406/154919072-98355dea-5567-48a9-a0f2-dbff82bf5fba.png)

**Comment by abiosoft** [comment]
You created them with --profile flag. You need to specify it when deleting as well.

**Comment by gayanhewa** [comment]
Yes. That works. Thanks a bunch. Adding this screenshot to help anyone else with the same question.

![Screen Shot 2022-02-21 at 7 54 05 pm](https://user-images.githubusercontent.com/1681406/154920840-04821c65-c52c-4b55-8d57-9505a02f4b05.png)
