### ISSUE TITLE
Port Publishing with unspecified host port does not work

### ISSUE THREAD

**Issue by dnatic09** [abiosoft/colima#195]
When you create a docker image with the host port auto-bound, it does not properly forward the port through the SSH tunnel to lima. From the below command: the `-p 8080:80` argument works perfectly because the host and docker ports are both specified. The argument `-p 80` does NOT work. Regardless of the auto-bound port, it cannot be reached from the host. This will break many Docker functions and use cases.

# Start Image
```
docker run -p 80 -p 8080:80 nginx
```
# Inspect image and ports; check auto-bound port to 80.
```
docker ps
```

# This Works
```
nc -v localhost 8080
```

# This Does NOT Work
```
nc -v localhost [port-auto-bound-to-80]
```

![image](https://user-images.githubusercontent.com/6172757/155008957-309cbdf3-0f2f-411f-a446-f1c46fbaacdd.png)

# Extra Notes
When you SSH into the Colima VM, you can see the Docker proxies running as expected. Netcat-ing against the ports works. Therefore, I suspect the issue lies between the VM and the host agent.

**Comment by abiosoft** [comment]
I am unable to reproduce this. 

Does the following work?
```
docker run -p 80 nginx
```

**Comment by dnatic09** [comment]
Issue can be closed.

I have no idea what I did to fix this, but I effectively deleted colima and docker, wiped all contexts, etc. After reinstalling, it works now.
