### ISSUE TITLE
Colima with docker vm failing to start 

### ISSUE THREAD

**Issue by matbhuvi** [abiosoft/colima#196]
Need help in solving this issue of Colima is failing to start in Mac.

```
colima colima start
INFO[0000] starting colima
INFO[0000] already running                               context=vm
INFO[0000] provisioning ...                              context=docker
FATA[0000] error provisioning docker: error at 'provisioning': error copying daemon.json to VM: exit status 1
```

```
colima version
colima version 0.3.3
git commit: ac876a5d9e4eda7d1d015896ebfbe1dd16b8c203

runtime: docker
arch: x86_64
```
[ha.stderr.log](https://github.com/abiosoft/colima/files/8113493/ha.stderr.log)

**Comment by abiosoft** [comment]
have you tried to reset and start afresh i.e. `colima delete` and `colima start`?

**Comment by matbhuvi** [comment]
Yes..i have tried. No luck

**Comment by abiosoft** [comment]
are you using Lima overrides?

**Comment by abiosoft** [comment]
Can you try two things.

1. Run with `--verbose` flag and share the output.
2. Try containerd runtime and see if it succeeds `colima start --runtime containerd`.
