### ISSUE TITLE
support docker.for.mac.host.internal 

### ISSUE THREAD

**Issue by saltbo** [abiosoft/colima#199]
I hope to visit the host from the container, by Docker Desktop using` docker.for.mac.host.internal`.

colima maybe not support it, can support it? or is there any other mode to visit?

**Comment by abiosoft** [comment]
This will be part of the next release, which is imminent.

**Comment by abiosoft** [comment]
It will however be `host.docker.internal` instead as per Docker's instruction https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds.

Closing in favour of https://github.com/abiosoft/colima/issues/57
