### ISSUE TITLE
"error provisioning docker" when override.yaml exists

### ISSUE THREAD

**Issue by Jdban** [abiosoft/colima#200]
I am running `colima` on an M1 mac. 
I have tried with the latest released version of `colima`, as well as the `HEAD` version, both have the same issue when using an `override.yaml` for lima.

I need to change some settings in [override.yaml](https://github.com/lima-vm/lima/blob/01ce318b113b88196ad4862278fdb9876cb03cc8/pkg/limayaml/default.yaml), so I have it saved to `~/.lima/_config/override.yaml`. 
I have yet to make any changes to the `override.yaml` file, it is still identical to the `default.yaml` file.

I've tried a couple different revisions of `default.yaml` from the lima repo since it seems to have changed a bit recently (just in case it changed behavior) but it did not. 

Whenever the override.yaml has values in it, I get an error about "group docker does not exist".

```bash
➜  colima start --cpu 1
INFO[0000] starting colima                              
INFO[0000] creating and starting ...                     context=vm
INFO[0038] provisioning ...                              context=docker
>  usermod: group 'docker' does not exist
FATA[0038] error provisioning docker: error at 'provisioning': error fixing user permission: exit status 6 

➜ colima status       
INFO[0000] colima is running                            
INFO[0000] runtime: docker                              
INFO[0000] arch: aarch64           
                     
➜  docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
````

If i delete the `override.yaml` (or comment out the entire file), then everything seems to work just fine

```bash
➜  colima start --cpu 1
INFO[0000] starting colima                              
INFO[0000] creating and starting ...                     context=vm
INFO[0021] provisioning ...                              context=docker
INFO[0022] restarting VM to complete setup ...           context=docker
INFO[0022] stopping ...                                  context=vm
INFO[0027] starting ...                                  context=vm
INFO[0048] starting ...                                  context=docker
INFO[0053] waiting for startup to complete ...           context=docker
INFO[0053] done                
                         
➜  docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

Is this a bug or am I doing something wrong?

**Comment by abiosoft** [comment]
Did you override the image iso as well? If yes, that is the problem.

**Comment by Jdban** [comment]
> Did you override the image iso as well? If yes, that is the problem.

I don't believe I did anything like that. How can I verify this?

**Comment by abiosoft** [comment]
Can you share the contents of `$HOME/.lima/_config/override.yaml` ?

**Comment by Jdban** [comment]
> Can you share the contents of `$HOME/.lima/_config/override.yaml` ?

My `$HOME/.lima/_config/override.yaml` is identical to the `default.yaml` currently in the master branch of the lima repo: [LINK](https://github.com/lima-vm/lima/blob/01ce318b113b88196ad4862278fdb9876cb03cc8/pkg/limayaml/default.yaml)

**Comment by abiosoft** [comment]
Every single config in the override file takes precedence over Colima's config. You should at least get rid of the `images` section https://github.com/lima-vm/lima/blob/01ce318b113b88196ad4862278fdb9876cb03cc8/pkg/limayaml/default.yaml#L16.

Colima uses a custom built image iso that bundles some dependencies. A user defined image iso is almost not going to work as the assumed dependencies would be missing.

**Comment by abiosoft** [comment]
If I may ask, what are you trying to override? There may be a better way out.

**Comment by Jdban** [comment]
Ah, thanks. That makes sense. Removing the image section worked.

Currently in the override.yaml, I need to add some mounts, set the CPU to 1 (which I know can be done with colima start --cpu 1, but still nice to have in config), and also change the cpuType.

**Comment by abiosoft** [comment]
That makes sense. I am trying to avoid the use of config file as I prefer the transparency of the interaction with Lima.

I know passing cli flags continuously can be tedious and will look for a user-friendly way of specifying defaults.

I think it safe to close this issue.

Thanks.
