### ISSUE TITLE
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k

### ISSUE THREAD

**Issue by fred214** [abiosoft/colima#203]
Hi, When I run docker in Mac with colima, there is warning
```
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
```
How did the warning caused?

**Comment by buchs** [comment]
The warning comes from OpenBLAS numerical library. That is getting loaded, and when it starts it wants to do some code optimization based on the processor cache size. It is merely reporting that it was unable to determine the cache size so it picked a default. This warning can safely be ignored. I haven't yet found a way to eliminate it.
