### ISSUE TITLE
gofish based install

### ISSUE THREAD

**Issue by joeblew99** [abiosoft/colima#209]
https://gofi.sh/

its brew but cross platform.

**Comment by AkihiroSuda** [comment]
gofish seems deprecated now: https://github.com/fishworks/gofish/commit/cac139aee7dce8b011f114474c6d67f712db6024

**Comment by abiosoft** [comment]
Thanks for the info @AkihiroSuda

**Comment by joeblew99** [comment]
damn it.. gofish is so useful
