### ISSUE TITLE
Questions about writable volumes

### ISSUE THREAD

**Issue by awrznc** [abiosoft/colima#21]
Thanks for this very useful project.
I am looking for primary information about `Lima's support for writable volumes` that exists in README.md.

> https://github.com/abiosoft/colima/blob/305d01fa83e0024738dfd028920cf72858f6a600/README.md#faq
> Colima uses Lima for the VM and Lima's support for writable volumes is still experimental.

I've explored the lima's repository and guessed that the following text is primary information about it.
Am I correct in this understanding?

> https://github.com/lima-vm/lima/blob/544d15d5af3ff3eb144148a36c17bc8f62f92a9c/pkg/limayaml/default.yaml#L43
> Setting `writable` to true is possible, but untested and dangerous.

**Comment by abiosoft** [comment]
Yes, that is it. 

I will be closing as this is not an issue.
