### ISSUE TITLE
Host networking as easy as possible

### ISSUE THREAD

**Issue by Flacedoo** [abiosoft/colima#220]
Hey everyone,
As I'm still a newbie in colima and also only rarely used docker before I'm a little lost - hopefully, one of you could help me out with what I'm missing.
Basically, I'm aiming for an as easy as possible solution to have a Linux machine on my macOS laptop. I want to use that for development via VS Code, and also other introspection tools. For that, I basically need an as open as possible network setup, meaning having an IP address to which I can contact with basically all ports open. Could you help me out on how to achieve that?
So far I thought about having a docker run with network=host mode, but as I understood it correctly that only exposes the network to the virtual machine of colima, not the macOS host, correct?
Thanks in advance!

**Comment by Flacedoo** [comment]
Thanks for the fast reply! For VSCode alone I think I'm going for Remote Containers, and that actually already works like a charm without further adaptions as I think it directly attaches to the docker service.

Regarding the port forwarding: Is it happening in both directions? I have applications (in ROS if that's something you know), which require bi-directional communication and also identification of their hosts with a hostname and port (URI): [ROS Docu](http://wiki.ros.org/ROS/NetworkSetup). When having them running in multiple docker container inside colina it already works like a charm, but as soon as I want to connect to them from my macos host I can't establish that..

I feel like I'm currently missing some basics in networking and containered environments. Do you have any idea in which direction I have to work to resolve that?

**Comment by abiosoft** [comment]
> Regarding the port forwarding: Is it happening in both directions? 

I do not know much about your scenario but the macOS host is reachable from the VM and containers via `host.docker.internal` hostname or `192.168.5.2` ip address.

**Comment by Flacedoo** [comment]
But the other way round, to access the VM from the host with either a Hostname or IP is only coming with the 0.4.0 release, did I got that right? If so: Do you have already a -rough- schedule for that?

**Comment by abiosoft** [comment]
> But the other way round, to access the VM from the host with either a Hostname or IP is only coming with the 0.4.0 release, did I got that right? If so: Do you have already a -rough- schedule for that?

About a week from now.

**Comment by abiosoft** [comment]
You can `brew install --head colima` to install the development version. The release might still take a while.

**Comment by Flacedoo** [comment]
Works like a charm - you’re awesome, thanks a lot!

**Comment by vsjoshtait** [comment]
> I do not know much about your scenario but the macOS host is reachable from the VM and containers via host.docker.internal hostname or 192.168.5.2 ip address.

Appreciate this card is closed, but iIs there documentation anywhere I could refer colleagues to which has more information about this IP Address? TIA

**Comment by abiosoft** [comment]
> Appreciate this issue is closed, but is there documentation anywhere I could refer colleagues to which has more information about this IP Address? TIA

Yeah, I do agree documentation is lacking in this regard.
