### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by ramlev** [abiosoft/colima#221]
I normally using docker desktop for MacOS M1, and tried Colima, and want to go back to docker desktop.

brew uninstall colima

and starting docker desktop

```
Cannot connect to the Docker daemon at unix:///Users/ME/.colima/docker.sock. Is the docker daemon running?
```

how to get back to docker desktop

**Comment by jandubois** [comment]
Try `docker context use default`.

I think colima creates its own context that points to the colima socket, and you have to tell docker to use the default context (and socket) again.

**Comment by ramlev** [comment]
Thank you so much, i just thought that i lost everything. im back :D

**Comment by mourad1081** [comment]
Please colima, apply this when uninstalling, I almost committed suicide because of this.

**Comment by dmuiX** [comment]
Wuhuuu thank you. `docker context use default` helped a lot.

**Comment by jasonfine** [comment]
Colima also adds ssh configs in `~/.colima/`

This broke existing saved connections in at least one other application (Sequel Ace SSH connections)

A full run-down on uninstallation really needs to be documented.

**Comment by davidtranjs** [comment]
For anyone who is still not able to switch to another Docker runtime, even after `docker context use default`, try `unset DOCKER_HOST`, and thank me later.
