### ISSUE TITLE
Add `UID 501` to the `docker` group for non-docker runtime

### ISSUE THREAD

**Issue by spkane** [abiosoft/colima#223]
When a user uses `colima ssh` they are UID 501. It would be useful if that user was already added to the `docker` group so that you can utilize `docker` without `sudo`

**Comment by abiosoft** [comment]
Well, that is the case if you are using the docker runtime. Do you have a contrary experience?

**Comment by rfay** [comment]
And... although 501 may be the most common first user on a standard, default install mac, it is absolutely not the only UID that a person will be using.

**Comment by abiosoft** [comment]
@abiosoft Colima does that, provided you start it with docker runtime. If you use containerd runtime and manually installed docker then you have to handle that yourself.

As per the command `sudo addgroup spkane docker` not working, it will only reflect in a new session i.e. you can verify after a restart.

**Comment by spkane** [comment]
@abiosoft Ok that makes more sense.

I am running with `containerd` by default, but have need for the docker daemon, simply for a tool that only works with Docker (and then I can sideload the resulting image from Docker into containerd.

I am not installing Docker, but simply running `sudo rc-service docker start` to spin it up.

Initially after making the group change, I did try restarting dockerd and ending my `colima ssh` session and then re-connecting and that did not work (which I found surprising - is SSH connecting to the same login session somehow? ), but restarting the VM and starting docker again, did work.

This is workable, but it still seems like it would be helpful to add this user to the group file either way, so that when dockerd is running, the user has the permissions configured already.

**Comment by abiosoft** [comment]
> Initially after making the group change, I did try restarting dockerd and ending my colima ssh session and then re-connecting and that did not work (which I found surprising - is SSH connecting to the same login session somehow? ), but restarting the VM and starting docker again, did work.

The way Lima works, ssh ControlMaster is used and that is technically like re-using same session. 
If you want to force an entirely new session, you may want to remove ControlMaster configs from the output of `colima ssh-config --format cmd` and run that as your ssh command.

> This is workable, but it still seems like it would be helpful to add this user to the group file either way, so that when dockerd is running, the user has the permissions configured already.

Yeah, that can be done. Your use case was not considered initially.

**Comment by abiosoft** [comment]
Kindly install the current development version with brew install --HEAD colima try again. Should be fixed now.

**Comment by spkane** [comment]
I can confirm that this is working in HEAD now. Thanks @abiosoft !
