### ISSUE TITLE
How to set registry-mirrors for colima daemon?

### ISSUE THREAD

**Issue by mnacharov** [abiosoft/colima#225]
Hi,

Is it possible to set registry mirror? Dockerhub has quite annoying rate limit setting

I have tried to add  registry-mirrors to `~/.colima/docker/daemon.json` file, but it did not help 

https://docs.docker.com/registry/recipes/mirror/

**Comment by eva-mueller-coremedia** [comment]
Did you try to download an image directly from your registry mirror? 
If this results in an error like this: `Error response from daemon: Get "https://<MY_REGISTRY_MIRROR>/v2/": x509: certificate signed by unknown authority`, it is likely that you need to add your registry mirror to `~/.colima/docker/daemon.json`:
```
{
    [...],
    "insecure-registries": ["MY_REGISTRY_MIRROR"],
    "registry-mirrors": [
        "https://MY_REGISTRY_MIRROR"
    ]
}
```

This requires a colima restart... At least, this is how it worked for me.

Maybe you need also to update `~/.docker/daemon.json` as well.

**Comment by GreenHatHG** [comment]
> 

Hello, This is not effective for me.
I have modified the two files `~/.docker/daemon.json` and `~/.colima/docker/daemon.json`
Then `colima stop` `colima start`

**Comment by abiosoft** [comment]
@GreenHatHG that is specific to v0.3.x, kindly check the [instructions on the FAQ](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#how-to-customize-docker-config-eg-add-insecure-registries)

**Comment by dragonlayout** [comment]
@GreenHatHG I have test add registry-mirrors on version 0.4.4 and it works. Hope it works for you.
`colima start --edit`  replace 
`docker: {}` to
```yaml
docker:
  registry-mirrors:
    - https://MY_REGISTRY_MIRROR
```

[According to the comment](https://github.com/abiosoft/colima/blob/fc948f8f055600986f87e29e3e632daf56ac8774/embedded/defaults/colima.yaml#L67), **Docker daemon configuration that maps directly to daemon.json**.

**Comment by OksiBlack** [comment]
Not works for me on Mac os

**Comment by GreenHatHG** [comment]
你的邮件已收到！

**Comment by zhangqiujie22** [comment]
Edit the file `~/.colima/default/colima.yaml`

replace
```
docker: {}
```

 to
```
docker:
  registry-mirrors:
    - YOUR_REGISTRY_MIRROR
```
