### ISSUE TITLE
Additional setup for nerdctl install?

### ISSUE THREAD

**Issue by millsjoe** [abiosoft/colima#226]
Is there additional setup needed to use containerd?

```
$ colima start --runtime containerd
```
I can use the nerdctl runtime but using the install command gives me the following:
```
$ colima nerdctl install
FATA[0000] open /usr/local/bin/nerdctl: no such file or directory
```

Am I missing a step that is needed for this to work correctly?

**Comment by abiosoft** [comment]
Could it be that you do not have `/usr/local/bin` directory?
Can you try specifying another path and see if the error remains. e.g. `colima install nerdctl --path $HOME/bin/nerdctl`

**Comment by millsjoe** [comment]
I did that and still had no luck. Eventually just running `colima delete` a few times seemed to have done it so must have been a conflict in the build somewhere? Doesn't look to be an issue anymore though thanks!
