### ISSUE TITLE
Use `goreleaser` to create releases

### ISSUE THREAD

**Issue by luisdavim** [abiosoft/colima#24]
I'd like to suggest using https://goreleaser.com/ to cut releases, this will allow you to easily create  cross-compiled versions for Intel and ARM macs.

**Comment by mavogel** [comment]
Or just make a PR, declare it as WIP and link the issue here :) Then folks know and won't do double work

**Comment by mavogel** [comment]
feel free to close then as well @abiosoft

**Comment by developer-guy** [comment]
Ah sorry about that, I missed that one 🤦

**Comment by developer-guy** [comment]
@abiosoft can you please re-open this issue, I'm going to complete it tonight

**Comment by mavogel** [comment]
unfortunately it's not necessary any more @developer-guy . See #147
