### ISSUE TITLE
Support configs of nerdctl, containerd  and buildkitd

### ISSUE THREAD

**Issue by saltbo** [abiosoft/colima#241]
I found Colima is supported to config the docker https://github.com/abiosoft/colima/issues/185, but not support to config `nerdctl`. 

Can we support it like docker？ It could be like this:

```bash
.
├── colima.yaml
├── docker
│   └── daemon.json
└── nerdctl
    ├── buildkit
    │   └── buildkitd.toml
    ├── containerd
    │   └── config.toml
    └── nerdctl.toml
```

If agree that, I can implement it

**Comment by abiosoft** [comment]
I am currently performing some refactors to provide support for config files and default settings. This can be supported afterwards.
