### ISSUE TITLE
Defaults for start arguments?

### ISSUE THREAD

**Issue by joelpittet** [abiosoft/colima#242]
Is there a way (like dotfile) for colima to specify the `--memory` `--cpu` flags instead of doing that each time? 

Instead of typing:
`colima start --cpu 4 --memory 8`
I could do something like 
`colima start`
And it would read from `~/.colima/config.yml` or something with:
```
cpu: 4
memory: 8
```

Not sure if this is a question or a feature request ;)

**Comment by rfay** [comment]
I've been confused about what arguments are only useful for first launch, and which must be done later.

For example, if you start the first time with `colima start --disk=100 --cpu 4 --memory 8` then does `colima start` without arguments later just use all 3 of those? I know it uses `--disk` because that can't be changed. But I've never been clear about other things.

And what about `--dns` which seems to be important right now?

Thanks!

**Comment by abiosoft** [comment]
I agree that the documentation can be better in this regard. However, proper config file support is in the works.

> And what about --dns which seems to be important right now?

DNS does not persist, it needs to be specified on each startup.

**Comment by rfay** [comment]
How about `--cpu` and `--memory` - do they persist?

**Comment by abiosoft** [comment]
> How about `--cpu` and `--memory` - do they persist?

yeah they all persist, `--dns` is the exception.

**Comment by abiosoft** [comment]
> I've been confused about what arguments are only useful for first launch, and which must be done later.

This is actually specified in `colima start --help`.

```
$ colima start --help
Start Colima with the specified container runtime (and kubernetes if --with-kubernetes is passed).
The --runtime, --disk and --arch flags are only used on initial start and ignored on subsequent starts.
```

**Comment by rfay** [comment]
Thanks! That always scrolled off the screen for me :) So only `--disk` really. So I've probably been messing up by not always specifying `--memory`

**Comment by abiosoft** [comment]
Yeah, you can always customize an existing VM with the exception of disk size as stated here https://github.com/abiosoft/colima#customization-examples.

> - modify an existing VM to 4CPUs and 8GiB memory.
>
>  ```
>  colima stop
>  colima start --cpu 4 --memory 8
>  ```

**Comment by rfay** [comment]
Hmm, you said in https://github.com/abiosoft/colima/issues/242#issuecomment-1079380722 "They all persist, DNS is the exception" 

So the doc says
`The --runtime, --disk and --arch flags are only used on initial start and ignored on subsequent starts`

but you're saying that if you use `--memory 6 --cpu 4` on the first start, those also persist (but can be overridden)?

**Comment by abiosoft** [comment]
> but you're saying that if you use --memory 6 --cpu 4 on the first start, those also persist (but can be overridden)?

Yes :) I can now see how this gets easily confusing.
