### ISSUE TITLE
Docker daemon does not start up when starting Colima on MacOS

### ISSUE THREAD

**Issue by bmichaud** [abiosoft/colima#243]
I removed Docker Desktop entirely from my Intel MacBook prior to installing docker and Colima with Homebrew. I have

* macOS Monterey, version 12.2.1, with a corporate Zscalar.

> $> uname -a
> Darwin Machine_name 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

* Docker version

> $> docker version
> Client:
>  Version:           20.10.10
>  API version:       1.41
>  Go version:        go1.17.3
>  Git commit:        ec1e6b3
>  Built:             Thu Nov 11 20:44:58 2021
>  OS/Arch:           darwin/amd64
>  Context:           colima
>  Experimental:      true

* colima version 0.3.4 (git commit: https://github.com/abiosoft/colima/commit/5a4a70481ca8d1e794677f22524e3c1b79a9b4ae)

> $> colima version
> colima version 0.3.4
> git commit: 5a4a70481ca8d1e794677f22524e3c1b79a9b4ae
> 
> runtime: docker
> arch: x86_64

* This is what happens when I start colima, then try to invoke docker:

> $> colima delete && colima start
> are you sure you want to delete colima and all settings? [y/N] y
> INFO[0001] deleting colima
> INFO[0002] deleting ...                                  context=docker
> INFO[0002] deleting ...                                  context=vm
> INFO[0002] done
> INFO[0000] starting colima
> INFO[0000] creating and starting ...                     context=vm
> INFO[0021] provisioning ...                              context=docker
> INFO[0021] restarting VM to complete setup ...           context=docker
> INFO[0021] stopping ...                                  context=vm
> INFO[0026] starting ...                                  context=vm
> INFO[0047] starting ...                                  context=docker
> INFO[0052] waiting for startup to complete ...           context=docker
> INFO[0052] done
> $> docker ps
> Cannot connect to the Docker daemon at unix:///Users/Ben.Michaud/.colima/docker.sock. Is the docker daemon running?

> $> docker info
> Client:
>  Context:    colima
>  Debug Mode: false
>  Plugins:
>   compose: Docker Compose (Docker Inc., 2.3.3)
> 
> Server:
> ERROR: Cannot connect to the Docker daemon at unix:///Users/Ben.Michaud/.colima/docker.sock. Is the docker daemon running?
> errors pretty printing info

**Comment by miralgj** [comment]
I had a similar issue and resolved it by deleting and recreating the VM.

```
colima stop
colima delete
colima start
```

**Comment by bmichaud** [comment]
> I had a similar issue and resolved it by deleting and recreating the VM.
> 
> ```
> colima stop
> colima delete
> colima start
> ```
I tried this several times, but to no avail. Here is the verbose output for this process in case it helps:
________________
[Ben.Michaud] [~] $> docker context use default
default
Current context is now "default"
[Ben.Michaud] [~] $> docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[Ben.Michaud] [~] $> colima stop --verbose
INFO[0000] stopping colima
INFO[0000] stopping ...                                  context=docker
>  * Stopping Docker Daemon ... [ ok ]
INFO[0001] stopping ...                                  context=vm
> msg="Sending SIGINT to hostagent process 29598"
> msg="Waiting for the host agent and the qemu processes to shut down"
> msg="[hostagent] Received SIGINT, shutting down the host agent"
> msg="[hostagent] Shutting down the host agent"
> msg="[hostagent] Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Stopping forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] Unmounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Unmounting \"/tmp/colima\""
> msg="[hostagent] Shutting down QEMU with ACPI"
> msg="[hostagent] Sending QMP system_powerdown command"
> msg="[hostagent] QEMU has exited"
INFO[0005] done
[Ben.Michaud] [~] $> colima delete --verbose
are you sure you want to delete colima and all settings? [y/N] y
INFO[0001] deleting colima
INFO[0001] deleting ...                                  context=vm
> msg="The QEMU process seems already stopped"
> msg="The host agent process seems already stopped"
> msg="Removing *.pid *.sock under \"/Users/Ben.Michaud/.lima/colima\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/ha.sock\""
> msg="Deleted \"colima\" (\"/Users/Ben.Michaud/.lima/colima\")"
INFO[0001] done
[Ben.Michaud] [~] $> colima start --verbose
INFO[0000] starting colima
INFO[0000] creating and starting ...                     context=vm
> msg="Terminal is not available, proceeding without opening an editor"
> msg="Attempting to download the image from \"~/.lima/_config/alpine-lima-clm-3.14.3-x86_64.iso\"" digest=
> msg="Downloaded image from \"~/.lima/_config/alpine-lima-clm-3.14.3-x86_64.iso\""
> msg="[hostagent] local user \"Ben.Michaud\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/Ben.Michaud/.lima/colima/serial.log\")"
> msg="SSH Local Port: 65262"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] The essential requirement 1 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\""
> msg="[hostagent] The essential requirement 2 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\""
> msg="[hostagent] The essential requirement 3 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf to contain \\\"user_allow_other\\\"\""
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Mounting \"/tmp/colima\""
> msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] The final requirement 1 of 1 is satisfied"
> msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="READY. Run `limactl shell colima` to open the shell."
INFO[0021] provisioning ...                              context=docker
INFO[0021] restarting VM to complete setup ...           context=docker
INFO[0021] stopping ...                                  context=vm
> msg="Sending SIGINT to hostagent process 30705"
> msg="Waiting for the host agent and the qemu processes to shut down"
> msg="[hostagent] Received SIGINT, shutting down the host agent"
> msg="[hostagent] Shutting down the host agent"
> msg="[hostagent] Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Stopping forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] Unmounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Unmounting \"/tmp/colima\""
> msg="[hostagent] Shutting down QEMU with ACPI"
> msg="[hostagent] Sending QMP system_powerdown command"
> msg="[hostagent] QEMU has exited"
INFO[0027] starting ...                                  context=vm
> msg="Using the existing instance \"colima\""
> msg="[hostagent] local user \"Ben.Michaud\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/Ben.Michaud/.lima/colima/serial.log\")"
> msg="SSH Local Port: 65325"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] The essential requirement 1 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\""
> msg="[hostagent] The essential requirement 2 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\""
> msg="[hostagent] The essential requirement 3 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf to contain \\\"user_allow_other\\\"\""
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Mounting \"/tmp/colima\""
> msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] The final requirement 1 of 1 is satisfied"
> msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="READY. Run `limactl shell colima` to open the shell."
> colima
> Current context is now "colima"
INFO[0047] starting ...                                  context=docker
>  * /var/log/docker.log: creating file
>  * /var/log/docker.log: correcting owner
>  * Starting Docker Daemon ... [ ok ]
INFO[0053] waiting for startup to complete ...           context=docker
INFO[0053] done
[Ben.Michaud] [~] $> docker ps
Cannot connect to the Docker daemon at unix:///Users/Ben.Michaud/.colima/docker.sock. Is the docker daemon running?

**Comment by abiosoft** [comment]
@bmichaud are you able to access docker in the VM? 

```sh
colima ssh # enter the vm
docker ps # does this work?
```

**Comment by bmichaud** [comment]
@abiosoft It turns out after exploring in the `~/.docker` folder that the context being used by the docker daemon is `colima`, while I was using `default`. The fix was to do this:
```
[Ben.Michaud] [~] $> docker context use colima
colima
Current context is now "colima"
[Ben.Michaud] [~] $> docker ps
Cannot connect to the Docker daemon at unix:///Users/Ben.Michaud/.colima/docker.sock. Is the docker daemon running?
[Ben.Michaud] [~] $> colima delete --verbose
are you sure you want to delete colima and all settings? [y/N] y
INFO[0001] deleting colima
INFO[0001] deleting ...                                  context=docker
> colima
INFO[0001] deleting ...                                  context=vm
> msg="Sending SIGKILL to the QEMU process 34371"
> msg="Sending SIGKILL to the host agent process 34363"
> msg="Removing *.pid *.sock under \"/Users/Ben.Michaud/.lima/colima\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/ga.sock\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/ha.pid\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/ha.sock\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/qemu.pid\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/qmp.sock\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/serial.sock\""
> msg="Removing \"/Users/Ben.Michaud/.lima/colima/ssh.sock\""
> msg="Deleted \"colima\" (\"/Users/Ben.Michaud/.lima/colima\")"
INFO[0001] done
[Ben.Michaud] [~] $> colima start --verbose
INFO[0000] starting colima
INFO[0000] creating and starting ...                     context=vm
> msg="Terminal is not available, proceeding without opening an editor"
> msg="Attempting to download the image from \"~/.lima/_config/alpine-lima-clm-3.14.3-x86_64.iso\"" digest=
> msg="Downloaded image from \"~/.lima/_config/alpine-lima-clm-3.14.3-x86_64.iso\""
> msg="[hostagent] local user \"Ben.Michaud\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/Ben.Michaud/.lima/colima/serial.log\")"
> msg="SSH Local Port: 64710"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] The essential requirement 1 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\""
> msg="[hostagent] The essential requirement 2 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\""
> msg="[hostagent] The essential requirement 3 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf to contain \\\"user_allow_other\\\"\""
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Mounting \"/tmp/colima\""
> msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] The final requirement 1 of 1 is satisfied"
> msg="READY. Run `limactl shell colima` to open the shell."
INFO[0028] provisioning ...                              context=docker
INFO[0028] restarting VM to complete setup ...           context=docker
INFO[0028] stopping ...                                  context=vm
> msg="Sending SIGINT to hostagent process 26106"
> msg="Waiting for the host agent and the qemu processes to shut down"
> msg="[hostagent] Not forwarding TCP 0.0.0.0:22"
> msg="[hostagent] Not forwarding TCP [::]:22"
> msg="[hostagent] Received SIGINT, shutting down the host agent"
> msg="[hostagent] Shutting down the host agent"
> msg="[hostagent] Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Stopping forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] Unmounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Unmounting \"/tmp/colima\""
> msg="[hostagent] Shutting down QEMU with ACPI"
> msg="[hostagent] Sending QMP system_powerdown command"
> msg="[hostagent] QEMU has exited"
INFO[0034] starting ...                                  context=vm
> msg="Using the existing instance \"colima\""
> msg="[hostagent] local user \"Ben.Michaud\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/Ben.Michaud/.lima/colima/serial.log\")"
> msg="SSH Local Port: 64742"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] The essential requirement 1 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\""
> msg="[hostagent] The essential requirement 2 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\""
> msg="[hostagent] The essential requirement 3 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf to contain \\\"user_allow_other\\\"\""
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Mounting \"/tmp/colima\""
> msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] The final requirement 1 of 1 is satisfied"
> msg="READY. Run `limactl shell colima` to open the shell."
> colima
> Successfully created context "colima"
> colima
> Current context is now "colima"
INFO[0054] starting ...                                  context=docker
>  * /var/log/docker.log: creating file
>  * /var/log/docker.log: correcting owner
>  * Starting Docker Daemon ... [ ok ]
INFO[0059] waiting for startup to complete ...           context=docker
INFO[0059] done
[Ben.Michaud] [~] $> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
```

**Comment by qhquanghuy** [comment]
> @bmichaud are you able to access docker in the VM?
> 
> ```shell
> colima ssh # enter the vm
> docker ps # does this work?
> ```

After my mac ran out of battery, I started colima and Docker started on the VM but not on the host. I deleted the VM and start new VM, docker worked fine. Are therer any other solution for this? Because of data losing when delete VM

**Comment by sellers** [comment]
I have had trouble when utilizing a runtime of containerd, versus runtime docker.  colima delete may reset your default runtime to docker which is why the above comments offer remedies. 

There may be a way to bridge that, as containerd starts faster for me, however I have not identified such at this point.
