### ISSUE TITLE
vm startup parameter `cpuType` is needed

### ISSUE THREAD

**Issue by oliverdding** [abiosoft/colima#248]
When use colima to run clickhouse, it cannot start and show message "not support CPU SSSE3". After browsing lima's issues, I found a [fix](https://github.com/lima-vm/lima/issues/641) for this by specificing:

```yaml
cpuType:
  x86_64: Haswell-v4
```

to make lima start vm with `Haswell-v4` instead of `qemu64`, which is default cpu type after sometime of this [PR](https://github.com/lima-vm/lima/pull/494), announcing performance improvement after switching.

## Environment

macOS 12.3 21E230 arm64
MacBookPro18,1

## Solution

Add parameters for cpuType.

**Comment by conradreisch** [comment]
May I add that it would be nice to also have ARM64 cpu types?

To my understanding, [lima](https://github.com/lima-vm/lima) supports ARM on ARM. So I would be very happy to have an option to run Colima "natively" on ARM.

**Comment by oliverdding** [comment]
@conradreisch AFAIK, colima support choosing architecture:

```bash
~
❯ colima start --help
Start Colima with the specified container runtime (and kubernetes if --with-kubernetes is passed).
The --runtime, --disk and --arch flags are only used on initial start and ignored on subsequent starts.

Usage:
  colima start [profile] [flags]

Examples:
  colima start
  colima start --runtime containerd
  colima start --with-kubernetes
  colima start --runtime containerd --with-kubernetes
  colima start --cpu 4 --memory 8 --disk 100
  colima start --arch aarch64
  colima start --dns 1.1.1.1 --dns 8.8.8.8

Flags:
  -a, --arch string       architecture (aarch64, x86_64) (default "aarch64")
  -c, --cpu int           number of CPUs (default 2)
  -d, --disk int          disk size in GiB (default 60)
  -n, --dns ipSlice       DNS servers for the VM (default [])
  -h, --help              help for start
  -m, --memory int        memory in GiB (default 2)
  -v, --mount strings     directories to mount, suffix ':w' for writable
  -r, --runtime string    container runtime (containerd, docker) (default "docker")
  -s, --ssh-agent         forward SSH agent to the VM
  -k, --with-kubernetes   start VM with Kubernetes

Global Flags:
  -p, --profile string   profile name, for multiple instances (default "default")
      --verbose          enable verbose log
```

It's only lack of ability to choose different cpu type, not the cpu architecture.

**Comment by conradreisch** [comment]
@oliverdding - my bad. Thanks for providing the solution to me!
