### ISSUE TITLE
M1 testing support

### ISSUE THREAD

**Issue by jnoortheen** [abiosoft/colima#250]
I own a M1-Air laptop and can help you test colima on this device.

**Comment by casaper** [comment]
I could contribute as well with such a device. MBP M1 Max to be precise.


```
ProductName:	macOS
ProductVersion:	12.3
BuildVersion:	21E230
```

**Comment by janvogt** [comment]
I could offer the M1 Pro (in an MBP)

**Comment by carusogabriel** [comment]
Is M1-Air (16GB RAM, 256 SSD) supported at this point?

**Comment by abiosoft** [comment]
@carusogabriel Yes, all M1 devices are supported.

The issue should actually be closed now.

**Comment by carusogabriel** [comment]
@abiosoft Thanks for answering! I have an M1-Air that can run at top resources with Docker Desktop, although unable to with Colima. Shall I open an issue?

**Comment by abiosoft** [comment]
Yes please, kindly open an issue.
