### ISSUE TITLE
Colima/Docker cannot download Docker hub base images in a Zscaler environment, while Docker Desktop could

### ISSUE THREAD

**Issue by bmichaud** [abiosoft/colima#256]
I have:
colima version 0.3.4
git commit: 5a4a70481ca8d1e794677f22524e3c1b79a9b4ae

runtime: docker
arch: x86_64
client: v20.10.13
server: v20.10.11

I'm working on a MacBook Pro in a Jamf/Zscaler environment. People are able to download images from docker hub in my environment if they use Docker Desktop.

I have placed the root certificates in my ~/.docker/certs.d directory and restarted colima, but I am still getting this error when I try to build a Docker image that has an alpine base image. It fails on the download of the base image:

```
[+] Building 0.5s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 34B                                                                                             0.0s
 => CANCELED [internal] load metadata for docker.io/library/nginx:alpine                                                     0.4s
 => ERROR [internal] load metadata for docker.io/library/node:12.18.1-alpine3.12                                             0.4s
------
 > [internal] load metadata for docker.io/library/node:12.18.1-alpine3.12:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/node/manifests/12.18.1-alpine3.12": x509: certificate signed by unknown authority
```
Is there a particular root CA certificate format I need? Does the file name need to be `ca.crt`? Does the format need to be anything in particular? I have tried a cert exported from Keychain Access in `.cer` format and in `PEM` format. 

Perhaps I need to find intermediate certificates? I'm not sure where those would be.

I have tried adding a `~/.docker/daemon.json` with an entry like this: `"insecure-registries": ["registry-1.docker.io"]`, but this did not work.

I also triedexporting the root certs in `.cer` and `PEM` format and putting them into the `~/.docker/certs.d/` directory and restarting and even deleting colima and starting, but that did not work. Perhaps I am not putting the correct certs in the certs.d folder? Perhaps not in the right format? 

Do I need to add something to the `override.yaml` to make this work? I tried adding this to the `override.yaml` as seen above:
```
provision:
  - mode: user
    script: |
    #!/bin/bash
    sudo ln -sf /Users/${USER}/.docker/certs.d /etc/docker/certs.d
```
But this resulted in a colima stop/start error:
```
FATA[0000] yaml: line 13: could not find expected ':'
WARN[0000] error detecting Lima config directory: error retrieving lima info: exit status 1
WARN[0000] falling back to default '$HOME/.lima'
```

_Originally posted by @bmichaud in https://github.com/abiosoft/colima/issues/131#issuecomment-1090920068_

**Comment by abiosoft** [comment]
Are the certificates in this format https://docs.docker.com/engine/security/certificates/#understand-the-configuration? 

```
$HOME/certs.d/              <-- Certificate directory
└── localhost:5000          <-- Hostname:port
   ├── client.cert          <-- Client certificate
   ├── client.key           <-- Client key
   └── ca.crt               <-- Certificate authority that signed
                                the registry certificate
```

**Comment by bmichaud** [comment]
> Are the certificates in this format https://docs.docker.com/engine/security/certificates/#understand-the-configuration?
> 
> ```
> $HOME/certs.d/              <-- Certificate directory
> └── localhost:5000          <-- Hostname:port
>    ├── client.cert          <-- Client certificate
>    ├── client.key           <-- Client key
>    └── ca.crt               <-- Certificate authority that signed
>                                 the registry certificate
> ```

@abiosoft , Thanks for the link. I was not using a subdirectory, no. However, I am still unclear about this. 
- My company has root certificates I could put in a folder (these are the ones I was trying to import earlier), but, given your answer, I am now unsure if those are the ones I want. 
- The errors I am getting pertain to `registry-1.docker.io`, so I think I need to add that as a subdirectory to `certs.d`. Since I don't have any certs specifically for that website, and certainly not the private key, all I can do is download the public key from the website using a browser and install that. Is that what you would recommend?

**Comment by bmichaud** [comment]
I just tried the following:
1. Created a new directory: `~/.docker/certs.d/registry-1.docker.io`
2. Used Firefox to go to https://registry-1.docker.io/v2/ and download the chain and client certificate. (Both in PEM format)
3. Renamed these file to have the expected file name extensions: `docker-com-chain.crt` and `docker-com.cert`
4. Placed the files in the directory: `~/.docker/certs.d/registry-1.docker.io`
5. Tried `colima stop && colima start`, then `docker pull adminer` failed: 
```
[Ben.Michaud] [~/.docker/certs.d] $> colima stop && colima start
INFO[0000] stopping colima
INFO[0000] stopping ...                                  context=docker
INFO[0001] stopping ...                                  context=vm
INFO[0006] done
INFO[0000] using docker runtime
INFO[0000] starting colima
INFO[0000] starting ...                                  context=vm
INFO[0020] provisioning ...                              context=docker
INFO[0020] starting ...                                  context=docker
INFO[0025] waiting for startup to complete ...           context=docker
INFO[0026] done
[Ben.Michaud] [~/.docker/certs.d] $> deploy-adminer
Error: No such container: adminer
Unable to find image 'adminer:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority.
See 'docker run --help'.
```
7. Tried `colima delete` and `colima start --verbose` and then tried the pull again:
```
[Ben.Michaud] [~/.docker/certs.d] $> colima delete
are you sure you want to delete colima and all settings? [y/N] y
INFO[0000] deleting colima
INFO[0001] deleting ...                                  context=docker
INFO[0001] deleting ...                                  context=vm
INFO[0001] done
[Ben.Michaud] [~/.docker/certs.d] $> colima start --verbose
INFO[0000] starting colima
INFO[0000] creating and starting ...                     context=vm
> msg="Terminal is not available, proceeding without opening an editor"
> msg="Attempting to download the image from \"~/.lima/_config/alpine-lima-clm-3.14.3-x86_64.iso\"" digest=
> msg="Downloaded image from \"~/.lima/_config/alpine-lima-clm-3.14.3-x86_64.iso\""
> msg="[hostagent] local user \"Ben.Michaud\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/Ben.Michaud/.lima/colima/serial.log\")"
> msg="SSH Local Port: 62616"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] The essential requirement 1 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\""
> msg="[hostagent] The essential requirement 2 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\""
> msg="[hostagent] The essential requirement 3 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf to contain \\\"user_allow_other\\\"\""
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Mounting \"/tmp/colima\""
> msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] The final requirement 1 of 1 is satisfied"
> msg="READY. Run `limactl shell colima` to open the shell."
INFO[0020] provisioning ...                              context=docker
INFO[0020] restarting VM to complete setup ...           context=docker
INFO[0020] stopping ...                                  context=vm
> msg="Sending SIGINT to hostagent process 19538"
> msg="Waiting for the host agent and the qemu processes to shut down"
> msg="[hostagent] Not forwarding TCP 0.0.0.0:22"
> msg="[hostagent] Not forwarding TCP [::]:22"
> msg="[hostagent] Received SIGINT, shutting down the host agent"
> msg="[hostagent] Shutting down the host agent"
> msg="[hostagent] Stopping forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Stopping forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] Unmounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Unmounting \"/tmp/colima\""
> msg="[hostagent] Shutting down QEMU with ACPI"
> msg="[hostagent] Sending QMP system_powerdown command"
> msg="[hostagent] QEMU has exited"
INFO[0026] starting ...                                  context=vm
> msg="Using the existing instance \"colima\""
> msg="[hostagent] local user \"Ben.Michaud\" is not a valid Linux username (must match \"^[a-z_][a-z0-9_-]*$\"); using \"lima\" username instead"
> msg="[hostagent] Starting QEMU (hint: to watch the boot progress, see \"/Users/Ben.Michaud/.lima/colima/serial.log\")"
> msg="SSH Local Port: 62635"
> msg="[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""
> msg="[hostagent] The essential requirement 1 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 2 of 5: \"user session is ready for ssh\""
> msg="[hostagent] The essential requirement 2 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 3 of 5: \"sshfs binary to be installed\""
> msg="[hostagent] The essential requirement 3 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 4 of 5: \"/etc/fuse.conf to contain \\\"user_allow_other\\\"\""
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/Ben.Michaud\""
> msg="[hostagent] Mounting \"/tmp/colima\""
> msg="[hostagent] Waiting for the final requirement 1 of 1: \"boot scripts must have finished\""
> msg="[hostagent] Forwarding \"/var/run/docker.sock\" (guest) to \"/Users/Ben.Michaud/.colima/docker.sock\" (host)"
> msg="[hostagent] Forwarding \"/run/lima-guestagent.sock\" (guest) to \"/Users/Ben.Michaud/.lima/colima/ga.sock\" (host)"
> msg="[hostagent] The final requirement 1 of 1 is satisfied"
> msg="READY. Run `limactl shell colima` to open the shell."
> colima
> Successfully created context "colima"
> colima
> Current context is now "colima"
INFO[0046] starting ...                                  context=docker
>  * /var/log/docker.log: creating file
>  * /var/log/docker.log: correcting owner
>  * Starting Docker Daemon ... [ ok ]
INFO[0051] waiting for startup to complete ...           context=docker
INFO[0051] done
[Ben.Michaud] [~/.docker/certs.d] $> docker pull adminer
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority
```

**Comment by abiosoft** [comment]
Oh wait, you are having issues pulling official image from Docker Hub? That should not happen.

The specification of the certs https://github.com/abiosoft/colima/issues/256#issuecomment-1094516482 is meant for private registry.

I am entirely not sure what is happening here. Are you behind a proxy or vpn?

**Comment by bmichaud** [comment]
> Oh wait, you are having issues pulling official image from Docker Hub? That should not happen. The specification of the certs [#256 (comment)](https://github.com/abiosoft/colima/issues/256#issuecomment-1094516482) is meant for private registry.
> 
> I am entirely not sure what is happening here. Are you behind a proxy or vpn?

I am using a corporate MacBook with a ZScaler proxy, yes.

**Comment by abiosoft** [comment]
Do you know the address that the proxy is running on? If yes, can you kindly ssh into the VM and follow this https://github.com/abiosoft/colima/issues/161#issuecomment-1069084734. 
NOTE: if the proxy server is running on a port on `localhost`, in the VM you should use `192.168.5.2` instead.

If that fixes it for you, then will make it as part of the next release.

> It appears that Docker Desktop, when installed, can utilize the root certificates available in the Mac Keychain, but colima cannot, but that is only a guess.

Yes, this is being worked on upstream in Lima at the moment.

**Comment by bmichaud** [comment]
> Are the certificates in this format https://docs.docker.com/engine/security/certificates/#understand-the-configuration?
> 
> ```
> $HOME/certs.d/              <-- Certificate directory
> └── localhost:5000          <-- Hostname:port
>    ├── client.cert          <-- Client certificate
>    ├── client.key           <-- Client key
>    └── ca.crt               <-- Certificate authority that signed
>                                 the registry certificate
> ```

As a point of clarification, I thought I was supposed to put the certs in `~/.docker/certs.d` (see https://github.com/abiosoft/colima/issues/131#issuecomment-1022809521), but your comment above, as a colleague pointed out, is saying I should put them in `~/certs.d` instead.

**Comment by bmichaud** [comment]
> Do you know the address that the proxy is running on? If yes, can you kindly ssh into the VM and follow this [#161 (comment)](https://github.com/abiosoft/colima/issues/161#issuecomment-1069084734). NOTE: if the proxy server is running on a port on `localhost`, in the VM you should use `192.168.5.2` instead.
> 
> If that fixes it for you, then will make it as part of the next release.
> 
> > It appears that Docker Desktop, when installed, can utilize the root certificates available in the Mac Keychain, but colima cannot, but that is only a guess.
> 
> Yes, this is being worked on upstream in Lima at the moment, though it does not appear to be the issue in this case.

I have a local colleague working with me who has duplicated the issue locally. In your suggestion above, the instructions are to log into the linux VM used by Colima and set up the lima account with environment variables: `HTTPS_PROXY` and `HTTP_PROXY`. I was able to do that and put in a "fake" value with a legacy proxy that the company is no longer using. However, that will not work here. 

My colleague said this about Zscalar: 
> the directions he linked to were for an HTTP/S proxy, while what zscaler is really doing is creating a lower level interface that does the proxying, closer to like, a full network proxy, e.g. regardless of the protocol

We will continue to try to figure out what we need to do, but assigning the CA certs to the proxy in our case is not a straight forward procedure. If you have any ideas, please let me know.

**Comment by bmichaud** [comment]
Additionally, I was wondering if logging into the VM and manually restarting the docker service would perhaps force it to load the certs I have added in, but I am guessing that the colima restart on the host will do that for me. 
```
colima:/etc/docker/certs.d$ rc-service docker restart
 * docker: superuser access required
```

**Comment by abiosoft** [comment]
you can use `sudo`

**Comment by bmichaud** [comment]
@abiosoft I am now able to run a `docker build -t adminer .` on my MacBook in a directory with a Dockerfile like this:
`FROM adminer
`
I found the particular Root CA cert in my Keychain that zscaler is signing with and I'm putting it in `~/.docker/certs.d/docker.io`. (NOTE: This seems to work when the cert is in PEM or in DER format.)

However, I can't do a straight `docker pull adminer`, for example, because that method seems to pull from `registry-1.docker.io/v2/` I get this error:
`$> docker pull adminer
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority`
(as noted above)

I have tried placing the same Root CA cert in the following subdirectories to no avail. Do you know where I should place it to get this working?
- `~/.docker/certs.d/registry-1.docker.io`
- `~/.docker/certs.d/registry-1.docker.io/v2`
- `~/.docker/certs.d/registry-1.docker.io:v2`

**Comment by an-ghinid** [comment]
Just wanted to chime in here and say I am in an almost identical environment to @bmichaud with a corp zscaler + jamf setup and am observing the exact same behaviour. Have yet to delve into it further, instead have just switched back over to using docker desktop for the moment.

**Comment by danielbobbert** [comment]
Since Zscaler will intercept (MITM) all your connections, it's rather tedious to declare certificate for every server individually. The following will solve your issue once and forever. I keep a copy of custom root CAs (e.g. Zscaler) in ${HOME}/.ca-certificates (important: the directory must be inside your home directory, so that it is auto-mounted inside Colima). Then I run:

#!/bin/zsh
CERTS="${HOME}/.ca-certificates"
colima ssh -- sudo cp ${CERTS}/* /usr/local/share/ca-certificates/
colima ssh -- sudo update-ca-certificates

This copies all my custom CA certs inside Colima and registers them as trusted root CAs. Now pulling through Zscaler works from all official registries without further configuration. It also allows me to install additional packages inside the Colima VM using "app" (which would otherwise also fail because of invalid TLS chain).
You may have to restart the docker daemon afterwards:
  colima ssh -- sudo service docker restart
(not sure about this, I'm doing it anyways because of other changes I am running during VM setup)

**Comment by abiosoft** [comment]
@danielbobbert thanks for the heads up. Lima v0.10.0 now supports specifying additional CA certs. That can be integrated into Colima as well.

**Comment by jandubois** [comment]
> Lima v0.10.0 now supports specifying additional CA certs

Note that the support for this feature in `lima-init` for alpine-lima has not been implemented yet, so just moving to lima 0.10 is not enough. I hope to get around to it soon, but not clear yet when I get the time.

**Comment by bmichaud** [comment]
> That's just a warning (I get it, too), but it still works.
> `/etc/ssl/certs/ca-certificates.crt` (that's the file that the warning is referring to) contains more than one certificate and `update-ca-certificates` seems to complain about this, but it doesn't seem to pose a problem.
> `update-ca-certificates` copies your CA certs from `/usr/local/share/ca-certificates` to `/etc/ssl/certs`, renaming them to `ca-cert-<name of your ca>` and also appends them to `/etc/ssl/certs/ca-certificates.crt`. All in all `/etc/ssl/certs/ca-certificates.crt` seems to be just a concatenation of all CAs in `/etc/ssl/certs`

Thanks, @danielbobbert, this process is much cleaner than what I came up with. It seems to be working for me now, but I am going to try to verify it on someone else's mac, where no shenanigans have occurred.

**Comment by mathieu-ruellan-dkt** [comment]
I'm facing the same pb with zscaler. Here a function in my .bashrc.

```
start_colima() {
  local CERTS="${HOME}/.ca-certificates"
  local URL="[registry-1.docker.io](http://registry-1.docker.io/):443"
  mkdir -p ${CERTS}
  openssl s_client -showcerts -connect ${URL} </dev/null 2>/dev/null|openssl x509 -outform PEM >${CERTS}/docker-com.pem
  openssl s_client -showcerts -verify 5 -connect ${URL} </dev/null 2>/dev/null | sed -ne '/-BEGIN/,/-END/p' >${CERTS}/docker-com-chain.pem
  colima start
  
  colima ssh -- sudo cp ${CERTS}/* /usr/local/share/ca-certificates/
  colima ssh -- sudo update-ca-certificates
  colima ssh -- sudo service docker restart
}
```

**Comment by royteeuwen** [comment]
Any update on getting a permanent fix for this instead in colima itself?

**Comment by kleinjoshuaa** [comment]
we use netskope and have the same issue. None of the above fixes were able to resolve it for me.

**Comment by hotwebmatter** [comment]
The following approach worked for me.

First, keep a copy of custom root CAs in `${HOME}/.ca-certificates` [as suggested above](https://github.com/abiosoft/colima/issues/256#issuecomment-1121280478).

Then, using the `provision` key in `~/.colima/default/colima.yml`:

```yaml
provision:
  - mode: system
    script: |
      CERTS="${HOME}/.ca-certificates"
      cp ${CERTS}/* /usr/local/share/ca-certificates/
      update-ca-certificates
      systemctl daemon-reload
      systemctl restart docker
```

This is a variant of the approach I suggested [here](https://github.com/abiosoft/colima/issues/956#issuecomment-1953264635), to set the colima proxy value correctly.

In fact, these may be combined into one `provision` script in cases where it proves necessary to copy certificates _and_ update proxy, as long as the `systemctl` steps are performed last.
