### ISSUE TITLE
receive error when colima start

### ISSUE THREAD

**Issue by jsstar522** [abiosoft/colima#263]
Hello, I got an error when I type CLI with `colima start`.
I tried it with **Macbook M1 Pro** and **Macbook Pro** both but I got same errors.

### INSTALLATION
```
brew install docker
brew install colima
```

### ERROR LOG
```
FATA[0000] error provisioning docker: error at 'provisioning': exit status 125
```

### LOG with --verbose
```
unknown flag: --description
See 'docker --help'.

Usage:	docker [OPTIONS] COMMAND

A self-sufficient runtime for containers
...
```

Is there command line like `docker --description` in code?

**Comment by abiosoft** [comment]
@jsstar522 looks like your docker client is relatively old and does not support `docker context` yet.

**Comment by jsstar522** [comment]
@abiosoft Thanks! I updated docker, then it was worked perfectly.
