### ISSUE TITLE
Connecting to buildkitd outside of the VM

### ISSUE THREAD

**Issue by blowfishpro** [abiosoft/colima#268]
I can see that `buildkitd` is running within the VM and I can run `buildctl` once I'm inside it (i.e. with `colima ssh`), however I can see that the buildkitd socket is not mapped to the host the way the docker socket is, and I don't see an easy way to configure this.  Is there some configuration option I'm missing that allows this?  Or could it be included by default?

**Comment by abiosoft** [comment]
I assumed that users would not be using buildkit directly. It can be added.

**Comment by blowfishpro** [comment]
This was mostly to support multi-platform builds.  I'm now not remembering why `docker buildx` wasn't working for my needs, if this is a lot of work I can re-examine this.

**Comment by abiosoft** [comment]
>  I'm now not remembering why docker buildx wasn't working for my needs

Can you share more details? Colima actually works fine with buildx though you need to install buildx manually as a docker plugin.

```
$ docker buildx ls
NAME/NODE       DRIVER/ENDPOINT  STATUS  PLATFORMS
colima        * docker
  colima        colima           running linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6

```

**Comment by blowfishpro** [comment]
Well I was able to get `docker buildx` working, multi-arch builds don't work with the docker driver but buildx can deploy its own container to run in (i.e. `docker buildx create --use`, and it works fine after you do that.

So I think it's fine to close this for now, maybe someone in the future will find a use case for direct access to `buildctl` but in this instance it seems like there's an easier thing to do.
