### ISSUE TITLE
Clockdrift in the created VM

### ISSUE THREAD

**Issue by dirkdev98** [abiosoft/colima#274]
Sometimes the time in the VM is lagging behind 'real'. This has happened a few times for me already, but still unable to find a cause for this or even a way to reproduce it. It seems to be after I lock my laptop and get back the next morning, but only once in a while (every 10 days or so) and not consistently every day.

Running a Macbook Pro M1 with the following Colima version & status;

Colima version:
```
colima version 0.3.4
git commit: 5a4a70481ca8d1e794677f22524e3c1b79a9b4ae

runtime: docker
arch: aarch64
client: v20.10.14
server: v20.10.11
```

Colima status:
```
INFO[0000] colima is running                            
INFO[0000] runtime: docker                              
INFO[0000] arch: aarch64 
```

`docker run -it --rm --cap-add SYS_TIME --privileged -e ALLOW_CIDR=0.0.0.0/0 -p 123:123/udp geoffh1977/chrony`

```
Writing New Config File

2022-05-07T08:00:43Z chronyd version 4.1 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP -SCFILTER +SIGND +ASYNCDNS +NTS +SECHASH +IPV6 -DEBUG)
2022-05-07T08:00:43Z Could not read valid frequency and skew from driftfile /var/lib/chrony/chrony.drift
2022-05-07T08:00:43Z Initial frequency -100000.000 ppm
2022-05-07T08:00:47Z System's initial offset : 978.140307 seconds slow of true (step)
2022-05-07T08:00:52Z Backward time jump detected!
2022-05-07T08:02:00Z Selected source 162.159.200.1 (pool.ntp.org)
2022-05-07T08:02:00Z System clock wrong by 978.685231 seconds
2022-05-07T08:18:18Z System clock was stepped by 978.685231 seconds
2022-05-07T08:02:57Z Backward time jump detected!
2022-05-07T08:02:57Z Can't synchronise: no selectable sources
2022-05-07T08:05:07Z Selected source 94.198.159.15 (pool.ntp.org)
2022-05-07T08:05:07Z System clock wrong by 977.327132 seconds
2022-05-07T08:21:24Z System clock was stepped by 977.327132 seconds
2022-05-07T08:05:06Z Backward time jump detected!
2022-05-07T08:05:06Z Can't synchronise: no selectable sources
```

**Comment by nifr** [comment]
I observe similar issues with the system time getting out of sync regularly. 
I assume clock drift could be a cause for the occasional networking issues aswell?

Hint: You can enable the NTP service `chrony` or `openntpd` directly in Alpine `lima` VMs as follows:

```
colima ssh -- sudo /sbin/setup-ntp -c chrony
colima ssh -- sudo /sbin/setup-ntp -c openntpd
 ```

Running this after every `colima delete` / `colima start` seems to improve overall stability of the VM.

**Comment by rfay** [comment]
Just a note that clock drift, especially when laptop slept, was a classic problem in docker/docker desktop for years and years. I'm sure you know that. I think the classic issue was https://github.com/docker/for-mac/issues/17

**Comment by jandubois** [comment]
This was supposed to be fixed in Lima with https://github.com/lima-vm/lima/pull/490.

Could you please file an issue against Lima, with the Lima version? While the Lima-internal "fix" has a more coarse resolution, it has the advantages that it should work even when not connected to the internet.

**Comment by dirkdev98** [comment]
Created lima-vm/lima#850.

@abiosoft would you still accept a PR to run `setup-ntp` anyways?

**Comment by abiosoft** [comment]
@dirkdev98 I would like to wait a bit for the responses on the issue. 

As a stopgap you can actually use Lima overrides to run those commands by creating a `~/.lima/_config/override.yaml` with the following contents.

```yaml
provision:
  - mode: system
    script: /sbin/setup-ntp -c chrony
  - mode: system
    script: /sbin/setup-ntp -c openntpd
```

**Comment by dirkdev98** [comment]
Much appreciated!

**Comment by AndreasA** [comment]
@abiosoft Any news regarding this?

**Comment by AndreasA** [comment]
ok. did some more tests and using
```
provision:
  - mode: system
    script: /sbin/setup-ntp -c busybox
```

seems to indeed work best (currently). after a few seconds (after start) the drift is in 0.0x second range. which is way better than before. though still not perfect.

**Comment by karlvr** [comment]
This problem appears to affect me during a `make` build in a host volume... "Clock skew detected" starts being detected up to 0.97s in the future.

```
make[5]: warning:  Clock skew detected.  Your build may be incomplete.
make[5]: Warning: File 'CMakeFiles/aom_decoder_app_util.dir/depend.make' has modification time 0.97 s in the future
make[5]: Warning: File 'CMakeFiles/aom_av1_encoder_avx2_intrinsics.dir/depend.make' has modification time 0.94 s in the future
```

Testing the same build running the container using Docker Desktop is successful with no clock skew warnings.

**Comment by mfriedenhagen** [comment]
We use testcontainers to spawn a Postgres DB during integration tests of a Java application. We see a positive drift, i.e. do something like `INSERT now() INTO tabA` and assume a little later that a `now()` call in the Java JVM would produce a later timestamp. But the timestamp in Postgres is between 100ms and 500ms ahead of the one from the JVM.

**Comment by ramarnat** [comment]
With the switch to ubuntu, /sbin/setup-ntp isnt there. I did this instead

```
provision:
  - mode: system
    script: |
      timedatectl set-ntp on
```

**Comment by abiosoft** [comment]
This has been long resolved.

**Comment by lu-zero** [comment]
I just tripped on it on colima 0.8.0

**Comment by mknj** [comment]
15 minute clock drift in my standard colima/docker setup


❯ date -Iseconds
2025-06-24T16:17:31+02:00
❯ docker run -it --rm alpine date -Is
2025-06-24T14:02:07+00:00
❯ colima version
colima version 0.8.1
git commit: 96598cc5b64e5e9e1e64891642b91edc8ac49d16

runtime: docker
arch: aarch64
client: v28.2.2
server: v27.4.0

**Comment by krmao** [comment]
it is still exists @abiosoft 

```shell
➜  docker git:(master) ✗ date -Iseconds
2025-10-23T11:43:42+08:00
➜  docker git:(master) ✗ docker run -it --rm alpine date -Is
2025-10-23T03:43:10+00:00
➜  docker git:(master) ✗ colima version
colima version 0.8.4
git commit: e2ddc15483af66e9b8a525d779a0cc926f15dbcb

runtime: docker
arch: aarch64
client: v28.4.0
server: v28.3.3
(django-im) ➜  docker git:(master) ✗
```

<img width="3598" height="490" alt="Image" src="https://github.com/user-attachments/assets/ed7667cf-6987-4566-960a-0956b986571c" />
