### ISSUE TITLE
How do i publish ports to host with nerdctl?

### ISSUE THREAD

**Issue by nicholasq** [abiosoft/colima#275]
Hello, so i started a colima instances with the containerd runtime. I'm trying to start nginx in the running vm with the following command:

`colima nerdctl run -p 127.0.0.1:80:80 nginx`

but i get this:
`FATA[0000] colima [profile=127.0.0.1:80:80] is not running`

here is the output of running `limactl list`:
```
NAME       STATUS     SSH                ARCH       CPUS    MEMORY    DISK      DIR
colima     Running    127.0.0.1:64515    aarch64    2       2GiB      60GiB     /Users/nicholasquezada/.lima/colima
```

What am I doing wrong? Thank you

**Comment by nicholasq** [comment]
It appears the usage of the `-p` is applying to `colima` itself and not to `nerdctl`. How do i differentiate between the two?

**Comment by abiosoft** [comment]
```
colima nerdctl -- run -p 127.0.0.1:80:80 nginx
```

You can run `colima nerdctl install` to have a `nerdctl` alias script in your PATH. So you would be able to use `nerdctl` directly afterwards.
