### ISSUE TITLE
`colima nerdctl install` fails if `/usr/local/bin` is does not exist

### ISSUE THREAD

**Issue by callahad** [abiosoft/colima#279]
```
$ colima nerdctl install
INFO[0000] /usr/local/bin not writable, sudo password required to install nerdctl binary
Password: 
sh: line 1: /usr/local/bin/nerdctl: No such file or directory
FATA[0002] exit status 1
```

This is because on a fresh install of macOS, `/usr/local/` is empty.

**Comment by rfay** [comment]
IIRC /usr/local is also not writeable without sudo on a fresh macOS, it's homebrew installation that makes it writeable on a new computer. That struck me as really strange; I've always had homebrew, so didn't know that it was homebrew setting /usr/local ownership to mine.
