### ISSUE TITLE
`host.docker.internal` not reachable from container

### ISSUE THREAD

**Issue by jaepetto** [abiosoft/colima#287]
## context
In order to develop some PHP application, I want to use XDebug for debugging. The way to acchieve this is to run a XDebug client on the host machine (my dev. machine) and configure php (from within the container) to contact it with debugging information.

### on the host
A debugger is running and listening on port 9003.
This can be tested by `nc -v -z localhost 9003`.

### colima VM
The colima vm is lauched without any specific information (`colima start`)

### container
The container is launched with a couple of specific information in the `docker-compose.yml` file:

```
version: '3.7'
services:
  php-lighttpd:
    container_name: xdebug-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
...
```

## problem
Unfortunately, the php instance in the container is not able to reach the debugger. The error message is:
> Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port)

This can be confirmed by getting into the container (`docker exec -it xdebug-php /bin/bash`) and try to connext with netcat (`nc -v -z host.docker.internal 9003`)

## question
I believe this is normal since the colima vm does not know where to forward the requests it receives from it's container on port 9003.
Therefore my question is the following: is there a way to start the colima machine with port forwarding so everything received on a given port is forwarded to my mac?

**Comment by abiosoft** [comment]
It was a regression in v0.4.0 that is no fixed https://github.com/abiosoft/colima/releases/tag/v0.4.1.

Either wait for the brew PR to get merged https://github.com/Homebrew/homebrew-core/pull/101672, or install from head `brew install --HEAD colima`.

Kindly re-open if still not resolved.

**Comment by jaepetto** [comment]
Thanks for your quick reply. Unfortunately, the problem remains...
```
root@xdebug-php:/var/www/html# nc -v -z host.docker.internal 9003
nc: connect to host.docker.internal (172.17.0.1) port 9003 (tcp) failed: Connection refused
```

**Comment by abiosoft** [comment]
Did you delete the extra hosts?

```
extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Comment by jaepetto** [comment]
I did restart colima but forgot to remove the extra hosts. Now the connection is successful. Thanks a lot for your swift help.
