### ISSUE TITLE
Pulling docker images from behind a company VPN

### ISSUE THREAD

**Issue by olliekennedy** [abiosoft/colima#294]
Hey I've been struggling to apply the correct proxy settings to the colima vm so that I can pull docker images. I've tried various methods with no success, mostly from this thread: https://stackoverflow.com/questions/23111631/cannot-download-docker-images-behind-a-proxy

The most common method seems to be creating `/etc/systemd/system/docker.service.d/http-proxy.conf` and applying `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` like this:
```
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:80"
Environment="HTTPS_PROXY=https://proxy.example.com:443"
Environment="NO_PROXY=localhost,127.0.0.1,docker-registry.example.com,.corp"
```
...but I've had no success with that. I've also tried adding to `daemon.json` with no success:
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://192.168.1.12:3128",
     "httpsProxy": "http://192.168.1.12:3128",
     "noProxy": "*.test.example.com,.example2.com,127.0.0.0/8"
   }
 }
}
```
I managed to get it working before colima was switched to alpine, but what is the correct method now? Thanks for your help!

**Comment by abiosoft** [comment]
# Colima docker respponse


Can you try the following?

**Note:** this assumes Colima v0.4.0 or newer.

1. SSH into the VM `colima ssh`
2. Edit `sudo vi /etc/init.d/docker`.  You can install other editors e.g. `sudo apk install vim nano`.
3. Append with the following
    ```sh
    set -o allexport
    if [ -f /etc/environment ]; then source /etc/environment; fi
    set +o allexport
    ```
4. Stop Colima `colima stop`
5. Set the environment variable in the Colima config. `colima start --edit` or edit `$HOME/.colima/default/colima.yaml`
    ```yaml
    env:
      HTTP_PROXY: http://proxy.example.com:80
      HTTPS_PROXY: http://proxy.example.com:443
      NO_PROXY: localhost,127.0.0.1,docker-registry.example.com,.corp
    ```
6. Start Colima `colima start`

**Comment by olliekennedy** [comment]
Thank you very much, that is exactly what I needed! Works perfectly now.

One follow on question - after doing the above, then completely deleting colima with colima stop, colima delete, brew uninstall colima and deleting the ~/.colima folder, when I reinstall and create a new colima VM, my proxy environment variables are already there! Do you know how they are getting populated / where they are cached, even beyond a complete uninstall? Thanks again

**Comment by abiosoft** [comment]
Proxy environment variables (`HTTP_PROXY`, `HTTPS_PROXY`,` NO_PROXY`) are always forwarded to the VM as long as they are available in the shell before you run `colima start`, irrespective of their presence in the Colima config file. 
That is most likely what is happening.

The issue is that Docker's init file does not utilise the environment variables by default. In your case after the reinstall, I would not expect your Docker commands to outrightly work as before, but the environment variables will be present.

**Comment by olliekennedy** [comment]
Fantastic, thank you so much for your help, you've unblocked us! Appreciate your time :)

**Comment by abiosoft** [comment]
Now that the issue is known, a proper fix will be worked on so you would not need to manually edit the init script.

Thanks.

**Comment by mdavino** [comment]
I solved it this way:

sudo vi /etc/systemd/system/docker.service.d/docker.conf

Append:
EnvironmentFile=/etc/environment

**Comment by mdavino** [comment]
@abiosoft ubuntu services are started by systemd. Then, the indicated workaround editing /etc/init.d/docker don't work for me.
[^1] "The  SCRIPT  parameter specifies a System V init script, located in /etc/init.d/SCRIPT, or the name of a systemd unit. The existence of a systemd unit of the same name as  a  script in  [/etc/init.d](file:///etc/init.d)  will  cause  the  unit  to  take  precedence over the init.d script."

Thanks.

[^1]:  https://manpages.ubuntu.com/manpages/lunar/en/man8/service.8.html

**Comment by CallJ051** [comment]
> Can you try the following?
> 
> **Note:** this assumes Colima v0.4.0 or newer.
> 
>     1. SSH into the VM `colima ssh`
> 
>     2. Edit docker init script `sudo vi /etc/init.d/docker`.  You can install other editors e.g. `sudo apk install vim nano`.
> 
>     3. Append with the following
>        ```shell
>        set -o allexport
>        if [ -f /etc/environment ]; then source /etc/environment; fi
>        set +o allexport
>        ```
> 
>     4. Stop Colima `colima stop`
> 
>     5. Set the environment variable in the Colima config. `colima start --edit` or edit `$HOME/.colima/default/colima.yaml`
>        ```yaml
>        env:
>          HTTP_PROXY: http://proxy.example.com:80
>          HTTPS_PROXY: http://proxy.example.com:443
>          NO_PROXY: localhost,127.0.0.1,docker-registry.example.com,.corp
>        ```
> 
>     6. Start Colima `colima start`
Thanks @abiosoft !
After a lot of browsing and googling around, these steps solved my issue as well, even in June 2024. 
However, I had to rely on `apt-get` instead to install an editor (`sudo apt-get update && sudo apt-get install vim`).
Step 5 was not required for me, since my proxy environment variables (`HTTP_PROXY`, `HTTPS_PROXY`, `ALL_PROXY`) are already set and present in my shell.

**Comment by SarwarSaif** [comment]
Even after following the steps above for adding the proxy, I'm getting this error:
Get "https://xxxxxx.lab": dial tcp: lookup xxxxxx.lab on 127.0.0.53:53: no such host

**Comment by mikehearn** [comment]
The init script editing worked for me! Strange that init scripts still exist in 2024 :) 

It'd be great if this stuff could be synced from the macOS System Settings.
