### ISSUE TITLE
Colima 0.4.2 does not work with Kind 0.14 for K8S v1.21

### ISSUE THREAD

**Issue by longwuyuan** [abiosoft/colima#305]
### Describe the Issue
- Kind 0.14 does not work with Colima v0.4.2
- Please refer to https://github.com/abiosoft/colima/issues/291
- That problem was resolved by a fix from Kind team and Kind v0.14 solved the problem

### Version
- Colima v0.4.2

% colima version
colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

runtime: docker
arch: x86_64
client: v20.10.16
server: v20.10.14
m@mypc [~] 
#### Lima Version:
% limactl --version
limactl version 0.11.0

#### Qemu Version
% qemu-img --version
qemu-img version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

### Operating System

- [x] macOS Intel
- [ ] macOS m1
- [ ] Linux

### To Reproduce

1. Update and upgrade brew
2. Install kind using brew
3. install Colima using brew
4.Try to use kindest/node:v1.21.x to create cluster `kind create cluster --image kindest/node:v1.21.0`

### Expected behavior
Kind and Colima to work with K8s image v1.12.x

### Additional context
In nginx-ingress project https://github.com/kubernetes/ingress-nginx, our CI and Makefiles still use K8s v1.21.x because there are several providers and users still using K8S v1.21 .

If the combination of Kind v0.14 + Colima v0.4.2 will not support Kubernetes v1.21.x, then hopefully it will be announced somewhere or even better if the error is explicit about support matrix.

Impactwise just about everything that runs on Colima+Kind has to only use K8S v1.24.0 and above now

@bentheelder
@abiosoft

**Comment by abiosoft** [comment]
If I understand this correctly, Kind v0.13.0 + Colima works fine with Kubernetes < 1.24. While Kind v0.14.0 + Colima works fine with Kubernetes v1.24.

I would like to know if this is still related to lack of systemd in Colima's VM.

**Comment by longwuyuan** [comment]
Yesterday Kind 0.14 was working with Colima v0.4.1 to launch K8S v1.21.0 cluster.
I suspect if I force use Colima 0.4.1 with Kind v0.14, then I will be able to create K8s v1.21.0 cluster

**Comment by abiosoft** [comment]
Oh, you mean the problem is with Colima v0.4.2?

**Comment by longwuyuan** [comment]
I suspect. But not a problem as such. Based on the fact that Kind 0.14 was able to create Kubernetes v1.21.0 clusters. I did not go through changelog for Colima v0.4.2 so I am not certain. But I upgrade Bree and rebooted and my dev environ is broken now. Colima 0.4.2 works perfectly fine with Kind 0.14.0 if I create a K8S v1.24.X cluster (K8S v1.24 is default for Kind v0.14)

**Comment by longwuyuan** [comment]
I must repeat, my dev environ uses K8S v1.21.1 so its likely that the change needs to happen on our end. Its just that there are too many providers and users who still have not moved to K8S v1.24.X yet, and they require support.

**Comment by abiosoft** [comment]
I guess we first need to ascertain what version works and what versions does not. I would see if I can do that later in the day.

**Comment by longwuyuan** [comment]
ok. Please forgive me if I am reporting wrong or making any other mistake. I am trying to be careful and will improve as advised. Look forward to know if this combination of latest Colima and latest kind works with K8S versions older than 1.24.

Thank you very very much for this wonderful software.

**Comment by BenTheElder** [comment]
1.21.0 is from some old kind release. This is not a Colima bug, but it's also not considered a kind bug, the image is simply too old.

If you must use Kubernetes v1.21.0 instead of the latest v1.21.x patch, see https://kind.sigs.k8s.io/docs/user/quick-start/#building-images

**Comment by longwuyuan** [comment]
That was my mistake. As usual gratitude gratitude @bentheelder. I will
change sha in our scripts.

Thanks,
; Long

**Comment by longwuyuan** [comment]
I tried the new sha that you provided for kindest/node:v1.21 and our scripts created the K8S v1.21 cluster using Kind v0.14 on Colima 0.4.2. Thank you so much @BenTheElder . Gratitude
