### ISSUE TITLE
Macbook Pro 13" M1 Pro with 32GB Ram => more than 3GB freeze and system restart

### ISSUE THREAD

**Issue by dennisgermany** [abiosoft/colima#310]
### Describe the Issue
I am using a Macbook Pro 13" M1 Pro with 32GB Ram with colima. The default settings are working good. Trying to give more RAM leads to a system freeze. (2 and 3 GB works but 4, 5 and 8 doesn't).

#### Colima Version:

What is the output of `colima version` 

colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

#### Lima Version:

What is the output of `limactl --version`
limactl version 0.11.0

#### Qemu Version

What is the output of `qemu-img --version`
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel
- [x] macOS m1
- [ ] Linux

### To Reproduce

1. colima start --memory 4
2.
3.
4.

### Expected behavior

lima booting no freeze and no restart

### Additional context

- installed today via brew install colima

**Comment by jandubois** [comment]
Lima is limiting memory to 3 GiB if you are on an earlier macOS version than 12.4 (see https://github.com/lima-vm/lima/pull/796 for details), but should not freeze.

If you are on 12.4 and are still having problems with memory sizes over 3 GiB, then please report them against the lima project (ideally try to reproduce with plain lima, without colima first, but I don't see the underlying issue could be with colima).

**Comment by dennisgermany** [comment]
Indeed upgrading my mac to 12.4 helped fixing the problem. Thank you very much :)
