### ISSUE TITLE
Export environment variable DOCKER_HOST when colima links to Docker CLI

### ISSUE THREAD

**Issue by chunleng** [abiosoft/colima#311]
### Describe the Issue

There are quite a number of issues that ended

- https://github.com/GoogleContainerTools/skaffold/issues/7078#issuecomment-1110808514
- https://github.com/abiosoft/colima/issues/266

#### Colima Version:

What is the output of `colima version`

```
colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b
```

#### Lima Version:

What is the output of `limactl --version`

```
limactl version 0.11.0
```

#### Qemu Version

What is the output of `qemu-img --version`

```
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [X] macOS Intel
- [ ] macOS m1
- [ ] Linux

### To Reproduce

1. build dockerfile via Skaffold
2. Skaffold command fails with `Build Failed. Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Check if docker is running.`

### Expected behavior

Skaffold should build Dockerfile properly

### Additional context

The following command has been tested and solves the issue

```
export DOCKER_HOST=unix:///Users/<name>/.colima/local/docker.sock
```

**Comment by chunleng** [comment]
Realized that I got the concept of `$DOCKER_HOST` mixup. Without `$DOCKER_HOST` it seems to point to `default` docker context, which does not exist since colima does not use that context.

The problem here only arises because I have a Kubernetes cluster that needs to utilize docker to build and while it is clear to colima user that a `colima-x` Kubernetes cluster should use the `colima-x` docker context, the docker and kubectl do not know this relation.

Wonder if there is a better way to handle this?

**Comment by abiosoft** [comment]
You can link Colima's socket to the default Docker socket location as specified in the [FAQ](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running).

```
sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
```

**Comment by chunleng** [comment]
The above fixes part of the issue and the other part was not well thought out, so I guess I will close this issue until better definition regarding my use case between docker and kubernetes.

Thank you for the help!
