### ISSUE TITLE
Connection refused while pulling image from private registry in Mac M1

### ISSUE THREAD

**Issue by jtegedor** [abiosoft/colima#318]
### Description
I am trying to pull a docker image from a private registry not directly accessible.  I am therefore using ssh to an intermediate computer to forward the remote registry port 5000 and make it available on localhost:5000, but I get connection refused when trying to pull an image:

```
$ curl -k  https://localhost:5000/v2/_catalog
{"repositories":["test_image"]}
$ docker pull localhost:5000/test_image
Using default tag: latest
Error response from daemon: Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused
```

This works perfectly if I use Docker Desktop instead, but it does not work with Colima. https://github.com/abiosoft/colima/issues/239 is somehow related but not quite the same. Help is much appreciated.

#### Colima Version:

colima version HEAD-d377735
git commit: d3777350f38b78282f78e63d8e42c8f7cbab798c

runtime: docker
arch: aarch64
client: v20.10.16
server: v20.10.14
#### Lima Version:

limactl version 0.11.0

#### Qemu Version

qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel
- [x] macOS m1
- [ ] Linux

**Comment by abiosoft** [comment]
Hmm, what I think is happening is that `localhost` by default is marked as an insecure registry. Due to that, request is being made via http rather than https (according to your curl request).

Is this an https request?

> ```
> $ curl -k  https://localhost:5000/v2/_catalog
> {"repositories":["test_image"]}
> ```

**Comment by jandubois** [comment]
> This works perfectly if I use Docker Desktop instead,

I'm surprised that this works with DD. The image is pulled by the docker daemon, which is running inside a VM. `localhost` for the daemon refers to the VM and not the host.

So unless you forwarded the registry **into** the VM and not just to the host, you will need to use the host IP address to fetch it. Which also means you would need to configure it as an insecure registry because the certs won't match.

I'm interested in understanding how this works with Docker Desktop though; the only thing I can think of is some kind of automatic reverse port forwarding. Maybe they have special support for this in VPNKIT?

**Comment by abiosoft** [comment]
@jtegedor can you `colima start --edit` or edit the config at `$HOME/.colima/default/colima.yaml` and add `https://localhost:5000` to list of insecure registries as mentioned in the [FAQ](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#how-to-customize-docker-config-eg-add-insecure-registries)?

**Comment by jtegedor** [comment]
@abiosoft , not quite working either, after `colima start --edit` and restart:

```
[1]$ grep -A 4 ^docker .colima/default/colima.yaml 
docker:
  insecure-registries:
    - registry:5000
    - localhost:5000
    - 127.0.0.1:5000
 
[2]$ docker pull registry:5000/test_image
Using default tag: latest
Error response from daemon: Get "http://registry:5000/v2/": dial tcp: lookup registry on 1.1.1.1:53: no such host

[3]$ docker pull localhost:5000/test_image
Using default tag: latest
Error response from daemon: Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused

[4]$ docker pull 127.0.0.1:5000/test_image
Using default tag: latest
Error response from daemon: Get "http://127.0.0.1:5000/v2/": dial tcp 127.0.0.1:5000: connect: connection refused
```

**Comment by jandubois** [comment]
You continue to use variants of `localhost`, which cannot work, as I explained earlier:

> So unless you forwarded the registry **into** the VM and not just to the host, you will need to use the host IP address to fetch it.

Configure `host.docker.internal:5000` as an insecure registry and then try that one.

**Comment by jtegedor** [comment]
@jandubois , that works!

```
[1]$ grep -A 3 ^docker .colima/default/colima.yaml 
docker:
  insecure-registries:
    - host.docker.internal:5000

[2]$ docker pull host.docker.internal:5000/test_image
Using default tag: latest
latest: Pulling from test_image
d8d02d457314: Downloading [=====
...
```

I think it would be nice if Colima replicates the behaviour of DD in this case, otherwise it is a bit difficult to understand what is going on for users with limited experience (like me).

Many thanks, appreciated!
