### ISSUE TITLE
How to change kernel variables so they persist

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#319]
### Describe the Issue

I'd like to change `fs.inotify.max_user_watches` in the lima guest (it defaults to a measly 8192; Docker Desktop at least gives 1048576)

I can `colima ssh` and `sysctl -w fs.inotify.max_user_watches=1048576` and it works... until restart. It doesn't persist.

I tried creating /etc/sysctl.d/local.conf with `fs.inotify.max_user_watches=1048576` as the contents, but that doesn't seem to have any effect.

#### Colima Version:

What is the output of `colima version`

```
% colima version
colima version HEAD-d377735
git commit: d3777350f38b78282f78e63d8e42c8f7cbab798c
```

#### Lima Version:

What is the output of `limactl --version`
`limactl version 0.11.0`

#### Qemu Version

What is the output of `qemu-img --version`

`qemu-img version 7.0.0`

### Operating System

- [ ] macOS Intel
- [x] macOS m1
- [ ] Linux

### To Reproduce

As above, try to make persistent change to fs.inotify.max_user_watches

**Comment by abiosoft** [comment]
This can be handled inside Colima.
For more flexibility, a config option can be provided for users to specify arbitrary commands as part of VM provision.

**Comment by abiosoft** [comment]
Kindly `brew install --head colima` and it should be fixed by now.

Specifying arbitrary commands as part of VM provision will be properly worked on.

**Comment by rfay** [comment]
That definitely works, thanks so much! And 1M should be enough for most cases. Longer term it would be nice to be able to provide arbitrary commands. Thanks! And so fast!
