### ISSUE TITLE
Volume mounts do not work (files aren't shared between host and container)

### ISSUE THREAD

**Issue by Amar1729** [abiosoft/colima#323]
### Describe the Issue
Volume mounts (`docker run -v` or `volumes:` in docker-compose) do not share files between macOS host and docker container. Files created on host are not seen by container, and files created from inside container are not seen on host (but do appear inside colima's VM).

#### Colima Version:

What is the output of `colima version`

Tested on an ARM and Intel mac:
```
# m1 mac
colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

runtime: docker
arch: aarch64
client: v20.10.16
server: v20.10.11
```

```
# intel mac
colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b
```

#### Lima Version:

What is the output of `limactl --version`

```
# m1 mac
limactl version 0.11.0
```

```
# intel mac
limactl version 0.11.0
```

#### Qemu Version

What is the output of `qemu-img --version`

```
# m1
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

```
# intel mac
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [x] macOS Intel
- [x] macOS m1
- [ ] Linux

### To Reproduce

1. Create a new directory with one empty file inside and cd into it
```
$ mkdir /tmp/fake && cd /tmp/fake && touch host-fakefile
```
2. Run a docker container with the current directory as a volume, and try to list files
```
$ docker run --rm -it -v $(pwd):/app ubuntu:20.04 ls
```
3. The output SHOULD be one file, `host-fakefile` - instead, it is empty 
4. Test creation of files from inside container with `touch`:
```
$ docker run --rm -it -v $(pwd):/app ubuntu:20.04 touch container-fakefile
```
6. The host system still only sees `host-fakefile`:
```
$ ls
host-fakefile
```

7. But colima's VM sees only `container-fakefile`:
```
$ colima ssh

colima:/tmp/fake $ ls
container-fakefile
```

### Expected behavior

The container `ls` command (step 2) would see `host-fakefile`, and - if running steps in order - the host's `ls` (step 6) would see both `container-fakefile` and `host-fakefile`. I confirmed this behavior with the docker daemon (NOT `colima`) on a Linux machine running Ubuntu 18.04.

```
$ docker --version
Docker version 19.03.12, build 48a66213fe

$ mkdir /tmp/fake && cd /tmp/fake && touch host-fakefile

$ docker run --rm -it -v $(pwd):/app -w /app ubuntu:20.04 ls
host-fakefile

$ docker run --rm -it -v $(pwd):/app -w /app ubuntu:20.04 touch container-fakefile

$ ls
container-fakefile host-fakefile
```

**Comment by sercant** [comment]
@Amar1729 I think `/tmp/` folder is not in the mounted by default. You can see the mounted folders with the following command.

```bash
$ colima stop
$ limactl edit colima
```

and check the `mounts` part in the configuration:

```yaml
...
mounts:
    - location: "~"
      writable: true
    - location: /tmp/colima
      writable: true
...
```

You can add folders to mount in the `colima start` command. Find more info via `colima start --help`.

**Comment by Amar1729** [comment]
Awesome, thanks @sercant i knew there must be something i was doing wrong! I have some docker stuff stored under `/opt` and that's not mounted by default either. `colima start --mount "/opt/docker:w"` worked for me 👍

**Comment by Amar1729** [comment]
My bad, didn't even recognize #267 as the same issue before posting this.
