### ISSUE TITLE
M1 Colima start issue

### ISSUE THREAD

**Issue by hs-shakhzod-khodjaev** [abiosoft/colima#325]
### Describe the Issue
I installed recent version of colima successfully. Tried to start it with "colima start", the process starts, reaches "waiting ssh", and my laptop restarts automatically.

#### Colima Version:

colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

#### Lima Version:

limactl version 0.11.0

#### Qemu Version

qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel
- [x] macOS m1
- [ ] Linux

### To Reproduce

1. brew install colima
2. colima start
3.
4.

### Expected behavior

The process "colima start" reaches "awaiting ssh" step and the laptop crashes and restarts automatically

**Comment by hs-shakhzod-khodjaev** [comment]
my laptop crashes

**Comment by hs-shakhzod-khodjaev** [comment]
And my $HOME/.lima/colima/serial.log file is empty after restart

**Comment by hs-shakhzod-khodjaev** [comment]
Found a solution!

I had MacOS 12.2. Updated it to 12.4 and it solved the issue.

**Comment by abiosoft** [comment]
Thanks for troubleshooting.
