### ISSUE TITLE
Cannot specify path including spaces in --editor argument of command line

### ISSUE THREAD

**Issue by murata100** [abiosoft/colima#327]
### Describe the Issue

input
```
colima start --edit --editor "/usr/bin/my editor"
```

output
```
INFO[0000] editing in /usr/bin/my editor
FATA[0000] error editing config file: fork/exec /usr/bin/my: no such file or directory
```

#### Colima Version:

```
colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

runtime: docker
arch: x86_64
client: v20.10.17
server: v20.10.11
```

#### Lima Version:

```
limactl version 0.11.0
```

#### Qemu Version

```
qemu-img version 6.2.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [x] macOS Intel
- [ ] macOS m1
- [ ] Linux

### To Reproduce

```
colima start --edit --editor "/usr/bin/my editor"
```

### Expected behavior

open "/usr/bin/my editor"

### Additional context

nothing

**Comment by abiosoft** [comment]
Oops, that was an oversight due to the consideration that it is possible to pass args to the editor. e.g. `code --wait --new-window`.

Which editor are you trying to use?

**Comment by murata100** [comment]
I'm sorry.

I just happened to make an operation mistake and noticed.
I have nothing to wanna do

**Comment by murata100** [comment]
`/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code`

**Comment by abiosoft** [comment]
> I wanted to do this
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code

Why not install code binary in PATH and that way you can simply specify `code` as the editor.

<img width="606" alt="Screenshot 2022-06-09 at 7 04 41 AM" src="https://user-images.githubusercontent.com/240448/172776019-9c67eaf8-4e7d-41ef-bf90-0e8e703b0eb4.png">

**Comment by murata100** [comment]
I'm sorry, I know.
I just wanted to give it a try 😄 

Also, to create a common command line script for those who are not doing it

**Comment by abiosoft** [comment]
Yeah, thanks for reporting.

It has been fixed btw and will be merged once the build passes https://github.com/abiosoft/colima/pull/328. 
You can verify afterwards by installing the head version on brew with `brew install --head colima`.
