### ISSUE TITLE
gvisor-tap-vsock debug cause big daemon.log file

### ISSUE THREAD

**Issue by moolex** [abiosoft/colima#332]
### Describe the Issue
set gvisor-tap-vsock Configuration with debug cause `~/.colima/default/network/daemon.log` file very large, docker pull with an 1.5GB image will make daemon.log increased almost 370MB

#### Colima Version:

colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

runtime: docker
arch: x86_64
client: v20.10.17
server: v20.10.11

#### Lima Version:

limactl version 0.11.0

#### Qemu Version

qemu-img version 7.0.0

### Operating System

- [x] macOS Intel

### To Reproduce

just `colima start`

**Comment by SuperFola** [comment]
This isn't a bug, you asked for logs and this is a log file.

**Comment by moolex** [comment]
> This isn't a bug, you asked for logs and this is a log file.

Not a bug, but maybe it's better with debug when user provide --verbose flag in cli

**Comment by abiosoft** [comment]
This should be resolved by now and will be part of the next release. 
You can also try it out now in head `brew install --HEAD colima`
