### ISSUE TITLE
Bad configuration option: 'identityfile when colima ssh on macOS M1

### ISSUE THREAD

**Issue by tonidy** [abiosoft/colima#349]
### Description

Got this error when running `colima ssh`

```
command-line: line 0: Bad configuration option: 'identityfile
FATA[0000] exit status 255
```

- Enable Ubuntu layer (`--layer`)
- Enable reachable IP address (`--network-address`)

### Version

Colima Version:
```
colima version 0.4.2
git commit: f112f336d05926d62eb6134ee3d00f206560493b

runtime: docker
arch: aarch64
client: v20.10.17
server: v20.10.11
```
Lima Version:
```
limactl version 0.11.1
```
Qemu Version:
```
qemu-img version 7.0.0
```

### Operating System

- [ ] macOS Intel
- [X] macOS M1 Monterey 12.4
- [ ] Linux

### Reproduction Steps

1. `colima start --memory 5 --layer --network-address`
2. `colima ssh`

### Expected behaviour

Can connect into the VM

**Comment by abiosoft** [comment]
This has been fixed and will be part of the next release. 
You can build from source or install the development version `brew install --head colima` if you would rather not wait until the next release.

Thanks.

**Comment by tonidy** [comment]
@abiosoft sorry for late reply. I just waited for the next release then because I can still working without ubuntu layer.

Thanks
