### ISSUE TITLE
Trying to connect to a database using Colima

### ISSUE THREAD

**Issue by rohanafsan** [abiosoft/colima#350]
### Description

Due to lack of documentation, I am reaching out through here.  I am trying to connect to a specific database ip using `colima start -i xxx.x.x.x` but I get an error saying unknown shorthand flag: 'i' in -i. How else would I do it if not like this? Would it be through the config file

### Version

Colima Version: HEAD-2fbc0fd
git commit: 2fbc0fdef39eb904d993fb65fae18efa744c870b
Lima Version:  0.11.1
Qemu Version:

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

1.colima start -i 127.0.0.1
2.
3.

### Expected behaviour

Colima starting up as expected

**Comment by rfay** [comment]
`colima start -h` shows you the available options. What is it you want to do? (In head I recommend `colima start --edit` to set your preferences in the config file.)

```
Start Colima with the specified container runtime and optional kubernetes.

Colima can also be configured with a YAML file.
Run 'colima template' to set the default configurations or 'colima start --edit' to customize before startup.

Usage:
  colima start [profile] [flags]

Examples:
  colima start
  colima start --edit
  colima start --runtime containerd
  colima start --kubernetes
  colima start --runtime containerd --kubernetes
  colima start --cpu 4 --memory 8 --disk 100
  colima start --arch aarch64
  colima start --dns 1.1.1.1 --dns 8.8.8.8

Flags:
  -a, --arch string                 architecture (aarch64, x86_64) (default "aarch64")
  -c, --cpu int                     number of CPUs (default 2)
      --cpu-type string             the CPU type, options can be checked with 'qemu-system-aarch64 -cpu help'
  -d, --disk int                    disk size in GiB (default 60)
  -n, --dns ipSlice                 DNS servers for the VM (default [])
  -e, --edit                        edit the configuration file before starting
      --editor string               editor to use for edit e.g. vim, nano, code (default "$EDITOR" env var)
      --env stringToString          environment variables for the VM (default [])
  -h, --help                        help for start
  -k, --kubernetes                  start with Kubernetes
      --kubernetes-ingress          enable Traefik ingress controller
      --kubernetes-version string   must match a k3s version https://github.com/k3s-io/k3s/releases (default "v1.23.6+k3s1")
  -l, --layer                       enable Ubuntu container layer
  -m, --memory int                  memory in GiB (default 2)
  -V, --mount strings               directories to mount, suffix ':w' for writable
      --mount-type string           volume driver for the mount (sshfs, 9p) (default "sshfs")
      --network-address             assign reachable IP address to the VM
  -r, --runtime string              container runtime (containerd, docker) (default "docker")
  -s, --ssh-agent                   forward SSH agent to the VM

Global Flags:
  -p, --profile string   profile name, for multiple instances (default "default")
  -v, --verbose          enable verbose log
      --very-verbose     enable more verbose log
```

**Comment by rohanafsan** [comment]
I want colima to connect to a specific ip address. Not sure what I would do to make that work

**Comment by rfay** [comment]
Not sure it's colima's job to connect to anything. Colima's job is to run docker VM or other environments (kubernetes, etc) where you can do a variety of things.

**Comment by rohanafsan** [comment]
Right but with docker I can connect to a specific container with an IP address. How would I do that with Colima?

**Comment by rfay** [comment]
If you're running colima with docker, then the docker containers are running inside it, and you would typically connect to them by name. If you have containers running elsewhere (outside colima) you'll have to jump through lots of hooks to use them. It's possible you misunderstand what colima is for. It's a complete environment for running docker containers and related environments.
