### ISSUE TITLE
Can't access api hosted in container

### ISSUE THREAD

**Issue by iamdakshay** [abiosoft/colima#356]
### Description

I tried installing and using colima on Macbook.
```
brew install colima
brew install docker
brew install docker-compose
```
`colima start`

I built image and ran it. Exposed port 5004.
 Tried to access http://localhost:5004/, but getting error, **This site can’t be reached
localhost refused to connect.**

Dockerfile:

```
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env

WORKDIR /app

# Copy everything
COPY . ./

# Restore as distinct layers
RUN dotnet restore

# Build and publish a release
RUN dotnet publish -c Release -o out


# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 5004
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://*:5004
ENTRYPOINT ["dotnet", "loggingwithserilog.api.dll"]
```

### Version

**colima version HEAD-3a85204**
git commit: 3a85204fa783ea0d73c9f073f89da2393bc05e5e

runtime: docker
arch: aarch64
client: v20.10.17
server: v20.10.11
**limactl version 0.11.1
qemu-img version 7.0.0**

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Additional context

```
docker run loggingwithserilogapi  --rm -p 5004:5004 --name loggingwithserilogapi_1
[10:54:29  INF  ] Now listening on: http://[::]:5004
[10:54:29  INF  ] Application started. Press Ctrl+C to shut down.
[10:54:29  INF  ] Hosting environment: Development
[10:54:29  INF  ] Content root path: /app
```

**Comment by iamdakshay** [comment]
Yes tried different ports.

**Comment by abiosoft** [comment]
> Yes tried different ports.

I am not referring to ports, I am actually referring to other containers. Have you tried to run another container (like the caddy example above) and got the same behaviour?

**Comment by iamdakshay** [comment]
Oh my bad. Yes, it worked.
