### ISSUE TITLE
Error when start Colima with Kubernetes

### ISSUE THREAD

**Issue by jinguoliu** [abiosoft/colima#363]
### Description

➜  colima start -k
INFO[0000] settings from older colima version detected and copied 
INFO[0000] starting colima                              
INFO[0000] runtime: docker+k3s                          
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
INFO[0031] provisioning ...                              context=docker
INFO[0031] starting ...                                  context=docker
INFO[0037] provisioning ...                              context=kubernetes
INFO[0037] downloading and installing ...                context=kubernetes
INFO[0048] loading oci images ...                        context=kubernetes
INFO[0060] starting ...                                  context=kubernetes
INFO[0065] updating config ...                           context=kubernetes
> error: mkdir /.kube: read-only file system
FATA[0065] error starting kubernetes: error at 'updating config': exit status 1 

### Version

Colima Version: v0.4.4
Lima Version: 0.11.1
Qemu Version: 7.0.0

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

**Comment by imxw** [comment]
I have the same issue in macOS M1

**Comment by jinguoliu** [comment]
I don't remember if it was upgraded from a version <0.4.0. After a reinstallation, it works on the same version.
