### ISSUE TITLE
Network issue in Macos Intel: Cannot pull repo by registry-1.docker.io and Cannot request website like "google" inside container

### ISSUE THREAD

**Issue by xiantang** [abiosoft/colima#364]
### Description

<img width="242" alt="image" src="https://user-images.githubusercontent.com/34479567/178028541-0b409577-4185-49ef-9e9e-d8cbd97e644d.png">

I use macOS Monterey and try to use colima to replace docker Desktop.

But sometime I can meet this two issue at same time no matter how whether I use AnyConnect VPN :

1.  Cannot pull repo by registry-1.docker.io
<img width="898" alt="image" src="https://user-images.githubusercontent.com/34479567/178029522-f28be5c9-ccd0-4870-8ae9-b4443ca765cc.png">
but I can visit this link using chrome.
<img width="731" alt="image" src="https://user-images.githubusercontent.com/34479567/178029618-363cfbed-49cd-40c6-a31d-140c7b5233be.png">

2.  Cannot request website like "google" inside container
My container will request public and internal webside when it  start, but I find it cannot to request any website which is base on HTTP/HTTPS 

when I try to use cURL to request google it will stuck long time.
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/34479567/178030530-ab9ddde5-3491-4589-afa2-e1677e0e7160.png">
 

### Version

git commit: 8bb1101a861a8b6d2ef6e16aca97a835f65c4f8f

runtime: docker
arch: x86_64
client: v20.10.14
server: v20.10.11

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Additional context

I think this two issue is related, because it's happen in same time

**Comment by vigohe** [comment]
same issue! but now it's working after I restart colima

```bash
colima stop
colima start
```

**Comment by ventsislav-georgiev** [comment]
Sporadically the networking breaks. Sometimes even on existing images, the docker metadata check for new version of the tag fails. `colima stop && colima start` always fixes it.

**Comment by SuperFola** [comment]
I haven't had any problem like this (M1 Mac) since I added the certificates of docker and our private registry to the VM, but that could be a different problem, though I had the same error messages (most likely SSL related problems).

**Comment by techguy0079** [comment]
@SuperFola  Can you please share the steps which helped you in the SSL problems while accessing registry-1.docker.io.
I have uploaded the certs to /etc/docker/certs.d directory inside the VM but still the same issue. I am unable to pull images form docker hub as SSL issue is not resolved. Any help would be appreciated.

**Comment by xiantang** [comment]
migrated to Orbstack Closed
