### ISSUE TITLE
Regenerate docker context

### ISSUE THREAD

**Issue by miralize** [abiosoft/colima#368]
### Description

Hey @abiosoft, love this project :)

Just wondering if theres a way to re-run the Provision method for docker. I had some issues with my .docker config so I nuked it but now i dont have an context entry for colima. Is there a way to regenerate it?

I tried `brew reinstall colima` but that was to no avail either

**Comment by abiosoft** [comment]
Simply stop and start colima. The context is added on startup.

**Comment by miralize** [comment]
Ah thanks :)
