### ISSUE TITLE
How to configure Swap size?

### ISSUE THREAD

**Issue by AndreKelling** [abiosoft/colima#371]
Is it possible to configure the so called "Swap" size?

Is it possible to check what is the current configured value for the Swap size?

Is there a way with the current colima CLI (v 0.4.4)?

**Background**

Similar to this issue solver answer: https://github.com/benweet/stackedit/issues/1177#issuecomment-353474049

I would like to debug on the Swap size side and may hope for better results with my very own "Killed" issue:

```
Killed
error Command failed with exit code 137.
```

**Comment by AndreKelling** [comment]
okay,

i did solved my issue because i hadn't enough RAM active.
Because i was on a macOS version where there was an issue with.

while colima start up there is a log about that:

> [hostagent] Reducing the guest memory from 16GiB to 3GiB, to avoid host kernel panic on macOS <= 12.3 with QEMU >= 7.0; Please update macOS to 12.4 or later, or downgrade QEMU to 6.2; See https://github.com/lima-vm/lima/issues/795 for the further background.

but my initial question may still be a valid one....

**Comment by SuperFola** [comment]
AFAICT lima does not have an option to set swap size, and since colima is a wrapper around lima your question might be better on the lima repo.

**Comment by abiosoft** [comment]
There is an upstream issue https://github.com/lima-vm/lima/issues/965 as well as a discussion https://github.com/lima-vm/lima/discussions/941.

**Comment by AndreKelling** [comment]
closed as referenced to lima-vm repo
