### ISSUE TITLE
nerdctl in colima seems limited

### ISSUE THREAD

**Issue by alessandroargentieri** [abiosoft/colima#378]
### Description

When starting Colima with `containerd` as runtime you are supposed to interact with your containers with `nerdctl` command line tool.

Unfortunately, differently from `docker`, you cannot install it on macOS because is not supported, so you have to use Colima as mean to interact with `nerdctl`.

The problem is that `colima nerdctl` doesn't allow all the commands flags that `nerdctl` documentation indicates.
For example, in the [official nerdctl documentation](https://github.com/containerd/nerdctl#basic-usage) we read this command shown as basic example:

```bash
$ nerdctl run -it --rm alpine
```

doing the same with Colima, instead, returns:

```bash
$ colima nerdctl run -it --rm alpine
FATA[0000] unknown shorthand flag: 'i' in -it   
```

the same happens with the flags `--name`.

### Version

colima version 0.4.4
git commit: 8bb1101a861a8b6d2ef6e16aca97a835f65c4f8f
runtime: containerd
arch: aarch64
client: v0.20.0
server: v1.5.8
limactl version 0.11.2

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. `colima start --runtime containerd`
2. `colima nerdctl run -it --rm alpine`

### Expected behaviour

I'm expected to have the container starting in lima virtual machine

**Comment by abiosoft** [comment]
If you run `colima nerdctl --help`, you'd see

```
$ colima nerdctl --help
Run nerdctl to interact with containerd.
This requires containerd runtime.

It is recommended to specify '--' to differentiate from Colima flags.
```

You should add `--` to your commands and the following should work fine.
```
colima nerdctl -- run -it --rm alpine
```

You can also run install the nerdctl script with `colima nerdctl install` for easier access.
```sh
$ colima nerdctl install # install nerdctl in PATH
$ nerdctl run -it --rm alpine # works as desired
```

**Comment by alessandroargentieri** [comment]
Thanks! It works perfectly!
