### ISSUE TITLE
Docroot not set as defined

### ISSUE THREAD

**Issue by ursbraem** [abiosoft/colima#391]
### Description

I try switching from Docker Desktop to colima for use with ddev. 
After fully uninstalling Docker Desktop and then installing colima it works.

But the env variable $DOCROOT (which is set and can be echoed in the ddev container) is not respected in the routing. The domain always lands in the project root / app root directory. 

The issue does not arise with Docker desktop.

I'm looking at it in parallel in the ddev community, the issue is the same as: https://github.com/drud/ddev/issues/3764

### Version

Colima Version: 0.4.4
Lima Version: 0.11.3
Qemu Version: 7.0.0
ddev Version: 1.20.0

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

1. brew install docker
2. brew install colima
3. brew install ddev
4. Install [drupal test build ](https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal-9-composer-build) or any other project with docroot != project root
5. Now I get (nginx):
- https://my-drupal9-site.ddev.site/ -> 404 
- https://my-drupal9-site.ddev.site/web -> 404
- https://my-drupal9-site.ddev.site/web/core/install.php -> 200 

### Expected behaviour

- https://my-drupal9-site.ddev.site/ -> 200 pointing into the right directory

### Additional context

I don't know how to reproduce with colima only, to find out if it's a colima or ddev issue.
Not sure if that makes sense, but as opposed to the ddev container, where the $DOCROOT is returned:

```
ddev ssh
echo $DOCROOT
web
```

With `colima ssh` that is empty:

```
colima ssh
echo $DOCROOT

```

**Comment by rfay** [comment]
This has nothing to do with coima, and it's misunderstanding on your part.  Please close the issue and continue with the many other places you've asked this.

**Comment by rfay** [comment]
DDEV does not provide a DOCROOT environment variable, and using `colima ssh` has nothing to do with DDEV.

To set the docroot for a DDEV project, you can edit it in .ddev/config.yaml, or use `ddev config --docroot=<docroot>`.

There's no reason to ever use `colima ssh` - you use `ddev ssh` if you need it with ddev. That gets you into a completely different container.

DOCROOT is set in the ddev web container but it does not affect the project's behavior.
