### ISSUE TITLE
Warnings when using latest colima on macOS

### ISSUE THREAD

**Issue by ventsislav-georgiev** [abiosoft/colima#404]
### Description

Installing colima from HEAD prints warnings on macOS.
Every command logs these warnings:
```
W0822 11:07:08.240926   31394 native_arm64.go:52] Could not read /proc/cpuinfo: open /proc/cpuinfo: no such file or directory
W0822 11:07:08.241069   31394 native_arm64.go:177] Could not read /proc/self/auxv: open /proc/self/auxv: no such file or directory
```

The `start` command creates the vm and provisions k3s cluster. The ssh command and the k3s cluster is working.

May be related to: https://github.com/google/gvisor/issues/7849

### Version

Colima Version: HEAD-6c4889b
Lima Version: 0.11.3
Qemu Version: 7.0.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. brew install colima --HEAD
2. any command: start, status, version.

**Comment by abiosoft** [comment]
> May be related to: https://github.com/google/gvisor/issues/7849

Yeah, it is possible. Will revert to an older version of the dependency and see.

**Comment by abiosoft** [comment]
I have successfully reproduced this and working on a fix.

**Comment by abiosoft** [comment]
This should be fixed now.
