### ISSUE TITLE
Can not mount files from local /tmp dir into container 

### ISSUE THREAD

**Issue by rlewkowicz** [abiosoft/colima#405]
### Description

With docker, I mount a config into a container at runtime. I try to do it here, and it fails. Both files exist, and both are indeed files. 

The key difference seems to be /tmp

### Version

colima version 0.4.4
git commit: 8bb1101a861a8b6d2ef6e16aca97a835f65c4f8f

runtime: docker
arch: x86_64
client: v20.10.14
server: v20.10.11

kubernetes
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.23.6+k3s1
---
limactl version 0.11.3
---
qemu-img version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

```
touch /tmp/test
docker run -ti -v /tmp/test:/lib/libapk.so.3.12.0 alpine
```

### Expected behaviour

I should be able to mount files from tmp

```
touch test
docker run -ti -v $(pwd)/test:/lib/libapk.so.3.12.0 alpine
```

works

**Comment by abiosoft** [comment]
Only `$HOME` and `/tmp/colima` directories are mounted by default, you can simply use `/tmp/colima` instead.
