### ISSUE TITLE
Error Provisioning Kubernetes while starting colima on version 0.4.4

### ISSUE THREAD

**Issue by ujwalkumar1995** [abiosoft/colima#409]
### Description

I had an older version of colima and updated it recently using brew.
On latest version of colima, facing below issue while starting colima.
<img width="959" alt="Screenshot 2022-08-25 at 7 45 44 PM" src="https://user-images.githubusercontent.com/20976813/186689331-5e444d02-8990-4764-b4da-0e15e2ec345c.png">

### Version

Colima Version: 0.4.4
Lima Version: 0.11.3
Qemu Version: 7.0.0

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

Installed latest colima version from brew and ran colima start
Had an older version of colima already installed. Not sure if that is something that may have caused this.

### Expected behaviour

Should have been able to provision kubernetes without throwing any error.

### Additional context

Have already tried limactl delete colima and colima delete and started it again. Also tried uninstalling and installing colima again from brew. No luck as of now.

**Comment by nosiop** [comment]
I have the same problem. My Operating System is MacOS with M1 Pro. Can anyone can give the reason and solution of this.

**Comment by abiosoft** [comment]
This looks like a broken download. Can you clear the caches at `$HOME/Library/Caches/colima` and try again?

A more robust download mechanism is in the works.

**Comment by nosiop** [comment]
> This looks like a broken download. Can you clear the caches at `$HOME/Library/Caches/colima` and try again?
> 
> A more robust download mechanism is in the works.

For some reason, I download the file from github server is very slow and may lose connection.
Can I download related files by myself and move to somewhere colima can read from, instead of downloading from github server when execute "colima start --kubernetes --arch aarch64". 
such as [k3s-airgap-images-arm.tar.gz](https://github.com/k3s-io/k3s/releases/download/v1.23.6%2Bk3s1/k3s-airgap-images-arm.tar.gz)
If that works. I am not sure which files are necessary？ Can you give a file list for downloading?

**Comment by abiosoft** [comment]
You can hack around it. You would need to compute the sha256 of the download URL (from GitHub) and use it as the filename in the cache directory `$HOME/Library/Caches/colima`.

A better approach would be to provide alternative options for the downloads.

1. Permit the skipping of the cache files. i.e. k3s would download them from the image registry (may be faster in your case).
2. Accept user-provided url for the airgap images.

The problem with **1** is that the images would be getting re-downloaded after a `colima delete`.

**Comment by ujwalkumar1995** [comment]
> This looks like a broken download. Can you clear the caches at `$HOME/Library/Caches/colima` and try again?
> 
> A more robust download mechanism is in the works.

Clearing the cache worked for me. Thank you for the resolution.
