### ISSUE TITLE
YAML warnings

### ISSUE THREAD

**Issue by aretrace** [abiosoft/colima#426]
### Description

Status is spuing a malformed warning indicating `"Non-strict YAML is deprecated and will be unsupported in a future version of Lima" comment="main file \"/Users/<username>/.lima/colima/lima.yaml\"` when initializing both startup and shutdown. 

### Version

Colima Version: 0.4.4
Lima Version: 0.12.0
Qemu Version: 7.1.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

- `colima start`
- `colima stop`
- `colima ssh`
- ...etc...

### Expected behaviour

No warnings or errors in status messages.

**Comment by rfay** [comment]
This is new with today's upgrade to lima 0.12.0, I saw it too.

**Comment by aretrace** [comment]
I was hesitant updating via homebrew today, I got that spider sense tingling that something might happen. Containers seem to be OK at least.

**Comment by jandubois** [comment]
Is this the full warning? It should include the name of the fields that are not part of the lima schema.

I suspect colima is storing additional information in `lima.yaml` under private keys. This will no longer be allowed in the future, so we can catch it when a user misspells a setting, which right now is just being ignored silently. For now the deprecation warning should be harmless (although ugly and annoying, but that is its purpose).

**Comment by rfay** [comment]
Here's the full complaints:

https://gist.github.com/rfay/97a0dae94c2e49830356e426c2ce0353

**Comment by jandubois** [comment]
Thanks, this is the reason: `unknown field "colimaState"`.

So it will require a change to colima to fix this.

@abiosoft  I would suggest to write any addition state into e.g. a `colima.json` right next to the `lima.yaml`, so it doesn't interfere.

**Comment by abiosoft** [comment]
Thanks @jandubois, I will extract it.

**Comment by abiosoft** [comment]
This should be fixed now. 

It can be tested immediately by installing the head `brew install --HEAD colima` and will be part of the next release.

Thanks.

**Comment by AkihiroSuda** [comment]
Do you have a timeline for the next release? 🙏

**Comment by abiosoft** [comment]
> Do you have a timeline for the next release? 🙏 

I am looking to include vmnet_socket. But I can delay it since it is not as pressing.
