### ISSUE TITLE
"colima stop -f" not working when startup status is unknown

### ISSUE THREAD

**Issue by rpkoller** [abiosoft/colima#439]
### Description

When i tried to start colima today i ran into the following error: 

```
$> colima start 
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] preparing network ...                         context=vm
INFO[0000] starting ...                                  context=vm
> Using the existing instance "colima"
> errors inspecting instance: [failed to get Info from "/Users/myuser/.lima/colima/ha.sock": Get "http://lima-hostagent/v1/info": dial unix /Users/myuser/.lima/colima/ha.sock: connect: connection refused]
FATA[0000] error starting vm: error at 'starting': exit status 1 
```

if i take a look into `~/.lima/colima`  i only have the following list of files: 

```
serial.log
lima.yaml
ha.stdout.log
ha.stderr.log
ha.pid
diffdisk
colima.yaml
cidata.iso
basedisk
```
ha.sock i somehow missing?! but i haven't edited or done anything or touched anything in that folder? i've also tried 

```
$> colima list
PROFILE    STATUS    ARCH       CPUS    MEMORY    DISK      RUNTIME    ADDRESS
default    Broken    aarch64    4       8GiB      100GiB
```
i've also tried (found in https://github.com/abiosoft/colima/issues/381):

```
$> colima stop -f
INFO[0000] stopping colima                              
INFO[0000] not running                                   context=vm
INFO[0000] done   
```

but `colima start` still fails afterwards. is there a way to get the broken state back to working? and the other question i wonder what actually caused that sudden fail? 

### Version

Colima Version:
```
$> colima version  
colima version 0.4.6
git commit: 10377f3a20c2b0f7196ad5944264b69f048a3d40
```
Lima Version:
```
$> limactl --version
limactl version 0.12.0
```
Qemu Version:
```
$> qemu-img --version
qemu-img version 7.1.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

I don't know how to reproduce. I simply did a `colima start` and i ran into the error mentioned in the description.

**Comment by rpkoller** [comment]
strange. https://github.com/abiosoft/colima/issues/381#issuecomment-1223561114 stated `limactl stop -f colima is the equivalent to `colima stop -f` but `colima stop -f` had the following output with no effect: 

```
$> colima stop -f
INFO[0000] stopping colima                              
INFO[0000] not running                                   context=vm
INFO[0000] done
```

while limactl stop had the following output: 

```
$> limactl stop -f colima
INFO[0000] The QEMU process seems already stopped       
INFO[0000] Sending SIGKILL to the host agent process 1167 
INFO[0000] Removing *.pid *.sock under "/Users/rkoller/.lima/colima" 
INFO[0000] Removing "/Users/rkoller/.lima/colima/ga.sock" 
INFO[0000] Removing "/Users/rkoller/.lima/colima/ha.pid" 
INFO[0000] Removing "/Users/rkoller/.lima/colima/ha.sock" 
```

the odd part is the output that `ha.sock` is removed since the file wasnt in place as seen in the description. or does that mean that way a regeneration of the missing `ha.sock` file is triggered in lima?

**Comment by rpkoller** [comment]
and the odd part. i've taken another look into the `~/.lima/colima` folder. when i was unable to start colima the files were: 
```
serial.log
lima.yaml
ha.stdout.log
ha.stderr.log
ha.pid
diffdisk
colima.yaml
cidata.iso
basedisk
```
after the `limactl stop -f colima` and the i was able to restart the files are

```
serial.log
qemu.pid
lima.yaml
ha.stdout.log
ha.stderr.log
ha.pid
diffdisk
colima.yaml
cidata.iso
basedisk
```

the only difference it the `qemu.pid`. but the `ha.sock` file isnt there?!

**Comment by abiosoft** [comment]
Thanks for troubleshooting @rpkoller.

Yeah, Colima validates if it's running before attempting to stop and that's why the behaviour is different. It basically calls `limactl stop -f colima` and performs some cleanups.

Now I can see the use-case of not requiring a running status before attempting to stop. Will work on this soon.
