### ISSUE TITLE
Any way to disable colima’s modification of `~/.ssh/config`?

### ISSUE THREAD

**Issue by fooness** [abiosoft/colima#441]
### Description

Is there any way to disable the modification of my `~/.ssh/config` file when running `colima start`?

**Comment by abiosoft** [comment]
Not yet. Will add this soonest.

**Comment by abiosoft** [comment]
@fooness you can try it out in the development version `brew install --HEAD colima`. It will be part of the next release.

```
colima start --ssh-config=false
```

**Comment by fooness** [comment]
@abiosoft Thank you very much helping out here and adding this startup option, that’s amazing. Will give it a try tomorrow, but the changes to the respective files look rather comprehensive; I’m rather optimistic it will work as intended.

Thanks!
