### ISSUE TITLE
`docker compose up -d` -> unknown shorthand flag: 'd' in -d

### ISSUE THREAD

**Issue by Jasperav** [abiosoft/colima#447]
### Description

I want to use Docker compose in Github actions for macos. I want to spin up a docker-compose.yml file. On my own machine, this command works:

`docker compose up -d`

The exact same command fails while I installed Colima:

`unknown shorthand flag: 'd' in -d`

This is the relevant part of the job in Github actions (macos-12):

```
      - name: Build dependencies
        run: |
          cd ./server
          ls
          docker compose up -d
```

This is the output:

```
brew install docker colima
colima start
Run cd ./server
docker-compose.yml
unknown shorthand flag: 'd' in -d
See 'docker --help'.
```

Probably docker compose isn't installed?

### Version

Colima Version: 0.4.6
Lima Version: 0.12.0
Qemu Version: 7.1.0

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

1. I included everything in the description

### Expected behaviour

Docker compose should be working, but it doesn't :(

**Comment by rfay** [comment]
The Docker client (`docker`) and the compose subcommand (for `docker compose` and the `docker-compose` executable are not part of the Colima project. You'll want to take a look at your setup, but this has nothing to do with Colima. 

On github actions you'll likely want to install the compose plugin, see https://docs.docker.com/compose/install/linux/#install-the-plugin-manually

Alternately, you can download the `docker-compose` binary a number of ways and use it. Just make sure you get the 2.x version.

Please close this as it doesn't have to do with Colima.

**Comment by abiosoft** [comment]
It is installable with brew as well. Simply change your installation line to include it.

```
brew install docker docker-compose colima 
```
