### ISSUE TITLE
Missing .kube/config file? Generate one by default or reset?

### ISSUE THREAD

**Issue by icosahedron** [abiosoft/colima#454]
### Description

I don't know if this is the right place to ask this, but could there be a default .kube/config file included or something?

Something happened to my .kube/config after I did a `colima delete` and a bunch of other commands, and I have no idea what this file should look like.

I've uninstalled colima (and lima and kubernetes-cli) thinking maybe it's generated upon install by the bottle (homebrew).

macOS Monterey
M1 Mac

**Comment by abiosoft** [comment]
You don't have to worry about it, a new one will be generated if required (either by Colima or any other Kubernetes setup).

```sh
colima start --kubernetes # generates ~/.kube/config if missing
```

**Comment by icosahedron** [comment]
Thanks.

**Comment by archcst** [comment]
Hi,
I have a cluster running over a year with colima, and today I'm encountering this issue:

```
❯  kgpon middleware
E0320 17:23:01.882503   15022 memcache.go:238] couldn't get current server API group list: the server has asked for the client to provide credentials
```

I guess it might be that the certification has been expired, so I `rm ~/.kube/config` and try to generate a new one as you mentioned:


```
❯  colima start --kubernetes
INFO[0000] starting colima
INFO[0000] runtime: containerd+k3s
INFO[0000] preparing network ...                         context=vm
INFO[0003] starting ...                                  context=vm
INFO[0023] provisioning ...                              context=containerd
INFO[0024] starting ...                                  context=containerd
INFO[0029] provisioning ...                              context=kubernetes
INFO[0030] starting ...                                  context=kubernetes
INFO[0032] done
```

But the config file is not generated, I'm wondering if there's a way that I could generated it manually?
```
❯  kgpon middleware
E0320 17:38:46.613307   17150 memcache.go:238] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp [::1]:8080: connect: connection refused

❯  ll ~/.kube
total 16
drwxr-x---  4 archcst  staff   128B  9 25  2022 cache
-rw-------@ 1 archcst  staff   6.8K  5 24  2023 config-add-aliyun
-rw-r--r--  1 archcst  staff     0B  4 28  2023 empty
```

**Comment by archcst** [comment]
I fond the way to manually export kubeconfig file, for anyone who encounter the same issue here:

```shell
colima ssh
cat /etc/rancher/k3s/k3s.yaml > /Users/archcst/.kube/config
```

Notice that the second line will OVERWRITE `~/.kube/config` file, if the file has other configs, you might want to copy the echo area and paste into your kubeconfig file  manually.
