### ISSUE TITLE
Add support for different kubernetes versions

### ISSUE THREAD

**Issue by tibcoplord** [abiosoft/colima#46]
Currently, kubernetes 1.22 is a little new for me, so I've edited my local colima tree to use v1.21.5+k3s2

It would be nice to be able to specify the kubernetes version on the command line ... will be especially useful for desktop testing applications on different versions.

Cheers.

**Comment by adamalex** [comment]
Good call! The JSON for this is available at https://api.github.com/repos/k3s-io/k3s/tags

**Comment by eacarvalho** [comment]
Hi, I have a similar issue, please is it possible to use previous version of Kubernetes? I've tried to edit `colima.yaml` file but no effect.

I'm running on Mac and installed Colima using Homebrew.

```
colima version
colima version 0.2.2
git commit: b2c7697bee2d73e995f156fe8e9870eb246c07e6

runtime: docker
client: v20.10.12
server: v20.10.7

kubernetes
Client Version: v1.23.1
Server Version: v1.22.2+k3s2
```

**Comment by abiosoft** [comment]
> please is it possible to use previous version of Kubernetes?

@eacarvalho at the moment, no. But it is being planned. 


What version of kubernetes would you like to use?

**Comment by eacarvalho** [comment]
Hi @abiosoft, the version should be lower than `1.22`, preferable `v1.20.x` due some incompatibility regarding the `1.22+` version but definitely lower than `1.22` in order to work for our deployment.

```
Ingress: The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22.
```

```
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
```

Nice that this is being planned, I wish I could use this feature soon. Thanks a lot!

**Comment by abiosoft** [comment]
> Nice that this is being planned, I wish I could use this feature soon. Thanks a lot!

@eacarvalho it is not as complex for me to add, what is more tedious is testing different versions and ensuring they still work as desired. I'll see what I can do to speed it up.

Would you be willing to assist with testing and use the development version? It may take a while before the next release.

**Comment by eacarvalho** [comment]
> Would you be willing to assist with testing and use the development version?

Please let me know in case you produce a development version!

**Comment by spkane** [comment]
I would be happy to help support a bit of testing as well. Making it reasonably easy to install a different version of k3s would be very helpful, especially due to the major changes that are currently in 1.22.

**Comment by spkane** [comment]
For the time being, you can change the k3s version in the current VM with something like this:

* Find the release you want [here](https://github.com/rancher/k3s/releases) (*e.g.* **v1.21.9+k3s1**)

```sh
$ colima ssh
# sudo /usr/local/bin/k3s-uninstall.sh
# sudo apk add curl
# curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.9+k3s1 sh -
# cat /etc/rancher/k3s/k3s.yaml
```

* If you copy the contents of the ` /etc/rancher/k3s/k3s.yaml` file on the VM into a file on your local host called `~/.kube/colima-k3s.yaml` then you should be able to connect to the new k3s release with something like this `kubectl --kubeconfig  ~/.kube/colima-k3s.yaml version`

**Comment by abiosoft** [comment]
> I would be happy to help support a bit of testing as well. Making it reasonably easy to install a different version of k3s would be very helpful, especially due to the major changes that are currently in 1.22.

Alright, thanks. I'll see if I can squeeze this in before the next release.
