### ISSUE TITLE
how to add extra-config

### ISSUE THREAD

**Issue by ljshwyykl** [abiosoft/colima#478]
### Description

i want to add 
```
apiserver.service-node-port-range=1-65535   
```
how?

### Version

Colima Version:
Lima Version:
Qemu Version:

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1.
2.
3.

**Comment by abiosoft** [comment]
Kindly fill the issue template or add more details.

Thanks.

**Comment by shivknight** [comment]
For posterity, you can modify the args colima passes to k3s like so
```
kubernetes:
  k3sArgs:
    - --service-node-port-range="1-65535"
```
See https://docs.k3s.io/cli/server for complete reference of flags that k3s accepts
