### ISSUE TITLE
colima - clean up not working (volume mount)

### ISSUE THREAD

**Issue by heesuk-ahn** [abiosoft/colima#48]
## Problem Share

lima reads volumes as read-only by default.

To convert a volume to write, I should use the `--mount` option.

I applied and executed `colima start --mount {directory_path}:w` to apply the writable option to the volume.

After the write test I did colima stop for clean up

```
$ colima stop
```

and then I restart colima just default mode

```
$ colima start
```

Then, the volumes that did the write test were not mounted properly.

So I tried to connect to colima with ssh.

```
$ colima ssh
```

And I see that the direcotry that I have tested before mount is mounted on colima vm.

```
my@lima-colima:/Users/foo$ ls
apps  kube
```

`app` and `kube` were used to test mount with `--mount app:w kube:w` .

I used `colima delete` and tried `colima start` again, but it did not clean up. 🤔 

How can I clean up the previously mounted settings in lima?

As I think, it doesn't seem to be initialized during clean up after modifying `default.yaml` of lima.

Any good solutions for this?

**Comment by psalaberria002** [comment]
I just hit the same issue. `colima delete` and then starting fresh made it work.

**Comment by abiosoft** [comment]
I am not sure this is still an issue. Kindly update to the Colima v0.3.0 or newer and try again.
