### ISSUE TITLE
SSH Agent socket forwarding

### ISSUE THREAD

**Issue by jsuchenia** [abiosoft/colima#487]
### Description

There is an option (--ssh-agent) to enable socket forwarding to SSH connections. It works when you wish to ssh to a VM (_limactl colima shell_)

Lima supports reverse socket forwarding between host and guest - so it could be nice to forward an agent socket from a host to a guest, then it can be easily mounted inside a docker container.

It's possible to do that (as mentioned in this ticket: https://github.com/lima-vm/lima/issues/834)

**Comment by abiosoft** [comment]
You can do that by following the instructions here https://github.com/abiosoft/colima/issues/127#issuecomment-1014474574.

**Comment by kernel-io** [comment]
how would you do this during a build while using docker? (standard problem where you need resources that are stored in git - and you'd like to use host ssh agent to authenticate from the guest doing the build)
