### ISSUE TITLE
vz-support doesn't seem to support rosetta 2

### ISSUE THREAD

**Issue by kj-creater** [abiosoft/colima#494]
### Description
x86 container on arm linux with docker got `/usr/bin/qemu-x86_64` on m1 mac

### Version

Colima Version: v0.4.6-12-g49d7318
Lima Version: HEAD-45f9128
Qemu Version: 7.1.0
macOS Version: 13.1 22C5050e

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Run x86 alpine image
    ```
    docker pull alpine --platform amd64
    docker run -idt --name=vz-test alpine
    ```
2. Run `ps` command in the container named 'vz-test' and got output
    ```
    docker exec -it vz-test ps -ef
    PID   USER     TIME  COMMAND
        1   root      0:00 {sh} /usr/bin/qemu-x86_64 /bin/sh /bin/sh
       31  root      0:00 ps -ef
    ```

**Comment by abiosoft** [comment]
It should be fixed now, kindly confirm.

```
$ docker run --rm -it --platform=linux/amd64 alpine
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {sh} /mnt/lima-rosetta/rosetta /bin/sh
    8 root      0:00 /bin/ps -ef
/ #
```

**Comment by kj-creater** [comment]
It's working fine now, thank you

**Comment by lloeki** [comment]
@abiosoft b26af71 enables Rosetta via `binfmt_misc`:

https://github.com/abiosoft/colima/commit/b26af718e17fee77006545dfceb7ac86b20ee2ee#diff-bfdb99fc167407787835579f379b52f91bec566d6be855cc51a39fe848d238adR512-R521

... but it seems like `qemu-x86_64` is still lying around:

```
$ ls -1 /proc/sys/fs/binfmt_misc/
qemu-x86_64  register     rosetta      status

$ cat /proc/sys/fs/binfmt_misc/rosetta 
enabled
interpreter /mnt/lima-rosetta/rosetta
flags: OCF
offset 0
magic 7f454c4602010100000000000000000002003e00
mask fffffffffffefe00fffffffffffffffffeffffff

$ cat /proc/sys/fs/binfmt_misc/qemu-x86_64 
enabled
interpreter /usr/bin/qemu-x86_64
flags: POCF
offset 0
magic 7f454c4602010100000000000000000002003e00
mask fffffffffffefe00fffffffffffffffffeffffff
```

Just to be sure which one gets picked up, I manually removed `qemu-x86_64`:

```
echo -1 > /proc/sys/fs/binfmt_misc/qemu-x86_64
```

Alternatively it could be disabled instead, so as to be easily re-enablable if need be:

```
echo 0 > /proc/sys/fs/binfmt_misc/qemu-x86_64
```

Probabaly the change in b26af71 could be amended somehow to do that, and/or `qemu-x86_64` default to be disabled when Rosetta is known to be available. WDYT?

**Comment by abiosoft** [comment]
@lloeki thanks for pointing that out. It should be disabled now https://github.com/abiosoft/colima/commit/29f7ef0ac39e3c993760640d5c262ae6db0a837b.
