### ISSUE TITLE
Can't start with --network-address because tmp file does not match regex

### ISSUE THREAD

**Issue by skagedal** [abiosoft/colima#495]
### Description

Hi! When I run `colima start --network-address`, I get the following:

```
❯ colima start —-network-address
INFO[0000] starting colima [profile=—-network-address]
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
INFO[0001] creating and starting ...                     context=vm
> filename "/var/folders/gy/s09fnwhn6qd2yhk6mck7c1r40000gn/T/colima-—-network-address.yaml" is invalid: identifier "colima-—-network-address" must match ^[A-Za-z0-9]+(?:[._-](?:[A-Za-z0-9]+))*$: invalid argument
FATA[0001] error starting vm: error at 'creating and starting': exit status 1
```

I found a few other issues relating to --network-address but as far as I could see, they were other issues. I got this problem when running on `colima 0.4.6` and then tried with HEAD colima, but same results.

### Version

Colima Version: HEAD-1c742bc
Lima Version: limactl version 0.13.0
Qemu Version: qemu-img version 7.1.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Install colima
2. Run `colima start --network-address`

### Expected behaviour

Colima starts and assigns a reachable IP address to the VM.

**Comment by skagedal** [comment]
Ohhh wait, is this just a bit of confused command line argument parsing? It seems to work with `colima start default --network-address` :D

**Comment by abiosoft** [comment]
This is strange, `--network-address` is a flag and should be picked up as such. The profile name defaults to `default` if missing. 

Any idea if `--network-address=true` behaves same way?

**Comment by abiosoft** [comment]
I am unable to reproduce this, are you using any special characters or your shell is manipulating the hyphen?

**Comment by skagedal** [comment]
Wow. Somehow* I managed to get an em-dash instead of one of the hyphens. Can even see it in my copy-paste from the terminal above: `colima start —-network-address`. So, completely a user error. Sorry! :) 

[* I know why, it's because I copied it from this [comment](https://github.com/testcontainers/testcontainers-java/issues/5034#issuecomment-1319812252))
