### ISSUE TITLE
sshfs is now unmaintained

### ISSUE THREAD

**Issue by ohookins** [abiosoft/colima#497]
### Description

As per https://github.com/libfuse/sshfs the project is now unmaintained, and so will not receive any updates or patches (including for security issues). Is there going to be a plan for replacing/removing this component from Colima?

### Version

Colima Version: 0.4.6
Lima Version:
Qemu Version:

### Operating System

- [X] macOS Intel
- [ ] macOS M1
- [ ] Linux

### Reproduction Steps

1.
2.
3.

**Comment by ohookins** [comment]
https://github.com/neunenak/sshfs seems like it could be a new successor.

**Comment by abiosoft** [comment]
The next release `v0.5.0` would be moving over to 9p mounts as the default, with the option of virtiofs (and Virtualisation.Framework) for macOS 13 and above.

**Comment by rfay** [comment]
I'm pretty worried about the performance consequences of 9p.. it could be a major shock to people. Discussion in https://cloud-native.slack.com/archives/C043N6ZFV9S/p1665436861986039?thread_ts=1665063734.137219&cid=C043N6ZFV9S - I know there's hope for faster 9p, but 10x slower than sshfs is a lot.

> Performance testing, 9p vs sshfs mount type,  here’s what I did, happy to put it in an issue:
Base drupal 9 demo_umami install using DDEV + colima, considering only the files that are typically bind-mounted (so via sshfs and 9p) in web/sites/default/files.
Testing inside container (ddev ssh, same as docker exec -it <container>)
Both colima profiles had 4GB memory. There are 2694 files, a mixture of jpg, css, etc, a total of only 31MB.
time find . -type f -exec cp {} /dev/null \;
With Colima 9p profile: 60-67s.
With Colima sshfs profile: 7s.
That’s nearly a 10x difference, which could be a big shock to people.
You can easily recreate this with ddev and colima, brew install colima drud/ddev/ddev and use the Drupal9 quickstart in https://ddev.readthedocs.io/en/latest/users/quickstart/#drupal

**Comment by rfay** [comment]
I've already hijacked this thread too much, but also discussed in slack virtiofs on Linux as used by docker desktop for Linux is completely unreliable and makes that pretty much a disaster to this point. OTOH virtiofs on docker desktop for mac is finally usable in latest release, at least with the trivial test I tried.

**Comment by AkihiroSuda** [comment]
> I'm pretty worried about the performance consequences of 9p

The performance was significantly improved in QEMU 7.2.
Seems even faster than sshfs, although still slower than virtiofs (Virtualization.framework).

**Comment by rfay** [comment]
But QEMU 7.2 hasn't made it into homebrew yet, as you know. Is there an easy way to test with 7.2?

**Comment by AkihiroSuda** [comment]
> But QEMU 7.2 hasn't made it into homebrew yet, as you know. Is there an easy way to test with 7.2?

`brew install --HEAD qemu`

**Comment by rfay** [comment]
Nice, massive progress in general. 

Colima HEAD+QEMU HEAD:
`ddev exec 'cd web/sites/default/files && time find . -type f -exec cp {} /dev/null \;'` (Similar to previous test mentioned in slack)

9p: 3.6s
sshfs: 2.0s

Close enough not to worry now. But even sshfs seems 2x faster than before, although I didn't go back and test previous versions right now.

`ddev composer install` of a Drupal site is quite a lot slower with 9p than with mutagen (native linux in container), but that's thousands of files.

**Comment by fskaeh** [comment]
> The next release `v0.5.0` would be moving over to 9p mounts as the default, with the option of virtiofs (and Virtualisation.Framework) for macOS 13 and above.

Great to know! Is there any ETA for that release?

**Comment by abiosoft** [comment]
> > The next release `v0.5.0` would be moving over to 9p mounts as the default, with the option of virtiofs (and Virtualisation.Framework) for macOS 13 and above.
> 
> Great to know! Is there any ETA for that release?

You can expect it to follow Lima [v0.14.0](https://github.com/lima-vm/lima/releases/tag/v0.14.0-beta.1) release.

**Comment by AkihiroSuda** [comment]
> > > The next release `v0.5.0` would be moving over to 9p mounts as the default, with the option of virtiofs (and Virtualisation.Framework) for macOS 13 and above.
> > 
> > 
> > Great to know! Is there any ETA for that release?
> 
> You can expect it to follow Lima [v0.14.0](https://github.com/lima-vm/lima/releases/tag/v0.14.0-beta.1) release.

FYI I think I can release Lima v0.14.0 next week. By the end of the year in the worst case.

**Comment by fskaeh** [comment]
> > > > The next release `v0.5.0` would be moving over to 9p mounts as the default, with the option of virtiofs (and Virtualisation.Framework) for macOS 13 and above.
> > > 
> > > 
> > > Great to know! Is there any ETA for that release?
> > 
> > 
> > You can expect it to follow Lima [v0.14.0](https://github.com/lima-vm/lima/releases/tag/v0.14.0-beta.1) release.
> 
> FYI I think I can release Lima v0.14.0 next week. By the end of the year in the worst case.

https://github.com/lima-vm/lima/releases/tag/v0.14.0 :eyes: :eyes: :eyes: 
I'm very ready to leave Docker Desktop behind.

**Comment by abiosoft** [comment]
@fskaeh it is now available in head. Waiting for some user feedback before pushing a release.

```sh
# ensure Lima is v0.14.0
brew install --head colima
```

**Comment by rfay** [comment]
I don't know that it's possible, but I think it would improve stability to pin colima to a particular version of lima, and to incorporate lima into colima instead of using brew to do the linkage.

**Comment by AkihiroSuda** [comment]
> https://github.com/neunenak/sshfs seems like it could be a new successor.

https://github.com/deadbeefsociety/sshfs seems active too

**Comment by h4sh5** [comment]
SSHFS is no longer orphaned https://github.com/libfuse/sshfs/

**Comment by ohookins** [comment]
Will close this issue in light of the previous comment. Any change to different file sharing mechanisms I'd consider a topic for another ticket.
