### ISSUE TITLE
kubernetes port forward doesn't work out-of-the-box

### ISSUE THREAD

**Issue by giordyb** [abiosoft/colima#5]
Hi,

when running colima with kubernetes, the kubectl port-forward command doesn't work and throws the following error: 
`unable to do port forwarding: socat not found`

I was able to fix the issue by running the following commands:

```
colima ssh
sudo apt-get install socat
```

thank you for releasing this project, it has successfully replaced docker-desktop in my workflow.

**Comment by giordyb** [comment]
see PR #6

**Comment by abiosoft** [comment]
Thanks

**Comment by abiosoft** [comment]
v0.1.5 released for this
