### ISSUE TITLE
Disable sshfs cache option is missing

### ISSUE THREAD

**Issue by viwal** [abiosoft/colima#514]
### Description

I am using colima/docker as my dev environment where I run my API as http-server (uvicorn). 
Anytime I change code on host it takes about 10 seconds until sever (inside the container) gets reloaded. 
I did some testing and foud out that the delay is caused by sshfs cache. 

In lima I can start new vm with configuration below wich helped:
```
mounts:
- location: "~"
  writable: false
  sshfs:
    cache: false    # this option helps with delay
```

I also tested experimental config:
```
vmType: "vz"
mountType: "virtiofs"
```
which works also perfectly.

What I am missing in Colima is to be able to define lima.yaml (or at least some options).
I tried to modify colima config by running `colima start --edit` but `cache` option is ignored/removed once lima vm is created (at least I dont see it in `~/.lima/colima/lima.yaml`)

Is there anything I am missing, because I expect many people use docker for realtime developement and I am surprised there is not opened issue already.

**Comment by abiosoft** [comment]
Next time, kindly fill the issue template as it helps to provide context of your environment.

> I also tested experimental config:
> 
> ```
> vmType: "vz"
> mountType: "virtiofs"
> ```
> 
> which works also perfectly.

If you update to v0.5.0, it defaults to using vz and virtiofs (if you are on macOS 13).

> What I am missing in Colima is to be able to define lima.yaml (or at least some options). I tried to modify colima config by running `colima start --edit` but `cache` option is ignored/removed once lima vm is created (at least I dont see it in `~/.lima/colima/lima.yaml`)

You cannot modify the config directly as it gets generated (and replaced) on startup. What you can do instead is to create an override file for Lima `~/.lima/_config/override.yaml`. However, I would recommend against it except you are an advanced user.

There is gradual migration away from sshfs with the preferred options being virtiofs (for vz) and 9p (for qemu), they are both more reliable with file consistency than sshfs.

**Comment by viwal** [comment]
Well, I am sorry about the template I missed that (actually I opened a feature request, where is not any template set, it's set for Issue report as I see now).

Also I missed the `0.5.0` version was realeased. 

Tested on my macOs 13 (intel) and it works perfectly.

Thanks.
