### ISSUE TITLE
Cannot See Network Shares in Colima VM SSH

### ISSUE THREAD

**Issue by cliss** [abiosoft/colima#518]
### Description

I can't seem to get Colima's VM to be able to read a network share on the host. I can get it to read and write files on the local filesystem, but nothing on a network share that the host has mounted via SMB.

### Version

Colima Version: 
```
colima version 0.5.0
git commit: 5a94ab4f098ec0fe94e6d0df8b411fb149fe26fe

runtime: docker
arch: aarch64
client: v20.10.21
server: v20.10.20
```
Lima Version: `0.14.1`
Qemu Version: `7.2.0`

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. Mount a SMB file share using macOS; in my case, the share is `Archive` and as such is mounted on the host as `/Volumes/Archive`
2. Start Colima using `colima start --mount /Volumes/Archive:w`. (I have also tried adding `--mount-type 9p`)
3. `colima ssh`
4. Attempt to `ls /Volumes/Archive`

Actual:
✅ `/Volumes/Archive` exists
❌  There are no files in `/Volumes/Archive`

### Expected behaviour

Expected:
- `/Volumes/Archive` exists
-  There are files in `/Volumes/Archive`

Actual:
✅ `/Volumes/Archive` exists
❌  There are no files in `/Volumes/Archive`

### Additional context

```
casey@miniserve ~/Colima> ls -l --color .
total 8
drwxr-xr-x  5 casey  staff   160 Dec 18 07:46 config/
drwxr-xr-x  2 casey  staff    64 Dec 17 21:00 downloads/
-rw-r--r--  1 casey  staff  2230 Dec 18 07:45 servarr.yml
lrwxr-xr-x  1 casey  staff    16 Dec 17 20:40 synology@ -> /Volumes/Archive
casey@miniserve ~/Colima> colima start --mount ~/Colima:w --mount /Volumes/Archive:w
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] creating and starting ...                     context=vm
INFO[0013] provisioning ...                              context=docker
INFO[0014] starting ...                                  context=docker
INFO[0019] done                                         
casey@miniserve ~/Colima> colima ssh
colima:/Users/casey/Colima$ ls
config       downloads    servarr.yml  synology
colima:/Users/casey/Colima$ ls -l
total 4
drwxr-xr-x    5 casey    casey          160 Dec 18 12:46 config
drwxr-xr-x    2 casey    casey           64 Dec 18 02:00 downloads
-rw-r--r--    1 casey    casey         2230 Dec 18 12:45 servarr.yml
lrwxr-xr-x    1 casey    casey           16 Dec 18 01:40 synology -> /Volumes/Archive
colima:/Users/casey/Colima$ ls /Volumes/Archive
colima:/Users/casey/Colima$ 
```

**Comment by davidolrik** [comment]
I believe that this issue is the same as #524

**Comment by abiosoft** [comment]
> I believe that this issue is the same as #515

Likely. Can @cliss confirm if upgrading to v0.5.1 resolves it for him?

**Comment by cliss** [comment]
Following [these instructions](https://github.com/abiosoft/colima/issues/524#issuecomment-1361301625) seems to have worked at a glance. I'm running out the door now, and can dig more later, but initial results seem like I'm good:

<img width="374" alt="Screenshot_2022-12-21_at_10_23_55_AM" src="https://user-images.githubusercontent.com/282460/208940788-9fdaddaa-dd89-4454-85b7-8d9801113802.png">

Lima is still `0.14.1` but was built from source.

**Comment by cliss** [comment]
I uninstalled both `lima` and `colima`, and did a standard `brew install` of `colima`. That **does** seem to do the trick on my M1 Mac mini:

```
casey@miniserve ~> colima start --mount /Users/casey:w --mount /Volumes/Archive:w
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
INFO[0021] provisioning ...                              context=docker
INFO[0021] starting ...                                  context=docker
INFO[0026] done     
casey@miniserve ~> colima ssh
colima:/Users/casey$ ls
Applications    Desktop         Documents       Drive           Movies          Pictures        backup-test.sh  done
Colima          Docker          Downloads       Library         Music           Public          backup.sh       done~
colima:/Users/casey$ cd Colima
colima:/Users/casey/Colima$ ls
config       downloads    servarr.yml  synology
colima:/Users/casey/Colima$ cd synology
colima:/Volumes/Archive$ ls
/* Removing for privacy but suffice it to say, stuff was here. ;) */
```

However, a new question:

**Is it possible to mount the host's home folder (in my case, `/Users/casey/` as `~` in the Colima VM?**

I'm trying to set up a Docker compose file that refers to everything as relative paths, and that doesn't seem to be possible with the way Colima is mounting my home folder. Instead I'll need to use the absolute path. Or maybe I'm holding it wrong, so to speak?

If you'd like me to start a new issue about this, I'm happy to.

**Comment by abiosoft** [comment]
@cliss the interaction with docker (and docker compose) is via the docker client on your host machine. Therefore `~` should point to your home directory as expected.

Except you're working inside the Colima VM instead.

Can you share some more details about your docker compose file?
