### ISSUE TITLE
Cannot access internet after Colima v0.5.0 upgrade

### ISSUE THREAD

**Issue by dmzobel** [abiosoft/colima#523]
### Description

After upgrading from Colima v0.4.6 to v0.5.0, the DNS resolver in Colima/Docker does not work. I did not encounter this issue when using v0.4.6.

### Version

Colima Version:
```
colima version 0.5.0
git commit: 5a94ab4f098ec0fe94e6d0df8b411fb149fe26fe

runtime: docker
arch: aarch64
client: v20.10.21
server: v20.10.18
```

Lima Version: `0.14.1`
Qemu Version: `7.2.0`

### Operating System

- [X] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. `brew upgrade colima` -> Upgraded from 0.4.6 to 0.5.0 using Homebrew
2. `colima start`
3. `docker pull alpine` -> Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.107.1:53: read udp 192.168.5.15:52036->192.168.107.1:53: i/o timeout
4. `colima ssh`
5. `ping google.com` -> bad address 'google.com'
6. `ping 8.8.8.8` -> Normal packet response: `64 bytes from 8.8.8.8: seq=0 ttl=42 time=2500402.173 ms`

### Expected behaviour

Requests to the Docker registry and other internet addresses would succeed.

### Additional context

At least two other engineers at my company are experiencing this issue, which is how I know that it affects both Apple Intel and M1 processors. 

I've read through some other issues and not identified a fix yet. Issue https://github.com/abiosoft/colima/issues/456 appears similar, but I did not experience problems due to a MacOS upgrade. I was running MacOS 13.0.1 using both Colima v0.4.6 and Colima v0.5.0. Also passing the `--dns` flag during `colima start` does not fix the issue. 

Issue https://github.com/abiosoft/colima/issues/344 also sounded very similar; however, I did not use Nix to install colima (I use homebrew), and again, `colima start --dns 1.1.1.1` did not fix the issue.

I've seen mention of VPNs causing this issue (or similar), but I'm experiencing this issue whether or not I'm behind a VPN.

**Comment by prookie** [comment]
Thank you so much for this issue.
I am looking for solution for this problem which appeared out of nowhere for me two days ago. I just made the connection through googling that when I installed a package via homebrew a few days ago it caused updates to other installed packages – including colima as I now realized.
I am using an M1 as well (macOS 13.0.1).

**Comment by rfay** [comment]
It's critical that you mention whether you're on Ventura or Monterrey - could you provide that info?

I'm not having any troubles like this. One thing you might try is to create a new profile and see if it exhibits these problems. Then you'll know if it has anything to do with your existing profile.

```
colima start vz --cpu 4 --memory 6 --vm-type=vz --dns=1.1.1.1
colima start qemu--cpu 4 --memory 6 --vm-type=qemu --dns=1.1.1.1 
```

That would give you two brand new fresh profiles using vz and qemu. You can `colima ssh -p vz` and `colima ssh -p qemu` and see what your results are in there.

**Comment by fskaeh** [comment]
I'm encountering this issue as well with Colima 0.5.0 on MacOS 13.1. It's sporadic and seems to affect only some specific domains. For example, Watchtower systematically fails with the same error while trying to pull images from docker hub to update my containers, but that's the only issue I've noted so far. I have a bunch of running containers that pull data from various internet services all the time and are working just fine. I also noticed under heavy netword load, Colima sometimes crashes (`colima status` will just hang forever).

Just for reference, here's my command to start Colima:

``` zsh
$HOMEBREW_BIN_PATH/colima start --activate \
  --arch aarch64 \
  --cpu 8 \
  --disk 494 \
  --dns 1.1.1.1 \
  --dns 1.0.0.1 \
  --memory 16 \
  --mount $DOWNLOADS_PATH:w \
  --mount $SERVER_PATH:w \
  --mount $NAS_PATH:w \
  --mount-type virtiofs \
  --runtime docker \
  --ssh-agent \
  --vm-type vz```

**Comment by TheNaderio** [comment]
MacOS 12.6 (Monterey) on MacBook Pro M1Pro with colima 0.5.0 - same problem.
I cannot curl from my containers to the internet.

passing `--dns 1.1.1.1.` doesnt helped

The mentioned commands from @rfay leads to an error: `Error: unknown flag: --vm-type`, so I tried it without this option `colima start vz --cpu 4 --memory 6 --dns=1.1.1.1`, what started a new profile. After this, running my containers and everything is back to normal.

I ran `colima delete` followed by my normal start-command `colima start --cpu 4 --memory 16`. After this, my "normal" profile is working again.

Thank you for pointing me in the right direction ;)

**Comment by rfay** [comment]
You didn't have `--vm-type` because it's not available for Monterrey.

**Comment by kamil-mrzyglod** [comment]
I can also confirm (MacOS 12.6), M1 Pro - after upgrading to Colima 0.5.0 I couldn't pull any image with the following message:
```
Error response from daemon: Get "https://mcr.microsoft.com/v2/": dial tcp: lookup mcr.microsoft.com on 192.168.5.3:53: read udp 192.168.5.15:34908->192.168.5.3:53: i/o timeout
```

After deleting the profile and recreating it with `colima start vz --cpu 4 --memory 6 --dns=1.1.1.1` it started to work again.

**Comment by dmzobel** [comment]
Yep, deleting and recreating the profile seems to have fixed the issue for me as well! 

I first followed @rfay's suggestion and created two new profiles, `vz` and `qemu`. Both of those had no issues accessing the internet. Then I deleted the `default` profile and created a new default, and that one is also working like normal. I'll also note that I did not need to provide `--dns` or any other options to the start command in order for this to work.

Thanks everyone for the help! I'll close this issue as it appears we have a fix.

**Comment by rfay** [comment]
The one thing to remember is that when you delete a profile you lose all volumes that existed there. (You also lose images and containers, but those are not a problem to replace). 

@abiosoft Any idea why people would be having this problem that requires recreating the profile? I don't think we anticipated that. In recent versions of Colima that hasn't been necessary.

**Comment by TheNaderio** [comment]
> The one thing to remember is that when you delete a profile you lose all volumes that existed there
I was about to write the same - I use mainly ddev with a hook that backs up my databases on exit, so no problem for me:
I edit my upper post to prevent user from losing stuff when they type in every command without thinking about It ;)

**Comment by prookie** [comment]
Is there any easy way to copy all databases from the previously used profile to the newly created one? I have quote a few projects to manually migrate otherwise.

**Comment by rfay** [comment]
With `ddev` you would `ddev snapshot --all` and then `ddev snapshot restore` on the new instance. There are other ways to export the contents of a volume that you can find with an internet search, depends on your needs.

**Comment by prookie** [comment]
I tried switching to a new VZ profile but could not restore DDEV snapshots there and had further problems with the serving of the website. For that reason I just switched back to my default profile from the past (before Colima was upgraded to 0.5.0 and which did not have working DNS resolution with 0.5.0) to do some further troubleshooting in hope of getting it working again (like downgrading to 0.4.6) and to my surprise – it immediately just worked again. No clue how or why it fixed itself.

**Comment by rfay** [comment]
@prookie I haven't been able to recreate your problem with restoring snapshots on a vz profile in colima. If you can recreate this could you please give step-by-step instructions? I don't know why this would be a problem. Since it's off-topic for this issue you might want to take it up in a DDEV issue or in DDEV Discord, https://discord.gg/hCZFfAMc5k

**Comment by prookie** [comment]
I don't think the described DNS problem has anything to do with DDEV, I just wanted to tell everyone about that weird self-healing after creating a new profile and later switching back to the original one that has been broken through the Colima 0.5.0 update but somehow is not anymore. The snapshot restore issue (in a new VZ type profile?) is of course an issue for the DDEV team. 🙂

**Comment by alexpapworth** [comment]
Thanks for all the answers. This approach worked for me after upgrading to Colima 0.5.2.

```bash
colima delete
colima start
```

**Comment by milosmns** [comment]
Maybe it would be nice to offer `colima delete && colima start` as a fix from the CLI output when such errors happen. This workaround fixed it for me too.

**Comment by rchilly** [comment]
Same problem as everyone above.

At the time, my default configuration file (`~/.colima/default/colima.yaml`) had an empty array for `dns`.

I added `1.1.1.1`, restarted `colima`, and voila.
