### ISSUE TITLE
Fast dns lookups freeze the docker vm

### ISSUE THREAD

**Issue by artygus** [abiosoft/colima#529]
### Description

Fast dns lookups makes the docker vm unresponsive with slirp network driver. For the context, I have a setup where dynamic resources gets created in envoy proxy dynamically, every upstream domain name gets resolved after being added to config, it happens in big batches and  hence generates > 50 dns lookups. This didn't happen with gvproxy driver.

Probably, this bug has to be reported to lima-vm, but I wonder if you could keep gvproxy for a while, it was removed just recently in https://github.com/abiosoft/colima/commit/40bf7bf79d4b1cdad801af37ca4b71e325d32c29.

Sample results from `slirp` dns stress (both colima v0.5.0 and v0.4.6)

```
Requests sent:      5r/s    Replies received:      5r/s (mean=190ms / max=292ms)
Requests sent:    245r/s    Replies received:    245r/s (mean=250ms / max=362ms)
Requests sent:    195r/s    Replies received:    195r/s (mean=326ms / max=374ms)
Requests sent:     70r/s    Replies received:     70r/s (mean=319ms / max=358ms)
# vm hangs
```

Sample results from `gvproxy` dns stress (colima 0.4.6)

```
Requests sent:   6764r/s    Replies received:   6764r/s (mean=7ms / max=48ms)
Requests sent:   6443r/s    Replies received:   6443r/s (mean=8ms / max=53ms)
Requests sent:   5505r/s    Replies received:   5505r/s (mean=9ms / max=66ms)
Requests sent:   5844r/s    Replies received:   5844r/s (mean=9ms / max=61ms)
Requests sent:   5896r/s    Replies received:   5896r/s (mean=8ms / max=64ms)
Requests sent:   5586r/s    Replies received:   5586r/s (mean=9ms / max=64ms)
Requests sent:   5944r/s    Replies received:   5944r/s (mean=9ms / max=55ms)
Requests sent:   5700r/s    Replies received:   5700r/s (mean=9ms / max=61ms)
Requests sent:   5682r/s    Replies received:   5682r/s (mean=9ms / max=58ms)
 # all good
```

### Version

Colima Version: 0.5.0
Lima Version: 0.14.1
Qemu Version: 7.2.0

### Operating System

- [ ] macOS Intel
- [X] macOS M1
- [ ] Linux

### Reproduction Steps

1. docker run --rm -it golang:alpine
2. go install github.com/MickaelBergem/dnsstresss@latest
3. dnsstresss -r 192.168.5.3:53 google.com 

### Expected behaviour

VM doesn't become unresponsive

**Comment by abiosoft** [comment]
It was removed because Lima was utilising gvproxy as well but only for the macOS virtualization and not QEMU.

Also considering that native virtualization may eventually be the preferred option on macOS, the overhead of utilising gvproxy does not seem necessary. Coupled with some issues like https://github.com/abiosoft/colima/issues/466.

Gvproxy can be bought back quite easily.

**Comment by artygus** [comment]
@abiosoft thanks for the swift response! Yeah, I'm looking forward to native osx virtualization. Not everyone on my team is on Ventura unfortunately, I guess it would take some time for people to get there. In the mean time it would be nice to have gvproxy as a fallback. I'd be happy to craft a PR to bring it back to save you some time
