### ISSUE TITLE
Feature Request: support configurable apt source in docker installation

### ISSUE THREAD

**Issue by ciiiii** [abiosoft/colima#53]
Official apt source is slow in some network environments, maybe configurable apt source is better.

**Comment by abiosoft** [comment]
This will be addressed in version 0.3.0 and the release is imminent.
The distro is being switched to Alpine with dependencies pre-installed, so internet connection would no longer be required to start up Colima.

**Comment by ciiiii** [comment]
@abiosoft This sounds great, can I do some work for this?

**Comment by abiosoft** [comment]
> @abiosoft This sounds great, can I do some work for this?

Thanks for offering to help. However, I am close to being done already.

Are you skilled in Go? How best do you think you can contribute?

**Comment by ciiiii** [comment]
I use Go and do work on K8S things, so coding about docker and K8S is good for me.
