### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by chenrui333** [abiosoft/colima#534]
It has been a year with the [early development project status note](https://github.com/abiosoft/colima/pull/49), maybe consider removing it. Thanks!

https://github.com/abiosoft/colima/blob/fc2ffc3175aa073ba724eb491ec851a154b894da/README.md?plain=1#L135-L138

**Comment by abiosoft** [comment]
Yeah, I think it is worth removing now.

**Comment by chenrui333** [comment]
yeah, we have tons of serious usage on colima, and this got just raised internally. :)
