### ISSUE TITLE
Consider going back to sshfs as default mount type, at least for QEMU; 9p performance is awful

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#544]
### Description

We had hopes for 9p performance, and still should, but right now it's terrible. 

I just did a set of performance comparisons of different Colima and Docker Desktop characteristics in https://ddev.com/ddev-local/ddev-docker-desktop-and-colima-benchmarking-updated-dec-2022/ and found that the QEMU/9p setup wasn't even worth waiting for; it's as bad as Docker Desktop alone used to be. 

I think we should consider sshfs as the default still until things shake out. However, my experience with Virtiofs was not bad at all, except for the serious performance problem described in https://github.com/drud/ddev/issues/4466#issuecomment-1361261185 and https://github.com/Code-Hex/vz/pull/117, which should make it into new versions of Lima in the near future.

**Comment by abiosoft** [comment]
This is already in progress and a release is going out soon.

**Comment by balajiv113** [comment]
@abiosoft 
Done the changes in lima as well
https://github.com/lima-vm/lima/pull/1268

Note: This should provide improved performance (equal to/slightly better than QEMU) but not as performant as the above workaround.

**Comment by AkihiroSuda** [comment]
> We had hopes for 9p performance, and still should, but right now it's terrible.

Did you try QEMU 7.2?

**Comment by rfay** [comment]
QEMU 7.2.0 is all I've tried.
