### ISSUE TITLE
SSSE3 instruction set not supported with x86_64 VM

### ISSUE THREAD

**Issue by danielleontiev** [abiosoft/colima#566]
### Description

I use MacOS Ventura on M1 CPU and try to create x86_64 VM to run x86_64 image:

```sh
colima start --arch x86_64
docker run --rm yandex/clickhouse-server:21.7.11.3
```

Output:

```
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
Instruction check fail. The CPU does not support SSSE3 instruction set.
```

Just for comparison, starting colima with aarch64 arch and running the same image results in expected "wrong cpu architecture" error:

```sh
colima start
docker run --rm yandex/clickhouse-server:21.7.11.3
```

Output:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x4cb21f, 0x9)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.newosproc(0xc420024000, 0xc420033fc0)
        /usr/local/go/src/runtime/os_linux.go:160 +0x194
runtime.newm(0x4d6db8, 0x0)
        /usr/local/go/src/runtime/proc.go:1572 +0x132
runtime.main.func1()
        /usr/local/go/src/runtime/proc.go:126 +0x36
runtime.systemstack(0x53ae00)
        /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc42001e768 sp=0xc42001e760
runtime.main()
        /usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc42001e7c0 sp=0xc42001e768
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42001e7c8 sp=0xc42001e7c0
Configuration file '/etc/clickhouse-server/config.xml' isn't readable by user with id '101'
```

### Version

Colima Version: 

colima version 0.5.2
git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72

runtime: docker
arch: aarch64
client: v20.10.22
server: v20.10.20

Lima Version:

limactl version 0.14.2

Qemu Version:

qemu-img version 7.2.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/daniilleontiev/.colima/default/docker.sock

### Reproduction Steps

1. `colima start --arch x86_64`
2. `docker run --rm yandex/clickhouse-server:21.7.11.3`

### Expected behaviour

Docker image starts successfuly

**Comment by SuperFola** [comment]
It looks like a qemu problem to me (or maybe lima if it allows passing custom flags to qemu), not a colima one. You need to pass some arguments to qemu to enable ssse3, something like `-cpu qemu64,+ssse3,`

**Comment by abiosoft** [comment]
AFAIK, those instruction sets are not supported for emulated architecture. If you were to be on Intel Mac, it would be available.

**Comment by danielleontiev** [comment]
Ok, thank you for pointing out!

So, if I understand correctly, my only option is to use container runtime that does not rely on QEMU under the hood?

**Comment by abiosoft** [comment]
> So, if I understand correctly, my only option is to use container runtime that does not rely on QEMU under the hood?

Nope. Rather what I meant is that to take full capabilities of the CPU, you must run containers with same architecture as the host CPU.

i.e. `linux/aarch64` containers on m1 Mac and `linux/amd64` containers on Intel Mac.
