### ISSUE TITLE
Support host.docker.internal for the VM to talk to the host OS

### ISSUE THREAD

**Issue by zen0wu** [abiosoft/colima#57]
First of all, thanks for making this, it's super great!

I wonder if it's possible to add something similar to `host.docker.internal` what Docker Desktop does,
so that containers can easily talk to the ports on the host OS.

**Comment by jandubois** [comment]
Lima defines `host.lima.internal` inside the guest; I think it should be visible to containers as well.

**Comment by zen0wu** [comment]
Just tested it, and it works, thanks a lot @jandubois! Closing.

**Comment by cpopp** [comment]
Maybe I'm missing something but host.lima.internal doesn't seem to resolve from inside a container with colima. Any insight? Thanks!

```
$ docker run -it --rm bash:4.4 ping host.lima.internal
ping: bad address 'host.lima.internal'

$ colima version
colima version HEAD-784cec0
git commit: 784cec04dc126b02f5d2697a864282d5d2301afe

runtime: docker
arch: x86_64
client: v20.10.6
server: v20.10.11
```

I am able to ping `host.lima.internal` after executing `colima ssh`, but that's from within the VM and not from a container.

**Comment by jandubois** [comment]
I've been meaning to fix this before, but somehow forgot about it. I just filed https://github.com/lima-vm/lima/issues/622 to implement it in lima itself.

**Comment by cpopp** [comment]
Should this be available with the latest HEAD? `host.lima.internal` works, but `host.docker.internal` does not and https://github.com/abiosoft/colima/issues/199#issuecomment-1048778994 seemed to indicate it would be.

```
$ colima version
colima version HEAD-5085352
git commit: 5085352f7fdb5f63d6826e76707dc89e117da2c2

$ docker run -it --rm bash:4.4 ping host.docker.internal
ping: bad address 'host.docker.internal'

$ docker run -it --rm bash:4.4 ping host.lima.internal
PING host.lima.internal (192.168.5.2): 56 data bytes
64 bytes from 192.168.5.2: seq=0 ttl=254 time=0.205 ms
...
```

Based on the discussion in the following thread it seems like colima will need a change for `host.docker.internal` to be supported: https://github.com/lima-vm/lima/issues/491#issuecomment-1047396173

**Comment by abiosoft** [comment]
> Should this be available with the latest HEAD? `host.lima.internal` works, but `host.docker.internal` does not and https://github.com/abiosoft/colima/issues/199#issuecomment-1048778994 seemed to indicate it would be.

Did you override the DNS settings?

**Comment by cpopp** [comment]
@abiosoft I changed nothing other than starting the colima VM from HEAD and trying the containers. I expected based on your comment in https://github.com/abiosoft/colima/issues/199#issuecomment-1048778994 that `host.docker.internal` would just work by default, since if the DNS settings have to be overrided then `docker.for.mac.host.internal` seems like it could be just as easily supported.

If the outcome is `host.docker.internal` isn't supported by default, that's good to know. (We have a mixture of less experienced users that use a mix of Docker Desktop and colima and we try to make sure some getting started examples for containers work without modification. So we'd either have to provide two examples, or add the extra step to override DNS when using colima).

**Comment by abiosoft** [comment]
@cpopp is Lima up to date as well? It requires Lima v0.8.3 and above.

```
limactl --version
```

**Comment by cpopp** [comment]
Yeah, I was/am running v0.8.3
```
$ limactl --version
limactl version 0.8.3
```

Just to make sure I went ahead and destroyed my VM (`colima delete`) and created it from scratch and it works now. So, maybe something with the way I upgraded colima to test it (`brew uninstall colima` followed by `brew install --HEAD colima`) left around enough of the old lima VM for the old DNS behavior to be in place.

Seems to work now, so thanks for the assistance!

```
$ docker run -it --rm bash:4.4 ping host.docker.internal
PING host.docker.internal (192.168.5.2): 56 data bytes
64 bytes from 192.168.5.2: seq=0 ttl=254 time=0.339 ms
...

$ docker run -it --rm bash:4.4 ping host.lima.internal
PING host.lima.internal (192.168.5.2): 56 data bytes
64 bytes from 192.168.5.2: seq=0 ttl=254 time=0.204 ms
...
```
