### ISSUE TITLE
"limactl list" JSON format changed incompatibly in lima HEAD

### ISSUE THREAD

**Issue by aaronlehmann** [abiosoft/colima#572]
### Description

This lima-vm PR changes the "limactl list --json" output to a JSON array instead of a JSON object: https://github.com/lima-vm/lima/pull/1249

Because of this change, trying to run colima with lima HEAD causes colima not to see that the VM is running:

```
$ colima status
FATA[0000] colima is not running
```

### Version

Colima Version: 0.5.2
Lima Version: limactl version HEAD-baca0e7
Qemu Version:

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

**Comment by abiosoft** [comment]
Yeah, a fix is already being worked on https://github.com/abiosoft/colima/pull/563.

Colima will soon be bundling Lima to avoid issues due to version compatibility.

**Comment by jandubois** [comment]
I don't think this change (in Lima) was intentional, and probably should be reverted before the next Lima release, as it is only in the unreleased `master` branch so far.

**Comment by abiosoft** [comment]
> I don't think this change (in Lima) was intentional, and probably should be reverted before the next Lima release, as it is only in the unreleased `master` branch so far.

That is good to know. I had to admit I was a bit surprised by this breaking change as it caught me off-guard. 

I know pinning the Lima version for Colima is inevitable but since Colima has been the indirect edge-case tester for Lima so far, I was very much willing to defer it.

**Comment by jandubois** [comment]
> I had to admit I was a bit surprised by this breaking change

Yes, me too! 😄 

I've created https://github.com/lima-vm/lima/issues/1280 to track this on the Lima side; let's wait to hear from @AkihiroSuda, but I'm very sure that we don't want to break compatibility this way.

**Comment by jandubois** [comment]
The change in Lima has been reverted in https://github.com/lima-vm/lima/pull/1281, so I think this issue can be closed (after testing).

**Comment by jandubois** [comment]
> since Colima has been the indirect edge-case tester for Lima so far, I was very much willing to defer it.

Please report any changes that seem to break backwards compatibility on the Lima repo as soon as possible, and don't just work around it/adjust to it.

We intend to maintain compatibility, and getting early reports of any breakage can prevent the breakage from slipping into an actual release.

If breaking compatibility is unavoidable, it would be announced in the release notes well in advance of making the breaking change. But hopefully this will not become necessary.

**Comment by abiosoft** [comment]
I can confirm that the revert upstream works as desired.

Thanks @jandubois
