### ISSUE TITLE
Question - Restart of Colima resets all docker containers...?

### ISSUE THREAD

**Issue by codethought** [abiosoft/colima#578]
Hello

In trying to move from Docker Desktop to Colima I've run into a problem that I cannot figure out how to resolve. I'm able to start Colima and create docker containers via docker-compose without issue. However if I restart colima it is as I'm doing a new install/reconfiguration of the container that I've already had running. Shouldn't the state of the containers be persisting during restarts the way they did when I used Docker Desktop?

Thanks.

**Comment by abiosoft** [comment]
Can you kindly fill the issue template (and maybe recreate the issue) ? It provides us some context for your scenario.

**Comment by codethought** [comment]
@abiosoft  sure - I'll re file with the template.. apologies..!
