### ISSUE TITLE
colima template does not save changes using TextMate

### ISSUE THREAD

**Issue by kdambekalns** [abiosoft/colima#598]
### Description

When using the following to edit the template it works fine, changes are saved:

```
# uses vi
colima template
# uses VS Code
colima template --editor code
```

But when using [TextMate](https://macromates.com/) (yes, that still is a very fast editor for day-to-day use and works with the latest macOS 13.2) changes not saved, the tenplate file remains unchanged.

```
colima template --editor mate
```

I suspect something in the way TextMate saves the temporary file is "weird" – but if you see a way to fix it on the colima side, that would be great.

This really confused of us for a while…

### Version

Colima Version:
```
git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72

runtime: docker
arch: aarch64
client: v20.10.23
server: v20.10.20
```

Lima Version: `limactl version 0.14.2`
Qemu Version: `qemu-img version 7.2.0` (not used, though)

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/karsten/.colima/default/docker.sock
```

### Reproduction Steps

1. Use `colima template --editor mate` to change something
2. Check the template file
3. Changes are not saved

### Expected behaviour

Changes are saved to the template file.

**Comment by abiosoft** [comment]
@kdambekalns does textmate have a free version or trial? I would need to reproduce this to know what's going on.

I know some editors need additional flags to wait for the caller. e.g. vscode has the `--wait` flag.

**Comment by kdambekalns** [comment]
Yes, you could simply download TextMate to try that. But in fact the `--wait` flag is the solution. Fun fact: for some reason`code` (i.e. VS Code) works without that…

So, these work fine:

```shell
colima template --editor "mate --wait"
EDITOR="mate --wait" colima template
```

You can even see it, if you check the terminal when TextMate is still open: colima already saved the (yet unchanged) template and is done, while the editor is still open. 🙈

**Comment by abiosoft** [comment]
> Fun fact: for some reasoncode (i.e. VS Code) works without that…

Because it was handled :D due to the popularity of VSCode. Any other editor can be added as well, including TextMate.

https://github.com/abiosoft/colima/blob/cf522e8c74f3dd811544600bcdb2ba83c970d51d/cmd/util.go#L97-L98
