### ISSUE TITLE
unknown flag: --vz-rosetta

### ISSUE THREAD

**Issue by PTLMxDboi** [abiosoft/colima#607]
### Description

Macbook M1 Pro
MacOS 13.1

Running: colima start --cpu 4 --memory 8 --disk 64 --arch aarch64 --vm-type=vz --vz-rosetta

Error: unknown flag: --vz-rosetta

### Version

Colima Version: HEAD-d2b24d2
limactl version: 0.14.2

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

colima status
FATA[0000] colima is not running

### Reproduction Steps

1. brew install --HEAD colima
2. brew install docker
3. brew install docker-compose
4. colima start --cpu 4 --memory 8 --disk 64 --arch aarch64 --vm-type=vz --vz-rosetta

**Comment by abiosoft** [comment]
This is very strange as it appears your machine meets the requirements for rosetta.

- M1 device
- macOS 13 (Ventura).

Could it be that you are executing a different binary? Can you confirm the output of `which colima` and run with the absolute path e.g. `/usr/local/bin/colima start`

**Comment by PTLMxDboi** [comment]
which colima
/usr/local/bin/colima

ll /usr/local/bin/colima
/usr/local/bin/colima -> ../Cellar/colima/HEAD-d2b24d2/bin/colima

My MacM1 was restored from a Mac x86.
I was suspected a brew version issue.
I've uninstalled/reinstalled brew/colima but...same issue

which brew
/opt/homebrew/bin/brew

brew -v
Homebrew 3.6.20
Homebrew/homebrew-core (git revision c78e92f14ff; last commit 2023-02-03)

**Comment by PTLMxDboi** [comment]
Ok, I managed to fix the issue by totally uninstalling/removing brew before to reinstall the correct version.

**Comment by cyberman219** [comment]
I've just got the same issue unknown flag: --vz-rosetta.
**Macbook PRO**
- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [x] macOS M1 >= 13 (Ventura)
- [ ]  Linux

**Version**
- `limactl -v` = limactl version 0.14.2
- `brew -v`
Homebrew 3.6.21
Homebrew/homebrew-core (git revision 66e600d9e6a; last commit 2023-02-08)
Homebrew/homebrew-cask (git revision 9da035cce5; last commit 2023-02-07)
- `colima version`
colima version 0.5.2
git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72

When I tried to execute `colima start --arch x86_64 --vm-type=vz --cpu 4 --memory 12 --disk 100 --vz-rosetta`, I got `FATA[0000] unknown flag: --vz-rosetta`
- `which colima` = `/opt/homebrew/bin/colima`
- `ll /opt/homebrew/bin/colima` = `lrwxr-xr-x  33B Feb  8 09:37 /opt/homebrew/bin/colima -> ../Cellar/colima/0.5.2/bin/colima`

I did try to `brew uninstall colima` and install it again but did not help

**Comment by lee-bin** [comment]
Hi, @PTLMxDboi
I am using Apple M1 Pro and macOS Ventura 13.2.1.
How do you totally uninstalling/removing brew? I use this https://mac.install.guide/homebrew/5.html to uninstall brew and then reinstall brew and colima, but still got the same error.

which brew
/opt/homebrew/bin/brew
which colima
/opt/homebrew/bin/colima

My colima path is different from you. How you do install colima? I use `brew install colima` to install it.

**Comment by PTLMxDboi** [comment]
@lee-bin yes, you have the good path. This is the correct one:

which colima
/opt/homebrew/bin/colima

I was having it in the wrong path: /usr/local/bin/colima
I managed by re-installing brew and also, after uninstalling colima, I had to uninstall lima manually too.

**Comment by lee-bin** [comment]
@PTLMxDboi Thanks. I took the advice from https://github.com/abiosoft/colima/issues/630#issuecomment-1445463366 and resolved the issue.
