### ISSUE TITLE
Handle LIMA_HOME env variable

### ISSUE THREAD

**Issue by seregamorph** [abiosoft/colima#61]
In case if custom LIMA_HOME env variable is set up, the colima starting fails:
```
maxbook:~(:|✔) % echo $LIMA_HOME
/Users/morph/dev/lima
maxbook:~(:|✔) % colima start
INFO[0000] using docker runtime                         
INFO[0000] starting colima                              
INFO[0000] creating and starting ...                     context=vm
> msg="instance \"colima\" already exists (\"/Users/morph/dev/lima/colima\")"
FATA[0000] error starting vm: error at 'creating and starting': exit status 1 
```
a bit more details may be found here: https://github.com/abiosoft/colima/discussions/60

Reason to customize the variable: faster filesystem on non-default path

**Comment by jandubois** [comment]
@abiosoft Not sure if this is important for `colima`, but if you use `LIMA_HOME` as the location for forwarded sockets, then you need to also evaluate symlinks. I've added https://github.com/lima-vm/lima/pull/400 to provide an easy way to get the actual value used by lima:

```console
$ limactl info | jq -r .limaHome
/Users/jan/.lima
```
