### ISSUE TITLE
Creating unwanted proxy

### ISSUE THREAD

**Issue by adriangalera** [abiosoft/colima#610]
### Description

Hi! I don't have any proxy setup in my computer 

```
env |grep PROXY
```

and colima is creating a proxy:

```bash
➜  ~ docker info | grep "Proxy"
 HTTP Proxy: http://192.168.8.231:8100
 HTTPS Proxy: http://192.168.8.231:8100
```

If I enter the colima machine with ssh, I can see that this config comes from `/etc/environment`:

```bash
➜  ~ colima ssh
colima:/Users/adrian.galera$ cat /etc/environment
#
# This file is parsed by pam_env module
#
# Syntax: simple "KEY=VAL" pairs on separate lines
#
#LIMA-START
HTTPS_PROXY=http://192.168.8.231:8100
HTTP_PROXY=http://192.168.8.231:8100
http_proxy=http://192.168.8.231:8100
https_proxy=http://192.168.8.231:8100
#LIMA-END
colima:/Users/adrian.galera$
```

Right now I cannot pull docker images as it tries to reach internet via that non-existent proxy :(
```bash
➜  ~ docker run hello-world
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": context deadline exceeded.
```

Any idea? I tried modifying the /etc/environment but it gets overriden when I restart colima

I tried with head version and the same happens

### Version

Colima Version: 0.5.2
Lima Version: limactl version 0.14.2
Qemu Version: qemu-img version 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [X] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

➜  ~ colima status
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/adrian.galera/.colima/default/docker.sock

### Reproduction Steps

Not sure how to reproduce this

### Expected behaviour

No proxy defined in colima

**Comment by abiosoft** [comment]
Have you tried lowercase?

```
env | grep proxy
```

**Comment by adriangalera** [comment]
yep:
```bash
➜  env | grep proxy
➜  
```

**Comment by abiosoft** [comment]
That's strange. It is getting that value from somewhere.

Have you used those proxy values anywhere else?

**Comment by adriangalera** [comment]
You're absolutely right!

I was playing around with proxies some time ago. It turns out i had the proxy setup in another interface which I did not use normally.

Sorry for bothering you :(

Now docker is back! Thank you
