### ISSUE TITLE
Using Apple virtualization framework `vz` and `virtiofs`on macOS <13.0

### ISSUE THREAD

**Issue by dmohns** [abiosoft/colima#618]
### Description

This is a mixture of a question and a feature request 😉 

## Scope

Would it be possible to run Colima using Apple's virtualization framework, i.e. `vmType: vz` and  and `mountType: virtiofs` on macOS <13.0 (in particular MacOS 12)?

I'm not exactly an expert on virtualization but after looking a bit at Apple docs

- https://developer.apple.com/documentation/virtualization
- https://developer.apple.com/documentation/virtualization/vzvirtiofilesystemdeviceconfiguration/

it appears that those are available at macOS 11 and 12 respectively. But there might another reason for why Colima requires macOS 13 which I don't know.

## Use case

macOS 13 has quite short list of supported devices, see https://support.apple.com/en-us/HT213264 It would be great to run Colima using Apple's virtualization framework on older devices or for users that cannot upgrade to macOS 13 for other reasons (if it's technically possible).

**Comment by jacksongoode** [comment]
It should be possible > 12.5 at least Docker has it enabled?

**Comment by AkihiroSuda** [comment]
Lima (and consequently Colima) requires macOS 13 because macOS 12 version of Virtualization.framework doesn't support UEFI

**Comment by btorsaldivar** [comment]
Yes, the combination of vmType: vz and and mountType: virtiofs is working on my MBP 13 2020:

````
❯ inxi -S
System:
  Host: xxxxxx Kernel: 22.3.0 arch: x86_64 bits: 64 Console: s010
    OS: Darwin 22.3.0
````
````
❯  colima start --vm-type=vz --mount-type=virtiofs
````
````
❯ colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/xxxx/.colima/default/docker.sock
````

**Comment by dmohns** [comment]
> Lima (and consequently Colima) requires macOS 13 because macOS 12 version of Virtualization.framework doesn't support UEFI

Understood, so there is no hope of ever having `vz` on MacOS 12. Thanks for clarifying.
