### ISSUE TITLE
How to map to vscode?

### ISSUE THREAD

**Issue by dragon512** [abiosoft/colima#62]
This is more of a question I am sure people will start to ask. Is there a way to map logic to allow vscode to see this as docker running? At the moment given the base default setup I can run docker to do all the basic stuff on the CLI, however when I try to load vs code to do a remote docker dev environment, I get an error message that vscode about docker is not running. I am not sure if anyone know if there is a work around to this. It would be great if there was.

**Comment by abiosoft** [comment]
Set docker context to `colima` in settings or edit the settings json file and add `"docker.context": "colima"`.

**Comment by dragon512** [comment]
I am running version 0.2.2. From the cli docker commands seem to run. From vs studio I am getting an error as vscode connection to a container defined by the local devcontainer.json with a 

failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``

I am guessing **docker-credential-desktop** is the issue. Not sure if anything can be done with this

**Comment by abiosoft** [comment]
Checked the solution in this issue. https://github.com/abiosoft/colima/issues/52

**Comment by dragon512** [comment]
Yep that seems to be it. I changed to it to  ~/.docker/config.json to
`
{
  "credsStore" : "osxkeychain",
  "auths" : {
  }
}
`
and that seems to fix it. 

I also did `rm ~/.docker/config.json` and that seems to work as well

Now having issues with read-only mounts. looking at other issues here to see if there a solution

**Comment by abiosoft** [comment]
I will be closing this as the issue itself is resolved

As for writeable mounts, you can use the `--mount` flag. And in version 0.3.0, mounts are going to default to writeable.

Thanks.

**Comment by 960208781** [comment]
try it  https://marketplace.visualstudio.com/items?itemName=song-chaoyang.colima
