### ISSUE TITLE
Colima unable to connect with Zscaler

### ISSUE THREAD

**Issue by jmjava** [abiosoft/colima#624]
### Description

I am using 0.5.2 and still not able to access the default docker registry 

I have tried options posted in :

# https://github.com/abiosoft/colima/issues/256
# https://github.com/abiosoft/colima/issues/131

nothing is working I still cannot pull.  I can login however.  

trying simple command :

docker pull ubuntu

After adding the Zscaler cert to both 

/usr/local/share/ca-certificates/ 
and
 /etc/docker/certs.d

and adjusting the template

docker:
  insecure-registries:
    - registry-1.docker.io:8443 (also tried 443)
    
➜  kubernetes git:(master) ✗ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
677076032cca: Retrying in 1 second     
error pulling image configuration: download failed after attempts=6: x509: certificate signed by unknown authority

Is there any improved workaround for 0.5.2 ?

thanks,

John

### Version

Colima Version:
Lima Version:
Qemu Version:

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [X] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU                 
INFO[0000] arch: x86_64                                 
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/menkjo/.colima/default/docker.sock 

### Reproduction Steps

1.  attempt to configure colima to pull from docker hub
2.  docker pull ubuntu

### Expected behaviour

docker image to be pulled

**Comment by jmjava** [comment]
This was ZScaler related not an issue with Colima

**Comment by chrismith-equinix** [comment]
@jmjava - I'm facing the same issue. What specifically was the Zscaler issue?

**Comment by jmjava** [comment]
we never got this fixed but in other environments like Kind we had to add
the Zscaler cert to the base docker image and do   update-ca-certificates

**Comment by limhs25** [comment]
https://www.atpeaz.com/disable-zscaler-temporarily-on-your-mac/#google_vignette 

it's work to me

**Comment by david-mecham-ncino** [comment]
copying the zscaler crt file to ~/docker/certs.d/{{domain}} eg `~/docker/certs.d/registry-1.docker.io` on the host machine works for me, though it is annoyingly fragile.

Ultimately the solution should probably be Collima integrating properly with the system Toolchain. Manually man handling and installing ZScaler certs takes control of certificate signing out of the hands of the system admins. (which is likely the reason they are using a proxy service like ZScaler to begin with).
