### ISSUE TITLE
[BUG/provisioning] colima failed to start

### ISSUE THREAD

**Issue by mritd** [abiosoft/colima#63]
When we mount a directory under the user directory to the docker container, and at the same time set the container to start automatically; the second time colima starts up, a mount error will occur.

**Error log:**

```sh
~ ❯❯❯ colima start
INFO[0000] using docker runtime
INFO[0000] starting colima
INFO[0000] starting ...                                  context=vm
> msg="[hostagent] The essential requirement 4 of 5 is satisfied"
> msg="[hostagent] Waiting for the essential requirement 5 of 5: \"the guest agent to be running\""
> msg="[hostagent] The essential requirement 5 of 5 is satisfied"
> msg="[hostagent] Mounting \"/Users/xxxxx\""
> msg="[hostagent] fuse: mountpoint is not empty"
> msg="[hostagent] fuse: if you are sure this is safe, use the 'nonempty' mount option"

INFO[0063] provisioning ...                              context=docker
FATA[0063] error provisioning docker: error at 'provisioning': error copying deamon.json: exit status 1
```

**Analysis of the cause of the error:**

- 1. Use docker compose to run a container with local dir mounts
- 2. Restart colima (`colima stop && colima start`)
- 3. The docker in the VM is automatically started by default, and then the container in compose is started
- 4. Docker Compose will automatically create a mount directory that does not exist
- 5. Lima tries to mount via sshfs, and the mount fails because the directory is not empty(Compose has created the mount directory)
- 6. colima tried to copy daemon.json in the mount directory, but the copy failed

**docker-compose.yaml**

```yaml
version: '3.8'
services:
  caddy:
    image: mritd/caddy
    container_name: caddy
    restart: always
    volumes:
      - ./conf:/etc/caddy
    ports:
      - "1234:1234"
```

I'm not sure if I describe it clearly. I temporarily turn off the VM internal docker to automatically start to solve this problem (`systemctl disable docker`); does anyone else have a better solution?

**Comment by abiosoft** [comment]
Hi, are you still experiencing this?

Can you kindly try the development version and see if the issue is fixed. `brew install --HEAD colima`.

**Comment by mritd** [comment]
I tried the latest code and the problem still exists.

The core of the problem is:

If we do not prevent docker from starting automatically (systemd), containers with `restart=always` will run automatically;

If this container mounts a directory under the user directory (`/Users/xxx/...`) at the same time, then because lima has not completed the sshfs mount at this time, this will cause docker to automatically create this directory; wait until When lima's sshfs tries to mount, the mount fails because the directory already exists.

You can reproduce this problem through the docker compose file in the attachment below (just start compose and restart colima to trigger it)

[caddy.tar.gz](https://github.com/abiosoft/colima/files/7632298/caddy.tar.gz)

**Comment by abiosoft** [comment]
I think I understand the issue now

**Comment by mritd** [comment]
My test only needs to turn off the automatic startup of docker to fix this problem(`colima ssh && systemctl disable docker`);

By the way:

I see that the `service` command is heavily used in the code. In the new system, we should adjust to use the `systemctl` command;

I tried to modify the code, but obviously there are too many changes. I'm not sure if you use the service command to be compatible with other systems.

**Comment by abiosoft** [comment]
@mritd Ubuntu is being replaced with Alpine in the new version.

Can you build from source? If yes, kindly try the next version by following [these instructions](https://github.com/abiosoft/colima/issues/70#issuecomment-983031349).

**Comment by mritd** [comment]
Wow that's so cool! ! ! !

😆, haha     I found a small bug, it will cause compilation error:

![image](https://user-images.githubusercontent.com/13043245/144212240-b12602a3-887b-4f9c-8ef1-cc03ab8cd63b.png)

**Comment by abiosoft** [comment]
It's because I'm still actively working on it. It should build nonetheless as the package is not imported anywhere else.

**Comment by abiosoft** [comment]
or just put an empty fine that is named with `.bin` suffix in the directory. That should suffice.

**Comment by mritd** [comment]
I tested the alpine version of colima and this problem has been fixed. Do I need to close this issue?

**Comment by abiosoft** [comment]
> I tested the alpine version of colima and this problem has been fixed. Do I need to close this issue?

Thanks for trying it.

**Comment by anhirvon** [comment]
I can see this issue with 
colima version 0.3.4
git commit: 5a4a70481ca8d1e794677f22524e3c1b79a9b4ae
runtime: docker
arch: x86_64
limactl version 0.9.1

Do we have official fix available for this one?
