### ISSUE TITLE
unknown flag: --vz-rosetta 

### ISSUE THREAD

**Issue by jeiksegovia** [abiosoft/colima#630]
### Description

Run `colima start --arch aarch64 --vm-type=vz --vz-rosetta`
it shows:
`FATA[0000] unknown flag: --vz-rosetta` 

Im running m1 Ventura 13.1

### Version

Colima Version: 0.5.2
Lima Version: 0.14.2
Qemu Version: 7.2.0 

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

colima start --vz-rosetta --arch aarch64 --vm-type=vz
Error: unknown flag: --vz-rosetta
Usage:
  colima start [profile] [flags]

Examples:
  colima start
  colima start --edit
  colima start --runtime containerd
  colima start --kubernetes
  colima start --runtime containerd --kubernetes
  colima start --cpu 4 --memory 8 --disk 100
  colima start --arch aarch64
  colima start --dns 1.1.1.1 --dns 8.8.8.8
  colima start --dns-host example.com=1.2.3.4
  colima start --kubernetes --kubernetes-disable=coredns,servicelb,traefik,local-storage,metrics-server

Flags:
      --activate                     set as active Docker/Kubernetes context on startup (default true)
  -a, --arch string                  architecture (aarch64, x86_64) (default "aarch64")
  -c, --cpu int                      number of CPUs (default 2)
      --cpu-type string              the CPU type, options can be checked with 'qemu-system-aarch64 -cpu help'
  -d, --disk int                     disk size in GiB (default 60)
  -n, --dns ipSlice                  DNS resolvers for the VM (default [])
      --dns-host strings             custom DNS names to provide to resolver
  -e, --edit                         edit the configuration file before starting
      --editor string                editor to use for edit e.g. vim, nano, code (default "$EDITOR" env var)
      --env stringToString           environment variables for the VM (default [])
  -h, --help                         help for start
  -k, --kubernetes                   start with Kubernetes
      --kubernetes-disable strings   components to disable for k3s e.g. traefik,servicelb (default [traefik])
      --kubernetes-version string    must match a k3s version https://github.com/k3s-io/k3s/releases (default "v1.25.4+k3s1")
  -l, --layer                        enable Ubuntu container layer
  -m, --memory int                   memory in GiB (default 2)
  -V, --mount strings                directories to mount, suffix ':w' for writable
      --mount-type string            volume driver for the mount (sshfs, 9p, virtiofs) (default "sshfs")
      --network-address              assign reachable IP address to the VM
      --network-driver string        network driver to use (gvproxy, slirp) (default "gvproxy")
  -r, --runtime string               container runtime (containerd, docker) (default "docker")
  -s, --ssh-agent                    forward SSH agent to the VM
      --ssh-config                   generate SSH config in ~/.ssh/config (default true)
  -t, --vm-type string               virtual machine type (qemu, vz) (default "qemu")

Global Flags:
  -p, --profile string   profile name, for multiple instances (default "default")
  -v, --verbose          enable verbose log
      --very-verbose     enable more verbose log

FATA[0000] unknown flag: --vz-rosetta 

### Reproduction Steps

1.Run `colima start --arch aarch64 --vm-type=vz --vz-rosetta`

### Expected behavior

Colima creates a new VM with Rosseta 2

**Comment by jhult** [comment]
I'm not sure if `--vz-rosetta` is in version 0.5.2. But, it works for me using `HEAD-c7ab3cf`.

Try installing from `--head`  and then try again:

```
$ brew install --HEAD colima
$ colima --version
colima version HEAD-c7ab3cf
```

Note: You may first need to do `brew remove colima`

**Comment by Nicolab** [comment]
Any idea when the support of `--vz-rosetta` flag will be released to Brew?

**Comment by abiosoft** [comment]
> Any idea when the support of --vz-rosetta flag will be released to Brew?

In the next few days, we are trying to wrap us some features.

**Comment by Nicolab** [comment]
Great, thank you

**Comment by jeiksegovia** [comment]
Thanks, everyone!!
