### ISSUE TITLE
Unable to create rosetta support VM | unknown flag --vm-type 

### ISSUE THREAD

**Issue by parthashar** [abiosoft/colima#650]
### Description

Whilst running ```colima start --arch aarch64 --vm-type=vz --vz-rosetta``` as provided in the docs, I get the following error
**FATA[0000] unknown flag: --vm-type**

### Version

Colima Version:
- colima version 0.5.4
- git commit: feef4176f56a7dea487d43689317a9d7fe9de27e
- runtime: docker
- arch: aarch64
- client: v23.0.1
- server: v20.10.20

Lima Version: 

- limactl version 0.15.0

Qemu Version:

- qemu-img version 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [X] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

Profile:
```colima start --memory 8 --mount $HOME:w```

Colima Status:
```
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/parth.ashar/.colima/default/docker.sock
```

### Reproduction Steps

1. Installed via brew ```./brew install colima docker docker-compose```
2. colima start --arch aarch64 --vm-type=vz --vz-rosetta
3.

### Expected behaviour

A VM is to be created that supports X86 images via Rosetta

### Additional context

I've also tried using the -e / --edit flag, and editing the config during start, like so ``` colima start -e ``` and changing the Virtual Machine type flag from **qemu** to **vz**. 

I get the following error:
```
FATA[0060] error in config file: invalid vmType: 'vz'
```

**Comment by parthashar** [comment]
Thanks!
https://github.com/abiosoft/colima/compare/main...parthashar:colima:patch-1

Created this PR to add this to the docs :)

**Comment by parthashar** [comment]
Apologies! 
https://github.com/abiosoft/colima/pull/652

**Comment by mitar** [comment]
I was confused by this as well. I think it would be better if colima would report that `vz` value is not supported for the `--vm-type` flag, maybe mention even that the hardware does not support it. Instead of just removing the whole option.

**Comment by christianlittle7** [comment]
Agreed, I would prefer the output to be more clear that it's not supported on my platform rather than the option just not being found. Saying it's not found made me think I was getting an old version of the software, or had misconfigured my installation.
