### ISSUE TITLE
fstrim does not work as described in FAQ

### ISSUE THREAD

**Issue by Pat-Ayres** [abiosoft/colima#659]
### Description

The FAQ has a section on [manually reclaiming disk](https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#manual), but when I run the command as written, it fails:
```
🕙[ 15:05:40 ] [🧱 ]  ❯ colima ssh -- sudo fstrim -a
fstrim: unrecognized option: a
BusyBox v1.33.1 () multi-call binary.

Usage: fstrim [OPTIONS] MOUNTPOINT

        -o OFFSET       Offset in bytes to discard from
        -l LEN          Bytes to discard
        -m MIN          Minimum extent length
        -v              Print number of discarded bytes
FATA[0000] exit status 1
```

I think `fstrim` is supposed to have a `-a` flag, so I'm not sure what is going on.

### Version

Colima Version: 0.5.4
Lima Version: 0.15.0
Qemu Version: 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] address:
INFO[0000] socket: unix:///Users/payres/.colima/default/docker.sock

### Reproduction Steps

1. colima ssh -- sudo fstrim -a
2.
3.

### Expected behaviour

disk space is reclaimed as documented in the FAQ

**Comment by abiosoft** [comment]
Can you share the output of the following commands?
```sh
colima ssh -- which fstrim
colima ssh -- uname -a
colima ssh -- cat /etc/os-release
```

The `-a` flag is indeed present for me.

```
$ colima ssh -- fstrim --help

Usage:
 fstrim [options] <mount point>

Discard unused blocks on a mounted filesystem.

Options:
 -a, --all                trim mounted filesystems
 -A, --fstab              trim filesystems from /etc/fstab
 -I, --listed-in <list>   trim filesystems listed in specified files
 -o, --offset <num>       the offset in bytes to start discarding from
 -l, --length <num>       the number of bytes to discard
 -m, --minimum <num>      the minimum extent length to discard
 -v, --verbose            print number of discarded bytes
     --quiet-unsupported  suppress error messages if trim unsupported
 -n, --dry-run            does everything, but trim

 -h, --help          display this help
 -V, --version       display version

Arguments:
 <num> arguments may be followed by the suffixes for
   GiB, TiB, PiB, EiB, ZiB, and YiB (the "iB" is optional)

For more details see fstrim(8).
```

**Comment by Pat-Ayres** [comment]
* `colima ssh -- which fstrim` -> `/sbin/fstrim`
* `colima ssh -- uname -a` -> `Linux colima 5.10.109-0-virt #1-Alpine SMP Mon, 28 Mar 2022 11:20:52 +0000 aarch64 Linux`
* `colima ssh -- cat /etc/os-release`
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.6
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
BUILD_ID=""
VARIANT_ID="clm"
```

**Comment by abiosoft** [comment]
Looks like you are still running an older version of the colima iso. You will need to reset Colima to take advantage of the feature.

This is the current version.

```
$ uname -a
Linux colima 5.15.82-0-virt #1-Alpine SMP Mon, 12 Dec 2022 09:15:17 +0000 aarch64 Linux

$ cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.3
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
BUILD_ID=""
VARIANT_ID="clm"
```

**Comment by Pat-Ayres** [comment]
Not sure if I ran into a bug in colima or just some wonkiness, but that did not work for me. I was getting an error that `daemon.pid` did not exist when I tried to run `colima start`. I did have some pending MacOS updated, so I applied those and restarted and then `colima start` succeeded.

In any case, that did the trick, everything looks good now.

```
colima:~$ uname -a
Linux colima 5.15.82-0-virt #1-Alpine SMP Mon, 12 Dec 2022 09:15:17 +0000 aarch64 Linux
colima:~$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.3
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
BUILD_ID=""
VARIANT_ID="clm"
```

For future reference, is this required to do at some cadence? Should I be checking release notes for when new ISOs get distributed and resetting the env when that happens?

**Comment by abiosoft** [comment]
> Should I be checking release notes for when new ISOs get distributed and resetting the env when that happens?

Yeah, it is always mentioned in the release notes if a reset would be required.
