### ISSUE TITLE
Cannot get ForwardAgent: true to work

### ISSUE THREAD

**Issue by neil-greenwood** [abiosoft/colima#66]
I installed colima and docker through HomeBrew. I started colima, pulled an image and started a container. When I connect to that container, I see `Could not open a connection to your authentication agent.` when running `ssh-add -L`.
I then edited `~/.lima/colima/lima.yaml` and added `forwardAgent: true`.

Even after killing the container and starting a new one, I still get no connection to the agent inside the container.

Am I doing something wrong?

**Comment by abiosoft** [comment]
@neil-greenwood it needs to be implemented directly in Lima.

Even though the visible config is at `~/.lima/colima/lima.yaml`, it is being overwritten on every startup. Changing it manually will have no effect.

This will be fixed in the next version.

**Comment by neil-greenwood** [comment]
Thanks. That's good to hear.
Is there any way to work around the issue in the meantime? I will try copying my public keys into the container, as a brute-force approach, if there's no other option.
