### ISSUE TITLE
Failed to Pull Local Docker Image

### ISSUE THREAD

**Issue by zachbugay** [abiosoft/colima#661]
### Description

I am trying to run an image that is in the local docker repository. The pod is failing to start. 

Failed to pull image "kubia": rpc error: code = Unknown desc = Error response from daemon: pull access denied for kubia, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

### Version

❯ colima version
colima version 0.5.4
git commit: feef4176f56a7dea487d43689317a9d7fe9de27e

runtime: docker
arch: x86_64
client: v23.0.1
server: v20.10.20

kubernetes
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.25.4+k3s1

❯ limactl --version
limactl version 0.15.0

❯ qemu-img --version
qemu-img version 7.2.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

❯ colima status
INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/zach/.colima/default/docker.sock
INFO[0000] kubernetes: enabled

### Reproduction Steps

I created a super basic node js app.

```javascript
const http = require("http");
const os = require("os");

console.log("Kubia server starting...");

var handler = function (request, response) {
  console.log("Received request from " + request.connection.remoteAddress);
  response.writeHead(200);
  response.end("You've hit " + os.hostname() + "\n");
};

var www = http.createServer(handler);
www.listen(8080);
```

Dockerfile
```
FROM node:latest
ADD app.js /app.js
ENTRYPOINT [ "node", "app.js" ]
```

Build the docker file, it, then run it as a simple pod.

```
docker build -t kubia .
docker tag kubia foobar/kubia
kubectl run kubia --image=bugay/kubia --port=8080
```

From what I am reading, Colima should have access to the local docker registry, but it appears that it does not. 

### Expected behaviour

kubectl is able to access the local image, and runs it as a pod.

**Comment by abiosoft** [comment]
> ```
> docker build -t kubia .
> docker tag kubia foobar/kubia
> kubectl run kubia --image=bugay/kubia --port=8080
```

Is this a typo? because you have a different tag for the image.

**Comment by zachbugay** [comment]
> > ```
> > docker build -t kubia .
> > docker tag kubia foobar/kubia
> > kubectl run kubia --image=bugay/kubia --port=8080
> > ```
> 
> 
> ```
> 
> Is this a typo? because you have a different tag for the image.
> ```

it’s only a typo on the submission but locally I’ve made sure the image is there.

**Comment by abiosoft** [comment]
Oh, you need to set image pull policy to `Never`.
You can check this issue https://github.com/abiosoft/colima/issues/210#issuecomment-1061965551.

**Comment by zachbugay** [comment]
> Oh, you need to set image pull policy to `Never`.
> You can check this issue [#210 (comment)](https://github.com/abiosoft/colima/issues/210#issuecomment-1061965551).

That was exactly it. Thank you so much! You are wonderful!!!
