### ISSUE TITLE
Colima & Cilium

### ISSUE THREAD

**Issue by SavvasM1** [abiosoft/colima#663]
### Description

Hey! I am having issues making [Cilium](https://cilium.io/) work within the embedded K3s kubernetes of colima -- even after starting it with the `--kubernetes-disable="network-policy"` flag. We seem to have found that there's other things such as flannel that need to be disabled but these options aren't exposed via colima `--kubernetes-disable` flags. Any ideas how to make this work, or if this is possible at all?

Thanks!

**Comment by abiosoft** [comment]
Can you point me to list of things that needs to be disabled on k3s?

Thanks.

**Comment by SavvasM1** [comment]
Hey @abiosoft , thank you for the response.

Based on the latest testing applied, it seems that these two flags are required for cilium to successfully run:
```
 --k3s-arg "--disable-network-policy@servers:*" \
 --k3s-arg "--flannel-backend=none@servers:*"
```

**Comment by abiosoft** [comment]
Maybe introduce a `--k3s-args` instead. That would cover all cases.

The only reason I'm wary of that is that some users may specify arguments that might break's Colima's behaviour. 
Maybe putting a caveat of the consequences would suffice.

**Comment by abiosoft** [comment]
This does not look correct to me `"--disable-network-policy@servers:*" `, there should be an `=` somewhere in there. Did you get that from somewhere or it's a typo.

Is there anywwhere else to check the docs apart from https://docs.cilium.io/en/stable/installation/k3s/#installation-using-k3s ?

**Comment by abiosoft** [comment]
Looking at the docs, these are the two flags you need `--flannel-backend=none` and  `--disable-network-policy`.

**Comment by SavvasM1** [comment]
Yea, exactly as I pointed out above. If you are talking about the @servers part, that seemed to be a requirement for me to run the cluster (on an M1 Mac using k3d)

**Comment by SavvasM1** [comment]
> @SavvasM1 all that is needed is the --k3s-arg flag support, right?

Yes, I'd reckon so. If that could be added to the startup flags, probably the same way that the --kubernetes-disable flag works by accepting a number of params, that'd be great! Would also be nice if that came up in the help text as well. 

As a "stretch" thought, I am not sure whether we'd like to rework the existing `--kubernetes-disable` flag to handle free-form args that people can pass while still supporting the current functionality, but I believe you are right, a `--k3s-arg` flag would do it. I've also seen some other default flannel config in the `k3s.go` file, not sure whether that needs to  be changed as well, in the event where flannel is disabled.

Thanks!

**Comment by abiosoft** [comment]
> As a "stretch" thought, I am not sure whether we'd like to rework the existing `--kubernetes-disable` flag to handle free-form args that people can pass while still supporting the current functionality

They will get deprecated in favour of the more explicit `--k3s-arg`. User reactions to the deprecation would determine if it should be removed. In fact, the implementation would simply translate them to an equivalent `--k3s-arg` value.

> I've also seen some other default flannel config in the k3s.go file, not sure whether that needs to be changed as well, in the event where flannel is disabled.

I do not expect it to affect anything. Disabling flannel would simply render the file redundant and should not affect any other networks.

**Comment by SavvasM1** [comment]
Sounds good to me! Let me know if you require anything else. Would be nice to have this in sooner than later!

**Comment by chyyran** [comment]
Hi, are there any updates on getting `—k3s-arg` in?

**Comment by abiosoft** [comment]
> Hi, are there any updates on getting `—k3s-arg` in?

Yeah, I was busy but I am hoping to get to it this week.

**Comment by howardburgess** [comment]
Here's a script to start Colima and Cilium using the v0.5.5 release.

[colima-cilium.sh.txt](https://github.com/abiosoft/colima/files/11722076/colima-cilium.sh.txt)

Key parts:
```shell
printf "=== Starting Colima with Kubernetes but no CNI\n"
colima start --memory 8 --cpu 4 \
    --kubernetes --kubernetes-disable="" \
    --k3s-arg "--disable-network-policy" \
    --k3s-arg "--flannel-backend=none"

printf "=== Creating BPF and cgroup mounts on the Colima VM\n"
colima ssh -- sudo mount -t bpf bpffs /sys/fs/bpf
colima ssh -- sudo mount --make-shared /sys/fs/bpf
colima ssh -- sudo mkdir -p /run/cilium/cgroupv2
colima ssh -- sudo mount -t cgroup2 none /run/cilium/cgroupv2
colima ssh -- sudo mount --make-shared /run/cilium/cgroupv2
colima ssh -- sudo mount --make-shared /

printf "=== Installing Cilium\n"
cilium --context=colima install
```

**Comment by mapkon** [comment]
Hello,

Is the intention to implement something that replaces the script by @howardburgess?

**Comment by howardburgess** [comment]
I can't speak for @abiosoft but I don't think the intention is to add direct support in Colima for starting Cilium. However, the changes made in https://github.com/abiosoft/colima/pull/717 will allow people to do so, if they do want to use Colima + Cilium together.

**Comment by livespotty** [comment]
**Add the following also "colima ssh -- sudo chown -R root:root /opt/cni/bin" to the script.**


> Here's a script to start Colima and Cilium using the v0.5.5 release.
> 
> [colima-cilium.sh.txt](https://github.com/abiosoft/colima/files/11722076/colima-cilium.sh.txt)
> 
> Key parts:
> 
> printf "=== Starting Colima with Kubernetes but no CNI\n"
> colima start --memory 8 --cpu 4 \
>     --kubernetes --kubernetes-disable="" \
>     --k3s-arg "--disable-network-policy" \
>     --k3s-arg "--flannel-backend=none"
> 
> printf "=== Creating BPF and cgroup mounts on the Colima VM\n"
> colima ssh -- sudo mount -t bpf bpffs /sys/fs/bpf
> colima ssh -- sudo mount --make-shared /sys/fs/bpf
> colima ssh -- sudo mkdir -p /run/cilium/cgroupv2
> colima ssh -- sudo mount -t cgroup2 none /run/cilium/cgroupv2
> colima ssh -- sudo mount --make-shared /run/cilium/cgroupv2
> colima ssh -- sudo mount --make-shared /
> colima ssh -- sudo chown -R root:root /opt/cni/bin
> 
> printf "=== Installing Cilium\n"
> cilium --context=colima install
