### ISSUE TITLE
Panic when shutting down "misuse of an invalid handle"

### ISSUE THREAD

**Issue by pwagland** [abiosoft/colima#672]
### Description

Calling `colima stop` causes a panic message to be printed:
```
colima stop
INFO[0000] stopping colima
INFO[0000] stopping ...                                  context=docker
tINFO[0004] stopping ...                                  context=vm
> [hostagent] Received SIGINT, shutting down the host agent
> [hostagent] panic: runtime/cgo: misuse of an invalid Handle
> github.com/spf13/cobra.(*Command).ExecuteC(0x140001ba600)
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
> main.main()
> 	/private/tmp/lima-20230228-12249-xydhn3/lima-0.15.0/cmd/limactl/main.go:24 +0x20
FATA[0159] error stopping vm: error at 'stopping': exit status 2
```

Colima _did_ stop.

### Version

Colima Version: 0.5.4
Lima Version: 0.15.0
Qemu Version: 7.2.0

colima version 0.5.4
git commit: feef4176f56a7dea487d43689317a9d7fe9de27e

runtime: docker
arch: aarch64
client: v20.10.21-rd
server: v20.10.20

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs

### Reproduction Steps

1. Run colima stop
2. Be unlucky

I'm not consistently unlucky, and only rarely see this.

### Expected behaviour

No panic should be printed when colima shuts down.

**Comment by abiosoft** [comment]
Closing in favour of upstream issues.
