### ISSUE TITLE
FATA[0078] error provisioning kubernetes: error at 'downloading and installing': exit status 1 

### ISSUE THREAD

**Issue by obiekrix** [abiosoft/colima#677]
### Description

Starting colima with kubernetes fails with the titled error

### Version

Colima Version: 0.5.4
Lima Version:
Qemu Version:

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

% colima status
FATA[0000] error retrieving current runtime: empty value 

### Reproduction Steps

 colima start --arch x86_64 -c 2 -m 4  --with-kubernetes -r containerd
INFO[0000] starting colima                              
INFO[0000] runtime: containerd+k3s                      
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
INFO[0067] provisioning ...                              context=containerd
INFO[0067] starting ...                                  context=containerd
INFO[0074] provisioning ...                              context=kubernetes
INFO[0074] downloading and installing ...                context=kubernetes
> gzip: invalid magic
FATA[0078] error provisioning kubernetes: error at 'downloading and installing': exit status 1 

### Additional context

I used a Mac M2 13 Ventura

Below is my colima information:

% brew info colima
==> colima: stable 0.5.4 (bottled), HEAD
Container runtimes on MacOS (and Linux) with minimal setup
https://github.com/abiosoft/colima/blob/main/README.md
/opt/homebrew/Cellar/colima/0.5.4 (8 files, 14.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-03-31 at 16:33:30
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/colima.rb
License: MIT
==> Dependencies
Build: go ✔
Required: lima ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 478 (30 days), 54,412 (90 days), 202,827 (365 days)
install-on-request: 479 (30 days), 54,405 (90 days), 202,821 (365 days)
build-error: 1 (30 days)

**Comment by aelsnz** [comment]
I had similar issue with specific k3s version that was downloaded.  However I was not using `--arch x86_64` as depending on what you want to run, emulation is bit slower.

You can see the details if you add the flag `--very-verbose`.

What helped for me at the time was to try different/specific k3s version, for more detail see - https://github.com/k3s-io/k3s/releases

I ended up using: `--kubernetes-version="v1.24.3+k3s1"` and this worked for me.

**Comment by obiekrix** [comment]
Thanks @aelsnz 

I am specifying the `--arch x86_64` argument because I am using a Mac with an Apple Silicon processor and the images I intend to run were built for amd64 (not arm64 or aarch64).

Your suggestion worked fine if I don't specify the `--arch x86_64` argument but once I specify it, I am back to the same issue. See logs below:

```

colima start  --arch x86_64  --kubernetes  --kubernetes-version="v1.24.3+k3s1" --very-verbose  
TRAC[0000] cmd ["limactl" "info"]                       
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
TRAC[0000] error retrieving running instance: instance 'colima' does not exist 
INFO[0000] starting colima                              
INFO[0000] runtime: docker+k3s                          
INFO[0000] preparing network ...                         context=vm
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "start" "default" "--gvproxy" "--verbose"] 
INFO[0000] creating and starting ...                     context=vm
TRAC[0000] cmd ["limactl" "start" "--tty=false" "/var/folders/y2/knh6q2d56ll5hmk8drk1z1q40000gn/T/colima.yaml"] 
> Terminal is not available, proceeding without opening an editor
> "Attempting to download the image from \"https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.0-2/alpine-lima-clm-3.16.2-x86_64.iso\"" digest="sha512:e9e118498f3a0745574ffc3686105d2c9777f7142164fe50ee47909dabd504c80ac29aeb76f9582706173310d1488d3b6f0ee9018e2a6aadc28eefb7767b63ec"
> Using cache "/Users/user/Library/Caches/lima/download/by-url-sha256/e1cbaef56fc8e75af106d934389a17618643fcecfa066302d45ffb0390709851/data"
> [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/user/.lima/colima/serial.log")
> SSH Local Port: 62368
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] The essential requirement 1 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
> [hostagent] The essential requirement 2 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 3 of 5: "sshfs binary to be installed"
> [hostagent] The essential requirement 3 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 4 of 5: "/etc/fuse.conf (/etc/fuse3.conf) to contain \"user_allow_other\""
> [hostagent] The essential requirement 4 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 5 of 5: "the guest agent to be running"
> [hostagent] The essential requirement 5 of 5 is satisfied
> [hostagent] Mounting "/Users/user" on "/Users/user"
> [hostagent] Mounting "/tmp/colima" on "/tmp/colima"
> [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished"
> [hostagent] Forwarding "/var/run/docker.sock" (guest) to "/Users/user/.colima/default/docker.sock" (host)
> [hostagent] Forwarding "/var/run/docker.sock" (guest) to "/Users/user/.colima/docker.sock" (host)
> [hostagent] Forwarding "/run/lima-guestagent.sock" (guest) to "/Users/user/.lima/colima/ga.sock" (host)
> [hostagent] Not forwarding TCP 0.0.0.0:22
> [hostagent] Not forwarding TCP [::]:22
> [hostagent] The final requirement 1 of 1 is satisfied
> READY. Run `limactl shell colima` to open the shell.
TRAC[0063] cmd ["lima" "sudo" "cat" "/etc/hosts"]       
TRAC[0063] cmd ["lima" "sudo" "sh" "-c" "echo -e \"192.168.5.2\\thost.docker.internal\" >> /etc/hosts"] 
TRAC[0064] cmd ["lima" "sudo" "cat" "/etc/hosts"]       
TRAC[0064] cmd ["lima" "sudo" "sh" "-c" "echo -e \"127.0.0.1\\tcolima\" >> /etc/hosts"] 
INFO[0064] provisioning ...                              context=docker
TRAC[0064] cmd ["lima" "sudo" "mkdir" "-p" "/etc/docker"] 
TRAC[0064] cmd int ["lima" "sudo" "sh" "-c" "cat > /etc/docker/daemon.json"] 
TRAC[0064] cmd ["docker" "context" "inspect" "colima"]  
TRAC[0064] cmd ["docker" "context" "create" "colima" "--description" "colima" "--docker" "host=unix:///Users/user/.colima/default/docker.sock"] 
> colima
> Successfully created context "colima"
TRAC[0064] cmd ["docker" "context" "use" "colima"]      
> colima
> Current context is now "colima"
INFO[0064] starting ...                                  context=docker
TRAC[0064] cmd ["lima" "sudo" "service" "docker" "start"] 
>  * /var/log/docker.log: creating file
>  * /var/log/docker.log: correcting owner
>  * Starting Docker Daemon ... [ ok ]
TRAC[0064] cmd ["lima" "sudo" "docker" "info"]          
TRAC[0070] cmd ["lima" "sudo" "docker" "info"]          
INFO[0070] provisioning ...                              context=kubernetes
TRAC[0070] cmd ["lima" "sudo" "service" "k3s" "status"] 
TRAC[0070] cmd ["lima" "k3s" "--version"]               
TRAC[0071] cmd ["lima" "command" "-v" "k3s-uninstall.sh"] 
TRAC[0071] cmd ["lima" "uname" "-m"]                    
TRAC[0071] cmd ["lima" "uname" "-m"]                    
TRAC[0071] cmd ["limactl" "list" "colima" "--json"]     
INFO[0071] downloading and installing ...                context=kubernetes
TRAC[0071] cmd ["lima" "cp" "/Users/user/Library/Caches/colima/caches/afdbefa644a6bd2e4574b495e55e57b8461a0d6a49089850c9a0a2981da259da" "/tmp/k3s"] 
TRAC[0074] cmd ["lima" "sudo" "install" "/tmp/k3s" "/usr/local/bin/k3s"] 
TRAC[0074] cmd ["lima" "cp" "/Users/user/Library/Caches/colima/caches/6b2b0d5b8fbf51db5bc99377f64212f587d5193c234a516e1ca5d69f93d4e60d" "/tmp/k3s-airgap-images-amd64.tar.gz"] 
TRAC[0074] cmd ["lima" "gzip" "-f" "-d" "/tmp/k3s-airgap-images-amd64.tar.gz"] 
> gzip: invalid magic
FATA[0074] error provisioning kubernetes: error at 'downloading and installing': exit status 1 
```

**Comment by ignatiusteo-zh** [comment]
Same issue using `arch=host` and any kubernetes version:
```
TRAC[0181] cmd ["lima" "cp" "/Users/ignatius/Library/Caches/colima/caches/b70dd9d1b6738db039df896b4f3e6cc80b33e971518330991402ee38e9078756" "/tmp/k3s-airgap-images-arm64.tar.gz"]
TRAC[0181] cmd ["lima" "gzip" "-f" "-d" "/tmp/k3s-airgap-images-arm64.tar.gz"]
> gzip: invalid magic
FATA[0182] error provisioning kubernetes: error at 'downloading and installing': exit status 1
```

macOS M1 Ventura 13.2.1
colima version 0.5.2
git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72

runtime: docker
arch: aarch64
client: v23.0.1
server: v20.10.20

**Comment by abiosoft** [comment]
It is actually a known issue with the way the Kubernetes assets is being downloaded.
Clearing the colima cache and trying again should resolve it.

```
rm -rf ~/Library/Caches/colima
```

**Comment by obiekrix** [comment]
Thanks @abiosoft.
Your solution worked after few trials.
I later noticed that the strength of one's internet connectivity could also be a factor.

So as a future guide.

stop colima if running
`colima stop`
clear colima cache
`rm -r ~/Library/Caches/colima`
delete the cluster
`colima delete`
start colima with your preferred configurations
e.g. `colima start --with-kubernetes`

Thanks once again

**Comment by ignatiusteo-zh** [comment]
`rm -r ~/Library/Caches/colima` didn't work for me. 

What worked for me was blowing away the `~/.colima`, `~/.lima`, and `~/.docker` folders.

**Comment by Meghajit** [comment]
I tried all the approaches mentioned above like changing the k3s version and clearing the `~/.docker` and `~/.colima` cache, but none of them worked for me. I was trying Colima with Kubernetes using this: ( on Mac M2)

`colima start --kubernetes --kubernetes-version="v1.24.3+k3s1"`

I was getting this error constantly, albeit with a different `FATAL[...]` code each time:

```
FATA[0125] error provisioning kubernetes: error at 'loading oci images': error downloading
'https://raw.githubusercontent.com/k3s-io/k3s/v1.24.3+k3s1/install.sh': error retrieving redirect url: error running [curl -Ls -o
 /dev/null -w %{url_effective} https://raw.githubusercontent.com/k3s-io/k3s/v1.24.3+k3s1/install.sh], output: "", err: "exit 
status 28"
```
Found that the script was unable to download from `raw.githubusercontent.com` because of a DNS resolution failed with my ISP(Jio India). Changing the DNS/switching to another network worked. Putting it here, in case it helps someone.

**Comment by renedelima** [comment]
> I had similar issue with specific k3s version that was downloaded. However I was not using `--arch x86_64` as depending on what you want to run, emulation is bit slower.
> 
> You can see the details if you add the flag `--very-verbose`.
> 
> What helped for me at the time was to try different/specific k3s version, for more detail see - https://github.com/k3s-io/k3s/releases
> 
> I ended up using: `--kubernetes-version="v1.24.3+k3s1"` and this worked for me.

Good find. Picking `v1.29.3+k3s1` to match the client version solved the problem on my side.
