### ISSUE TITLE
Global flag (-p / --profile) not applied to "colima list" when multiple profiles in use

### ISSUE THREAD

**Issue by aelsnz** [abiosoft/colima#680]
### Description

I have an environment where I run more than one Colima profile running.
When using the list command I can see both profiles, but when I just want to list one, the "-p / --profile" global flags are ignored.

```
$  colima list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME       ADDRESS
rex        Running    aarch64    6       8GiB      20GiB    docker+k3s    192.168.106.15
xyz        Running    aarch64    2       2GiB      60GiB    docker

$  colima list -p rex
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME       ADDRESS
rex        Running    aarch64    6       8GiB      20GiB    docker+k3s    192.168.106.15
xyz        Running    aarch64    2       2GiB      60GiB    docker
```

### Version

Colima Version: 0.5.4
Lima Version: 0.15.0
Qemu Version: 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
$ colima status -p xyz
INFO[0000] colima [profile=xyz] is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/aelsnz/.colima/xyz/docker.sock

$ colima status -p rex
INFO[0000] colima [profile=rex] is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: 9p
INFO[0000] address: 192.168.106.15
INFO[0000] socket: unix:///Users/aelsnz/.colima/rex/docker.sock
INFO[0000] kubernetes: enabled
```

### Reproduction Steps

1.  create two profiles: `colima start -p abc; colima start -p xyz`
2.  run `colima list`
3.  run `colima list -p abc` 

### Expected behaviour

The global profile flag should apply to the list command showing only the specified profile.
If the profile does not exist no profiles should be shown.

**Comment by abiosoft** [comment]
This is an oversight, thanks for spotting it.

**Comment by aelsnz** [comment]
Is there any indication on when the next version might be released with these updates?  I know we can use - `brew install --HEAD colima` to get latest changes, but some might want stable release.
