### ISSUE TITLE
Colima can't run Airbyte

### ISSUE THREAD

**Issue by maver1ck** [abiosoft/colima#687]
### Description

Hi,
I'm trying to run Airbyte (https://github.com/airbytehq/airbyte) locally using colima.

This is working flawless on Debian arm64 VM on UTM. (with Docker-CE 23.0.3)

Unfortunately on Colima stack doesn't start up. 

I did: `colima delete && colima start` to reset colima VM.

### Version

Colima Version: colima version 0.5.4
Lima Version: limactl version 0.15.0
Qemu Version: qemu-img version 7.2.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/maverick/.colima/default/docker.sock
```

### Reproduction Steps

1. Clone Airbyte repo https://github.com/airbytehq/airbyte
2. Run `./run-ab-platform.sh`

### Expected behaviour

Airbyte is listening on port 8000.

### Additional context

I'm using docker compose version 2.17.2

### Logs:
```
[+] Running 3/0
 ✔ Container airbyte-temporal  Created                                                                                                                                                                          0.0s
 ✔ Container init              Created                                                                                                                                                                          0.0s
 ✔ Container airbyte-db        Created                                                                                                                                                                          0.0s
Attaching to airbyte-db, airbyte-temporal, init
init              | MOUNT: /local_parent
init              | ROOT_PARENT: /tmp
init              | ROOT: /tmp/airbyte_local
init              | MOUNT_ROOT: /local_parent//airbyte_local
Error response from daemon: error while creating mount source path '/Users/maverick/src/ezdihar/airbyte/temporal/dynamicconfig': chown /Users/maverick/src/ezdihar/airbyte/temporal/dynamicconfig: permission denied
```

**Comment by maver1ck** [comment]
I checked same script on debian arm64 VM run on lima without problems.
So this bug is colima related.

**Comment by abiosoft** [comment]
The only issue saw was related to `chmod` of a directory. It is a limitation of Colima's default volume mount type, sshfs.
If you try either 9p mounts (notable slower) or virtiofs (experimental and requires macOS 13), then it works fine.

```sh
colima delete # reset

# use 9p mounts
colima start --mount-type 9p # 9p mounts

# or use virtualization.framework with uses virtiofs mount
colima start --vm-type vz
```

**Comment by maver1ck** [comment]
@abiosoft 
I tried with newest instalation of everything.
airbyte-temporal is not starting so other components are failing
```
{"level":"error","ts":"2023-06-28T10:32:55.697Z","msg":"Unable to read dynamic config file. Continue with default settings but the ERROR MUST BE FIXED before the next upgrade","error":"unable to validate dynamic config: dynamic config: config/dynamicconfig/development.yaml: stat config/dynamicconfig/development.yaml: no such file or directory","logging-call-at":"main.go:140","stacktrace":"go.temporal.io/server/common/log.(*zapLogger).Error\n\t/temporal/common/log/zap_logger.go:142\nmain.buildCLI.func2\n\t/temporal/cmd/server/main.go:140\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163\ngithub.com/urfave/cli/v2.(*App).RunContext\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313\ngithub.com/urfave/cli/v2.(*App).Run\n\t/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main\n\t/temporal/cmd/server/main.go:50\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"
```

**Comment by terrysiu-pm** [comment]
fwiw, I am encountering the same issue trying to run Airbyte locally. I'm not using colima and just running the `run-ab-platform.sh` script on WSL2 with no Docker Desktop integration. The `airbyte-temporal` container fails to start also with a similar error message above:

```
{"level":"info","ts":"2023-07-18T22:26:42.283Z","msg":"Build info.","git-time":"2023-03-29T22:11:52.000Z","git-revision":"edbafd63e19dc0d585ec8cd0ebd793d3c6c6f6d6","git-modified":true,"go-arch":"amd64","go-os":"linux","go-version":"go1.20.2","cgo-enabled":false,"server-version":"1.20.1","debug-mode":false,"logging-call-at":"main.go:143"}
Unable to create dynamic config client. Error: unable to validate dynamic config: dynamic config: config/dynamicconfig/development.yaml: stat config/dynamicconfig/development.yaml: no such file or directory
```

Should there be an actual `development.yaml` file in the local `./temporal/dynamicconfig` directory since there is a volume mount against this directory for the `airbyte-temporal` container in the docker-compose?

**Comment by eddie-cosma** [comment]
@terrysiu-pm I believe there should be. I noticed that directory was chowned by a different uid, presumably related to the container. I ran `chown -R myuser:myuser temporal` and `touch temporal/dynamicconfig/development.yaml` and that allowed me to start everything up fine. I am running in docker on Arch, i.e., without colima.

**Comment by terrysiu-pm** [comment]
thanks @eddie-cosma , your suggestion worked!! i did change the ownership of the `temporal` directory earlier to myself, but was looking for a valid, non-empty `development.yaml` to use. Totally did not think of just trying an empty one! The `airbyte-temporal` container creates that `temporal` directory on first startup, and in my case, was owned by `root`.

**Comment by maver1ck** [comment]
I removed everything then start colima with `vm-type vz`. It works.

**Comment by jenser2144** [comment]
Anyone still facing this issue? I have similar issue using colima and have not been able to resolve. I'm on M1 macOS 12, so am using the 9p mount command:
```
colima start --mount-type 9p
```
I have checked ownership of the temporal files and everything checks out there. Anyone have any thoughts?
