### ISSUE TITLE
Is it possible to get the socket_vmnet updated?

### ISSUE THREAD

**Issue by aelsnz** [abiosoft/colima#693]
### Description

I have been looking into why sometimes when you start colima with k3s the `col0` interface in the vm does not get a DHCP ip and noticed that the the socket_vment provided is still older version.
Is it possible to update this to the latest to make sure we include the latest updates/fixes?

See - https://github.com/lima-vm/socket_vmnet/releases 

I am referencing the build in `scripts/build_vmnet.sh` where an older git commit is used to build the socket_vmnet.

Thank you in advance.

**Comment by abiosoft** [comment]
PR created https://github.com/abiosoft/colima/pull/694

Once the PR is merged, you can test with.

```sh
brew install --head colima # install development version
sudo rm -rf /opt/colima # clear existing networking assets
colima start --network-address
```
