### ISSUE TITLE
Colima does not start on Github actions Ubuntu runner

### ISSUE THREAD

**Issue by cristianrgreco** [abiosoft/colima#696]
### Description

I run Colima without issue on my local Ubuntu machine.

I am trying to create a Github actions pipeline using Colima on a Ubuntu runner, but it does not start. It times out with the message `"[hostagent] Waiting for the essential requirement 1 of 5: \"ssh\""`

The step is simply this:
```yaml
- name: Setup Colima
  run: |
    curl -L https://nixos.org/nix/install | sh -s -- --daemon
    nix-env -iA nixpkgs.colima
    colima start --runtime docker
```

Is there some example of Colima running on Linux in Github actions? I've tried several different things from other issues (such as installing qemu, different cpu types, etc), but nothing works.

I'm able to run it on macos, but the performance of the macos machines in GHA is terrible. The build takes on average 3x longer than on a linux machine.

Any help greatly appreciated.

### Version

Colima Version: 0.5.4
Lima Version: 0.15.0
Qemu Version: 7.2.1

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [X] Linux

### Output of `colima status`

N/A, cannot start.

### Reproduction Steps

1. Create a github action with the YAML in the description.

### Expected behaviour

Colima should start.

**Comment by abiosoft** [comment]
@cristianrgreco can you use the `--verbose` flag and check the logs?

**Comment by abiosoft** [comment]
Is virtualization enabled by default on Github actions for Linux? 
e.g. on Github codespaces, I either need to add the user to the `kvm` group or modify the permissions on `/dev/kvm`.

**Comment by abiosoft** [comment]
> Does this mean that Colima cannot run on the normal Linux runners?

Yeah, colima utilises VMs on Linux as well.

**Comment by cristianrgreco** [comment]
Hopefully in the future GH will either [fix the performance of their MacOS runners](https://github.com/actions/runner-images/issues/1336), or support nested virtualisation on their normal runners.

Thanks for your time @abiosoft
