### ISSUE TITLE
host.docker.internal not available in pods running in kubernetes

### ISSUE THREAD

**Issue by roderik** [abiosoft/colima#698]
### Description

Running colima with the settings below in the reproduction steps, and going on the vm using ```colima ssh``` gives me the following host file

```
cat /etc/hosts
127.0.0.1	localhost localhost.localdomain
::1		localhost localhost.localdomain
192.168.5.2	host.lima.internal
192.168.5.2	host.docker.internal
127.0.0.1	colima
```

Which means i can curl etc to host.docker.internal

Now in a pod in kubernetes, this domain is not available at all

```
cat /etc/hosts 
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.17.0.6	ingress-nginx-controller-6d9bc7c659-pwfd5
```
```
nslookup host.docker.internal
Server:		10.43.0.10
Address:	10.43.0.10:53

Non-authoritative answer:

** server can't find host.docker.internal: NXDOMAIN
```

I would expect it to be in the pod itself

I worked around it for now by adding the following to my pod specs, but it feels bad to add local dev env info in my manifests
```
  hostAliases:
  - ip: "192.168.5.2"
    hostnames:
    - "host.docker.internal"
```

### Version

Colima Version:

```
colima version 0.5.4
git commit: feef4176f56a7dea487d43689317a9d7fe9de27e

runtime: docker
arch: aarch64
client: v23.0.3
server: v20.10.20

kubernetes
Client Version: v1.27.0
Kustomize Version: v5.0.1
Server Version: v1.25.4+k3s1
```
Lima Version: `limactl version 0.15.0`
Qemu Version: `qemu-img version 7.2.1`

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] address: 192.168.106.2                       
INFO[0000] socket: unix:///Users/roderik/.colima/default/docker.sock 
INFO[0000] kubernetes: enabled  
```

### Reproduction Steps

1. `colima start --cpu 6 --memory 16 --disk 100 --kubernetes --network-address --network-driver gvproxy --vm-type vz --vz-rosetta` (tried qemu and slirp as well, with or without network-address, with or without the default or custom dns)
2. `helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace --set controller.watchIngressWithoutClass="true" --set controller.ingressClassResource.default="true"`
3. shell into the controller pod (it has curl) and try to access host.docker.internal

### Expected behaviour

host.docker.internal should be available in the pod, either through /etc/hosts or dns

**Comment by aelsnz** [comment]
Is there any plans to address this in the near future.  I am seeing similar issue as reported here.
is there a way to add that to the cluster dns ? any workaround on how to add this in mean time?

**Comment by aelsnz** [comment]
Another solution I used for this was to deploy the colima + k3s environment, then before you deploy ingress-nginx you can update (patch) the CoreDNS configmap (coredns) and update the Corefile to include `192.168.5.2 host.docker.local` address under hosts.

**Comment by rfay** [comment]
It seems that host.docker.internal is no longer 192.168.5.2 in v0.6.*, We're all seeing the actual IP as 192.168.104.2

So I assume that Colima is now setting host.docker.internal and it's no longer a fixed IP address.

Is this intentional or a regresssion?
