### ISSUE TITLE
Docker cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by vraravam** [abiosoft/colima#7]
At the outset, let me say I'm really thankful for this awesome contribution!

I have a small issue - and a workaround which I think can benefit others if it gets fixed/incorporated into the core:

1. I start colima with the command-line invocations (`colima start`)
2. use it as normal to build images, etc.
3. I then shutdown colima (`colima stop`)
4. Subsequently, even if I start colima again (`colima start`), the docker commands don't work.
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I found out that this is due to the fact that the socket file is still available, and is a broken symlink
<img width="914" alt="Screenshot 2021-09-10 at 7 57 35 PM" src="https://user-images.githubusercontent.com/69629/132869483-154342e9-2588-4bea-869e-e047c385da20.png">

If I delete the `/var/run/docker.sock` - then I am able to restart colima and continue with work:
```
sudo rm -rf /var/run/docker.sock
```

Can this issue be fixed? Or is there a better way to solve this problem?

**Comment by abiosoft** [comment]
It is perfectly fine for the docker socket file to be available and be a broken link. In fact, that was the design. It becomes an active link only when Colima is up and running.

Are you sure that Colima started successfully and yet you couldn't use docker? If yes, can you share the outputs of `colima start`, `colima version` and `colima status` commands executed in that order.

Thanks.

**Comment by abiosoft** [comment]
I will actually be closing this issue as what you've described (with regards to the socket) is the expected behaviour. 
I will re-open when an issue is ascertained.

**Comment by vraravam** [comment]
As mentioned in point 4, the subsequent start of `colima` still has the error.

ok - I think my usage was the problem:
I have these aliases:
```
alias start_colima='colima start --cpu 3 --memory 6 --disk 75'
alias stop_colima='colima stop'
```
My guess: when I use `start_colima` and it detects a change in the config, then the socket doesn't work anymore. Is this true?

**Comment by abiosoft** [comment]
okay, can you kindly share the outputs of these commands? https://github.com/abiosoft/colima/issues/7#issuecomment-916957279

**Comment by vraravam** [comment]
```
; colima start
Linux
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-09-10 14:53:54 UTC; 52min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 764 (dockerd)
      Tasks: 16
     Memory: 1.7G
     CGroup: /system.slice/docker.service
             └─764 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
Warning: Stopping docker.service, but it can still be activated by:
  docker.socket
time="2021-09-10T21:17:39+05:30" level=info msg="Sending SIGINT to hostagent process 46698"
time="2021-09-10T21:17:39+05:30" level=info msg="Waiting for the host agent and the qemu processes to shut down"
time="2021-09-10T21:17:39+05:30" level=info msg="[hostagent] Received SIGINT, shutting down the host agent"
time="2021-09-10T21:17:39+05:30" level=info msg="[hostagent] Shutting down the host agent"
time="2021-09-10T21:17:39+05:30" level=info msg="[hostagent] Unmounting \"/Users/vijay\""
time="2021-09-10T21:17:39+05:30" level=info msg="[hostagent] Unmounting \"/tmp/colima\""
time="2021-09-10T21:17:39+05:30" level=info msg="[hostagent] Shutting down QEMU with ACPI"
time="2021-09-10T21:17:39+05:30" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedly"
time="2021-09-10T21:17:39+05:30" level=info msg="[hostagent] Sending QMP system_powerdown command"
time="2021-09-10T21:17:49+05:30" level=info msg="[hostagent] Forwarding \"/run/user/501/lima-guestagent.sock\" (guest) to \"/Users/vijay/.lima/colima/ga.sock\" (host)"
time="2021-09-10T21:17:49+05:30" level=warning msg="[hostagent] failed to setting up forward from \"/run/user/501/lima-guestagent.sock\" (guest) to \"/Users/vijay/.lima/colima/ga.sock\" (host)"
time="2021-09-10T21:17:49+05:30" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedly"
time="2021-09-10T21:17:59+05:30" level=info msg="[hostagent] Forwarding \"/run/user/501/lima-guestagent.sock\" (guest) to \"/Users/vijay/.lima/colima/ga.sock\" (host)"
time="2021-09-10T21:17:59+05:30" level=warning msg="[hostagent] failed to setting up forward from \"/run/user/501/lima-guestagent.sock\" (guest) to \"/Users/vijay/.lima/colima/ga.sock\" (host)"
time="2021-09-10T21:18:00+05:30" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedly"
time="2021-09-10T21:18:10+05:30" level=info msg="[hostagent] Forwarding \"/run/user/501/lima-guestagent.sock\" (guest) to \"/Users/vijay/.lima/colima/ga.sock\" (host)"
time="2021-09-10T21:18:10+05:30" level=warning msg="[hostagent] failed to setting up forward from \"/run/user/501/lima-guestagent.sock\" (guest) to \"/Users/vijay/.lima/colima/ga.sock\" (host)"
time="2021-09-10T21:18:10+05:30" level=warning msg="[hostagent] connection to the guest agent was closed unexpectedly"
time="2021-09-10T21:18:15+05:30" level=info msg="[hostagent] QEMU has exited"
; colima stop
```
I can confirm that just using `colima start` and `colima stop` avoided the issue. And thus, it points to the fact that *colima thinking that the config changed* is the root cause of this behavior

**Comment by abiosoft** [comment]
Thanks for the sharing the log output. 
BTW I am actually not asking for the verbose output :), the standard one is fine.

I am struggling to reproduce your scenario. Are you saying that starting colima with `colima start --cpu 3 --memory 6 --disk 75` is causing the issue for you?.

If you wouldn't mind one more time, can you just run this in your terminal and share the output as it is from your terminal. No need to tail the verbose log.
```
colima stop
colima start --cpu 3 --memory 6 --disk 75
colima version
colima status
```

**Comment by vraravam** [comment]
<img width="851" alt="Screenshot 2021-09-10 at 10 04 45 PM" src="https://user-images.githubusercontent.com/69629/132887364-20b6891f-004f-4983-97da-a6b8c5a282b3.png">

**Comment by abiosoft** [comment]
That looks perfectly fine.

If you were able to reproduce it again, it would be appreciated if you can update this thread.

Thanks.
