### ISSUE TITLE
Update cri-dockerd to version 0.30

### ISSUE THREAD

**Issue by codeprefect** [abiosoft/colima#701]
### Description

Based on my experience debugging #697, I have found out the root cause to be the version of cri-dockerd Colima installed in the virtual machine.

Kubernetes v1.26 dropped support for the CRI endpoint v1alpha2, and only supports v1, this was added to cri-dockerd in version [0.3.0](https://github.com/Mirantis/cri-dockerd/releases/tag/v0.3.0).

**Comment by abiosoft** [comment]
Yeah, this would be done soon.

Thanks for troubleshooting.

**Comment by abiosoft** [comment]
Thanks.
