### ISSUE TITLE
Debugging container creation failure with old nerdctl is hard, upgrade timeline?

### ISSUE THREAD

**Issue by scandey** [abiosoft/colima#707]
### Description

I'm trying to get a reasonably complex Docker setup (https://github.com/OpenC3/cosmos) working in Colima. I haven't gotten very far though, since the `nerdctl compose` command appears to hide all of the actual error messages when running compose. That appears to have been updated in nerdctl already and the lima project has updated to use that version of nerdctl. Is there a timeline for Colima following suite and upgrading nerdctl?

```
> nerdctl compose up
...
FATA[0000] error while creating container xxx: exit status 1
FATA[0000] exit status 1
```

### Version

Colima Version: 
colima version 0.5.4
git commit: feef4176f56a7dea487d43689317a9d7fe9de27e

runtime: containerd
arch: aarch64
client: v1.1.0
server: v1.6.8

Lima Version:
limactl version 0.15.1

Qemu Version:
qemu-img version 8.0.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: containerd                          
INFO[0000] mountType: sshfs

### Reproduction Steps

1. git clone https://github.com/OpenC3/cosmos-project
2. nerdctl compose up
3. get some warnings, but mostly just an opaque `FATA[0000] error while creating container cosmos-testbed_openc3-minio_1: exit status 1 `

### Expected behaviour

Nerdctl appears to have changed in recent versions to show more errors, but Colima is behind by a few versions back now. 

### Additional context

https://github.com/abiosoft/colima/issues/105 has some info about upgrading the underlying tools but I couldn't parse it easily

**Comment by abiosoft** [comment]
Among the features being explored in the long run is the ability to upgrade the container runtimes without necessarily upgrading Colima itself.

As a stop-gap, I would to try to push out an update to include the latest containerd.
