### ISSUE TITLE
Problem with docker run -v $HOME/.colima/default/docker.sock:/var/run/docker.sock

### ISSUE THREAD

**Issue by bumfo** [abiosoft/colima#712]
### Description

I'm trying to access colima inside a container. 

First use docker run -v $HOME/.colima/default/docker.sock:/var/run/docker.sock to mount docker.sock into the container.

Inside the container, run
```
curl -XPOST --unix-socket /var/run/docker.sock -d '{"Image":"nginx"}' -H 'Content-Type: application/json' http://localhost/containers/create
```

And it says "curl: (7) Couldn't connect to server"

### Version

Colima Version: 0.5.4
Lima Version: 0.15.1
Qemu Version: 8.0.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/$USER/.colima/default/docker.sock

### Reproduction Steps

1. execute docker run with `-v $HOME/.colima/default/docker.sock:/var/run/docker.sock`
2. Inside the container, run `curl -XPOST --unix-socket /var/run/docker.sock -d '{"Image":"nginx"}' -H 'Content-Type: application/json' http://localhost/containers/create`
3. it says "curl: (7) Couldn't connect to server"

### Expected behaviour

It connects successfully

**Comment by abiosoft** [comment]
Hi, you should simply use `-v /var/run/docker.sock:/var/run/docker.sock`.

It needs the path to the docker socket in the underlying VM, not your host.
