### ISSUE TITLE
Colima terminate with std::bad_alloc

### ISSUE THREAD

**Issue by saussact** [abiosoft/colima#721]
### Description

When i am trying to build a docker image on "colima start -c 4 -m 8 -a x86_64"  

 => ERROR [build-stage 6/8] RUN npm install                                                                                                                                                                                        2.7s
------
 > [build-stage 6/8] RUN npm install:
#0 2.558 terminate called after throwing an instance of 'std::bad_alloc'
#0 2.559   what():  std::bad_alloc

### Version

Colima Version: 0.5.4
Lima Version: 0.15.1
Qemu Version: 8.0.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

╰─➤  colima status                    
INFO[0000] colima is running using QEMU                 
INFO[0000] arch: x86_64                                 
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] socket: unix:///Users/thibaultsaussac/.colima/default/docker.sock 

### Reproduction Steps

1.
2.
3.

**Comment by abiosoft** [comment]
Closing in favour of more active duplicate #723
