### ISSUE TITLE
Too many identity files specified ssh error

### ISSUE THREAD

**Issue by datajerk** [abiosoft/colima#735]
### Description

Support:

```
ssh:
  loadDotSSHPubKeys: false
```

See: https://github.com/lima-vm/lima/issues/1616

If I try to add this to lima.yaml it gets removed on colima start.

### Version

Colima Version: 0.5.5
Lima Version: 0.16.0
Qemu Version: 8.0.2

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Reproduction Steps

1.  Have over 100 ssh keys in .ssh
2.  colima start
3.  watch ssh never get setup

### Expected behaviour

By default do NOT scan .ssh for keys, should be explicitly defined.

**Comment by abiosoft** [comment]
This can actually be made the default behaviour.

**Comment by abiosoft** [comment]
This has been fixed and would be part of the next release.

You can try it now by using the development version `brew install --head colima`.
