### ISSUE TITLE
Upgrade default kubernetes version

### ISSUE THREAD

**Issue by aran** [abiosoft/colima#752]
### Description

By default colima sets up v1.24.3+k3s1. On a fresh install on an M1 Mac, colima with kubernetes did not work out of the box, as no node came online. With no other changes, just upgrading to v1.25.4+k3s1 made it work. (I didn't try newer 1.25.x releases).

**Comment by dfsdevops** [comment]
Yes, it is essentially broken out of the box with the current default version. It also works with 1.27 releases.

Seeing a lot of errors like this in the k3d logs on v1.24.3+k3s1

```
time="2023-08-04T22:17:37Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: --docker is no longer supported; to continue using docker, install cri-dockerd and set --container-runtime-endpoint"
```

**Comment by aran** [comment]
There is some way to get "stuck" based on some state in ~/.colima where new colima instances will use an old kubernetes version. But this problem has been fixed in a clean install on up-to-date colima.
