### ISSUE TITLE
How to set the docker server engine version?

### ISSUE THREAD

**Issue by astrolemonade** [abiosoft/colima#765]
### Description

How to set the docker server engine version that is provisioned by colima?
```
❯ docker version
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.6
 Git commit:        ced0996600
 Built:             Wed Jul 19 19:44:22 2023
 OS/Arch:           darwin/arm64
 Context:           colima

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri May 12 13:54:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```
I would like to upgrade the docker server engine to 24.0.5 as well.

### Version

Colima Version: 0.5.5
Lima Version: 0.17.0
Qemu Version: 8.0.3

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

❯ colima status
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/<omitted>/.colima/default/docker.sock

### Reproduction Steps

1.
2.
3.

**Comment by MrwanBaghdad** [comment]
We're facing some issue in addition to upgrading docker we'd like to upgrade buildkitd

**Comment by abiosoft** [comment]
The docker version is fixed and bundled as part of underlying iso with the primary reason being the ability to startup successfully without an internet connection.

You can actually add custom provision script by either modifying the template file `colima template` or `colima start --edit` and modifying the `provision` section of the script. That way, it runs on every startup.

**Comment by chulkilee** [comment]
^ what about adding this to README or somewhere in the doc?
