### ISSUE TITLE
When I try to run colima I keep getting error: FATA[0001] error starting vm: error at 'starting': exit status 1

### ISSUE THREAD

**Issue by ParasPandeyE** [abiosoft/colima#778]
### Description

I installed colima but when I try to run it I keep getting the following error:
colima start --vm-type qemu
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
INFO[0000] starting ...                                  context=vm
> [hostagent] Shutting down the host agent
> [hostagent] failed to exit SSH master
> [hostagent] Shutting down QEMU with ACPI
> [hostagent] failed to open the QMP socket "/Users/paraspandey/.lima/colima/qmp.sock", forcibly killing QEMU
> [hostagent] QEMU has already exited
> exiting, status={Running:false Degraded:false Exiting:true Errors:[] SSHLocalPort:0} (hint: see "/Users/paraspandey/.lima/colima/ha.stderr.log")
It would be great if anyone could help 

### Version

Colima Version: 0.5.5
Lima Version: 0.17.1
Qemu Version: 8.0.4

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

FATA[0000] colima is not running

### Reproduction Steps

1.colima start --vm-type qemu
2.
3.

**Comment by abiosoft** [comment]
This seems to be an issue with Qemu. https://github.com/lima-vm/lima/issues/1742.

Downgrading seems to work for now.

```
curl -OSL https://raw.githubusercontent.com/Homebrew/homebrew-core/dc0669eca9479e9eeb495397ba3a7480aaa45c2e/Formula/qemu.rb
brew install ./qemu.rb
```

**Comment by abiosoft** [comment]
As a side note, the next minor version `v0.6.0` would include bundled dependencies so issues like this would no longer arise.

**Comment by ParasPandeyE** [comment]
Thank you, @abiosoft downgrading worked for me

**Comment by yinshangwei** [comment]
> This seems to be an issue with latest Qemu update. [lima-vm/lima#1742](https://github.com/lima-vm/lima/issues/1742).
> 
> Downgrading seems to work for now.
> 
> ```
> curl -OSL https://raw.githubusercontent.com/Homebrew/homebrew-core/dc0669eca9479e9eeb495397ba3a7480aaa45c2e/Formula/qemu.rb
> brew install ./qemu.rb
> ```

Thanks. Downgrading qemu from 8.0.4 to 8.0.3 worked for me.
