### ISSUE TITLE
Colima can not run with arch x86_64

### ISSUE THREAD

**Issue by yuhao-postnl** [abiosoft/colima#800]
### Description

After using brew install colima, I can start using colima start, but when I want to use colima start --arch x86_64, it stuck for a while and exit (FATA[0600] error starting vm: error at 'creating and starting': exit status 1).

### Version

Colima Version: 0.5.5
Lima Version: 0.17.2
Qemu Version: 8.1.0

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/yuhao.dai/.colima/default/docker.sock
```

### Reproduction Steps

1. brew install colima
2. colima start --arch x86_64

### Additional context

I have already tried downgrading qemu to 8.0.4, which works for a few days. I reinstall colima today and tried to install qemu 8.0.4 following the steps in issue (https://github.com/abiosoft/colima/issues/787), but it cannot be installed again (see issue: https://github.com/dxtich/homebrew-core/issues/1). 

I am wondering is there any alternative way to start colima with arch of x86 maybe not using qemu?

**Comment by dagstuan** [comment]
I noticed the same thing yesterday. Qemu seems to struggle with starting an x86_64 VM. The contents of `serial.log` during startup seems to indicate that something takes too long.

```[   60.972677] rcu: INFO: rcu_preempt detected stalls on CPUs/tasks:
[   60.976187] rcu: 	0-...!: (0 ticks this GP) idle=0d58/0/0x0 softirq=44/44 fqs=0 (false positive?)
[   60.979262] 	(detected by 1, t=6005 jiffies, g=-1171, q=1981 ncpus=2)
[   60.982317] Sending NMI from CPU 1 to CPUs 0:
[   11.583693] NMI backtrace for cpu 0 skipped: idling at native_safe_halt+0xb/0x10
[   11.583693] INFO: NMI handler (nmi_cpu_backtrace_handler) took too long to run: 2.006 msecs
[   60.982317] rcu: rcu_preempt kthread timer wakeup didn't happen for 6004 jiffies! g-1171 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402
[   60.982317] rcu: 	Possible timer handling issue on cpu=0 timer-softirq=15
[   60.982317] rcu: rcu_preempt kthread starved for 6005 jiffies! g-1171 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402 ->cpu=0
[   60.982317] rcu: 	Unless rcu_preempt kthread gets sufficient CPU time, OOM is now expected behavior.
[   60.982317] rcu: RCU grace-period kthread stack dump:
[   60.982317] task:rcu_preempt     state:I stack:0     pid:15    ppid:2      flags:0x00004000
[   60.982317] Call Trace:```

[serial.log](https://github.com/abiosoft/colima/files/12519880/serial.log)

**Comment by yuhao-postnl** [comment]
> I noticed the same thing yesterday. Qemu seems to struggle with starting an x86_64 VM. The contents of `serial.log` during startup seems to indicate that something takes too long.
> 
> ```
> [   60.976187] rcu: 	0-...!: (0 ticks this GP) idle=0d58/0/0x0 softirq=44/44 fqs=0 (false positive?)
> [   60.979262] 	(detected by 1, t=6005 jiffies, g=-1171, q=1981 ncpus=2)
> [   60.982317] Sending NMI from CPU 1 to CPUs 0:
> [   11.583693] NMI backtrace for cpu 0 skipped: idling at native_safe_halt+0xb/0x10
> [   11.583693] INFO: NMI handler (nmi_cpu_backtrace_handler) took too long to run: 2.006 msecs
> [   60.982317] rcu: rcu_preempt kthread timer wakeup didn't happen for 6004 jiffies! g-1171 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402
> [   60.982317] rcu: 	Possible timer handling issue on cpu=0 timer-softirq=15
> [   60.982317] rcu: rcu_preempt kthread starved for 6005 jiffies! g-1171 f0x0 RCU_GP_WAIT_FQS(5) ->state=0x402 ->cpu=0
> [   60.982317] rcu: 	Unless rcu_preempt kthread gets sufficient CPU time, OOM is now expected behavior.
> [   60.982317] rcu: RCU grace-period kthread stack dump:
> [   60.982317] task:rcu_preempt     state:I stack:0     pid:15    ppid:2      flags:0x00004000
> [   60.982317] Call Trace:
> ```
> 
> [serial.log](https://github.com/abiosoft/colima/files/12519880/serial.log)

Maybe did you try the workaround solution at https://github.com/abiosoft/colima/issues/787? This workaround worked for me for several days. But yesterday, I could not install qemu 8.0.4 anymore. I am wondering if you also have the same issue.

**Comment by dagstuan** [comment]
@yuhao-postnl I did manage to downgrade to `8.0.4`, but i had to also downgrade `capstone` at the same time, since it has gone from 4 to 5. I successfully downgraded to qemu `8.0.4` with the following commands:

```curl https://raw.githubusercontent.com/Homebrew/homebrew-core/05d02418e00ef6e9af79018e3655536063f68ab2/Formula/q/qemu.rb -o qemu.rb
curl https://raw.githubusercontent.com/Homebrew/homebrew-core/442f9cc511ce6dfe75b96b2c83749d90dde914d2/Formula/c/capstone.rb -o capstone.rb
brew unlink qemu
brew install qemu.rb
brew unlink capstone
brew install capstone.rb```

After this, capstone should be at 4.0.2 and qemu should be at 8.0.4

**Comment by yuhao-postnl** [comment]
> @yuhao-postnl I did manage to downgrade to `8.0.4`, but i had to also downgrade `capstone` at the same time, since it has gone from 4 to 5. I successfully downgraded to qemu `8.0.4` with the following commands:
> 
> ```
> curl https://raw.githubusercontent.com/Homebrew/homebrew-core/05d02418e00ef6e9af79018e3655536063f68ab2/Formula/q/qemu.rb -o qemu.rb
> curl https://raw.githubusercontent.com/Homebrew/homebrew-core/442f9cc511ce6dfe75b96b2c83749d90dde914d2/Formula/c/capstone.rb -o capstone.rb
> brew unlink qemu
> brew install qemu.rb
> brew unlink capstone
> brew install capstone.rb
> ```
> 
> After this, capstone should be at 4.0.2 and qemu should be at 8.0.4

Thank you so much for the help, I really appreciate it! Have struggled two days on this problem!

**Comment by AkihiroSuda** [comment]
The patch is now cherry-picked to `qemu 8.1.0_3`
https://github.com/Homebrew/homebrew-core/pull/141489/commits/6f7d27ff99df995d97cdeb89f5114b1b7f9e36d7

**Comment by dagstuan** [comment]
Thank you @AkihiroSuda! `qemu 8.1.0_3` works fine on two arm-based machines here 👍
