### ISSUE TITLE
colima is not exposing IP address with option --network-address

### ISSUE THREAD

**Issue by devendrapratapsingh** [abiosoft/colima#801]
### Description

I am using M1 Mac pro and trying to create my multiple VMs. I am able to create the VMs but I am not able to expose IP address for all the VMs by using --network-address.

I have tried all the options but no luck. 
I have removed everything for colima like --vm-type vz and reinstall but no solution.

Please find the complete verbose logs of `colima start --network-address`

```
~ % colima start --very-verbose  --network-address
TRAC[0000] cmd ["limactl" "info"]                       
TRAC[0000] cmd ["limactl" "list" "colima" "--json"]     
TRAC[0000] error retrieving running instance: instance 'colima' does not exist 
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] preparing network ...                         context=vm
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "start" "default" "--vmnet" "--gvproxy" "--very-verbose"] 
TRAC[0000] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
TRAC[0001] cmd ["/opt/homebrew/bin/colima" "daemon" "status" "default"] 
INFO[0001] creating and starting ...                     context=vm
TRAC[0001] cmd ["limactl" "start" "--tty=false" "/var/folders/_0/0c57z9ts7hl3fc_t_qzdkfr00000gn/T/colima.yaml"] 
> Terminal is not available, proceeding without opening an editor
> "QEMU binary \"/Users/uniquenotion/.colima/_wrapper/3a9197e1ca3cd2da076da2b473d7a7eb118e2cca/bin/qemu-system-aarch64\" is not properly signed with the \"com.apple.security.hypervisor\" entitlement" error="binary \"/Users/uniquenotion/.colima/_wrapper/3a9197e1ca3cd2da076da2b473d7a7eb118e2cca/bin/qemu-system-aarch64\" seems signed but lacking the \"com.apple.security.hypervisor\" entitlement"
> You have to sign the QEMU binary with the "com.apple.security.hypervisor" entitlement manually. See https://github.com/lima-vm/lima/issues/1742 .
> "Attempting to download the image" arch=aarch64 digest="sha512:84c93e8aaa09446618bf87daa993e260da69b50e95670aed5df6671b2cff9464810752cbf70f6ee5ddf9d3e1c91d98104b3c573cc024c5f0687ad3f4d2e93ebc" location="https://github.com/abiosoft/alpine-lima/releases/download/colima-v0.5.5/alpine-lima-clm-3.18.0-aarch64.iso"
> Using cache "/Users/uniquenotion/Library/Caches/lima/download/by-url-sha256/bbac3cc01786365dbff7aa3e7c1dc2dcc8ee0aeacd6df51bce9840c8feeca75f/data"
> [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/uniquenotion/.lima/colima/serial*.log")
> SSH Local Port: 54896
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] Waiting for the essential requirement 1 of 5: "ssh"
> [hostagent] The essential requirement 1 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
> [hostagent] The essential requirement 2 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 3 of 5: "sshfs binary to be installed"
> [hostagent] The essential requirement 3 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 4 of 5: "/etc/fuse.conf (/etc/fuse3.conf) to contain \"user_allow_other\""
> [hostagent] The essential requirement 4 of 5 is satisfied
> [hostagent] Waiting for the essential requirement 5 of 5: "the guest agent to be running"
> [hostagent] The essential requirement 5 of 5 is satisfied
> [hostagent] Mounting "/Users/uniquenotion" on "/Users/uniquenotion"
> [hostagent] Mounting "/tmp/colima" on "/tmp/colima"
> [hostagent] Waiting for the final requirement 1 of 1: "boot scripts must have finished"
> [hostagent] Forwarding "/var/run/docker.sock" (guest) to "/Users/uniquenotion/.colima/default/docker.sock" (host)
> [hostagent] The final requirement 1 of 1 is satisfied
> READY. Run `limactl shell colima` to open the shell.
TRAC[0053] cmd ["lima" "sudo" "cat" "/etc/hosts"]       
TRAC[0053] cmd ["lima" "sudo" "sh" "-c" "echo -e \"192.168.5.2\\thost.docker.internal\" >> /etc/hosts"] 
TRAC[0053] cmd ["lima" "sudo" "cat" "/etc/hosts"]       
TRAC[0053] cmd ["lima" "sudo" "sh" "-c" "echo -e \"127.0.0.1\\tcolima\" >> /etc/hosts"] 
INFO[0053] provisioning ...                              context=docker
TRAC[0053] cmd ["lima" "sudo" "mkdir" "-p" "/etc/docker"] 
TRAC[0053] cmd int ["lima" "sudo" "sh" "-c" "cat > /etc/docker/daemon.json"] 
TRAC[0053] cmd ["docker" "context" "inspect" "colima"]  
TRAC[0053] cmd ["docker" "context" "create" "colima" "--description" "colima" "--docker" "host=unix:///Users/uniquenotion/.colima/default/docker.sock"] 
> colima
> Successfully created context "colima"
TRAC[0054] cmd ["docker" "context" "use" "colima"]      
> colima
> Current context is now "colima"
INFO[0054] starting ...                                  context=docker
TRAC[0054] cmd ["lima" "sudo" "service" "docker" "start"] 
>  * /var/log/docker.log: creating file
>  * /var/log/docker.log: correcting owner
>  * Starting Docker Daemon ... [ ok ]
TRAC[0054] cmd ["lima" "sudo" "docker" "info"]          
TRAC[0059] cmd ["lima" "sudo" "docker" "info"]          
TRAC[0059] cmd ["lima" "sudo" "cat" "/etc/colima/colima.json"] 
TRAC[0059] cmd ["lima" "sudo" "mkdir" "-p" "/etc/colima"] 
TRAC[0059] cmd ["lima" "sudo" "mkdir" "-p" "/etc/colima"] 
TRAC[0059] cmd int ["lima" "sudo" "sh" "-c" "cat > /etc/colima/colima.json"] 
TRAC[0059] cmd ["lima" "sudo" "cat" "/etc/colima/colima.json"] 
TRAC[0059] cmd ["lima" "sudo" "mkdir" "-p" "/etc/colima"] 
TRAC[0059] cmd ["lima" "sudo" "mkdir" "-p" "/etc/colima"] 
TRAC[0059] cmd int ["lima" "sudo" "sh" "-c" "cat > /etc/colima/colima.json"] 
INFO[0059] done                                         
TRAC[0059] cmd ["limactl" "list" "--json"]              
TRAC[0059] cmd ["limactl" "shell" "colima" "sh" "-c" "ifconfig col0 | grep \"inet addr:\" | awk -F' ' '{print $2}' | awk -F':' '{print $2}'"] 
TRAC[0059] cmd ["limactl" "show-ssh" "--format" "config" "colima"] 
TRAC[0059] cmd ["limactl" "list" "colima" "--json"]     
TRAC[0059] cmd ["limactl" "shell" "colima" "sh" "-c" "ifconfig col0 | grep \"inet addr:\" | awk -F' ' '{print $2}' | awk -F':' '{print $2}'"] 
```

Verify command : `colima list`

```~ % colima list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    aarch64    2       2GiB      60GiB    docker     
```

### Version

Colima Version: 0.5.5
Lima Version: 0.17.2
Qemu Version: 8.1.0_2

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [x] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using QEMU                 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: sshfs                             
INFO[0000] address:                                     
INFO[0000] socket: unix:///Users/uniquenotion/.colima/default/docker.sock 

### Reproduction Steps

1.brew install colima
2.colima start --network-address
3.colima list

### Expected behaviour

```
colima list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    aarch64    2       2GiB      60GiB    docker        192.168.5.12
```

### Additional context

It worked only once in January,2023 but after that I have tried so many times but never worked. I really need this to work on m1 mac pro. Please provide the clear steps to fix this problem not exposing IP address

**Comment by devendrapratapsingh** [comment]
I found some additional error in DHCP lease in ~/.lima/colima/serial*.log: 
udhcpc: broadcasting discover
udhcpc: broadcasting select for 192.168.5.15, server 192.168.5.2
udhcpc: lease of 192.168.5.15 obtained from 192.168.5.2, lease time 86400
 [ ok ]
 *   col0 ...udhcpc: started, v1.36.0
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
udhcpc: broadcasting discover
```
udhcpc failed to get a DHCP lease
udhcpc: no lease, forking to background
```

**Comment by devendrapratapsingh** [comment]
I fixed my problem by disabling ipv6 in colima VM.

steps to fix:

1. colima start (without exposing IP address)
2. colima ssh
3. sysctl -w net.ipv6.conf.all.disable_ipv6=1
4. coilima start --network-address

I got expected behavior of colima list
colima list                   
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    aarch64    2       2GiB      60GiB    docker     192.168.106.2

**Comment by pablodaniel03** [comment]
> I fixed my problem by disabling ipv6 in colima VM.
> 
> steps to fix:
> 
> 1. colima start (without exposing IP address)
> 2. colima ssh
> 3. sysctl -w net.ipv6.conf.all.disable_ipv6=1
> 4. coilima start --network-address
> 
> I got expected behavior of colima list colima list PROFILE STATUS ARCH CPUS MEMORY DISK RUNTIME ADDRESS default Running aarch64 2 2GiB 60GiB docker 192.168.106.2

Hello! I am facing same issues. I could access to my containers and then I simply could not access to the exposed ports. Noticed this column in the `colima ls` command output was empty and found your comment. Followed your steps but it is not working for me:

* Colima Start Command:

``` bash
colima start --cpu 8 --memory 12 --arch x86_64 --vm-type=vz --network-address
```

```
~ % colima list
PROFILE    STATUS     ARCH      CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    x86_64    8       12GiB     60GiB    docker     
```

**Comment by guenichone** [comment]
I did it and it's not working. 

> steps to fix:
> 
> 1. colima start (without exposing IP address)
> 2. colima ssh
> 3. sysctl -w net.ipv6.conf.all.disable_ipv6=1
> 4. coilima start --network-address

Still no network address, I'm on macos 14.1 (23B2073)

**Comment by pablodaniel03** [comment]
> I did it and it's not working.
> 
> > steps to fix:
> > ...
> 
> Still no network address, I'm on macos 14.1 (23B2073)

@guenichone, I could fix it by deleting the colima vm and create a new one but using the `--profile` flag.

``` bash
colima stop
colima delete
colima start --profile x86_64 --cpu 8 --memory 12 --arch x86_64 --vm-type=vz --network-address
```

You must add the `--profile x86_64` flag to each colima command you want to execute and the `ADDESS` column still blank but now I can access to my containers. I think this can also work if you delete the VM and then remove manually the `colima.sock` file.

**Comment by Zordid** [comment]
Also getting really really disappointed with this issue. I cannot reach my docker forwarded ports and I also see that no address is shown in `colima list`. I have tried the described steps here, although I must admit I do not really understand the order and why you start colima, ssh into it and THEN start colima again (a second time?) - is this really what you do, @devendrapratapsingh ?

**Comment by Zordid** [comment]
> > I did it and it's not working.
> > > steps to fix:
> > > ...
> > 
> > 
> > Still no network address, I'm on macos 14.1 (23B2073)
> 
> @guenichone, I could fix it by deleting the colima vm and create a new one but using the `--profile` flag.
> 
> ```shell
> colima stop
> colima delete
> colima start --profile x86_64 --cpu 8 --memory 12 --arch x86_64 --vm-type=vz --network-address
> ```
> 
> You must add the `--profile x86_64` flag to each colima command you want to execute and the `ADDESS` column still blank but now I can access to my containers. I think this can also work if you delete the VM and then remove manually the `colima.sock` file.

What does using a profile have to do with this issue? Isnt't this just a different name than default?

**Comment by JackieTreeh0rn** [comment]
same issue when emulating x86_64 on M1 Mac.  disabling IPv6 has not helped.

**Comment by thezanke** [comment]
> I can confirm that using ` --profile` instead of `--arch` works, the address is listed as well under `colima list`
> 
> ie: `colima start --profile x86_64 --vm-type=vz --vz-rosetta --cpu 8 --memory 8 --disk 10 --network-address`

Having tried this, I think all this has done is name the profile "x86_64" but dropped the actual x86_64 architecture emulation that you were getting from using `--arch`.

**Comment by drobert** [comment]
> I can confirm that using ` --profile` instead of `--arch` works, the address is listed as well under `colima list`
> 
> ie: `colima start --profile x86_64 --vm-type=vz --vz-rosetta --cpu 8 --memory 8 --disk 10 --network-address`

I can confirm that this does *not* work for me on apple silicon m2 in Sonoma 14.7.5. I still have nothing listed in `network`. Using colima version 0.8.1 from `brew`
