### ISSUE TITLE
VM time getting out of sync

### ISSUE THREAD

**Issue by chrisdostert** [abiosoft/colima#82]
Hello, thanks for the awesome project! 

I'm running into an issue where if the machine goes to sleep, when it wakes up the VM time will be quite out of sync, leading to things relying on accurate time such as access tokens expiration failing.

**Comment by jandubois** [comment]
This is a Lima issue that is being tracked at https://github.com/lima-vm/lima/issues/355

**Comment by abiosoft** [comment]
This should be fixed now with https://github.com/lima-vm/lima/pull/490 merged.
