### ISSUE TITLE
Lima upgrade breaks DNS on existing VMs

### ISSUE THREAD

**Issue by aaronlehmann** [abiosoft/colima#827]
### Description

When I upgrade lima from 0.17.2 to `HEAD-de1b3ee`, DNS stops working with existing VMs. I had to delete and recreate my VM for DNS to work at all.

I originally filed https://github.com/lima-vm/lima/issues/1783, but was told this looks like a colima-specific problem.

### Version

Colima Version: 0.5.5 (6251dc2c2c5d8197c356f0e402ad028945f0e830)
Lima Version: 1.17.2 -> HEAD
Qemu Version: 8.1.1

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [X] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [ ] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/alehmann/.colima/default/docker.sock

### Reproduction Steps

```
➜  ~ colima delete
are you sure you want to delete colima and all settings? [y/N] y
INFO[0001] deleting colima
INFO[0001] done
➜  ~ brew uninstall --ignore-dependencies lima
Uninstalling /opt/homebrew/Cellar/lima/HEAD-de1b3ee... (111 files, 169.3MB)
lima 0.17.2 is still installed.
To remove all versions, run:
  brew uninstall --force lima
➜  ~ brew link lima
Linking /opt/homebrew/Cellar/lima/0.17.2... 43 symlinks created.
➜  ~ lima -v
limactl version 0.17.2
➜  ~ colima start
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] creating and starting ...                     context=vm
INFO[0021] provisioning ...                              context=docker
INFO[0021] starting ...                                  context=docker
INFO[0026] done
➜  ~ docker run -ti --rm alpine ping google.com
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
9fda8d8052c6: Pull complete
Digest: sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a
Status: Downloaded newer image for alpine:latest
PING google.com (142.251.214.142): 56 data bytes
64 bytes from 142.251.214.142: seq=0 ttl=63 time=0.760 ms
64 bytes from 142.251.214.142: seq=1 ttl=63 time=0.980 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.760/0.870/0.980 ms
➜  ~ colima stop
INFO[0000] stopping colima
INFO[0000] stopping ...                                  context=docker
INFO[0001] stopping ...                                  context=vm
INFO[0004] done
➜  ~ brew unlink lima
Unlinking /opt/homebrew/Cellar/lima/0.17.2... 43 symlinks removed.
➜  ~ brew install --head lima
[...]
➜  ~ lima -v
limactl version HEAD-572b94a
➜  ~ docker run -ti --rm alpine ping google.com
ping: bad address 'google.com'
```

### Expected behaviour

Lima upgrades shouldn't require starting from scratch with a new VM.

**Comment by AkihiroSuda** [comment]
Should have been solved in:
- https://github.com/lima-vm/lima/pull/1898

**Comment by aaronlehmann** [comment]
@AkihiroSuda: This does appear to have fixed the problem. Thank you so much!
