### ISSUE TITLE
Detect when running under colima/lima (as opposed to Docker Desktop)

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#84]
I'm the maintainer of [ddev](https://github.com/drud/ddev) and looking at how to make ddev on top of colima fully functional. https://github.com/drud/ddev/issues/3208

One thing I probably have to do is detect when running on top of colima/lima as opposed to Docker Desktop. 

Any suggestions how I could detect that? I know how to detect when running on Gitpod, or WSL2, etc....

For example, right now since `host.docker.internal` is not available (but `host.lima.internal` is available) (https://github.com/lima-vm/lima/issues/456) I could just detect the situation and provide `host.docker.internal` anyway, based on `host.lima.internal` or whatever.

**Comment by abiosoft** [comment]
@rfay How is the check happening? Is it in a running container or via the docker client. If via the docker client the docker context will always be prefixed with `colima`.

```
docker info --format '{{.ClientInfo.Context}}'
```

**Comment by rfay** [comment]
Excellent, thanks! I'll use the info api, of course that's the right way.

**Comment by abiosoft** [comment]
@rfay kindly test with the development version `brew install --head colima`. It is far ahead of the current release and the next release is imminent.
