### ISSUE TITLE
colima should respect "~" in ssh config

### ISSUE THREAD

**Issue by cohml** [abiosoft/colima#840]
### Description

When `colima` starts up, it seems to check for the following line in `~/.ssh/config`:

```
Include /Users/<username>/.colima/ssh_config
```

If it doesn't find it, it adds it. If it does, no change is made.

However, if the path is already in the file with a `~`, i.e.,

```
Include ~/.colima/ssh_config
```

then `colima` fails to recognize it and adds a redundant entry.

This is unfortunate, because ssh config *does* respect `~`. Here is the relevant excerpt from [the ssh config man page](https://man7.org/linux/man-pages/man5/ssh_config.5.html):

> **Include**
>> Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may contain glob(7) wildcards and, for user configurations, shell-like ‘~’ references to user home directories.

By not respecting this flexibility, `colima` effectively forces users to hard code paths into their configs without painful workarounds such as aliases with `--ssh-config=false` baked in.

**Comment by abiosoft** [comment]
Thanks for reporting this.

**Comment by cohml** [comment]
Thank *you* for patching it so quickly!
