### ISSUE TITLE
Consider creating Nix Derivation

### ISSUE THREAD

**Issue by gsebil08** [abiosoft/colima#85]
Hi!

First of all, thanks for this great alternative to `docker` (especially with the new docker pricing on macOS!), this is working great (for my basic use case)! 🙏🏻 

Thanks to `nix` in my actual project I provide `docker` and `docker-compose` to avoid installing `Docker desktop` on our mac laptops, but we still need to `brew install colima`. It would be great to also provide `colima` in our `nix-shell`!

I tried _(and looks like for my basic `docker-compose.yaml` it is working great)_ to create by myself the derivation (on my laptop).

Hence, I am wondering if you already consider creating a `nix derivation` to make `colima` available on `nixpkgs`?

Thanks again!

**Comment by abiosoft** [comment]
@gsebil08 Thanks for the kind words and glad it works for you.

I actually do not know much about Nix and if I may ask, what does Nix offer? 

Is this in anyway related to what you're looking for https://github.com/abiosoft/colima/issues/79? 

And if you do know how to go about it, contributions are always welcome.

**Comment by dhess** [comment]
@gsebil08 I created a derivation that we use. I keep this reasonably up to date:

https://github.com/hackworthltd/hacknix/blob/main/nix/pkgs/colima/default.nix

However, IMO, you should probably make a packaging request on nixpkgs, rather than here.

**Comment by gsebil08** [comment]
@dhess thanks for the answer, I got something more "basic" on my side. It looks like I am not the only one who would like to have such a thing 😄.

@abiosoft Quickly, [Nix](https://github.com/NixOS/nixpkgs) is a "package manager" (Serokell recently published this interesting [article](https://serokell.io/blog/what-is-nix)).
On my side, I _just_ provide a `nix-shell` (which is just an other shell) with all necessary tools (`docker`, `stack`, `fluxctl`, `jmeter`, etc.) and allow every newcomer or new contributor to easily (only need to install `nix`) have a _perfectly working and ready_ work environment.

@dhess From my point of view, I think it is more accurate/reliable to ask to the current author/owner of a library to manage the nix part. Like that, when a new release is published, they can create the request on nixpkgs instead of relying on _fans_ like us 😄

@abiosoft I would be honored to help you to create the initial package on Nix! But my knowledges are really limited since I am a "basic user" of both `colima` and `nix` I do not feel legitimate to do it.

In a first time, I can provide you a sandbox repository, in which one `nix` and the `colima` package will be available (and of course with documentation to explain), this will allow you to test if everything is working well (because I only have a basic usage).
Then if you validate this, we could see together to create the packaging request/suggestion on nixpkgs.

Anyway, thanks for your quick answer, I really appreciate!

**Comment by abiosoft** [comment]
I guess this is now fixed with https://github.com/abiosoft/colima/pull/89.
