### ISSUE TITLE
Crash with rosetta in 0.6.0 (regression from 0.5.6)

### ISSUE THREAD

**Issue by lejoko** [abiosoft/colima#855]
### Description

Crash in Rosetta when running official mysql:5.7 image:

```
$ docker run -it --rm mysql:5.7
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
rosetta error: unhandled auxillary vector type 28
$
```

### Version

Colima Version: 0.6.0
Lima Version: 0.18.0
Qemu Version: 8.1.2

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
$ colima status -p rosetta
INFO[0000] colima [profile=rosetta] is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/joel/.colima/rosetta/docker.sock 
$ cat ~/.colima/rosetta/colima.yaml |grep -v "^ *#\|^ *$"
cpu: 8
disk: 60
memory: 8
arch: aarch64
runtime: docker
hostname: colima
kubernetes:
  enabled: false
  version: v1.28.3+k3s2
  k3sArgs:
    - --disable=traefik
autoActivate: true
network:
  address: false
  dns: []
  dnsHosts: {}
forwardAgent: false
docker: {}
vmType: vz
rosetta: true
mountType: virtiofs
mountInotify: true
cpuType: ""
provision: []
sshConfig: true
mounts: []
env: {}
$
```

### Reproduction Steps

1. Start colima with rosetta activated (as per described config)
2. run `docker run -it --rm mysql:5.7`
3. observe rosetta crashing

### Expected behaviour

A running mysql 5.7 container

### Additional context

It used to work in Colima 0.5.6

**Comment by lejoko** [comment]
Tested with (just upgraded) Colima 0.6.1 in the same conditions as above and nothing changed.

**Comment by abiosoft** [comment]
This actually worked for me.

```
docker run -it --rm --platform linux/amd64 mysql:5.7
```

**Comment by lejoko** [comment]
I'm on a M2 MacBook Pro With Ventura 13.6.2, all updates applied to both system and brew. Are you maybe on Sonoma ? I was reluctant to upgrade to Sonoma...

**Comment by abiosoft** [comment]
@lejoko ideally you should specify the `--platform linux/amd64` flag.

**Comment by abiosoft** [comment]
Sonoma 14.1 on an m1 mac mini.

**Comment by tmapes** [comment]
I ran into this on a different image (but could actually run mysql:5.7 fine).

Seems like it was fixed by Apple in 14.1

**Comment by lejoko** [comment]
Apparently it also works for me with Sonoma 14.1.1. That specific problem seem to exist only with Ventura. I'm currently testing other potentially problematic images.

By the way, big thanks for Colima!!

**Comment by lejoko** [comment]
Ok. Everything related to Colima works for me with Sonoma 14.1.1 (I still have crashes with rosetta but they're not related to Colima)

**Comment by Curtisjk** [comment]
I came across this issue today with colima 0.6.7 and Ventura 13.6.3, so is definitely not fixed.

Does anyone know how to apply a workaround?

**Comment by yous** [comment]
Direct use of lima doesn't have this issue in Ventura.
