### ISSUE TITLE
192.168.5.2 was always the published IP address to reach the host, now changed

### ISSUE THREAD

**Issue by rfay** [abiosoft/colima#857]
### Description

For the history of colima, the IP address in the container to reach services on the host was 192.168.5.2, and `host.docker.internal` DNS address was not set by colima.

In v0.6.*, the IP address seems to be 192.168.104.2 by default, and `host.docker.internal` can in fact be looked up.

Was this intentional? It does break xdebug on DDEV because due to Colima not setting it in the past, DDEV used a static value (192.168.5.2) for `host.docker.internal`. 

Related: 
* https://github.com/abiosoft/colima/issues/698 ?

### Version

Colima Version: 0.6.1
Lima Version: 0.18.0
Qemu Version:

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/rfay/.colima/default/docker.sock
```

### Reproduction Steps

Run an image with ping or nslookup in it. `ping host.docker.internal`

### Expected behaviour

Fixed IP address of 192.168.5.2 for the host value

### Additional context

Provisional DDEV workaround is `ddev config global --xdebug-ide-location=192.168.104.2`, at least if `docker run -it --rm ddev/ddev-webserver:v1.22.4 ping host.docker.internal` shows 192.168.104.2

**Comment by rfay** [comment]
I note that the lima docs still quote it as 192.168.5.2: https://lima-vm.io/docs/config/network/#host-ip-19216852

**Comment by balajiv113** [comment]
@rfay document is bit outdated will update it
https://github.com/lima-vm/lima/blob/master/pkg/networks/networks.TEMPLATE.yaml#L27

192.168.104.2 is the default in user-v2. But you can always change the gateway value in <lima_home>_config/networks.yaml

**Comment by rfay** [comment]
DDEV uses colima OOTB without asking people to make configuration changes, and certainly not in the Lima config.

**Comment by rfay** [comment]
A key thing now though is that `host.docker.internal` is now resolvable in Colima containers.  That's great... but when and how was that added? We can just stop using a wired-in IP address.

**Comment by abiosoft** [comment]
@balajiv113 I did confirm that changing the gateway value works as expected.

Will push out a new release as this can be an undesired breaking change for some.

**Comment by abiosoft** [comment]
> DDEV uses colima OOTB without asking people to make configuration changes, and certainly not in the Lima config.

@rfay they wouldn't need to do this. It will be handled by Colima.

**Comment by abiosoft** [comment]
Released https://github.com/abiosoft/colima/releases/tag/v0.6.2.
