### ISSUE TITLE
Error caching dependencies on colima start

### ISSUE THREAD

**Issue by rpkoller** [abiosoft/colima#859]
### Description

I ran into something really odd. I am using colima 0.6.1 on macos sonoma 14.1.1 with vz and virtiofs no a m1pro. i was testing the functionality of xdebug in ddev since someone in a slack channel ran into some issues. i tried if it is reproducible. but i ran into the same issue (@rfay already opened an issue for that problem https://github.com/abiosoft/colima/issues/857). but the problem was vscode and ddev were acting odd so i did a `ddev poweroff`to shut it down and did a `colima stop`afterwards to make sure everything was switched off and i could start clean for the next try. problem is. on `colima start`i ran into the following error i never saw before:  

```
$> colima start
INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0001] starting ...                                  context=vm
WARN[0004] error caching dependencies: %w error retrieving OS version from vm: error running [lima sh -c grep "^UBUNTU_CODENAME" /etc/os-release | cut -d= -f2], output: "", err: "exit status 255"  context=vm
WARN[0004] falling back to normal package install error retrieving OS version from vm: error running [lima sh -c grep "^UBUNTU_CODENAME" /etc/os-release | cut -d= -f2], output: "", err: "exit status 255"  context=vm
FATA[0004] error starting vm: error at 'starting': exit status 255 
```

the odd thing i was a bit absent minded, i wanted to do another `colima start`and see if i am able to start up properly (cuz i assumed colima hasnt started yet). but instead i types `ddev start`and the odd thing was the project started up without any complaints. also colima status showed nothing off: 

```
$> colima status
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/rkoller/.colima/default/docker.sock 
```

after that i was also able to stop the project properly and i was also able to start up colima another time without the error caching dependencies. i have not idea how to reproduce it (except give xdebug in ddev another try). but i just wanted to put the error on the radar in case it is something new and unknown. 

### Version

Colima Version: 0.6.1
Lima Version: limactl version 0.18.0
Qemu Version: QEMU emulator version 8.1.2

### Operating System

- [ ] macOS Intel <= 12 (Monterrey)
- [ ] macOS Intel >= 13 (Ventura)
- [ ] macOS M1 <= 12 (Monterrey)
- [X] macOS M1 >= 13 (Ventura)
- [ ] Linux

### Output of `colima status`

```
$> colima status
INFO[0000] colima is running using macOS Virtualization.Framework 
INFO[0000] arch: aarch64                                
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/rkoller/.colima/default/docker.sock 
```

### Reproduction Steps

1. run `colima start`
but as i already pointed out in the issue summary i have no idea how to reproduce the error yet. :(

**Comment by abiosoft** [comment]
Thanks for reporting. While the error message does not show it, there was indeed a bug here.

What happens is that some extra Ubuntu packages are needed. Instead of installing it normally, Colima downloads the `.deb` files to a local cache folder instead, then installs the `.deb` files manually afterwards. 

This ensures the files are not re-downloaded after a `colima delete`.

If the caching process fails somehow, it will fallback to the standard `apt install packages...` way of installing Ubuntu packages using the internet. 

In your case, the fallback option also failed (due to a bug).

**Comment by rpkoller** [comment]
awesome! thanks for the explanation and the fast fix!
