### ISSUE TITLE
Unable to start colima because of SHA validation

### ISSUE THREAD

**Issue by alefwd** [abiosoft/colima#868]
### Description

I'm unable to start colima (colima start) as it's failing to download binfmt. The part I don't understand is that colima is 0.6.2 but the path is _colima-core/releases/download/v0.6.0-2_

Error:
FATA[0029] error starting vm: error at 'creating and starting': error downloading binfmt: error downloading 'https://github.com/abiosoft/colima-core/releases/download/v0.6.0-2/binfmt-arm64.tar.gz': error validating SHA sum for 'binfmt.tar.gz': exit status 1 

### Version

colima version 0.6.2
git commit: 22d7e5fbc86d5b8e3b27065a762800bc7960a0ff
limactl version 0.18.0
qemu-img version 8.1.2
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] error retrieving current runtime: empty value 

### Reproduction Steps

1. Install colima with brew
2. Start it up with colima start

### Expected behaviour

It starts. Until last week it started no problems

### Additional context

I tried to uninstall colima and lima with brew, force stop it, and remove the ~/.colima and ~/.lima folder, and reinstall it but it doesn't help.

**Comment by abiosoft** [comment]
Can you clear the cache directory and try again?

```
rm -rf ~/Library/Caches/colima
```

Thanks for reporting.

**Comment by abiosoft** [comment]
It's actually not a hard requirement. It is only for running x86 containers on m1.

It can be modified to print a warning message instead.

**Comment by abiosoft** [comment]
Can you do a `brew install --head colima` and try again?

**Comment by khaxis** [comment]
something stupid like rebooting helped me. I still see the error, but docker is running

**Comment by abiosoft** [comment]
This should be fixed in v0.6.7.
