### ISSUE TITLE
kubectl port-forward fails in 0.6.x

### ISSUE THREAD

**Issue by ventsislav-georgiev** [abiosoft/colima#869]
### Description

Same as before: https://github.com/abiosoft/colima/issues/170
It seems the new ubuntu image doesn't have socat.

Here is the repro:
<img width="1511" alt="image" src="https://github.com/abiosoft/colima/assets/5616486/1dac33e3-62cd-4f2b-9d0e-fdb4e1435fc0">

### Version

v0.6.1

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

**Comment by abiosoft** [comment]
In the meantime, you can install socat manually.

```
colima ssh -- sudo apt install -y socat
```

**Comment by abiosoft** [comment]
Can you try with the current development version?

```
brew install --HEAD colima
```
