### ISSUE TITLE
FATA[0026] error starting vm: error at 'creating and starting': error downloading binfmt - error retrieving redirect url

### ISSUE THREAD

**Issue by lexsoft00** [abiosoft/colima#880]
### Description

I've started getting this error after upgrading to 0.6 with brew whenever I do a colima start.

```
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0000] preparing network ...                         context=vm
INFO[0000] creating and starting ...                     context=vm
FATA[0026] error starting vm: error at 'creating and starting': error downloading binfmt: error downloading 'https://github.com/abiosoft/colima-core/releases/download/v0.6.0-2/binfmt-arm64.tar.gz': error retrieving redirect url: error running [curl -Ls -o /dev/null -w %{url_effective} https://github.com/abiosoft/colima-core/releases/download/v0.6.0-2/binfmt-arm64.tar.gz], output: "", err: "exit status 60"
```

### Version

```
╰─ colima version && limactl --version && qemu-img --version                                                              ─╯
colima version 0.6.2
git commit: 22d7e5fbc86d5b8e3b27065a762800bc7960a0ff
limactl version 0.18.0
qemu-img version 8.1.2
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
╰─ colima status                                                                                                          ─╯
FATA[0000] error retrieving current runtime: empty value
```

### Reproduction Steps

1. Upgrade to /opt/homebrew/Cellar/colima/0.6.2
2. colima delete
3. colima start --cpu 6 --memory 12 --disk 100 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1
4. colima stop
5. colima start

**Comment by vbhosle** [comment]
Same issue with MacOS(12.6.8) + Intel 
❯ colima version && limactl --version && qemu-img --version
colima version 0.6.2
git commit: 22d7e5fbc86d5b8e3b27065a762800bc7960a0ff

limactl version 0.18.0
qemu-img version 8.1.2

**Comment by lexsoft00** [comment]
Upgrade and re-install fix it for me with the guide from here https://github.com/abiosoft/colima/issues/888#issuecomment-1822702581

`colima delete && colima prune`

**Comment by abiosoft** [comment]
This should be fixed in v0.6.7

**Comment by hugo-HDSF** [comment]
do you know when you will be pushing the new colima.rb for version 0.6.7 to brew ? because right now, the install pull 0.6.6 ... and this version isn't stable.

**Comment by abiosoft** [comment]
> do you know when you will be pushing the new colima.rb for version 0.6.7 to brew ? because right now, the install pull 0.6.6 ... and this version isn't stable.

v0.6.7 is now available on brew.
