### ISSUE TITLE
`docker ps`  does not work after `colima start`

### ISSUE THREAD

**Issue by eva-mueller-coremedia** [abiosoft/colima#9]
### Setup

Following the README.md and, I did the following

* Stop Docker Desktop for Mac
* `brew install lima docker kubectl`
* `curl -LO https://raw.githubusercontent.com/abiosoft/colima/v0.1.7/colima && sudo install colima /usr/local/bin/colima`

### Problem
As suggested in the gif for the minimal setup, I tried

`docker ps` => Results in `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
`colima start`
```
[colima] 11:12:52 creating and starting VM ...
[colima] 11:13:34 provisioning VM ...
[colima] 11:13:34 provisioning docker ...
[colima] 11:13:34 provisioning docker in VM ...
[colima] 11:13:56 restarting VM to complete docker setup ...
[colima] 11:14:27 VM restarted
[colima] 11:14:27 starting docker ...
[colima] 11:14:28 docker startup successful
[colima] 11:14:28 done
```

⚠️ `docker ps` => But this also results in `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

### Am I missing something?

# Further information
## `colima status`

```
docker is installed VM?
success

docker is running in VM?
success

docker is installed on Host?
success

docker client on host can access the VM server?
error

[...]

some checks failed :(
```

## `~/.colima/out.log`
```
Linux
/usr/bin/docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-09-16 09:14:17 UTC; 3min 53s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 751 (dockerd)
      Tasks: 10
     Memory: 129.7M
     CGroup: /system.slice/docker.service
             └─751 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
/usr/local/bin/docker
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
exit status 1
bash: line 1: minikube: command not found
exit status 127

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

## `kubectl cluster-info dump`
> The connection to the server localhost:8080 was refused - did you specify the right host or port?

## `/var/run/docker.sock` symlinks

```
ll /var/run/docker.sock

/var/run/docker.sock
lrwxr-xr-x 1 root 35 Sep 16 11:00 /var/run/docker.sock -> ~/.colima/docker.sock

ls -al ~/.colima
~/.colima
total 8
drwxr-xr-x   4 emueller  128 Sep 16 11:14 .
drwxr-xr-x+ 61 emueller 1952 Sep 16 11:13 ..
-rw-r--r--   1 emueller 1163 Sep 16 11:18 out.log
-rwxr-xr-x   1 emueller  217 Sep 16 11:14 socket.sh
```

⚠️ There is no `~/.colima/docker.sock`

### My Mac config
<img width="271" alt="Screenshot 2021-09-16 at 11 03 14" src="https://user-images.githubusercontent.com/14927927/133583758-53b9486f-ca06-4a3c-8f1d-bd455ed09f40.png">

**Comment by abiosoft** [comment]
Sorry. Do you mind doing a `colima delete` and `colima start`. And kindly update to v0.1.7.

This is strange.

**Comment by eva-mueller-coremedia** [comment]
sorry, i already had v0.1.7 installed... (updated the description) 
I did `colima delete` & `colima start` but still the same issue. 😢

**Comment by abiosoft** [comment]
sorry for the back and forth. Can you downgrade to v0.1.5 and see if the behaviour is same.

I just released 0.1.7 to supposedly fix this same issue.

**Comment by abiosoft** [comment]
I am unable to reproduce this.

Can you kindly do the following
* verify the contents of `ls ~Library/LaunchAgents` after a successful `colima start`? There should a plist file for colima.
* what does `ps aux | grep 'ssh -p'` give you?
* ensure Docker for Mac is not running.

**Comment by eva-mueller-coremedia** [comment]
✅ ensure Docker for Mac is not running
✅ verify you're running the right version with `colima version`: 0.1.7
✅ `ls ~/Library/LaunchAgents`after `colima start` results in 
```
com.abiosoft.colima.plist  [...]
```
✅ `ps aux | grep 'ssh -p 41122'` results in 
```
USER         52095   0.0  0.0  4417912    868 s004  S+   12:29PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox ssh -p 41122
```

Could you do me a favor and post a list of your used tools? Mine are
* lima: stable 0.6.4 (bottled)
* qemu: stable 6.1.0 (bottled), HEAD
* docker: stable 20.10.8 (bottled), HEAD
* kubernetes-cli: stable 1.22.1 (bottled), HEAD
* GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
* minikube: stable 1.23.0 (bottled), HEAD
* zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by abiosoft** [comment]
okay, I've seen the problem is that the socket forwarding process is failing to start. Either something else is using the port or the launchd is failing.

What does running this give you ?
```
lsof -nP -iTCP:"41122" | grep LISTEN
```

If (and only if) the above does not give an output, then do this. ​
```
ssh -p 41122 -i $HOME/.lima/_config/user -o NoHostAuthenticationForLocalhost=yes -L $HOME/.colima/docker.sock:/var/run/docker.sock -N 127.0.0.1 &
docker version
```

**Comment by eva-mueller-coremedia** [comment]
```
lsof -nP -iTCP:"41122" | grep LISTEN

qemu-syst 51760 USER   19u  IPv4 0xfb2e1b2a94cbc451      0t0  TCP 127.0.0.1:41122 (LISTEN)
```

**Comment by abiosoft** [comment]
I wasn't expecting that output :D, it looks fine. Can you now try the second command as mentioned above https://github.com/abiosoft/colima/issues/9#issuecomment-920791869?

As well kindly share the outputs of these two commands.
```
id
colima ssh id
```

**Comment by eva-mueller-coremedia** [comment]
OMG! Now it works. Your second command gave me the decisive hint.

```
ssh -p 41122 -i $HOME/.lima/_config/user -o NoHostAuthenticationForLocalhost=yes -L $HOME/.colima/docker.sock:/var/run/docker.sock -N 127.0.0.1

foobar@127.0.0.1: Permission denied (publickey).
```

For my daily work, I added the user `foobar` to my `~/.ssh/config` for all `Host *`.

As soon as I remove the user from `Hosts *` it works.
But the result is now

```
ssh -p 41122 -i $HOME/.lima/_config/user -o NoHostAuthenticationForLocalhost=yes -L $HOME/.colima/docker.sock:/var/run/docker.sock -N 127.0.0.1

unix_listener: cannot bind to path /Users/USER/.colima/docker.sock: Address already in use
Could not request local forwarding.
```
Is this intended?

**Comment by abiosoft** [comment]
Yeah, that is intended. You do not need to run the command manually. I only asked you to do that for troubleshooting purposes.

Everything should be fine now. If it is still not working, a simple `colima start` should fix it now.

**Comment by eva-mueller-coremedia** [comment]
Next problem I encounter is, that I have defined some entries in `/etc/hosts` like `127.0.0.1       docker.localhost`

The `/etc/hosts` in the lima VM only shows
```
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
192.168.5.2     host.lima.internal
```

Should I open a feature request for you for this topic to automount/mount `/etc/hosts` on demand?

**Comment by abiosoft** [comment]
> Should I open a feature request for you for this topic to automount/mount `/etc/hosts` on demand?

Yeah, you can. Provided you are unable to reach those ip addresses in the VM. To test, you can `colima ssh` and ping those addresses to see.

**Comment by abiosoft** [comment]
> For my daily work, I added the user `foobar` to my `~/.ssh/config` for all `Host *`.
> 
> As soon as I remove the user from `Hosts *` it works.

v0.1.9 has been released to address this. You can now re-add the user to your `~/.ssh/config` and it should work now.
