### ISSUE TITLE
Colima v0.6.5 seems really slow

### ISSUE THREAD

**Issue by hugo-HDSF** [abiosoft/colima#900]
### Description

I've been using colima for a while and recently did a brew up/d/g and since then, seems like my vms weren't visible, I thought iT was due to some kind of changes/refactor in the config files from recent updates so I just deleted all my vms and made them again But now ... dang it takes so long, even stopping a VM takes a while, I was curious to know why and and saw that is was prompting me to watch `/Users/user/.colima/_lima/colima-dev_arm_64/serial*.log` to watch for the process which I did. Then  I stepped upon log were it got stuck at : 

```
...
[    0.776346] systemd[1]: Started systemd-journald.service - Journal Service.


Ubuntu 23.10 colima-devarm64 ttyAMA0

colima-devarm64 login:
```

And I was wondering if it as okay or not or if there was weird behavior. today, I tried to create a simple vm : `>colima start dev_arm_64 --cpu 1 --disk 10 --memory 2` and then this appeard 5 times : `[hostagent] Waiting for the final requirement 1 of 1: boot scripts must have finished` and then this error got thrown :

```
did not receive an event with the "running" status
FATA[0626] error starting vm: error at 'creating and starting': error at 'starting': exit status 1
```

### Version

colima version 0.6.5
git commit: a3adebfcd9da8c85614d81030033d02f04908a79
limactl version 0.18.0
qemu-img version 8.1.2
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

colima status
FATA[0000] colima is not running

### Reproduction Steps

1.colima start dev_arm_64 --cpu 1 --disk 10 --memory 2
2.wait

### Expected behaviour

to create vm quickly

**Comment by bm-enverus** [comment]
I have also experience extremely slow colima vm since upgrading to v0.6.6. I also upgraded to macos sonoma around the same time, but i have uninstalled and reinstalled all dependencies. A vm running in aarch64 used to build one of my images in ~3 minutes. Now it takes well over 20 min, and setting vm flags like --vz-type vz does not seem to improve performance in any way.  Colima is also unstable and seems to crash more frequently now.

**Comment by hugo-HDSF** [comment]
I've actually manage to go back on versions and old onto the latest one that was working fine if somehow you're interested in it!

**Comment by abiosoft** [comment]
This should be fixed in v0.6.7

**Comment by hugo-HDSF** [comment]
I pinned colima to 0.5.6 thx to the colima.rb history file pushed on brew because it was the last version working fine, being reliable and fast just to mention. but i hope 0.6.7 will be the catch for me.

**Comment by hugo-HDSF** [comment]
@bm-enverus if you want to roll back sir, [here](https://nelson.cloud/how-to-install-older-versions-of-homebrew-packages/) is the perfect tutorial !
