### ISSUE TITLE
can't connect to host.docker.internal

### ISSUE THREAD

**Issue by dbarrosop** [abiosoft/colima#902]
### Description

Not sure what changed between 0.6.2 and 0.6.5 but on <=0.6.2 I could add on my docker-compose file:

```
        extra_hosts:
            - host.docker.internal:host-gateway
```

and then run a service on my laptop and connect from the container directly to it via that name. For instance, if I had on my laptop a service running on `:8080` from the container I could simply do `curl http://host.docker.internal:8080`. Now on 0.6.5 I get "connection refused". I noticed that `curl http://192.168.5.2:8080` works but I don't think hardcoding IPs is a good solution, specially when sharing the docker-compose file with others.

### Version

colima version 0.6.5
git commit: dev

runtime: docker
arch: aarch64
client: v20.10.25
server: v24.0.7
limactl version 0.18.0

qemu-img version 8.1.2
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/dbarroso/.colima/default/docker.sock
```

### Reproduction Steps

1. On your laptop run `nc -l 8080` 
2. `docker run --rm --add-host=host.docker.internal:host-gateway -it busybox sh -c 'echo asd | nc host.docker.internal 8080 && echo "success" || echo "failed"'`
3. `docker run --rm --add-host=host.docker.internal:host-gateway -it busybox sh -c 'echo asd | nc 192.168.5.2 8080 && echo "success" || echo "failed"'`

For instance:

On one terminal:
```
$ nc -l 8080
```

On another:

```
$ docker run --rm --add-host=host.docker.internal:host-gateway -it busybox sh -c 'echo asd | nc host.docker.internal 8080 && echo "success" || echo "failed"'
failed

$ docker run --rm --add-host=host.docker.internal:host-gateway -it busybox sh -c 'echo asd | nc 192.168.5.2 8080 && echo "success" || echo "failed"'
success
```

### Expected behaviour

Connecting via `host.docker.internal` should work as it used to on `<=0.6.2`

**Comment by abiosoft** [comment]
Does it work if you remove the `extra_hosts` section of your docker compose file?

**Comment by dbarrosop** [comment]
Yes, it works without it but removing it breaks compatibility with other docker setups. Those lines are there in the docker-compose file to make sure the same docker-compose works across environments. For reference:

https://github.com/moby/moby/pull/40007
https://github.com/docker/for-linux/issues/264


And as mentioned before this was working fine at least up to 0.6.2 (I upgraded this morning from 0.6.2 to 0.6.5 so unsure which version broke this).


BTW, awesome work with colima, huge fan here :)

**Comment by abiosoft** [comment]
Yeah, I am not asking you to remove it, I am only trying to confirm if it's only the `host-gateway` that's broken or the DNS.

I suspect it is configuration related.

Thanks for reporting.

**Comment by rfay** [comment]
In DDEV we only add that on Linux docker-ce systems, since `host.docker.internal` is provided by other systems like Docker Desktop/Colima/OrbStack everywhere. However, it would be nice if it worked both ways (provided by the docker setup *and* added by `--add-host=host.docker.internal:host-gateway`

**Comment by abiosoft** [comment]
The issue has been found.

For whatever reason, the docker daemon is not picking up the `host-gateway-ip` from the daemon config file. However, configuring dockerd via systemd works.

Fixing in https://github.com/abiosoft/colima/pull/904.

**Comment by abiosoft** [comment]
This should be fixed by now. You can verify by installing the development version `brew install --head colima`.

Thanks.

**Comment by dbarrosop** [comment]
Perfect, I can confirm it works now. Amazing work and thanks!

@rfay FWIW we always add it because it is basically a NOOP in docker-for-mac and other systems that add it automagically and it adds a consistent behavior across development environments.

**Comment by dbarrosop** [comment]
Yeah, this seems broken again in 0.6.7

**Comment by markaschneider** [comment]
Yup, not working for me in 0.6.7

**Comment by opticoder** [comment]
Not working with 0.7.0 also

**Comment by abiosoft** [comment]
Can you try the current development version? `brew install -head colima`.

**Comment by opticoder** [comment]
> Can you try the current development version? `brew install -head colima`.

Just checked - works fine. Hope the fix will land in the next colima version
