### ISSUE TITLE
Freshly installed colima does not start: error installing packages using mantic-debs: exit status 100 

### ISSUE THREAD

**Issue by PiotrKlimczak** [abiosoft/colima#903]
### Description

Colima does not start from new.

Simply using:
$ colima start --disk 100 -c 6 -m 6 -t vz --vz-rosetta 

And it fails as below:

INFO[0000] starting colima                              
INFO[0000] runtime: docker                              
INFO[0000] creating and starting ...                     context=vm
>   Package libnftnl11 is not installed.
> 
> dpkg: error processing package iptables (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  iptables
> The following packages have unmet dependencies:
>  iptables : Depends: libip6tc2 (= 1.8.9-2ubuntu2) but it is not going to be installed
>             Depends: libnetfilter-conntrack3 (>= 1.0.6) but it is not going to be installed
>             Depends: libnfnetlink0 (>= 1.0.2) but it is not going to be installed
>             Depends: libnftnl11 (>= 1.1.6) but it is not going to be installed
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
FATA[0042] error starting vm: error at 'creating and starting': error at 'starting': error installing packages using mantic-debs: exit status 100 

### Version

colima version 0.6.5
git commit: a3adebfcd9da8c85614d81030033d02f04908a79
limactl version 0.18.0
qemu-img version 8.1.3

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [X] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

FATA[0000] error retrieving current runtime: empty value 

### Reproduction Steps

1. colima start --disk 100 -c 6 -m 6 -t vz --vz-rosetta

### Expected behaviour

Colima starts

**Comment by PiotrKlimczak** [comment]
$ colima delete && colima prune
helped

**Comment by fungiboletus** [comment]
I had the same problem, and `colima delete` wasn't enough.  The prune solved the issue. Perhaps colima should clear its cache for old installs.
