### ISSUE TITLE
Upgrade `colima` from `0.5.x` to `0.6.x` deletes/recreates VM

### ISSUE THREAD

**Issue by joshbranham** [abiosoft/colima#912]
### Description

When using brew to upgrade colima to the latest version `brew update && brew upgrade colima` the existing VM is destroyed and subsequent `colima start` creates a fresh VM without any existing docker volumes or containers.

### Version

```
❯ colima version && limactl --version && qemu-img --version
colima version 0.6.6
git commit: 9ed7f4337861931b4d0192ca5409683a4b7d1cdc

runtime: docker
arch: aarch64
client: v24.0.5
server: v24.0.7
limactl version 0.18.0
qemu-img version 8.1.3
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [X] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
❯ colima status
INFO[0000] colima is running using QEMU
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: sshfs
INFO[0000] socket: unix:///Users/jbranham/.colima/default/docker.sock
```

### Reproduction Steps

1. (Somehow) install colima 0.5.x with `brew`
2. Create a vm `colima start`, run a container with a volume and write some data
3. Upgrade colima to the latest `0.6.x`
4. Start again with `colima start` and run the same container with the same volume, noting the volume is new

### Expected behaviour

It was not clear that upgrading colima here would erase the VM. This did not appear to happen in previous upgrades via brew, and I don't recall seeing any logs about this happening.

**Comment by abiosoft** [comment]
There is actually a message on the release notes in that regards https://github.com/abiosoft/colima/releases.
Nonetheless, we realised that the release notes are not read by most users; due to the primary distrubition channel being Homebrew.

Work is in progress to ensure that there are in-app warnings for such breaking changes in the future.

Thanks for the feedback.

**Comment by joshbranham** [comment]
Totally, I saw that message once I noticed the behavior, but it wasn't clear to me that it was an _automatic_ thing versus like an error the user gets and has to manually do it post-upgrade. Per the following message that is.

> Due to breaking changes, deletion of existing profiles is required via colima delete.

**Comment by phwoelfel** [comment]
Please really don't make such breaking changes without user interaction. I lost all my docker data because I did a `brew upgrade`.
