### ISSUE TITLE
Can't use docker desktop after stopping colima

### ISSUE THREAD

**Issue by hffmnn** [abiosoft/colima#93]
I tried the following:

1. `colima stop`
2. Start Docker Desktop
3. Run `docker ps`

=> `Cannot connect to the Docker daemon at unix:///Users/<user>/.colima/docker.sock. Is the docker daemon running?`

---

1. `colima stop`
2. `colima delete`
3. Start Docker Desktop
4. Run `docker ps`

=> `Cannot connect to the Docker daemon at unix:///Users/<user>/.colima/docker.sock. Is the docker daemon running?`

---

1. `colima stop`
2. `colima delete`
3. `brew uninstall colima`
4. Start Docker Desktop
5. Run `docker ps`

=> `Cannot connect to the Docker daemon at unix:///Users/<user>/.colima/docker.sock. Is the docker daemon running?`

---

Current workaround: Running `docker ps` with after a `export DOCKER_HOST=unix:///var/run/docker.sock` works.

Any idea where this redirection to `unix:///Users/<user>/.colima/docker.sock` happens?

**Comment by jandubois** [comment]
It is probably the docker context. Use `docker context list` to see which contexts are defined; the one with the `*` is the current default one.

I suspect is is set to `colima`, and you want to switch back to the Docker Desktop one with `docker use-context default`.

(All of this untested).

**Comment by hffmnn** [comment]
That was it, thanks a lot!

**Comment by ckcollab** [comment]
For anyone else goofing around with this, I had to do this to revert back to default docker:

```bash
docker context use default
```
