### ISSUE TITLE
Guard against changing VM type of an existing instance

### ISSUE THREAD

**Issue by rpkoller** [abiosoft/colima#936]
### Description

I ran into this while testing the problem in the context of lima 0.19.1. problem is. if you have for example an existing default instance 
```
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK      RUNTIME    ADDRESS
default    Running    aarch64    4       8GiB      100GiB    docker     
qemu       Stopped    aarch64    4       8GiB      20GiB                
```
during the testing i wanted to setup up another smaller instance for qemu with 20gb. by accident i forgot to add an instance label on colima start. i just entered `colima start--very-verbose --cpu 4 --memory 8 --disk 20 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1` . after a while i noticed 
```
$> colima list
PROFILE    STATUS     ARCH       CPUS    MEMORY    DISK     RUNTIME    ADDRESS
default    Running    aarch64    4       8GiB      20GiB    docker     
qemu       Stopped    aarch64    4       8GiB      20GiB               
```
I was overwriting my vz instance and all the data was lost. that shouldn't happen at all. if a start command is overwriting an existing instance there should be at least a prompt with something like are you sure you wante to replace your default volume default with 4 cpus, 8 gb of ram and 100 gb of disk running on vz/virtiofs with the new one? at the moment it is getting just replaced. a potential source for data loss. 

### Version

colima version 0.6.7
git commit: ba1be00e9aec47f2c1ffdacfb7e428e465f0b58a

runtime: docker
arch: aarch64

limactl version 0.19.1
qemu-img version 8.1.3
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Reproduction Steps

1. have a default for example vz instance. 
2. run `colima start--very-verbose --cpu 4 --memory 8 --disk 20 --vm-type=qemu --mount-type=sshfs --dns=1.1.1.1`
the default instance is just getting replaced with the new one.

**Comment by abiosoft** [comment]
This has been fixed for a while.
