### ISSUE TITLE
colima start error 

### ISSUE THREAD

**Issue by jim-parsons** [abiosoft/colima#961]
### Description

i use command to install colima `brew install colima`, but when i start colima, this error happens to me.

% colima start
INFO[0000] starting colima
INFO[0000] runtime: docker
INFO[0001] starting ...                                  context=vm
> Using the existing instance "colima"
> Starting the instance "colima" with VM driver "vz"
> Converting "/Users/tom/.colima/_lima/colima/basedisk" (qcow2) to a raw disk "/Users/tom/.colima/_lima/colima/diffdisk"
>
> 249.58 MiB / 3.50 GiB (6.96%) ? p/stime="2024-01-15T19:41:09+08:00" level=fatal msg="failed to convert \"/Users/tom/.colima/_lima/colima/basedisk\" to a raw disk \"/Users/tom/.colima/_lima/colima/diffdisk\": failed to call copySparse(), bufSize=1048576, copied=261095424: failed to read: failed to read compressed cluster (len=65536, off=261685248, desc=0x1F000000011FE91D): unexpected EOF"

### Version

colima version 0.6.7
git commit: ba1be00e9aec47f2c1ffdacfb7e428e465f0b58a
limactl version 0.19.1
qemu-img version 8.2.0
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

% colima status
FATA[0000] colima is not running

### Reproduction Steps

1. brew install colima docker
2. colima start

### Expected behaviour

colima starts correctly

**Comment by terev** [comment]
Seems related to https://github.com/abiosoft/colima/issues/930

**Comment by jim-parsons** [comment]
i tried the following actions and started normally.

> brew uninstall colima lima qemu
> rm -rf ~/.colima ~/.lima
> restarted macOS
> 'brew install --HEAD colima'

**Comment by AdrianFerreyra** [comment]
For those who feel uninstalling and reinstalling might be too much, give `colima delete` a try. It will set our colima to its initial startup state. You can still reinstall if it doesn't work!

**Comment by PiotrSzlagura** [comment]
@AdrianFerreyra `colima delete` actually helped me with issues related to `colima start`, thank you!
