### ISSUE TITLE
Colima is failing to do port forwarding after upgrading to Ventura 13.6.4

### ISSUE THREAD

**Issue by mig8447** [abiosoft/colima#969]
### Description

Exposed ports in containers are not being bound in the host

### Version

```
colima version 0.6.7
git commit: ba1be00e9aec47f2c1ffdacfb7e428e465f0b58a
limactl version 0.19.1
qemu-img version 8.2.0
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers
```

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [X] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

```
INFO[0000] colima [profile=x86_64] is running using macOS Virtualization.Framework 
INFO[0000] arch: x86_64                                 
INFO[0000] runtime: docker                              
INFO[0000] mountType: virtiofs                          
INFO[0000] socket: unix:///Users/user/.colima/x86_64/docker.sock
```

### Reproduction Steps

1. Create a simple container exposing a port
2. Run the container
3. Apps in ports cannot be accessed

### Expected behaviour

Applications should be accessible in the ports

**Comment by mig8447** [comment]
This is only happening for me on an x86_64 profile, will try to recreate the vm and see if that fixes it

**Comment by mig8447** [comment]
After recreating the vm, other ports started to work except for 1080, I had to change the container port to 1081 for the host to bind to it. Strange, but it is working now

**Comment by ndesai15** [comment]
On which week, did you create other profile? @mig8447 . I am facing similar issue where default profile on x86_64 is not forwarding ports while rosetta profile, is not creating the container successfully.

**Comment by mig8447** [comment]
> On which week, did you create other profile? @mig8447 . I am facing similar issue where default profile on x86_64 is not forwarding ports while rosetta profile, is not creating the container successfully.

No, I deleted that one and re-created it
