### ISSUE TITLE
Feature request: bundled vde_vmnet and vde-2

### ISSUE THREAD

**Issue by dobegor** [abiosoft/colima#97]
I'd like to use LoadBalancer's IP address directly, but currently it is only possible with vde-2 and vde_vmnet: https://baptistout.net/posts/kubernetes-clusters-on-macos-with-loadbalancer-without-docker-desktop/

It's quite hard to setup these dependencies manually, so maybe it's possible to bundle them with colima?

**Comment by abiosoft** [comment]
Yeah, I have considered this as well. I can not put an ETA on this but I am looking at adding it.

**Comment by abiosoft** [comment]
Kindly install the current development version with `brew install --HEAD colima`.
