### ISSUE TITLE
colima doesn't start on hosted github runner `macos-14` with M1 arm64

### ISSUE THREAD

**Issue by viceice** [abiosoft/colima#971]
### Description

qemu is exiting with error: `qemu-system-aarch64: Error: HV_UNSUPPORTED`

### Version

colima version 0.6.7
git commit: ba1be00e9aec47f2c1ffdacfb7e428e465f0b58a
limactl version 0.19.1
qemu-img version 8.2.0
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [X] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Output of `colima status`

colima not started

### Reproduction Steps

1. setup github action job with `runs-on: macos-14`
2.  run `brew install colima docker`
3. run `colima start` fails

### Expected behaviour

colima should start

### Additional context

running with `-t vz` gives: `Invalid virtual machine configuration. Virtualization is not available on this hardware.`

**Comment by rfay** [comment]
Please search issues before opening new ones. This one was just explained a few minutes ago:
* https://github.com/abiosoft/colima/issues/970

**Comment by viceice** [comment]
sorry, didn't seen it 😞

**Comment by rfay** [comment]
You can close this one now.
