### ISSUE TITLE
Colima should not tell linux users to "brew install"

### ISSUE THREAD

**Issue by mattbucci** [abiosoft/colima#980]
### Description

I found the default error defined here amusing https://github.com/abiosoft/colima/blob/9b0809d0ed9ad3ff1e57c405f27324e6298ca04f/environment/host/host.go#L198

```
FATA[0000] dependency check failed for docker: docker not found, run 'brew install docker' to install
```

I'm running on linux so obviously brew won't apply, 

I think an easy fix would be to only add the suffix ", run 'brew install docker' to install" when running on a mac host

### Version

colima version v0.6.8
git commit: 9b0809d0ed9ad3ff1e57c405f27324e6298ca04f

runtime: containerd
arch: x86_64
client: v1.7.0
server: 1.6.28
limactl version 0.20.1-12-g8af695d
qemu-img version 8.0.0 (qemu-kvm-8.0.0-16.el9_3.3)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [X] Linux

### Output of `colima status`

```
INFO[0000] colima is running using QEMU
INFO[0000] arch: x86_64
INFO[0000] runtime: containerd
INFO[0000] mountType: sshfs
```

### Reproduction Steps

1. try to run colima start on a linux based environment without docker installed
2. you will be prompted to "brew install xyz"

### Expected behaviour

Brew is not available on linux so it shouldn't be suggested. As linux users may be running in various environments I suggest leaving them to figure out how to install the missing dependency

### Additional context
Happy to PR if this issue and proposed solution make sense to you.

**Comment by sa7mon** [comment]
> Brew is not available on linux 

Bold assumption 

https://docs.brew.sh/Homebrew-on-Linux

**Comment by rfay** [comment]
Yeah, brew is really the only way I know of to get colima properly installed on linux, because of all the dependencies. Please close this @mattbucci

**Comment by mattbucci** [comment]
TIL, closing it.
